### ISSUE TITLE
Need 'light' style.

### ISSUE THREAD

**Issue by pakLebah** [JetBrains/JetBrainsMono#1]
Just found this new incredible font and I like it almost instantly. Thank you, Jetbrains.

However, I found the 'regular' typeface style is a bit too weight to my eyes. Could you guys make an additional 'light' style that is a bit thinner than the regular?

Thank you. Keep up the good job. 👍

**Comment by philippnurullin** [comment]
The Extra Light, Light, Semilight (special for dark themes) are in progress.

**Comment by Diablo-D3** [comment]
If semilight does what I think it does, then this will be an especially nice font.

**Comment by cata0309** [comment]
> The Extra Light, Light, Semilight (special for dark themes) are in progress.

I can't wait to use them ! Waiting for the release !

**Comment by fgenesis** [comment]
Light as in exactly 1 pixel wide? The font seems nice but looks super jarring with cleartype and all that antialiasing nonsense off -- some people prefer their font edges aligned to pixel boundaries ;)

**Comment by richardbushell** [comment]
That's great, is there an approximate time frame?

**Comment by philippnurullin** [comment]
@richardbushell 2—3 moths.

**Comment by ddotlic** [comment]
> 2—3 moths.

@philippnurullin Hey, is this still ongoing? Thanks for all the updates!

**Comment by philippnurullin** [comment]
@ddotlic Yes, it is. Sorry for the delay. 

Here is a small preview of what you can expect 
![image](https://user-images.githubusercontent.com/48058957/82434486-9514d400-9a9b-11ea-8c0c-a7bf19bb9f70.png)

**Comment by ddotlic** [comment]
> Sorry for the delay.

@philippnurullin Absolutely **no** need to apologize! Thanks for the preview, it looks awesome! There are even more variations than I hoped for.

Keep up the good work and thanks again.

**Comment by Omnieboer** [comment]
How/why is Semilight especially good for dark themes?

> The Extra Light, Light, Semilight (special for dark themes) are in progress.

I don't know if this is the right place to ask, but a Segoe is dominating the google search.

**Comment by philippnurullin** [comment]
@Omnieboer The thing is that the white object on the dark background seems a bit more bold. To put it simple, the light is glowing. The current Regular weight is made a bit more bold that usual, to grab extra pixels at the low Dpi. So it will not perform best on the dark background & at the larger sizes like, 16+ px.
That's where SemiLight become handy. It's just slightly thinner that Regular to help with optical corrections.

**Comment by Omnieboer** [comment]
And when JetBrains IDE's choose to ship these font options is up to them, I assume? Can't wait ^^

**Comment by cata0309** [comment]
> @ddotlic Yes, it is. Sorry for the delay.
> 
> Here is a small preview of what you can expect
> ![image](https://user-images.githubusercontent.com/48058957/82434486-9514d400-9a9b-11ea-8c0c-a7bf19bb9f70.png)

Loving it ! Keep up the good work and thank you for investing your time in improving this font ! It really means a lot to do such a tremendous work ! <3

**Comment by cata0309** [comment]
> And when JetBrains IDE's choose to ship these font options is up to them, I assume? Can't wait ^^

You can have the fonts much more sooner than when JetBrains IDE's will ship them. When they will be released on GitHub all you have to do is to delete the version of the font that your JetBrains IDE is bundled with so that your newly installed version(the one you grab from GitHub) can be recognized by the IDE.

**Comment by swapii** [comment]
Requesting EAP for this font :)

Can't wait to use light variant. Hope release will be soon.

Thanks for tiser.

**Comment by cata0309** [comment]
@philippnurullin how is the dev process for the new styles ? When should we expect to see it in the wild ?

**Comment by philippnurullin** [comment]
Hi @cata0309, the glyph part is pretty much done. Just need to update a few glyphs in Italic. 
We will start testing on this week, so if the results will be good it will be released very soon.

**Comment by cata0309** [comment]
Friendly ping @philippnurullin

**Comment by ITSecMedia** [comment]
Microsoft recently added additional font-weights to their Cascadia Code font and yes thats what we need for JetBrains Mono too, please! In certain apps, JetBrains Mono looks far too strong/bold yet.

**Comment by Talor-A** [comment]
Thank you @philippnurullin !! The new styles look great, especially the SemiLight for dark themes.
![image](https://user-images.githubusercontent.com/11509865/87183862-c770cf80-c29b-11ea-9fe3-e3acc0e3342c.png)
P.S. if anyone's trying to use that specific style in VS Code like me, you need to specify it as `JetBrainsMono-SemiLight` in the font family setting.

**Comment by swapii** [comment]
Great friday news! Thanks @philippnurullin!

PR to the Homebrew already created: https://github.com/Homebrew/homebrew-cask-fonts/pull/2187

But if you can't wait like me it can be installed via command:
```bash
brew cask install https://raw.githubusercontent.com/MindTooth/homebrew-cask-fonts/cask_repair_update-font-jetbrains-mono/Casks/font-jetbrains-mono.rb
```

Replace `install` with `reinstall` if cask `font-jetbrains-mono` was installed before.

**Comment by cata0309** [comment]
> Thank you @philippnurullin !! The new styles look great, especially the SemiLight for dark themes.
> ![image](https://user-images.githubusercontent.com/11509865/87183862-c770cf80-c29b-11ea-9fe3-e3acc0e3342c.png)
> P.S. if anyone's trying to use that specific style in VS Code like me, you need to specify it as `JetBrainsMono-SemiLight` in the font family setting.
What's the name of that theme?

**Comment by Talor-A** [comment]
> > Thank you @philippnurullin !! The new styles look great, especially the SemiLight for dark themes.
> > ![image](https://user-images.githubusercontent.com/11509865/87183862-c770cf80-c29b-11ea-9fe3-e3acc0e3342c.png)
> > P.S. if anyone's trying to use that specific style in VS Code like me, you need to specify it as `JetBrainsMono-SemiLight` in the font family setting.
> > What's the name of that theme?
@cata0309 it's [lucy](https://marketplace.visualstudio.com/items?itemName=juliettepretot.lucy-vscode), the best free one I've found yet :)

**Comment by cata0309** [comment]
Thank you ! I will definitely try it, looks awesome !

**Comment by saidattax** [comment]
For some reason italics are broken with Semi Light 😞 . I'm on Windows 10, and this is VS Code, I'm using it as `JetBrains Mono Semi Light` in my settings

![image](https://user-images.githubusercontent.com/20104752/87191191-8fa46f00-c311-11ea-98d9-a66a593b2c0d.png)

**Comment by philippnurullin** [comment]
@saidattax What files, exactly you installed in OS? 
I recommend to install plain .ttf. Variable font will not recognise the italics because of font family organization. For this to work you will need to wait until we merge all the font in one file.

**Comment by saidattax** [comment]
@philippnurullin 

I installed the .ttf files itself. `JetBrainsMono-SemiLight.ttf` and `JetBrainsMono-SemiLight-Italic.ttf` 

![image](https://user-images.githubusercontent.com/20104752/87216684-9659d300-c35f-11ea-8568-133763ada1ac.png)

**Comment by plakhin** [comment]
Windows 10
Installed all fonts from TTF Folder.

In Sublime Text, Semi Light works perfect!
`"font_face": "Jetbrains Mono Semi Light"`

Windows Terminal
Version: 1.0.1811.0
`"fontFace": "Jetbrains Mono"` works since first version.
But how to select Light or Semi Light? Tried `Jetbrains Mono Light`, `JetBrainsMono-SemiLight` and various ,different options - nothing helped

**Comment by plakhin** [comment]
Windows 10, Sublime Text.

```
	"font_face": "Jetbrains Mono Light",
	"font_options":
	[
		"gray_antialias",
		"subpixel_antialias",
		"directwrite"
	],
	"font_size": 10,
```

`i` looks like '1'. 
![image](https://user-images.githubusercontent.com/25561058/87216862-2571e580-c376-11ea-90a8-c90cc0179b74.png)

However for font size 11 it looks great 
![image](https://user-images.githubusercontent.com/25561058/87216871-3884b580-c376-11ea-8154-b9d181c7584c.png)

and no such problem with `Jetbrains Mono` and `Jetbrains Mono Semi Light`

![image](https://user-images.githubusercontent.com/25561058/87216890-5d792880-c376-11ea-803a-61f4d2fdc63c.png)
![image](https://user-images.githubusercontent.com/25561058/87216899-71248f00-c376-11ea-8949-f0c64dfe5314.png)

**Comment by plakhin** [comment]
Does it looks to me only that `L` and `gh` are completely different weight?
![image](https://user-images.githubusercontent.com/25561058/87217114-90bcb700-c378-11ea-8e51-04ba57e87bba.png)

**Comment by saidattax** [comment]
#266

**Comment by philippnurullin** [comment]
@plakhin Please, care to create a separate issue regarding `i`. Yes, this can be improved.
I see no errors in `L` + `gh`.

Closing this issue because the Lighter weight was delivered.

**Comment by BornForFever** [comment]
@saidattax Maybe you can create an issue in Vscode respository

**Comment by CodeCrazy-ywt** [comment]
@philippnurullin I don't know if it's suitable to ask here, but I just wonder how I can apply the SemiLight to VScode.

**Comment by philippnurullin** [comment]
Yes, you can. The **SimeLight** name was scrapped due to to unfamiliarity. So now it's called **Light**. 
1. Go to the settings. 
2. Find `Editor: Font Weight`. 
3. Set value to `300`. This will be the **Light** weight.

**Comment by CodeCrazy-ywt** [comment]
Ok, I see. Big thanks
