### ISSUE TITLE
Diacritics on arbitrary characters not supported

### ISSUE THREAD

**Issue by hvdijk** [JetBrains/JetBrainsMono#100]
This report is based on how JetBrains Mono appears in Visual Studio Code.

When Unicode combining diacritical marks are used to place accents on arbitrary letters, unless the letter+accent is a known combination, the accent gets rendered as a box, and the letter gets rendered as non-monospaced. It should be fine to have a sub-optimal fallback for combinations not previously considered, as long as the result has the same width as all other characters and it is possible to make out which character it is supposed to be, but what happens now messes up the alignment and it is not possible to see which accent was intended.

This comes up in at least `j́`, which can be used in Dutch for emphasis, such as in "Dat is van míj́!"

This admittedly has very limited support in many other fonts as well, and even gets displayed wrong in my browser window here, but one very notable font where it does work almost perfectly is Fira Code. This is an issue when considering JetBrains Mono as a replacement for that.

**Comment by philippnurullin** [comment]
Fixed in 2.300
