### ISSUE TITLE
Lowercase "q" has a very short leg

### ISSUE THREAD

**Issue by sabi0** [JetBrains/JetBrainsMono#101]
Currently it looks very similar to "a", especially in italics:
![image](https://user-images.githubusercontent.com/11509875/73177666-df9acb00-410f-11ea-9b9d-e9fce7e3c814.png)

IntelliJ IDEA 201.3803.71
Font size: 14

**Comment by jdw1996** [comment]
Agreed. For the sake of completeness, I'll add that the 'b', 'd', and 'p' also have ascenders/descenders that are too short, although they don't have the same similarity to the 'a' of course.

**Comment by philippnurullin** [comment]
https://github.com/JetBrains/JetBrainsMono/issues/35
