### ISSUE TITLE
dash/minus character wider than other characters

### ISSUE THREAD

**Issue by sewkokot** [JetBrains/JetBrainsMono#102]
The width of dash/minus character is wider than other characters as shown below

![jetBrainsMono_dash_width](https://user-images.githubusercontent.com/12695169/73189979-92295880-4125-11ea-88b9-c823c7534241.png)

Tested in Emacs.

**Comment by philippnurullin** [comment]
@sewkokot Looks like all the metrics are broken. What OS you using? Is it the latest version of the font?

**Comment by sewkokot** [comment]
I have just found that I downloaded the modified slashed zero font version from the last post of:
https://github.com/JetBrains/JetBrainsMono/issues/8
The 1.0.2 version (dotted zero) is Ok. Sorry for the noise and thank you for this font :)

**Comment by philippnurullin** [comment]
@sewkokot Glad to know it works. Have fun!

**Comment by NetOperatorWibby** [comment]
Oh damn, didn’t realize my hack messed up the metrics. Welp, that’s why it’s a hack.
