### ISSUE TITLE
Zero - hinting the dot

### ISSUE THREAD

**Issue by qgates** [JetBrains/JetBrainsMono#104]
Further to #25, I have similar issues with the dot in zeros being off-centre at some font sizes. Probably my OCD, but I'd love to see the dot centred correctly at all sizes.

Kudos for all the work that's gone into JBM, it's my new coding font. Much cleaner than Fira and a welcome change from the my old trusty (but serif-heavy) Consolas.

**Comment by philippnurullin** [comment]
@qgates Its a hinting bug. Right now we are working on 1.0.3 which will have manual hinting. It will address the problems like this.

**Comment by qgates** [comment]
@philippnurullin seem to be having the same issue in v1.0.3. Tested in Sublime Text and VSCode. At some sizes the dot is centred correctly, but some it's too high or too low.

**Comment by qgates** [comment]
As an aside, it would be nice if the dot was more of a dot and less of a line. It may be my imagination but the dot looks more like a line and seems to fill most of the zero now in 1.0.3

**Comment by philippnurullin** [comment]
@qgates Hi, can you provide the screenshots of `0` in context in following sizes. 10, 11, 12, 13, 14, 15. Thanks in advance.

**Comment by qgates** [comment]
Here you go. As you can see 10-13 are fine, 14 and 15 are too high (16 is the same), 17 is too low (18 the same), 19 too high (20 the same), 21 too low etc. These shots were taken in Sublime Text running on win10.

![image](https://user-images.githubusercontent.com/4213509/74163008-9ff8d680-4c19-11ea-94b8-5a309998048a.png)

**Comment by qgates** [comment]
> As an aside, it would be nice if the dot was more of a dot and less of a line. It may be my imagination but the dot looks more like a line and seems to fill most of the zero now in 1.0.3

Now that I've been working with JBM for a little while the dot (line) definitely clutters the zero a bit much. Reducing its length a little, towards a dot, would provide a cleaner reading experience overall imo.

**Comment by philippnurullin** [comment]
@qgates In the 1.0.3 the dot was enlarged to be more pronounced & work better with PostScript hinting. Ok, in 1.0.4 i will me it smaller & we will see how its working. The ideal placement of the dot in all sizes achievable only with TrueType hinting but its not woking well with some things we want to introduce in future, so bear with us until we find a way to add it.
