### ISSUE TITLE
Uppercase W unclear esp. at smaller font sizes

### ISSUE THREAD

**Issue by qgates** [JetBrains/JetBrainsMono#105]
Bit of a nitpick, but uppercase W might be cleaner if the central upstroke didn't go all the way to the top, a little like how it is with the uppercase M in reverse. In Consolas and Fira Code, W appears more clearly, thanks to the greater angles allowed by the shorter central upstroke.

**Comment by philippnurullin** [comment]
@qgates Hi, if the connection of the stroke is lowered it will make the line more ragged, by adding the empty space. In continues reading the eye will be bumping on it. In Consolas & Fira it may work because it's more dynamic nature but it won't work in JetBrains Mono.

**Comment by qgates** [comment]
@philippnurullin Fair point. Since 1.0.3 the look/clarity of W w M m seems to have improved anyway.
