### ISSUE TITLE
Terrible font rendering in Visual Studio 2019

### ISSUE THREAD

**Issue by alexhajdu** [JetBrains/JetBrainsMono#108]
![image](https://user-images.githubusercontent.com/1824796/73344702-1e04c700-4283-11ea-9524-d2374433f826.png)

I've big issues using your font in Visual Studio. See the screenshot and config.

JetBrains Mono 1.0.2
13px
Visual Studio 2019 Professional 16.4.3, 100%
screen res: 2560x1440

**Comment by philippnurullin** [comment]
@alexhajdu Hi, what type of antialiasing is used in your IDE?

**Comment by alexhajdu** [comment]
@philippnurullin I'm not aware I can choose the type of antialiasing in Visual Studio. I see issues in comparison with VSCode or CLion on the same setup. On different fonts, the difference is not so huge.

**Comment by philippnurullin** [comment]
@alexhajdu Looks like hinting problem. In latest versions JetBrains Mono was processed by ttfautohint. The next release will include manual hinting. Hope this solves the problem. Can you send me screenshots with more monospaced fonts? Like Fira Code, Menlo, Consolas.

**Comment by alexhajdu** [comment]
![image](https://user-images.githubusercontent.com/1824796/73367187-75b92780-42af-11ea-943a-c58bb4ad1e32.png)
FiraCode 13px

**Comment by alexhajdu** [comment]
![image](https://user-images.githubusercontent.com/1824796/73367267-97b2aa00-42af-11ea-8a97-439d355a1502.png)
InputMono, 13

**Comment by alexhajdu** [comment]
![image](https://user-images.githubusercontent.com/1824796/73367333-b9139600-42af-11ea-9396-aad8ed6142ea.png)
Menlo, 13

**Comment by glenvan** [comment]
@alexhajdu, I have similar issues in VS2015. I used an extension called [Text Sharp](https://marketplace.visualstudio.com/items?itemName=SergeyVlasov.TextSharp) to set the rendering mode to ClearType / Ideal, disabling the Display hinting for now.

It looks better (if a little fuzzy) to my eye.

**Comment by alexhajdu** [comment]
See my ticket and answers from MS about readability and rendering engine differences for VSCode and VS. It's kinda interesting. Also, the hotfix will be delivered in the next update. 
https://developercommunity.visualstudio.com/content/problem/899361/editor-readability.html?childToView=904574#comment-904574

**Comment by rmaenk** [comment]
Hello, I have the same issue in Visual Studio 2017 (build 15.9.19). 
As workaround you can use zoom level different than 100%.
In my case zoom level is 110% and font size is 11pt - good for FullHD monitor, use large font size for 2K-4K. Zoom input element can be found in left bottom corner in IDE.
![image](https://user-images.githubusercontent.com/18357436/73885766-691d6c00-4879-11ea-8816-9b4b6167d5b6.png)

**Comment by chiniara** [comment]
You can also install the textsharp plugin, it makes the text rendering inside VS2019 a LOT better

**Comment by alexhajdu** [comment]
I've created a ticket also for Visual Studio developers. They implemented it promptly and font antialiasing is now part of the Visual Studio 16.5.0.

**Comment by tullo-x86** [comment]
This just started happening on my machine after installing the most recent VS2019 update (16.5.3).

I fixed it using the TextSharp extension with these settings:

![image](https://user-images.githubusercontent.com/2888110/78915071-000ccd00-7a51-11ea-8060-9911c3634a63.png)

**Comment by gabrielcoffee** [comment]
I had the same problem, I tried to lower the font and zoom and installed the TextSharp and both didn't make any difference. I would like to use vscode but for some reason it doesn't work with unity for me, great.

**Comment by alexhajdu** [comment]
Note we have antialiasing right in the VS so TextSharp is IMHO no longer a must.
![image](https://user-images.githubusercontent.com/1824796/81556505-b1718c00-938a-11ea-9900-818b22c8b628.png)

**Comment by ITSecMedia** [comment]
The Microsoft devs forgotten to apply the new introduced font rendering feature to the onhover menus too. When you choose the best style for JetBrains Mono you get nasty rendering in the popups.
![image](https://user-images.githubusercontent.com/3316334/82508486-7a774500-9b05-11ea-8027-5fd28d8836aa.png)

**Comment by ITSecMedia** [comment]
And it looks like there is a ligature bug in VS for " -> <- " arrows.
![image](https://user-images.githubusercontent.com/3316334/82508577-c629ee80-9b05-11ea-94a5-30f6cf0c7336.png)

**Comment by cata0309** [comment]
> 
> 
> Note we have antialiasing right in the VS so TextSharp is IMHO no longer a must.
> ![image](https://user-images.githubusercontent.com/1824796/81556505-b1718c00-938a-11ea-9900-818b22c8b628.png)

How did you manage to set the font of the actual options ? The left menu

**Comment by johnisfine** [comment]
> Hello, I have the same issue in Visual Studio 2017 (build 15.9.19).
> As workaround you can use zoom level different than 100%.
> In my case zoom level is 110% and font size is 11pt - good for FullHD monitor, use large font size for 2K-4K. Zoom input element can be found in left bottom corner in IDE.
> ![image](https://user-images.githubusercontent.com/18357436/73885766-691d6c00-4879-11ea-8816-9b4b6167d5b6.png)

I'm using Cascadia Code font, font rendering was terrible, I've set size to 11px and zoom to 110% and it fixed it, thanks!

**Comment by OculiViridi** [comment]
> > Note we have antialiasing right in the VS so TextSharp is IMHO no longer a must.
> > ![image](https://user-images.githubusercontent.com/1824796/81556505-b1718c00-938a-11ea-9900-818b22c8b628.png)
> 
> How did you manage to set the font of the actual options ? The left menu

@johnisfine I think it's probably due to the Windows system font that the user has set on his system settings.

**Comment by thanhphuc3010** [comment]
> The Microsoft devs forgotten to apply the new introduced font rendering feature to the onhover menus too. When you choose the best style for JetBrains Mono you get nasty rendering in the popups. ![image](https://user-images.githubusercontent.com/3316334/82508486-7a774500-9b05-11ea-8027-5fd28d8836aa.png)

I had the same problem. How can I fix this. Thanks

**Comment by fernando-goncalves92** [comment]
> > The Microsoft devs forgotten to apply the new introduced font rendering feature to the onhover menus too. When you choose the best style for JetBrains Mono you get nasty rendering in the popups. ![image](https://user-images.githubusercontent.com/3316334/82508486-7a774500-9b05-11ea-8027-5fd28d8836aa.png)
> 
> I had the same problem. How can I fix this. Thanks

I'd like to know too.

**Comment by DajianXu** [comment]
I need text render like visual studio code.

**Comment by futuremotiondev** [comment]
Text rendering is still horrible here in 2025
