### ISSUE TITLE
Support for ASCII graphics

### ISSUE THREAD

**Issue by Otann** [JetBrains/JetBrainsMono#109]
Some ASCII graphics are not rendered monospaced:

![Screen Shot 2020-01-29 at 4 21 05 PM](https://user-images.githubusercontent.com/683786/73369787-781d8080-42b3-11ea-94fa-1490b5f7a20f.png)

Same example using Fira Code:

![Screen Shot 2020-01-29 at 4 21 27 PM](https://user-images.githubusercontent.com/683786/73369814-8370ac00-42b3-11ea-8d01-afdeb6228bbf.png)

**Comment by philippnurullin** [comment]
@Otann Hi, can you paste the exact symbols you your screenshots as a text. Looks like a part of them are included in v1.0.3. I need to look at the other part & see when we can add it.

**Comment by Otann** [comment]
Sure!

```
    ;             ┌─┐
    ;┌─┐   ┌─┐───▶│E│─┐ ┌─┐
    ;│A│──▶│C│    └─┘ ├▶│H│
    ;└─┘   └─┘─┐  ┌─┐ │ └─┘
    ;          ├─▶│F│─┘
    ;┌─┐   ┌─┐─┘  └─┘
    ;│B│──▶│D│    ┌─┐
    ;└─┘   └─┘───▶│G│
    ;             └─┘
```

**Comment by Otann** [comment]
I just installed IDEA EAP, where I think latest version is used and there it looks much better!

![Screen Shot 2020-02-18 at 11 05 45 AM](https://user-images.githubusercontent.com/683786/74725839-bc5ec980-523e-11ea-879d-0d07964ceafd.png)

```
    ;                   ┌────────────┐
    ;                   │   const    │
    ;                   ├────────────┤    ┌─────────────┐
    ;                   │     value ●┼─┐  │   concat    │
    ;                   └────────────┘ │  ├─────────────┤
    ;┌────────────┐ ┌────────────────┐ └──┼▶ 1    value │
    ;│ datasource │ │    iterator    │ ┌──┼▶ 2          │
    ;├────────────┤ ├────────────────┤ │  └─────────────┘
    ;│     edges ●┼─┼▶ items   name ●┼─┘
    ;└────────────┘ └────────────────┘
```

But it still have some width issues for some symbols.

**Comment by philippnurullin** [comment]
@Otann  in 2020.1 the latest version of the font is used, no matter the source. So if you installed the latest in your OS it will be used. This is preview of 1.0.4. with the line height of 1.
<img width="1094" alt="Screenshot 2020-02-19 at 11 32 18" src="https://user-images.githubusercontent.com/48058957/74816127-93583a80-530b-11ea-8d80-2ceca08003b1.png">

**Comment by Otann** [comment]
beautiful! thank you!
