### ISSUE TITLE
Brackets {} are broken in Rider

### ISSUE THREAD

**Issue by huran438** [JetBrains/JetBrainsMono#111]
Hello. https://www.jetbrains.com/lp/mono/ im usin Jetbrains Mono font. When u are using brackets {some_code_here} left bracket is higher than right bracket. My mind is blowing up. Can u fix this issue as soon as possible. Thanks.
![rider64_ylTxCxGOcQ](https://user-images.githubusercontent.com/1672637/73400961-3d3f3b00-42fb-11ea-90a2-2058c4bd5ce4.png)

**Comment by maaaks** [comment]
Same thing happens in PyCharm 2019.3.2 Proffessional on Debian. This is especially ugly when typing empty dict `{}`.

**Comment by bluelovers** [comment]
see 
https://github.com/JetBrains/JetBrainsMono/issues/56
https://github.com/JetBrains/JetBrainsMono/issues/49#issuecomment-575884476

need to update bounded font
