### ISSUE TITLE
need a better font display in terminal

### ISSUE THREAD

**Issue by bluelovers** [JetBrains/JetBrainsMono#113]
test cmd

```bash
ynpx qrcode-terminal -- 'http://github.com'
```

```ts
import { generate as qrcode } from 'qrcode-terminal';

let href = 'http://github.com';

qrcode(href, { small: true });
```

## expected result

> font name: Hasklig (O

![image](https://user-images.githubusercontent.com/167966/73479955-e5283780-43d3-11ea-87f1-aeb9234613e2.png)

## What happens instead

looks bad

> in webstorm run js (X

![image](https://user-images.githubusercontent.com/167966/73479829-aabe9a80-43d3-11ea-9b7b-c2e62336dc5e.png)

> in webstorm terminal (X

![image](https://user-images.githubusercontent.com/167966/73479899-c629a580-43d3-11ea-9e14-ffe73919876e.png)

**Comment by bluelovers** [comment]
ConsoleZ + Hasklig

![image](https://user-images.githubusercontent.com/167966/73487507-1b6cb380-43e2-11ea-9e5f-d6120c2f1bb9.png)

ConsoleZ + JetBrainsMono

![image](https://user-images.githubusercontent.com/167966/73487529-29bacf80-43e2-11ea-8dd4-ef6b10fcc69d.png)

**Comment by alexeyten** [comment]
Probably duplicate #84

**Comment by philippnurullin** [comment]
Yes, its a lack of Box drawing. We will add it in one of the next updates.
