### ISSUE TITLE
about `<>`  `</>`

### ISSUE THREAD

**Issue by bluelovers** [JetBrains/JetBrainsMono#116]
![image](https://user-images.githubusercontent.com/167966/73509806-6656ed00-441b-11ea-8b3f-d2f0a026ece5.png)

i think maybe need make `<>` and `</>` style is match

```
export default <></>
```

**Comment by philippnurullin** [comment]
@bluelovers Hi, can you be more specific? Is you suggesting that the `<` & `>` should be connected to the `/` from the both ends?

**Comment by bluelovers** [comment]
i feel `</>` looks too big then `<>`, maybe change `<>` a little bigger?

or make `</>`  a little small

**Comment by philippnurullin** [comment]
@bluelovers Ok, see what you talking about. Will look in to it in v1.0.4

**Comment by auduchinok** [comment]
Just to note: `<>` is also used as an operator in some languages (VB.NET, OCaml, F# come to mind) and making it significantly bigger would probably make it look a bit worse.

**Comment by philippnurullin** [comment]
@auduchinok Sure, thanks. Can you paste some code examples if you have them?

**Comment by bluelovers** [comment]
jsx
```jsx
function getGreeting {
  return <>Hello, Stranger.</>;
}
```

**Comment by auduchinok** [comment]
Here's some F#:
```fsharp
match reference.Module with
| :? IProjectPsiModule as projectPsiModule ->
    let referencedProject = projectPsiModule.Project
    if referencedProject <> project then
        result.Add(referencedProject.GetOutputFilePath(psiModule.TargetFrameworkId).FullPath)
| _ -> ()
```

```fsharp
if moduleKind <> AnonModule then
    x.ProcessReferenceNameSkipLast(lid)
```

Here's some VB.NET:
```vbnet
Protected Overrides Sub Run(methodDeclaration As IMethodDeclarationBase, data As ElementProblemAnalyzerData, consumer As IHighlightingConsumer)
  If methodDeclaration.Kind <> MethodDeclarationKind.SUB Then
    Return
  End If

  If methodDeclaration.AsKeyword IsNot Nothing Then
    consumer.AddHighlighting(New SubCannotHaveReturnTypeError(methodDeclaration))
  End If
End Sub

```
