### ISSUE TITLE
about the "==" problem

### ISSUE THREAD

**Issue by zhangmeng001** [JetBrains/JetBrainsMono#117]
I have found a fatal problem,when i type "==",two "=" is closed together，so the ”==" looks like one "=",that is confused.I hope you guys can improve it.

**Comment by lanrete** [comment]
This is called ligature, such feature is designed to improve readability for special characters like ==, -> or ++.   
Many modern coding fonts support ligature for better experience, if you don't like it you can turn it off in your IDE/editor

**Comment by zhangmeng001** [comment]
@lanrete thanks
