### ISSUE TITLE
Add Turkish ı (small dotless i)

### ISSUE THREAD

**Issue by monoblaine** [JetBrains/JetBrainsMono#12]
Turkish is not listed in the [supported languages list](https://www.jetbrains.com/lp/mono/#143-languages), but it's _almost_ supported. The only missing letter seems to be `ı` (Small dotless i) as `ğ`, `Ğ`, `ü`, `Ü`, `ş`, `Ş`, `İ` (Uppercase dotted i), `ö`, `Ö`, `ç` and `Ç` are already supported.

**Comment by philippnurullin** [comment]
Actually we have this letter. Did you try to type text on Turkish with JetBrains Mono?
Let me know if it works, will update the language list.

**Comment by monoblaine** [comment]
Oh, my assumption was based on the Diacritics table listed on the web site (`ı` is not listed there). Should've tried the font in the first place instead! 😃

And `ı` _is_ supported by the way:

![resim](https://user-images.githubusercontent.com/540974/72560008-2b9b7380-38b7-11ea-85b9-78c06270352c.png)

Should I close this and open another issue to request updating the language list?

**Comment by philippnurullin** [comment]
You can close this one & i made the request for adding the Turkish on the list, so it will be on page asap. The animation with numbers of languages will be updated to, but a bit later. 
Thanks for feedback!
