### ISSUE TITLE
Powerline symbols are not displaying in WSL and Powershell

### ISSUE THREAD

**Issue by RinsedSloth** [JetBrains/JetBrainsMono#121]
I am currently using the 1.0.2 version on Windows for WSL and Powershell but the powerline symbols are not displaying correctly, just as slashed boxes for example using tmux.

The other application where I have tried it is in VSCode integrated terminal and it is working there.

Just installed the fonts after a format so didn't have an old version installed previously.

**Comment by maksyms** [comment]
The same applies to PuTTY window, byobu/tmux.

**Comment by philippnurullin** [comment]
@RinsedSloth Hi, can you copy and paste the actual symbols from WSL? Did you try the other fonts in it?

**Comment by RinsedSloth** [comment]
@philippnurullin Sure, asides from every JetBrains Mono family I have only tried the default fonts and those are displayed correctly, haven't tried yet with other popular fonts but can try if needed. 

These are the symbols I can't see while using tmux and vim:
│ ─  ☰ ㏑ ᚠ ▾▸ but I assume it is affected every powerline symbol.

**Comment by philippnurullin** [comment]
@RinsedSloth The first two `│ ─ `are from Box drawing set. Coming in v1.0.3. The others are not supported yet.

**Comment by RinsedSloth** [comment]
My bad then, thought they were powerline symbols as they were shown in the vim-airline plugin which uses powerline patched fonts.

Thanks for your time and the font, really looking forward it. Loving it so far :)
