### ISSUE TITLE
Medium and ExtraBold installing saparately from Regular and Bold

### ISSUE THREAD

**Issue by shaltai** [JetBrains/JetBrainsMono#122]
It would be great to have it as a one font family in fonts.
macOS 10.14.6

<img width="319" alt="Screenshot 2020-02-04 at 16 41 50" src="https://user-images.githubusercontent.com/17108398/73750015-82d18d00-476d-11ea-9235-0e0e358cba24.png">

**Comment by philippnurullin** [comment]
@shaltai Hi, this is working like intended in v1.0.2. But on Mac OS, starting from 1.0.3 it will be merged into one family again.

**Comment by rmaenk** [comment]
> @shaltai Hi, this is working like intended in v1.0.2. But on Mac OS, starting from 1.0.3 it will be merged into one family again.

What about Windows OS? Fonts also are installed separatly.

**Comment by philippnurullin** [comment]
New family organisation should fix this. Fell free to reopen the issue if it isn't.
