### ISSUE TITLE
● character misaligned

### ISSUE THREAD

**Issue by TomPridham** [JetBrains/JetBrainsMono#123]
the ● character is larger than other characters and this causes it to look misaligned compared to other characters. 
![Screenshot from 2020-02-04 16-26-52](https://user-images.githubusercontent.com/8271228/73796723-3d13c500-476b-11ea-9f38-f5ab9c6654f6.png)

**Comment by philippnurullin** [comment]
@TomPridham Hi, the U+25CF is not currently supported by JetBrains Mono. So it taken from your fallback font. If you can choose it in your IDE, you can try Menlo.
