### ISSUE TITLE
Disable font ligatures for lookahead/lookbehind prefixes (regex)

### ISSUE THREAD

**Issue by andrebrait** [JetBrains/JetBrainsMono#126]
While this was a recent development in Fira Code, I think it's something they did right and maybe should also be implemented here (all screenshots are from JetBrains Mono 1.0.2).

* FiraCode in IntelliJ IDEA in a Java file:
![Fira-IDEA-Java](https://user-images.githubusercontent.com/5734074/73927597-f55b7d80-48d1-11ea-93f4-3918b564d18f.png)

* JetBrains Mono in IntelliJ IDEA in a Java file:
![JetBrains-IDEA-Java](https://user-images.githubusercontent.com/5734074/73927603-f68caa80-48d1-11ea-929f-2e0fae5d1a48.png)

* FiraCode in IntelliJ IDEA in a Python file:
![Fira-IDEA-Python](https://user-images.githubusercontent.com/5734074/73927598-f5f41400-48d1-11ea-879d-a13fad03b4f3.png)

* JetBrains Mono in IntelliJ IDEA in a Python file:
![JetBrains-IDEA-Python](https://user-images.githubusercontent.com/5734074/73927604-f7254100-48d1-11ea-892a-9da2dfa5a14d.png)

Sometimes, the ligature used is different depending on the text editor, too:

* FiraCode in Visual Studio Code in a Plain Text file (identical results in a Shell Script file):
![Fira-VSCode-Text](https://user-images.githubusercontent.com/5734074/73927602-f68caa80-48d1-11ea-9612-34e3c3d644d7.png)

* JetBrains Mono in Visual Studio Code in a Plain Text file (identical results in a Shell Script file):
![JetBrains-VSCode-Text](https://user-images.githubusercontent.com/5734074/73927607-f7bdd780-48d1-11ea-9e07-5220c7513420.png)

Other times, both end up using ligatures, though different ones, depending on the text editor, too (_**and maybe this is an issue with IntelliJ?**_):

* FiraCode in IntelliJ IDEA in a Shell Script file:
![Fira-IDEA-Shell](https://user-images.githubusercontent.com/5734074/73927601-f68caa80-48d1-11ea-9a62-8ccb7d048997.png)

* JetBrains Mono in IntelliJ IDEA in a Shell Script file:
![JetBrains-IDEA-Shell](https://user-images.githubusercontent.com/5734074/73927605-f7254100-48d1-11ea-8e5c-d453f3588f2f.png)

See https://github.com/tonsky/FiraCode/issues/578 for more details on what Fira Code did in this case.

From their changelog:
> Disabled ligatures after regexp lookahead/lookbehinds (?<=< (?<=> (?<==> (?<=| (?<== (?=:= (?=!= (?== (?=== (?==> (?=> (?=>> (?=<< (?=/= (?!! (?!!. (?!= (?!== (?<!! (?<!!. (?<!= (?<!== (?<!--

**Comment by philippnurullin** [comment]
@andrebrait Looks interesting! Thanks, we will include it in future updates.

**Comment by rmaenk** [comment]
Hello,
Another regexp case:
data: "|11|testdata|19|true"
regexp: "|\d+|.*"
rendered as:
![image](https://user-images.githubusercontent.com/18357436/74786504-ec00e680-52bd-11ea-8763-c93b820b4d12.png)
Regards,
Roman
