### ISSUE TITLE
Disable '/*' ligature after '*'

### ISSUE THREAD

**Issue by sabi0** [JetBrains/JetBrainsMono#128]
There are ligatures for '\*/' and '/\*'. The former is apparently disabled when adding another asterisk. But the latter does not take the preceding asterisk into account:

![image](https://user-images.githubusercontent.com/11509875/73951302-9c094380-48fd-11ea-87cc-d6050ad08c88.png)

**Comment by philippnurullin** [comment]
https://github.com/JetBrains/JetBrainsMono/issues/88
