### ISSUE TITLE
Tweaking font for Windows Cleartype

### ISSUE THREAD

**Issue by cpkio** [JetBrains/JetBrainsMono#13]
This font could use some tweaking for Cleartype compatibility. For now it looks not so great as Consolas or IBM Plex Mono, for example.

**Comment by philippnurullin** [comment]
Sorry that didn't answer this earlier. Took me almost 6 month.

At this point hinting is pretty much settled, so no further drastic modifications will be added.
I suggest trying the newest version https://github.com/JetBrains/JetBrainsMono/releases/tag/v2.001
If you have particular problems please create new issue & provide screenshots, so i can help you.
