### ISSUE TITLE
Strange ligature or just bug with symbols "#{".

### ISSUE THREAD

**Issue by tosspro** [JetBrains/JetBrainsMono#130]
![IMG_20200207_112957_973](https://user-images.githubusercontent.com/11601801/74018425-91eb5180-499e-11ea-8625-ca4d40d23974.JPG)
Font version 1.0.2 Regular.ttf

**Comment by philippnurullin** [comment]
This is ligature for Ruby operator.

**Comment by MatheusRich** [comment]
Why was this issue closed? Was this fixed?

**Comment by tosspro** [comment]
> Why was this issue closed? Was this fixed?

Because I've got answer to my issue that explain it.

**Comment by MatheusRich** [comment]
So is that what it is supposed to be? Ok.
