### ISSUE TITLE
The horizontal length issue of Mono Medium

### ISSUE THREAD

**Issue by ControlNet** [JetBrains/JetBrainsMono#132]
![image](https://user-images.githubusercontent.com/12800094/74049922-1c1fce00-4a10-11ea-924f-fdf666b39c74.png)

Referring to the image, the upper one (Jetbrains Mono Medium) has shorter length in horizontal than the bottom (Jetbrains Mono), which makes the content too compact. Personally, the readability became bad as the characters are thicker. I prefer the thickness of medium version with the horizontal length of reqular version.

Hope for improvement. Thank you!

**Comment by philippnurullin** [comment]
@ControlNet What IDE you using? What version of JetBrains Mono installed?

**Comment by ControlNet** [comment]
> @ControlNet What IDE you using? What version of JetBrains Mono installed?

OS: Windows 10 1909 64bit 
Font: JetBrainsMono-1.0.2 downloaded from https://www.jetbrains.com/lp/mono/
IDE: IDEA Ultimate 2019.3.2, Pycharm 2019.3.2.

The issue happens in both IDEs.

**Comment by philippnurullin** [comment]
@ControlNet Yes, that's a bug of bundled font. The font files are bundled with you IDE & they are old, really, old. To remove the bundled fonts:

1. IDEA\jbr\lib\fonts
2. If you using Toolbox C:\Users\ username\AppData\Local\JetBrains\Toolbox\apps\CLion\ch-0\193.6015.37\jbr\lib\fonts\
_The exact paths will be different in your case. Let me know if you have difficulties with it._

And it's important to restart.

After that the IDE will use the font installed in your OS, which is much better.

https://github.com/JetBrains/JetBrainsMono/issues/49
https://github.com/JetBrains/JetBrainsMono/issues/21

**Comment by ControlNet** [comment]
@philippnurullin 
That works, thank you. I hope the next version of these IDEs fixes the problem.

**Comment by philippnurullin** [comment]
@ControlNet The fix of this behaviour will be in 2020.1 of JetBrains IDE, which will be roughly in 2 months.
