### ISSUE TITLE
No ligature with -> on Visual Studio 2013/2019

### ISSUE THREAD

**Issue by JulienMaille** [JetBrains/JetBrainsMono#133]
Is there anything wrong with my setup? I would be surprised to be the first one to report this.

**Comment by glebd** [comment]
This is a long-standing bug in Visual Studio. It uses WPF test rendering which doesn't support the arrow (->) ligature. The WPF team is apparently aware of this and they plan to address it in a future release.

**Comment by JulienMaille** [comment]
Thank you. Seems they have not plan to fix it. https://github.com/tonsky/FiraCode/issues/259
