### ISSUE TITLE
messed up naming

### ISSUE THREAD

**Issue by jansindl3r** [JetBrains/JetBrainsMono#136]
MacOs: Family names shows name of the style too which results in massive list of fonts in the font list. Can it be nested, pelase? Thanks, I am looking forward to use it.

<img width="204" alt="Screenshot 2020-02-10 at 11 40 55" src="https://user-images.githubusercontent.com/44162266/74143029-5351d300-4bfa-11ea-8c74-a704cfab2854.png">

**Comment by philippnurullin** [comment]
@jansindl3r Hi, what version of the font you using?

**Comment by jansindl3r** [comment]
@philippnurullin ```1.0.2```, I have downloaded it directly from the official website

**Comment by philippnurullin** [comment]
@jansindl3r Try the latest from here https://github.com/JetBrains/JetBrainsMono/releases/tag/v1.0.3 The uploading to the site is not automated, so its lacking in speed, sorry. Let me know if this helps, or not.

**Comment by jansindl3r** [comment]
@philippnurullin thanks! Indeed, it is fine now. Sorry I expected I was getting the latest version
