### ISSUE TITLE
Clarify the copyright owner of JetBrains Mono

### ISSUE THREAD

**Issue by AlwaysLivid** [JetBrains/JetBrainsMono#138]
Hello, currently, the [HaikuPorts](https://github.com/haikuports/haikuports) project seems to be working on porting the font to the [Haiku](https://haiku-os.org) operating system through a process that requires declaring the copyright owners of a particular piece of software.

Although some copyright owners (specifically, those who have written code for this repository) have been clarified in the sense that their credit matches the one presented in the [Apache license](LICENSE), it's not precisely clear what's meant by the following in the [README](README.md) file:

```
You do not need to give credit to JetBrains, although we will appreciate it very much if you do.
```

I know that this is just a detail, but some input would be appreciated nevertheless.

**Comment by bulenkov** [comment]
You may just add JetBrains there. The sentence you've mentioned is about modifications. You can create your own font based on JetBrains Mono and name it as you wish. In this case it would be nice to mention the fact a new font is based on JBM, but it is not required. This is all this sentence about.

**Comment by AlwaysLivid** [comment]
> You may just add JetBrains there. The sentence you've mentioned is about modifications. You can create your own font based on JetBrains Mono and name it as you wish. In this case it would be nice to mention the fact a new font is based on JBM, but it is not required. This is all this sentence about.

Thanks for clearing this up.

**Comment by Begasus** [comment]
@bulenkov could you check the COPYRIGHT as mentioned in our PR if you are OK with it?
PS, using the link from your github page to download the font, so it's yours :)

**Comment by bulenkov** [comment]
Done

**Comment by Begasus** [comment]
Thanks, PR is merged on our side now, jetbrainsmono is now available for Haiku too :+1:
