### ISSUE TITLE
Add Vietnamese language

### ISSUE THREAD

**Issue by haunt98** [JetBrains/JetBrainsMono#14]
I don't see Vietnamese language in 143 languages supported.

**Comment by thang-nm** [comment]
@philippnurullin Do you have a plan for support Vietnamese?

**Comment by philippnurullin** [comment]
@thang-nm Yes, but can't say the exact date.

**Comment by dinhquochan** [comment]
Hey @philippnurullin can I contribute Vietnamese characters to VFC? I open *.vfc and see two masters is **Regular** & **ExtraBold**, just add glyphs like:

<img width="767" alt="image" src="https://user-images.githubusercontent.com/9979458/78366565-e0a61800-75ea-11ea-9c26-035ab11d47c7.png">

* a á à ả ã ạ ă ắ ằ ẵ ẳ ặ â ấ ầ ẫ ẩ ậ
* A Á À Ả Ã Ạ Ă Ắ Ằ Ẵ Ẳ Ặ Â Ấ Ầ Ẫ Ẩ Ậ
* i í ì ỉ ĩ ị
* I Í Ì Ỉ Ĩ
* u ú ù ũ ủ ụ ư ứ ừ ữ ử ự
* U Ú Ù Ũ Ủ Ụ Ư Ứ Ừ Ữ Ử Ự
* o ó ò õ ỏ ọ ô ố ồ ỗ ổ ộ ơ ớ ờ ỡ ở ợ
* O Ó Ò Õ Ỏ Ọ Ô Ố Ồ Ỗ Ổ Ộ Ơ Ớ Ờ Ỡ Ở Ợ
* y ý ỳ ỷ ỹ ỵ
* Y Ý Ỳ Ỷ Ỹ Ỵ

Src: https://vietnamesetypography.com/

**Comment by philippnurullin** [comment]
Hi @dinhquochan As you spotted i started to add the Vietnamese diacritics as an experiment. Talking about `uni0309 hookabovecomb` and others. The original idea was to include the Vietnamese in v1.0.5 release. But after experimenting i got the feeling that it is became too cluttered. Especially in ExtraBold. So to properly implement it, we need to make a whole diacritics revision. And i'm currently in process of that.

As i'm really thankful for you will to contribute but i already working on this part, so it will be not wise to stopping. Still can't say the exact release date. Just know it won't be in in the 1.0.6.

I'll be really grateful if you look at the results & thank you for the link.

**Comment by philippnurullin** [comment]
Hey! How is the added Vietnamese support in 1.0.6. Do you have any difficulties with it? If you stumble upon some problem feel free to open new issues.

**Comment by dinhquochan** [comment]
Yay, thank @philippnurullin
