### ISSUE TITLE
Usage of deprecated fonts location

### ISSUE THREAD

**Issue by andrhua** [JetBrains/JetBrainsMono#140]
Both webpage and readme states that one should place font to `~/.fonts/`, but fontconfig [since quite a while now](https://cgit.freedesktop.org/fontconfig/commit/?id=8c255fb185d5651b57380b0a9443001e8051b29d) favors the XDG Base Directory specifications, and eventually won't read anymore from `~/.fonts`.
Recommended directories are `/usr/share/fonts/` and `~/.local/share/fonts`, for system-wide and user-wide installations correspondingly.
All written above applies to Linux distros, which you neatly indicated with Ubuntu logo on webpage.

**Comment by philippnurullin** [comment]
@andrhua Thanks! We will correct the instructions.

**Comment by philippnurullin** [comment]
It took a wile but, was fixed in README & web page. Thanks for the feedback!
