### ISSUE TITLE
Misaligned 6, {}, not all ligatures vorking

### ISSUE THREAD

**Issue by philippnurullin** [JetBrains/JetBrainsMono#142]
### The problem
There is an issue with bundled version of the font in JetBrains IDE. The bundled version is always in priority, even if you installed the never in OS. This behaviour will be fixed in 2020.1

### The workaround
You need to manually remove the bundled fonts & install the new in OS.

1. **Win**
a) `<product (IDEA for example)>\jbr\lib\fonts`
b) If you using Toolbox `C:\Users\ username\AppData\Local\JetBrains\Toolbox\apps\<product (CLion for example)>\ch-0\193.6015.37\jbr\lib\fonts\`
**Mac**
`IntelliJ\ IDEA.app/Contents/jbr/Contents/Home/lib/fonts/`

2. [Install the new version](https://github.com/JetBrains/JetBrainsMono/releases/latest) in OS 
If you already have the older version of JetBrains Mono installed in OS, remove it first.

3. Don't forget to restart.

_Related issues_

1. {} 
https://github.com/JetBrains/JetBrainsMono/issues/21
https://github.com/JetBrains/JetBrainsMono/issues/49
https://github.com/JetBrains/JetBrainsMono/issues/111
2. Ligature problems
https://github.com/JetBrains/JetBrainsMono/issues/38
https://github.com/JetBrains/JetBrainsMono/issues/73
https://github.com/JetBrains/JetBrainsMono/issues/134
3. Font width problem
https://github.com/JetBrains/JetBrainsMono/issues/132
4. 6
https://github.com/JetBrains/JetBrainsMono/issues/42

**Comment by joveice** [comment]
Path for Fedora `~/.local/share/JetBrains/Toolbox/apps/PhpStorm/ch-0/<version>/jbr/lib/fonts/`

**Comment by philippnurullin** [comment]
Seems it's not relevant anymore. Closing.
