### ISSUE TITLE
Underlined URLs look weird

### ISSUE THREAD

**Issue by Midar** [JetBrains/JetBrainsMono#144]
When a URL like https://foo is rendered with underlining (e.g. in a mail program), there is no underlining for the // ligature. Not only does it weird to have the ligature there, but also that there's no underlining for such a long while.

**Comment by philippnurullin** [comment]
@Midar Hi, can you send a screenshot, so that i understand you more.

**Comment by Midar** [comment]
Sure: https://0x0.st/i-EF.png

As you can see here, the // and the / don't get underlining, and on top it looks inconsistent because the // look different to the /.

**Comment by philippnurullin** [comment]
@Midar This is default OS underline style. We can't do anything with it from the font perspective.

**Comment by Midar** [comment]
@philippnurullin Are you sure about this? If I switch to Monaco, it is rendered with a full underline that is not broken.

**Comment by Midar** [comment]
Also, I think the ligature might make it worse: Without it, looking at the single /, there's only a very minimal amount of break in the underlining. Would it maybe be possible to disable the ligature for ://, so that there's no ligature in URLs? My understanding is that the // ligature is mostly for comments, which usually don't happen directly after a : anyway.

**Comment by philippnurullin** [comment]
@Midar Monaco doesn't have ligature `//`, so the underline treated differently from OS perspective. Disabling it in `://` sequence might be a nice idea. Will think about it.

**Comment by Midar** [comment]
Would be great, as URLs look weird with the ligature, even without the underlining ;). Would be a nice thing for 1.0.4!
