### ISSUE TITLE
Lowercase f is misaligned

### ISSUE THREAD

**Issue by Midar** [JetBrains/JetBrainsMono#145]
When having an f next to an o or an a, the horizontal line of the f looks way off - I think it needs to be higher to align with the upmost point of the o or a. There's also a weird space to the right, which makes it look like really bad kerning.

**Comment by qgates** [comment]
On the horizontal line, yes, that looks slightly inconsistent with other lowercase letters like aou, which are taller in JBM than in other fonts. I'm not sure that anything could be done about this, since moving the stroke up would leave it too close to the top of the f, unless there is room to heighten the overall letter form.

I can't see any issue with spacing though. Screenshot along with configuration info would be useful.

**Comment by philippnurullin** [comment]
@Midar Please provide screenshots.

**Comment by Midar** [comment]
https://0x0.st/i-6V.png

It almost looks like the f is not a regular f, but 𝖿, especially as the italic version really looks like 𝑓.

**Comment by philippnurullin** [comment]
@Midar The letter must have readable construction at small sizes, so the horizontal stroke in `f` was moved down to leave the empty space between it & bended ascender. By doing so we also balance the black & white in letter & don't need the serif at the bottom.

**Comment by Midar** [comment]
@philippnurullin This is unfortunately very, very odd in combinations like "if" (ad that's one of the most common things in programming!) and "tf". See the following screenshot: https://0x0.st/i-hG.png

As t also extends over the horizontal line, can at least t and f be made consistent? It's driving me crazy to the point that I actually switched away from JetBrains Mono for now - which is sad, as it's otherwise a very nice font.

**Comment by philippnurullin** [comment]
@Midar I understand why in thees combinations it can look strange. If it's so critical, you can always switch to another font which is appealing to you. You can try [Fira Code](https://github.com/tonsky/FiraCode), for example, or [Cascadia](https://github.com/microsoft/cascadia-code).

**Comment by Midar** [comment]
Of course I can switch to another font, but I really like Jetbrains Mono - except for  the f. I'm not aware of *any* other font where f and t are misaligned. Any chance you can reconsider, or at least provide an alternative version? Or at least make i, t and f aligned by changing t and i instead of f? (Though even f and o look wrong, so o might need to be made slightly smaller as well then)

**Comment by philippnurullin** [comment]
@You can look at the Consolas & Cascadia. They are treating f the same way. Alternate construction may be introduced in a stylistic sets feature, but it's not coming anytime soon.
