### ISSUE TITLE
No ligature for -- while there is one for ==

### ISSUE THREAD

**Issue by Midar** [JetBrains/JetBrainsMono#146]
I can't help but feel it's weird that there is a ligature for == that just makes it longer, but none for --. The same is true for ++, which has a ligature which connects the two horizontal lines, but not for --.

**Comment by qgates** [comment]
There is a ligature for -- and ---, though it's subtle. The dashes are longer and space between them is reduced. Having one single line for these symbols would be confusing. 

If you want to see, try typing ---- (not a ligature) to see how plain, non-ligature dash symbols in succession compare.

**Comment by philippnurullin** [comment]
@Midar This is like @qgates described. The space in `--` was left to clearly indicate the symbols. At first it was a single line, but after testing it become clear that adding the space make the symbol more pronounced. The `---` made to be consistent.

**Comment by Midar** [comment]
Ok, I understand this :). Then only one question remains: Why have no separation for ==? Shouldn't == and -- be consistent, as the only difference is that == is -- twice, on top of each other?

**Comment by philippnurullin** [comment]
@Midar In `==` we didn't have the problem with recognition. Adding the space will crate more details & be problematic in ligatures like `!==`, so we left `==` as it is.

**Comment by Midar** [comment]
I understand, but it is indeed sometimes hard to tell = and == apart, so I thought this is generally not considered an issue, hence -- also being. Will there maybe at some point be multiple "configurations", optimized for different use cases? (I mean, ideally there would be a configuration file and people could then just type make ;))

**Comment by Midar** [comment]
Oh, also, @qgates: There is no ligature for -- for me at all. If I type -- and then add another one to make it ---, the first -- do not change at all.
