### ISSUE TITLE
~> ligature problematic for using the font in a terminal

### ISSUE THREAD

**Issue by Midar** [JetBrains/JetBrainsMono#147]
A lot of shell configurations (and some even by default) have a prompt that contains "$path>", e.g. "/tmp>". However, when the directory is the home, it's "~>" and suddenly the ~> ligature is used, making it weird. I tried working around this by adding U+FEFF, which changed nothing, as well as U+200C, which weirdly is printed as a full width space instead.

Is there a way to disable the ligature somehow? Injecting some special character to disable it in PS1 would be sufficient.

**Comment by qgates** [comment]
In my view this opens up the more general question of whether having ligatures is appropriate at all for certain use cases. Terminal fonts are a good example, though disabling ligatures would negatively impact the use of text-mode editors like vim for coding.

Ultimately a non-ligature version of the font may be best for such applications, and the best solution for this and a variety of other edge-case applications and stylistic preferences would be something along the lines of what the author refers to [here](https://github.com/JetBrains/JetBrainsMono/issues/8#issuecomment-584134324).

**Comment by philippnurullin** [comment]
@Midar Unfortunately there is no way to make an intelligent exclusion in this ligature. So i'm suggesting turn off ligatures, or wait for no ligature version of the font.

**Comment by Midar** [comment]
The problem is exactly that: I use vim in my terminal.

As for turning off ligatures: Isn't that *exactly* what U+200C is for? Or U+FEFF? That you explicitly say "Don't use a ligature here" - that's the only reason U+200C exists. And U+FEFF should also just break it, as it's a zero width character in between?

**Comment by philippnurullin** [comment]
@Midar Got you. I will add the U+FEFF in v1.0.4. 

Didn't saw the U+200C in fonts. Can you send me an example?

**Comment by Midar** [comment]
Both are not rendered at all, and occupy 0 pixels. Now that I think of it, I'm unsure whether those ever reach the font, or if it should be handled by the rendering engine.
