### ISSUE TITLE
No glyph for nbsp

### ISSUE THREAD

**Issue by yfinkel** [JetBrains/JetBrainsMono#148]
There is no glyph for non-breaking space (A0h). It's bad for console programs (i.e. FAR manager).

**Comment by philippnurullin** [comment]
@yfinkel It was added in v1.0.3. What version you using?

**Comment by yfinkel** [comment]
Well, it was 1.0.2. Thanks, now it's ok.

**Comment by philippnurullin** [comment]
@yfinkel Glad to hear!
