### ISSUE TITLE
Chinese content are not monospaced

### ISSUE THREAD

**Issue by Cat7373** [JetBrains/JetBrainsMono#149]
## Environment
OS: MacOS 10.15.2
Editor: VSCode 1.42.0
Font Version: 1.0.3

## Expected
Effects like Ubuntu Mono:
![Jietu20200214-161829](https://user-images.githubusercontent.com/9296576/74513512-b2d71800-4f45-11ea-8d16-e00f29e1f1bf.png)

## Actual
![Jietu20200214-165329](https://user-images.githubusercontent.com/9296576/74515992-8ffb3280-4f4a-11ea-8aae-edb13f0873cd.png)

**Comment by philippnurullin** [comment]
@Cat7373 Hi, currently JetBrains Mono don't support Chinese language. The symbols you seeing are from your fallback font. The only solution right now is to manually find a font with matching width. 
You can look for more info in this issue https://github.com/JetBrains/JetBrainsMono/issues/20

**Comment by Cat7373** [comment]
@philippnurullin 

Thank you, is there a plan for support?

**Comment by philippnurullin** [comment]
@Cat7373 We don't have an expertise in this language, so until we find the expert, we can't make it good. Sorry.
