### ISSUE TITLE
Font size changed when 1.0.2 -> 1.0.3

### ISSUE THREAD

**Issue by MonstraG** [JetBrains/JetBrainsMono#152]
Here is comparison with official site (Chrome) on the left and newest GoLand on the right (I've manually updated font to 1.0.3)
Chrome reports cite font as 13px, I have the same size in GoLand options.
![image](https://user-images.githubusercontent.com/17963791/74651671-28d9ba00-51a6-11ea-8885-b24f447270f4.png)

Here is letter "h" from "http" upclose:
![image](https://user-images.githubusercontent.com/17963791/74651842-91289b80-51a6-11ea-8e72-7428b9814d91.png)
This time my "h" is on the left, and site "h" is on the right. Both are 13px.

Now, I change my font size to 12px
![image](https://user-images.githubusercontent.com/17963791/74651919-bf0de000-51a6-11ea-909b-000fc669a0a1.png)
My "h" is on the left, size 12px, and site "h" is on the right, size 13px.

As you can see, for some reason my 12px letter is the same size as 13px from site.

Rolling back to 1.0.2:
![image](https://user-images.githubusercontent.com/17963791/74652058-0ac08980-51a7-11ea-9341-a7c2eac97491.png)
My "h" is, again, on the left, but both fonts are set up to be 13px, and are equal.

**Comment by philippnurullin** [comment]
@MonstraG This works as expected. In 1.0.3 the hinting was made different so it will keep the x-heights bigger specifically in 13px size. The font on the site is v1.0.1, we will update it eventually with the new symbols. Didn't catch whats the problem you having.

**Comment by MonstraG** [comment]
@philippnurullin The issue is that I don't like how it looks now. I prefer previous, smaller x-heights.

**Comment by philippnurullin** [comment]
@MonstraG Give your self some time to adapt. The text in general become bigger so it will be easier to recognise the letters. If it's not working for you, you can shift to 12. I'm sorry for the trouble.

**Comment by fkindgen** [comment]
@MonstraG You can download https://www.freetype.org/ttfautohint/ and in the program you can select the input/output font and select 'Dehint' and then you will have the old height.

**Comment by philippnurullin** [comment]
I strongly don't recommend doing so. Dehinted font on low DPI is really bad.
