### ISSUE TITLE
Request: JetBrainsMono font versions without ligatures

### ISSUE THREAD

**Issue by rmaenk** [JetBrains/JetBrainsMono#153]
Hello,
Is it possible to extend set of JetBarinsMono fonts with versions without ligatures (or disabled ligatures)?
This is useful for using in Visual Studio 2017/2019, because VS does not provide any setting to swith on/off ligatures. 
For instance this is related to cases like this: #126 

Regards,
Roman

PS: I like this font, thank you for sharing it for all of us ). Good work!

**Comment by philippnurullin** [comment]
@rmaenk Hi! The issue is duplicated. https://github.com/JetBrains/JetBrainsMono/issues/19
We will treat the #126 in time, so its not a big problem & we will have version without ligature soon. Thanks for the king words!
