### ISSUE TITLE
Ligatures not showing on Webfont version?

### ISSUE THREAD

**Issue by shshaw** [JetBrains/JetBrainsMono#155]
We added JetBrains as an editor font option on CodePen recently, but ligatures are not showing. Are the ligatures stripped out of the Web Font version or are there special settings to enable here?

We're only using the WOFF2 & WOFF versions, like so:

```
        @font-face {
          font-family: 'jetbrains-mono';
          src: url(${__font_url_jetbrains_mono_regular_woff2}) format('woff2'),
               url(${__font_url_jetbrains_mono_regular_woff}) format('woff');
          font-weight: 400;
          font-style: normal;
        }
        @font-face {
          font-family: 'jetbrains-mono';
          src: url(${__font_url_jetbrains_mono_italic_woff2}) format('woff2'),
               url(${__font_url_jetbrains_mono_italic_woff}) format('woff');
          font-weight: 400;
          font-style: italic;
        }
        .CodeMirror pre {
          font-family: 'jetbrains-mono', MonoSpace;
        }
```

I've tried enabling `font-variant-ligatures: normal;` and using these settings as shown on the README, but the ligatures still don't come through.
```
    -webkit-font-feature-settings: "liga" on, "calt" on;
    -webkit-font-smoothing: antialiased;
    text-rendering: optimizeLegibility;
```

Are there other CSS properties to use or any other recommendations?

**Comment by philippnurullin** [comment]
@shshaw Hi, do you have any `letter-spacing` modifications? Did you tried to switch from `.woff` to `.ttf`?  If not please do, so that we can indicate if `.woff` is bugged.

**Comment by shshaw** [comment]
We may have been on an older version. We've now reinstalled the latest version and all seems to be working.

**Comment by philippnurullin** [comment]
@shshaw Glad to hear. Don't hesitate to write if anything comes up.

**Comment by shshaw** [comment]
Thank you!
