### ISSUE TITLE
Provide glyphs for ← → ↑ ↓

### ISSUE THREAD

**Issue by tgeng** [JetBrains/JetBrainsMono#159]
First of all, I really love this font! Thank you for all the effort put into making it!

The shape of arrow heads of unicode characters ← → ↑ ↓ (No, not ligatures. These are useful for programming language Agda) are very small and hence not very readable (also not looking consistent with the rest of the font).

As a comparison, Fira Mono is [much more readable](https://www.1001fonts.com/fira-mono-font.html?text=%E2%86%90%20%E2%86%92%20%E2%86%91%20%E2%86%93). It would be great if JetBrains Mono would use the same big arrow heads for all unicode arrow characters as well.

Note that, I am not sure if it's because these codepoints are not available and hence my fallback font is used instead. If this is the case, it would be great if JetBrains Mono could provide characters for these code points as well.

**Comment by philippnurullin** [comment]
@tgeng Hi, it will be really helpful to look at the screenshots.

**Comment by tgeng** [comment]
Thanks philippnurullin! Oh this is embarrassing. It turns out to be a setting issue on my end. Actually JetBrains Mono indeed has big arrow heads for those characters. Sorry about that!

**Comment by tgeng** [comment]
Reopen with new title.

**Comment by philippnurullin** [comment]
@tgeng Please update the font to the latest version. `←` `→` `↑` `↓` & a bit of other arrows supported from v1.0.2.

**Comment by tgeng** [comment]
Yep I was on 1.0. Awesome! Thank you!
