### ISSUE TITLE
Add slashed zero variant

### ISSUE THREAD

**Issue by quirico** [JetBrains/JetBrainsMono#160]
Please, consider adding a slashed zero variant of the zero digit (U+0030) which can be enabled via the zero Open Type feature. In CSS that can be turned on with `font-variant-numeric: slashed-zero;`.

**Comment by alexeyten** [comment]
See #8

**Comment by philippnurullin** [comment]
@quirico https://github.com/JetBrains/JetBrainsMono/issues/8

**Comment by quirico** [comment]
Thanks and sorry for raising a duplicate.
