### ISSUE TITLE
May be add a little tail to the 'u' and 'U' char? it's too similar with 'v' in small size.

### ISSUE THREAD

**Issue by znydev** [JetBrains/JetBrainsMono#161]
may be add a little tail to the 'u' and 'U' char?

it's too similar with 'vV' in small size.

**Comment by philippnurullin** [comment]
@znydev Hi, can you send the screenshots with context. Maybe some examples where you having troubles with differentiating thees letters apart.

**Comment by znydev** [comment]
@philippnurullin nerver mind, I'm getting used to it. thanks you.
