### ISSUE TITLE
I can't select the medium size in IntelliJ Ultimate 2019.3.3

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [JetBrains/JetBrainsMono#162]
I tried to install only the medium size but it is not working

**Comment by philippnurullin** [comment]
@JavierSegoviaCordoba Hi. The font is bundled in your version of IDE. To install the new and custom version, you need to remove the bundled font. Follow thew instructions in here https://github.com/JetBrains/JetBrainsMono/issues/142

**Comment by JavierSegoviaCordoba** [comment]
It works :)

**Comment by JavierSegoviaCordoba** [comment]
IntelliJ 2020 still doesn't have the medium size font so I have to remove all default JetBrains font and add manually the medium size.

Windows and Mac versions detect the font with a different names (Mono vs Mono Medium) so when the IDE tries to get the font from settings repository it changes to the default font.

I hope this issue https://youtrack.jetbrains.com/issue/IDEA-92825 gets a higher priority. It is a 2014 issue btw...

**Comment by philippnurullin** [comment]
The algorithm of choosing weight is on IDEA side. The behaviour with the different names is also part of it. From the font perspective everything works like it should & nothing can be done, sorry. Closing this issue.
