### ISSUE TITLE
May be we can add a tail to 'u' to make a difference with 'v' and 'U'?

### ISSUE THREAD

**Issue by znydev** [JetBrains/JetBrainsMono#164]
![image](https://user-images.githubusercontent.com/30818783/75666057-21d79f00-5cb0-11ea-95fe-784a974ec38f.png)
like this:
![image](https://user-images.githubusercontent.com/30818783/75666108-3ae05000-5cb0-11ea-8391-99b441491f9b.png)

**Comment by znydev** [comment]
just like n.
![image](https://user-images.githubusercontent.com/30818783/75666221-64997700-5cb0-11ea-8240-95646907cecf.png)

**Comment by znydev** [comment]
Rotated 180 degrees。
![image](https://user-images.githubusercontent.com/30818783/75666346-98749c80-5cb0-11ea-8773-fb7119b5774a.png)

**Comment by philippnurullin** [comment]
@znydev I understand you proposal. The `u` was particularly stripped from the lower end of the stem to remove details. It may be not familiar, at first. But after a few days the habit changes & it will stop bothering you.

Can you send the screenshots with the examples of the code where you having the difficulties with differentiating the `u` from `v`.

**Comment by znydev** [comment]
Hi, thanks, you are right, it's may be a habit, I wll try.
![image](https://user-images.githubusercontent.com/30818783/75862455-f385cb00-5e39-11ea-9200-b17da2df245c.png)

**Comment by philippnurullin** [comment]
@znydev Its rarely you will encounter this amount of `u` & `v` together. In context of the word you will have no problem to understand which letter there is. But if you have examples where it can be a problematic, please sen them to me.

**Comment by znydev** [comment]
@philippnurullin ok, thanks, I will close this issue.
