### ISSUE TITLE
Make box-drawing characters use the full height

### ISSUE THREAD

**Issue by g-zimmer** [JetBrains/JetBrainsMono#165]
Box characters don't look pretty with the Font, there is a small cap between characters and the characters above/below.

The following

```
 ┌──┬──┐  ╔══╦══╗ ╒══╤══╕ ╓──╥──╖
 │  │  │  ║  ║  ║ │  │  │ ║  ║  ║
 ├──┼──┤  ╠══╬══╣ ╞══╪══╡ ╟──╫──╢
 │  │  │  ║  ║  ║ │  │  │ ║  ║  ║
 └──┴──┘  ╚══╩══╝ ╘══╧══╛ ╙──╨──╜
```

looks like this in IntelliJ with line spacing set to 1.0:

![image](https://user-images.githubusercontent.com/25695099/75689558-ae2e9580-5ca1-11ea-9981-24fab59593dc.png)

These characters should use the full height available. Especially command line interfaces use these characters frequently (e.g. tmux for visualizing terminal splits).

The font "Consolas" for instance looks pretty:

![image](https://user-images.githubusercontent.com/25695099/75690018-77a54a80-5ca2-11ea-9ae9-a3fc0a483547.png)

**Comment by philippnurullin** [comment]
@g-zimmer Hi, its duplicated in this issue https://github.com/JetBrains/JetBrainsMono/issues/84
The fix will be in v1.0.4
