### ISSUE TITLE
Ligature request for ~= (for Lua)

### ISSUE THREAD

**Issue by rafaskb** [JetBrains/JetBrainsMono#166]
When programming Lua, the *not equals* operator is `~=`. It would be nice to have a ligature transforming it into `≃`.

And congratulations for the font, it's a pleasure to work with it. :)

**Comment by philippnurullin** [comment]
@rafaskb Hi. Glad to hear that you enjoying it. 
Can you send the screenshots with this ligature in context of the code? I believe we have it already.

**Comment by rafaskb** [comment]
@philippnurullin Yeah sure! Here it is, with two fonts for comparison:

![lua not equals jetbrains mono](https://user-images.githubusercontent.com/2331058/75983967-4ad27c80-5ec8-11ea-8d69-cfc04d53d8a0.png)

I'm using version 1.0.3

**Comment by philippnurullin** [comment]
@rafaskb Are the other ligatures present? Can you type something like `=>` `->` `===` & send screenshot of them?

**Comment by rafaskb** [comment]
@philippnurullin Yeah, all ligatures seem to work just fine.

![lua ligatures](https://user-images.githubusercontent.com/2331058/76007823-6f8d1b00-5eed-11ea-82c6-16c2b4ea2747.png)

**Comment by philippnurullin** [comment]
@rafaskb What IDE you using? In DejaVu Sans used a different approach to ligatures. Can you also try the latest Fira Code, to see if this error is persistent?

**Comment by rafaskb** [comment]
@philippnurullin I'm using IntelliJ IDEA 2019.3.1 and macOS 10.14.4 with the latest JetBrains Mono font installed into the system.

I just downloaded the latest FiraCode release from Github and confirmed it works just fine with it. Here's a screenshot:

![image](https://user-images.githubusercontent.com/2331058/76093019-17aeec80-5f9f-11ea-835f-48588c74370c.png)

**Comment by philippnurullin** [comment]
@rafaskb Looks like you working on older bundled version of the font which don't have this ligature. 
You need to manually remove it from IDEA. The locations can be found in this issue. https://github.com/JetBrains/JetBrainsMono/issues/142
Let me know if this helps or not.

**Comment by rafaskb** [comment]
Oh that makes perfect sense. Disabling the bundled font and using the OS one solves the issue. I'm sorry for the trouble, I didn't realize I was already using a recent version of the IDE with the font bundled.

Now the ~= ligature works as expected, and it's looking good! :)

**Comment by rafaskb** [comment]
After updating IntelliJ to 2020.3, this specific ligature doesn't work anymore. Other ligatures are working just fine though.

**Comment by philippnurullin** [comment]
Hi @rafaskb This ligature was removed after requests. Sorry can't find the exact issue for that.
