### ISSUE TITLE
Support for Unicode math symbols

### ISSUE THREAD

**Issue by bergwerf** [JetBrains/JetBrainsMono#167]
Same issue as https://github.com/tonsky/FiraCode/issues/950. Common mathematical operators like union, subset, set membership, quantifiers, etc. are not in the font. These are very useful when the programming language has Unicode support and the IDE has a nice shortcut for typing standard LaTeX symbol. Are there plans to include such symbols?

**Comment by philippnurullin** [comment]
@bergwerf Hi, looks like this is related request. https://github.com/JetBrains/JetBrainsMono/issues/47 Is it? 

You mentioned `U+2208`, `U+2200` & `U+2203` as most frequently used. It also be really helpful to look at the list with priority groups, you talking about in FiraCode tread.

**Comment by bergwerf** [comment]
The three I mentioned are in the Agda list. The Coq standard library only
declares a few Unicode characters for notation (and this is optional),
although other characters are of course useful to create new notations.

I would say Unicode characters with common LaTeX names have priority.

**Comment by philippnurullin** [comment]
Glyphs were added starting from v 2.000
