### ISSUE TITLE
Ukrainian language not supported?

### ISSUE THREAD

**Issue by AlsoScratch** [JetBrains/JetBrainsMono#168]
#75 mentions that Dutch is not mentioned in the supported languages in the macOS Font Book. I also see that problem on my side.
But I noticed that Ukrainian is also missing so I went to [Alphabet Type CharSet Checker](https://www.alphabet-type.com/tools/charset-checker/) and it says that Dutch _is_ fully supported. (Not sure what else Font Book wants.)
On the other hand, Ukrainian is apparently missing U+02BC "Modifier Letter Apostrophe" and I'm not sure what that is used for.

**Comment by philippnurullin** [comment]
@AlsoScratch Hi, i'm not sure what its used for too, but its not a problem to addd it & find out whats its doing.

**Comment by AlsoScratch** [comment]
Can confirm Ukrainian is there now but Dutch is still missing.
