### ISSUE TITLE
Box-drawing chars: spacing problem

### ISSUE THREAD

**Issue by nifanic** [JetBrains/JetBrainsMono#169]
There is a space between the rows with box-drawing characters.

<img width="515" alt="2020-03-10_22-21-38" src="https://user-images.githubusercontent.com/28378773/76376281-5259b180-631e-11ea-864d-d0328775d67c.png">

To reproduce, see `npm` update notice surrounded by the box-drawing characters in WebStorm terminal.

**Comment by philippnurullin** [comment]
@nifanic Hi, looks like you have the old version of the font that not supporting Box Drawing at all. To fix this you need to manually remove the bundled font so IDE will see the new version, installed in OS.
Instruction on how to remove the bundled font can be found here https://github.com/JetBrains/JetBrainsMono/issues/142

Let me know if this works for you.

**Comment by nifanic** [comment]
Thank you, #142 helped to fix the issue.
