### ISSUE TITLE
Version tagging

### ISSUE THREAD

**Issue by radmen** [JetBrains/JetBrainsMono#17]
Hey,

I'd like to create AUR package for Arch-based Linux distros.
For me, it would be really helpful if the next versions of the font would be tagged (or marked as a release).

Would it be possible?

Thank you,

**Comment by radmen** [comment]
oh, wow. The [package](https://aur.archlinux.org/packages/jetbrains-mono/) is already on AUR. I guess I have nothing to do here :)

Going to close this issue.

**Comment by MinchinWeb** [comment]
The link seems to have changed. [New link](https://aur.archlinux.org/packages/fonts-jetbrains-mono/)
