### ISSUE TITLE
Character order in Font Book is odd

### ISSUE THREAD

**Issue by AlsoScratch** [JetBrains/JetBrainsMono#170]
<img width="432" alt="Screenshot 2020-03-12 at 12 36 13 AM" src="https://user-images.githubusercontent.com/48752273/76440921-8eae1000-63f9-11ea-8fc7-df23a6934cd4.png">
Why is capital H first? And what's up with the other letters that are out of order?

**Comment by nifanic** [comment]
[Hamburgevons](https://en.wikipedia.org/wiki/Hamburgevons)

**Comment by AlsoScratch** [comment]
I don't see any sign of that.

**Comment by nifanic** [comment]
That's what characters JetBrains people started to design font from.

"Hamburgevons" is an array of chars used in font design to evaluate font's look-n-feel.

Why does the order of chars matters for you? Trying to be difficult? 🙃

**Comment by AlsoScratch** [comment]
Font Book is the macOS font preview app. It has a view where you can see the characters in the font. Normally you'd expect it to be **A B C D E** and so on.
<img width="416" alt="Screenshot 2020-03-12 at 1 58 42 PM" src="https://user-images.githubusercontent.com/48752273/76491911-d2406280-6469-11ea-88e3-fe8de4cb9cb7.png">

But in JBM we see that capital `H` is out of place with the rest of the letters. Then it's followed by `n` `p` `o` `i` `l` `O` `h` `k` `g`.

I don't see the slightest bit of "Hamburgevons" in the order.

**Comment by AlsoScratch** [comment]
Can anyone explain why the letters don't appear in a way that makes sense? Perhaps you can consider Unicode order?

**Comment by philippnurullin** [comment]
@AlsoScratch This is a bug of Font-Lab (editor in which JetBrains Mono is made). When creating a font in this editor it assigns the Post-Script numbers to glyphs in order of creation, with no future possibility of changing it. 
I'm researching the ways to get rid of it, but because its don't influence any important experience the priority is low.

**Comment by AlsoScratch** [comment]
How feasible is Unicode order?

**Comment by philippnurullin** [comment]
@AlsoScratch Right now i see 2 options: 
- Rebuild font in new files from scratch by manually creating glyphs in right order, & paste the contour after.
- Try to switch to another font editor. Glyphs for example.

Both are problematic.

**Comment by AlsoScratch** [comment]
I know nothing about Font Lab, but shouldn't there be some setting to sort by Unicode or something? If not, maybe you could request it to them as a feature?

**Comment by nifanic** [comment]
I think, this is the order designers started to draw the letters in Font Lab. As fas as I know, it's impossible to change the order after the font is complete. 

When working on my fonts, I was experiencing the same problem when pasting drawn letters from _Illustrator_ to _Font Lab_ strictly in the order of appearance. Haven't tried current, 7th, version of _Font Lab_. Maybe now the order is changeable.

The order of appearance is not a problem. I think, you are asking a little bit too much for a free font.

**Comment by AlsoScratch** [comment]
Sometimes I want to be able to copy characters from Font Book but this strange order can make it difficult to know where the desired character is.

**Comment by philippnurullin** [comment]
FontLab added function to sort glyphs, just didn't know this was fixed. 
Will be fixed in v1.0.5.

**Comment by BornForFever** [comment]
@AlsoScratch Does that matter?
