### ISSUE TITLE
Consider putting ligature and no ligature versions in different folders

### ISSUE THREAD

**Issue by AlsoScratch** [JetBrains/JetBrainsMono#171]

**Comment by nifanic** [comment]
What's the point to have a **standalone non-ligature version** in first place, if you can switch the ligature feature on/off with your IDE (or even OS-wide)?

It's uneccessary overengineering.

**Comment by AlsoScratch** [comment]
Disable ligatures OS-wide... is that even possible?

**Comment by nifanic** [comment]
OS-wide is a bit too optimistic, but still font ligatures should've an ability to be turned on/off with IDE?

**Comment by AlsoScratch** [comment]
> OS-wide is a bit too optimistic, but still font ligatures should've an ability to be turned on/off with IDE?

Well, it depends on what you're using. I was simply talking about how the files are organized in the zip download file.

**Comment by alexeyten** [comment]
> What's the point to have a **standalone non-ligature version** in first place, if you can switch the ligature feature on/off with your IDE (or even OS-wide)?
> 
> It's uneccessary overengineering.

See #19

**Comment by Diablo-D3** [comment]
I'd rather not have ligatures anywhere on my monospace coding fonts, as they are a distraction and make it unclear what I am looking at. I also would prefer a standalone non-ligature version.

**Comment by alexeyten** [comment]
There _is_ a non-ligature version. 

> I also would prefer a standalone non-ligature version.

**Comment by philippnurullin** [comment]
@Diablo-D3 You can find the No Ligature version in `.ttf` format. It called **JetBrains Mono NL**. Here is a link https://github.com/JetBrains/JetBrainsMono/tree/master/ttf

**Comment by Diablo-D3** [comment]
Ahh, that wasn't here the last time I evaluated this font. I seem to have misunderstood the point of this ticket.

**Comment by philippnurullin** [comment]
Ok, at this point i'm 99% sure the file structure won't change. So there will be no separate NL folder.
Sorry, closing this issue.

**Comment by DannyBen** [comment]
> Ok, at this point i'm 99% sure the file structure won't change. So there will be no separate NL folder.

What is the downside of changing folder structure?
I would also prefer the NL version to live in its own folder, especially since sort order of the files (in some systems I guess) makes it so the filenames for TTFs with ligatures are interrupted in the middle by the NL ones (`JetBrainsMono-MediumItalic` followed by all the `*NL*` ones, followed by `JetBrainsMono-Regular`).

Like this, it is just messy - and people usually only use one or the other.

**Comment by CodeCrazy-ywt** [comment]
Yes, as you can see, filenames are a little messy.
![无标题](https://user-images.githubusercontent.com/62426149/128184653-6964eb5b-af6e-4e8d-9b85-3640aa571f31.png)
@philippnurullin IMHO it will be really much more convenient for users if you put NL into a standalone folder. Why not consider it?
