### ISSUE TITLE
Powerline font is taller than line height in v1.0.4

### ISSUE THREAD

**Issue by msjohal** [JetBrains/JetBrainsMono#172]
Powerline separator height taller than the line height, in v1.0.3 the height was correct. This was in alacritty on MacOS
<img width="86" alt="Screen Shot 2020-03-11 at 10 49 22 AM" src="https://user-images.githubusercontent.com/6979119/76447707-591c0f00-6386-11ea-8d7e-5915dd4c02ff.png">

**Comment by philippnurullin** [comment]
@msjohal Yes, the height of _arrow elements_ was increased to match Box Drawing. What IDE you using?

**Comment by msjohal** [comment]
That was in neovim

**Comment by delphinus** [comment]
I think it depends on the terminal you use. @msjohal  I see them with the valid size in my env (iTerm2).

**Comment by msjohal** [comment]
I still see the issue in iTerm2, it's only slightly larger, but it's still larger
<img width="88" alt="Screen Shot 2020-03-15 at 5 08 36 PM" src="https://user-images.githubusercontent.com/6979119/76713679-ab8b6180-66df-11ea-9823-88ebb0931c02.png"> Both screenshots are with font size 13.

**Comment by delphinus** [comment]
I see. I found it depends on some settings in iTerm2.

<img width="1042" alt="スクリーンショット 0002-03-16 19 19 12" src="https://user-images.githubusercontent.com/1239245/76746707-49079380-67bb-11ea-9b88-0f90b8a83d16.png">

When you disable this option (choose: `Never`), you can see the triangle sticking out.

<img width="640" alt="スクリーンショット 0002-03-16 19 33 53" src="https://user-images.githubusercontent.com/1239245/76747991-5f165380-67bd-11ea-9491-84b515c74011.png">

When enabled, it almost disappears, but I can see 1x2 dots.

<img width="639" alt="スクリーンショット 0002-03-16 19 33 22" src="https://user-images.githubusercontent.com/1239245/76748116-8bca6b00-67bd-11ea-8b6c-06b3e43f8316.png">

FYI: iTerm2 has built-in Powerline glyphs in it. So you can see perfect triangles with using the option: `Use built-in Powerline glyphs`.

<img width="641" alt="スクリーンショット 0002-03-16 19 34 17" src="https://user-images.githubusercontent.com/1239245/76748281-d51aba80-67bd-11ea-926b-f395e34fe6cc.png">

**Comment by philippnurullin** [comment]
Fix will be in v1.0.5

**Comment by philippnurullin** [comment]
Feel free to reopen if you you experiencing some bugs with new release.

**Comment by felixse** [comment]
![image](https://user-images.githubusercontent.com/30559812/77639840-a937cb80-6f59-11ea-8e8c-7a6663c737e3.png)

Arrows are not rendered (just a thin line if you look closely) in vscode and Fluent Terminal (both based on xterm.js) since the 1.0.5 update. No problems in Windows Terminal though

**Comment by philippnurullin** [comment]
@felixse Sorry for the stupid questions. Did you removed the old version of the font first? If not please remove it first, after reinstall the latest update & restart, to be sure.
If problem is still present please create a new issue, or drop me a line & i will do it.
