### ISSUE TITLE
font rendering in gvim is short and fat than pycharm, the 'f' is very clear.

### ISSUE THREAD

**Issue by dantezhu** [JetBrains/JetBrainsMono#174]

**Comment by dantezhu** [comment]
in pycharm: very pretty, the 'f' is tall.
![image](https://user-images.githubusercontent.com/1105212/76630024-4833ef00-657a-11ea-9463-ad590a6ca369.png)

but in gvim, short and fat, I dont know why...
![image](https://user-images.githubusercontent.com/1105212/76630134-71547f80-657a-11ea-9f22-55d1cb5318e4.png)

**Comment by dantezhu** [comment]
so, is there any solution? thanks ~~

**Comment by AlsoScratch** [comment]
I suggest comparing it to the height of the lowercase letter `l` under the same settings; it should be the same height.

**Comment by philippnurullin** [comment]
@dantezhu Hi, what version of the JetBrains Mono installed in your OS? Looks like the difference in font rendering method, but need more info.

**Comment by dantezhu** [comment]
@philippnurullin hi, my font version is 1.0.4

**Comment by philippnurullin** [comment]
Yes this is definitely the difference in methods of font rendering. So fixing the overall fatness of symbols is not possible. This is on gvim. Maybe you can change the _antialiasing_ in settings from _subpixel_ to _grayscale_. In some cases it gives a slighter more thin result. 

As for the ascenders (the upper elements in letters) they height is indeed must be like the capital letters, so i suppose the version you looking at in PyCharm is an old one bundled in it. So generally i recommend to remove the bundled version from IDE (instructions→https://github.com/JetBrains/JetBrainsMono/issues/142), but you don't like the current state of the Font. 

In version with the lighter weights the height of ascenders and capitals is a bit tuned, so wait till its released & see if you like it.
