### ISSUE TITLE
maybe `i1` is too close

### ISSUE THREAD

**Issue by bluelovers** [JetBrains/JetBrainsMono#176]
![image](https://user-images.githubusercontent.com/167966/76734392-cfad7800-679d-11ea-909c-88db944ac72a.png)

**Comment by philippnurullin** [comment]
Hi @bluelovers . To be precise the problem is that the empty space between the letter is not enough? Or is it you suggesting that the symbols looking similar?

**Comment by bluelovers** [comment]
i mean they looks similar at small font

**Comment by philippnurullin** [comment]
I'll see what can be done. Expect an update in v1.0.5

**Comment by BornForFever** [comment]
I suggest cancelling the bottom serif in either 1 or i (as a stylistic set)

**Comment by philippnurullin** [comment]
@BornForFever Maybe in future.
