### ISSUE TITLE
Source files require non-free tools (FontLab) — please consider switching to e.g. FontForge

### ISSUE THREAD

**Issue by andrewshadura** [JetBrains/JetBrainsMono#178]
Hi,

The source for the fonts currently comes in the FontLab format leading to the inability to make changes and rebuild the font files, effectively voiding the rights to the source (*the preferred form for making modifications*) granted under the license unless a valid license for FontLab is also held; moreover, if someone proceeds and uses the TTF output as the base for their modifications, they cannot fulfil the requirement to provide the source themselves.

One consequence of this is limiting contributions from the community, which currently have to either come in the form of bug reports or feature requests, or pull requests from owners of FontLab licenses only. Another consequence of this is that e.g. in Debian the font has to be packaged either in `non-free` or `contrib` repository since it cannot be rebuild from the provided source.

Please consider switching to FontForge or another free font toolchain.

**Comment by philippnurullin** [comment]
We definitely wont switch to FontForge but i can export files in .UFO file format & add them in the next update. I'm not 100% sure it won't break anything. As i know the TT hinting is not surviving this transfer. But right now we use _ttfautohint_, so it's not a problem.

**Comment by andrewshadura** [comment]
Well, that’s not quite the point… I’m talking about the *preferred form for making modifications*, so it has to be the primary source you build from as well. Otherwise the license grant is moot and doesn’t work.

**Comment by andrewshadura** [comment]
Having UFO sources would surely be better than nothing but it still makes the recipients of them second-class users and *not* receivers or the actual source.

**Comment by andrewshadura** [comment]
It also doesn’t help with contributions: e.g. if I contribute changes into the UFO source, you’d either have to do a potentially three-way merge or tell me to produce a FontLab file, which I cannot do without getting a license.

**Comment by philippnurullin** [comment]
Added the source files in .ufo format. 
I'm sorry that can't help you more. Closing this issue because nothing more can be done.

**Comment by philippnurullin** [comment]
Had to rollback the previous release.
The new one have the UFO. It have some issues but can be worked with.
