### ISSUE TITLE
Make the website of JetBrainsMono font open source

### ISSUE THREAD

**Issue by cata0309** [JetBrains/JetBrainsMono#18]
Hello ! 
I really like the homepage of the JetBrains Mono font that I also like a lot and I really think I could learn from it as it includes a lot of things ! The problem is that I need to struggle with the inspect element tool of the browser. Is there any chance it will go Open Source like the font it's presenting ?
Thank you !
(It could be added to a github pages branch on this repository)

**Comment by yole** [comment]
The page is part of the jetbrains.com Web site, which is not open-source, and there are no plans to open-source it.

**Comment by cata0309** [comment]
I understand, thank you!
