### ISSUE TITLE
<*> breaks in konsole

### ISSUE THREAD

**Issue by gsbhasin123** [JetBrains/JetBrainsMono#180]

**Comment by gsbhasin123** [comment]
![image](https://user-images.githubusercontent.com/48339289/76910574-a0653c80-686b-11ea-871e-0e093fe7e2e9.png)
this is how <*> looks in konsole. it works in vscode so I'm not sure what the issue is

**Comment by gsbhasin123** [comment]
I'm using release v1.0.4

**Comment by philippnurullin** [comment]
@gsbhasin123 Yes this is interpolation bug. Will be fixed in v1.0.5. Thanks for feedback!

**Comment by gsbhasin123** [comment]
Thanks!
Also, by "working in vscode", I meant that the ligature doesn't show at all, it just shows the regular symbol :p 
Would you know when 1.0.5 will be released?

**Comment by philippnurullin** [comment]
In 2—3 weeks.
