### ISSUE TITLE
Have you considered Google Fonts?

### ISSUE THREAD

**Issue by AlsoScratch** [JetBrains/JetBrainsMono#181]
Are you considering making JetBrains Mono available on Google Fonts?

**Comment by philippnurullin** [comment]
Yes, but the process is on hold right now.

**Comment by AlsoScratch** [comment]
Good to know 👍

**Comment by rcastellotti** [comment]
Any updates?

**Comment by inferno986return** [comment]
I would like an update. We aren't the only people who want this. 😃

https://github.com/google/fonts/issues/2308

**Comment by philippnurullin** [comment]
Nice to see!
Sadly, can't say anything new. When the lighter weights will be ready, we will continue the process.

**Comment by philippnurullin** [comment]
Please follow this issue https://github.com/JetBrains/JetBrainsMono/issues/99
