### ISSUE TITLE
>= ligature and XML-like tags

### ISSUE THREAD

**Issue by thewilkybarkid** [JetBrains/JetBrainsMono#183]
Spotted this problem with the ligature for `>=`:

<img width="597" alt="Screenshot 2020-03-19 at 11 22 33" src="https://user-images.githubusercontent.com/1784740/77062764-6fece200-69d4-11ea-9439-6339079447cc.png">

Is it possible to disable when it's the closing bracket of an XML-like tag?

**Comment by philippnurullin** [comment]
Hi, this problem was solved in v1.0.3. Please update to the latest version https://github.com/JetBrains/JetBrainsMono/releases

**Comment by thewilkybarkid** [comment]
Can confirm it's fine. Also switched to Brew to make updates easy. 👍

**Comment by philippnurullin** [comment]
Glad to hear. Have a nice day!
