### ISSUE TITLE
I found some bugs

### ISSUE THREAD

**Issue by BornForFever** [JetBrains/JetBrainsMono#184]
Hello @JetBrains ,

Your Jetbrains Mono font really appeals to me and I have fallen in love with this font. However, symbols like `<-` , `<==` and `<*>` looks wrong. Could you fix them? Big Thanks!
![批注 2020-03-20 211303](https://user-images.githubusercontent.com/62426149/77166967-1f6aa700-6af0-11ea-920c-2f410fec2047.png)
![批注 2020-03-20 211332](https://user-images.githubusercontent.com/62426149/77166975-22659780-6af0-11ea-8e19-20a3fff6fcb9.png)

**Comment by philippnurullin** [comment]
The bug with `<*>` is duplicated https://github.com/JetBrains/JetBrainsMono/issues/180. If its bothering you you can roll back to v1.0.3.

`<-` `<==` will be fixed in v1.0.5.

**Comment by BornForFever** [comment]
Please ignore `<-` and `<==` because they're already fixed in v1.0.4. However, I was using v1.0.3 when I opened this issue. 😄

**Comment by philippnurullin** [comment]
Thanks for updating! Because the bug with `<*>` is duplicated i'm closing this issue.
