### ISSUE TITLE
Charecter Request

### ISSUE THREAD

**Issue by CodeCrazy-ywt** [JetBrains/JetBrainsMono#187]
Some of the latin letters: ǎǒǐǔǖǘǚǜ
They are not supported and are shown in tofus.

**Comment by philippnurullin** [comment]
What languages using thees symbols?

**Comment by AlsoScratch** [comment]
They're used in Mandarin Pinyin.

**Comment by BornForFever** [comment]
Yes. Normally we don't use pinyins when writing code, but some people feel uncomfortable.
