### ISSUE TITLE
At the 10pt on non retina 0 looking like 8

### ISSUE THREAD

**Issue by philippnurullin** [JetBrains/JetBrainsMono#188]
![image](https://user-images.githubusercontent.com/48058957/77520251-fbadb500-6e91-11ea-9910-6d89e080d419.png)

**Comment by AlsoScratch** [comment]
Have you tried slashed zero?

**Comment by AlsoScratch** [comment]
The problem I see is that the middle part of the 8 shouldn't be so thick.
Anyway, have you tried slashed zero?

**Comment by BornForFever** [comment]
Enable the stylistic set 'zero' if your editor supports. e.g. if you're using vscode, add `"editor.fontLigature": "'zero'"` to the `settings.json` file.

**Comment by AlsoScratch** [comment]
Understood, but the problems I see @philippnurullin have are:
- It's not clear the dot in the zero is detached from the sides
- The contours of the sides of the 8 are not clear enough, failing to give the proper '8' shape

**Comment by philippnurullin** [comment]
The problem is cannot be solved by changing zero to slashed. It doesn't make any difference in small size. The possible solution is make sset with zero with different form.

**Comment by epa** [comment]
I find that even on a hi-dpi display the 0 and 8 are hard to tell apart.

When programming, distinguishing 0 from O is only moderately important.  It just isn't a common mistake to mix them up, beyond the most basic beginner level.  Unless you write l33tspeak you won't have long runs of characters where 0 and O both appear.  And if you do somehow muddle them, almost any programming language will give a syntax error.

But 0 and 8, on the other hand, commonly appear next to each other in numbers and there is no warning or error from the computer if you confuse them.  It's more important for a typeface to have a clear distinction between the different digits than it is between 0 and O, or 2 and Z, 1 and I, etc.

I think you should reconsider the dotted zero and either make it a much smaller dot, or have the 0 as a thin ellipse without dot.

**Comment by philgyford** [comment]
For what it's worth, having been the one to point this out and so feeling somehow responsible, here are some other examples of typefaces I happened to have installed, all in MacVim at 10px using Solarized theme.

![Screenshot 2020-04-28 at 10 34 05](https://user-images.githubusercontent.com/66670/80472173-48c2f200-893c-11ea-8aab-6a12b39ff0b3.png)

Zoomed 400%:

![Screenshot 2020-04-28 at 10 34 05 zoom](https://user-images.githubusercontent.com/66670/80472482-ae16e300-893c-11ea-901d-68597f588f42.png)

Some are easier than others to distinguish, even with dots or slashes. But I wouldn't presume to tell the designers how best to fix this for JetBrainsMono :)

**Comment by jozsefk9** [comment]
> For what it's worth, having been the one to point this out and so feeling somehow responsible, here are some other examples of typefaces I happened to have installed, all in MacVim at 10px using Solarized theme.
> 
> ![Screenshot 2020-04-28 at 10 34 05](https://user-images.githubusercontent.com/66670/80472173-48c2f200-893c-11ea-8aab-6a12b39ff0b3.png)
> 
> Zoomed 400%:
> 
> ![Screenshot 2020-04-28 at 10 34 05 zoom](https://user-images.githubusercontent.com/66670/80472482-ae16e300-893c-11ea-901d-68597f588f42.png)
> 
> Some are easier than others to distinguish, even with dots or slashes. But I wouldn't presume to tell the designers how best to fix this for JetBrainsMono :)

I can distinguish better without zoom in :-) By the way, "a" and "o" in Monaco are almost the same.

**Comment by riggs** [comment]
The lack of distinction between the characters 0 8 B is my biggest criticism of the font. I've been using it since it came out, but have been dealing with a lot of hex opcodes recently where this issue is thrust front & center for me:
<img width="224" alt="Screen Shot 2020-09-03 at 9 09 10 PM" src="https://user-images.githubusercontent.com/584232/92191723-18c7b600-ee2a-11ea-8094-434d1318f9ef.png">

**Comment by cata0309** [comment]
Try the latest version, the zero has been improved

**Comment by philippnurullin** [comment]
@riggs This looks like one of the old releases of JetBrains mono on your screen. Try to upgrade to the latest version & see if you have more pleasant experience.

Overall, thanks for the input. I'll see what can be improved.

**Comment by BornForFever** [comment]
Yeah, this is v1.0.3.

**Comment by riggs** [comment]
It's the current version in the 3 JetBrains IDEs I use (and update) regularly, so perhaps something could be done to include font updates more expediently.

**Comment by trygveaa** [comment]
Unfortunately, I think the 8 looks worse in 2.200 on my machine. It's a lot less clear in the middle and seems to be squished together.

2.200:
![image](https://user-images.githubusercontent.com/601966/96754393-87a8a080-13d1-11eb-9451-84af94ac22af.png)

2.002:
![image](https://user-images.githubusercontent.com/601966/96754477-a149e800-13d1-11eb-88f1-4ae4ead19ebc.png)

This is with font size 11 in the kitty terminal emulator on Arch Linux, using a 1920x1080 96 DPI display.

**Comment by jozsefk9** [comment]
This is 2.200, 9pt, Konsole:
![jetbrains mono 2 200 9pt_20201022_075826](https://user-images.githubusercontent.com/1645288/96831034-9f693e80-143c-11eb-8c34-94d314dde0cf.png)
Works fine for me.

**Comment by philippnurullin** [comment]
The original request was that the `8` is too similar to `0` + `B` was added to the list later.
Here is a comparison. The difference in letters is achieved so i'm closing this issue.

<img width="52" alt="Screenshot 2020-10-22 at 11 42 18" src="https://user-images.githubusercontent.com/48058957/99238468-cf70eb00-280a-11eb-9643-f6e55d09f3b2.png">
<img width="523" alt="Screenshot 2020-11-16 at 12 52 11" src="https://user-images.githubusercontent.com/48058957/99238475-d26bdb80-280a-11eb-84c7-eaa36567c012.png">
 
@trygveaa Yes indeed the `8` can be made a bit wider. I will try to improve it the next update.

**Comment by CodeCrazy-ywt** [comment]
Hey, so when will it be modified? At present the figure 8 construction looks inconsistent with font.
