### ISSUE TITLE
Powerline arrows not rendered

### ISSUE THREAD

**Issue by felixse** [JetBrains/JetBrainsMono#189]
![image](https://user-images.githubusercontent.com/30559812/77641322-29f7c700-6f5c-11ea-8dd2-af3e1e2932be.png)

Arrows are not rendered (just a thin line if you look closely) in Visual Studio Code and Fluent Terminal (both based on xterm.js) since the 1.0.5 update. No problems in Windows Terminal though

Problem still occurs after removing, restarting and reinstalling the font

**Comment by philippnurullin** [comment]
@felixse Found this issue. May be related https://github.com/microsoft/vscode/issues/84432
We will try to reproduce and understand what can be done from font perspective.

**Comment by william-shuman** [comment]
I'm seeing this same behavior with tilix and gnome-terminal.  I'm using powerline10k theme for zsh and after I updated to 1.0.5 the arrows disappeared.  It looks like it is trying to use U+EOBO to display the arrow.

**Comment by philippnurullin** [comment]
We reproduced the issue. Still don't know what causing it tho but we are looking.
@william-shuman U+EOBO is a correct unicode for the arrow symbol.

**Comment by qiaojunfeng** [comment]
I am experiencing the same issue, recent update breaks powerline right arrow.
For other fonts, this right arrow can correctly render.

**Comment by philippnurullin** [comment]
We found whats causing this bug. Expect fix in v1.0.6 at first half of next week. 
For now you can go back to v1.0.4 https://github.com/JetBrains/JetBrainsMono/releases/tag/v1.0.4
Thanks for patience.

**Comment by rdhar** [comment]
> ![image](https://user-images.githubusercontent.com/30559812/77641322-29f7c700-6f5c-11ea-8dd2-af3e1e2932be.png)
> 
> Arrows are not rendered (just a thin line if you look closely) in Visual Studio Code and Fluent Terminal (both based on xterm.js) since the 1.0.5 update. No problems in Windows Terminal though
> 
> Problem still occurs after removing, restarting and reinstalling the font

Out of curiosity, what're you using to display the branch info in PowerShell @felixse? I've recently started using the latest PS7 within VS Code on Win10 so have much to learn :)

**Comment by philippnurullin** [comment]
Please try v1.0.6. Feel free to reopen this issue if problem persists.

**Comment by felixse** [comment]
VS Code:
![image](https://user-images.githubusercontent.com/30559812/80691126-1a761b80-8ad0-11ea-96ce-82c4d3ec6f77.png)

The arrows are rendering now, but the branch symbol is missing and the arrows seem to be a bit shorter than the row height. Also some line artefact line in VS Code.

Windows Terminal:
![image](https://user-images.githubusercontent.com/30559812/80691398-7e004900-8ad0-11ea-92ab-dba8887b011c.png)

Branch symbol is showing up here, but arrow still missing some height.

**Comment by philippnurullin** [comment]
Thanks for the update. 
1. The line between the arrow. Will be fixed in the next update.
2. The 100% correct arrow placement by vertical axis. I don't think it's possible. The yellow zone is not a glyph so it renders a bit different in different editors.

But i have an idea. What Line height you have in VS code terminal? 
You can search the settings.json for `"terminal.integrated.lineHeight"`

**Comment by felixse** [comment]
`terminal.integrated.lineHeight` is 1

Any idea why the branch symbol is missing? Looks like the initial bug, but this time only this symbol is affected

**Comment by philippnurullin** [comment]
I have a theory, that the contour of branch symbol is collapsing because of the incorrect line height. When the line height is too small it causing the bug. Why it happens is beyond my understanding but first we need to confirm it.

Ok, can you set the line height to 20 for the experiment?

**Comment by felixse** [comment]
line height is a multiplicator for font size and only affects the background. But I tried font sizes from 10 to 20 and the symbol never showed up

**Comment by philippnurullin** [comment]
It's a shame.
Please send the OS, VS code version, we will try to reproduce & experiment more.

**Comment by felixse** [comment]
Thanks for looking into this. Regardless of this I'm really enjoying the font 😃 

Windows 10 Enterprise Version 1909 Build 18363.815
Visual Studio Code 1.44.2
