### ISSUE TITLE
(Continuously updating)Bugs on some of the arrows

### ISSUE THREAD

**Issue by BornForFever** [JetBrains/JetBrainsMono#196]
`<- <-- <== <-< <=< <<- <<= <~ <~~ -< -<< =<< <-| <=| <-> <=> <==>`
They are rendered as arrows. However, the italic ligatures have holes in them.
![批注 2020-04-08 183852](https://user-images.githubusercontent.com/62426149/78775139-4cf89100-79c8-11ea-8086-08debb69a15f.png)
The bugs occured in v1.0.3(as mentioned in #184), and were fixed in v1.0.4, but occured again in v1.0.5.

**Comment by BornForFever** [comment]
Supplement: `<~` and `<~~` also has the problem.
![批注 2020-04-08 184831](https://user-images.githubusercontent.com/62426149/78775908-95fd1500-79c9-11ea-9623-3670353c3d67.png)

**Comment by BornForFever** [comment]
And these as well: `-< -<< =<<`

**Comment by philippnurullin** [comment]
This will be fixed in the next update. As you can see the corrupted 1.0.6 had the fix, so wait a bit more.
