### ISSUE TITLE
1.0.6 TTF on Windows 10 seems completely broken

### ISSUE THREAD

**Issue by thebertster** [JetBrains/JetBrainsMono#197]
Hi there,

Just updated from 1.0.5 to 1.0.6 and am seeing major issues with all the fonts (Regular seems to be the worst however) at all sizes in all programs.

![image](https://user-images.githubusercontent.com/24496378/78807155-968eaf00-79bb-11ea-9f3b-281bc407971e.png)
![image](https://user-images.githubusercontent.com/24496378/78807353-d9e91d80-79bb-11ea-8efa-798c753a5814.png)

Compared with 1.0.5:
![image](https://user-images.githubusercontent.com/24496378/78807089-7ced6780-79bb-11ea-82d7-118fa05c9aa9.png)

**Comment by thebertster** [comment]
(Tried removing/reinstall, reboot and clearing Windows Font Cache completely.)

**Comment by rwalravens** [comment]
Same thing on my machine, also Win10.

**Comment by philippnurullin** [comment]
Yes, the hinting is corrupted in v1.0.6

**Comment by philippnurullin** [comment]
Rolled back that disaster. Expect proper 1.0.6 soon.

**Comment by philippnurullin** [comment]
Closing this. Issue related to the old version.
