### ISSUE TITLE
JetBrains Mono taller than before in WebStorm 2020.1

### ISSUE THREAD

**Issue by adrianboimvaser** [JetBrains/JetBrainsMono#199]
JetBrains Mono got deformed when I updated WebStorm to 2020.1. Here are screenshots of IntelliJ IDEA, PhpStorm (font looks the same on both), and WebStorm, where it looks taller.
![image](https://user-images.githubusercontent.com/1104728/78817816-1f045400-79aa-11ea-80aa-040a1d22498c.png)
![image](https://user-images.githubusercontent.com/1104728/78817834-26c3f880-79aa-11ea-9b40-a9cc9f138609.png)
![image](https://user-images.githubusercontent.com/1104728/78817855-2e839d00-79aa-11ea-8d90-635f0bf243e8.png)

Please let me know how I can fix it.

**Comment by adrianboimvaser** [comment]
This is Window. Apparently the problem only applies to 13 points. 12 and 14 look the same everywhere.

**Comment by kyleseven** [comment]
I see the same thing in PyCharm 2020.1. Removing the bundled fonts like in #142 fixed the issue for me.

**Comment by philippnurullin** [comment]
Yes, it's working like intended. All the releases after 1.0.3 have updated hinting which is making letter more tall. It was a tuff decision, but we believe this rendering is more close to the original font concept.
More about this in this issue. https://github.com/JetBrains/JetBrainsMono/issues/131

**Comment by adrianboimvaser** [comment]
Too bad, I already got used to the buggy font :(

**Comment by adrianboimvaser** [comment]
v1.0.5 looks a lot more like what I have in IntelliJ. I removed fonts from jbr\lib\fonts in all products and installed global OS fonts. Thank you all for the help.

**Comment by philippnurullin** [comment]
@adrianboimvaser Glad to hear you fond a solution. I will close this issue then.

**Comment by Lanayx** [comment]
Looks like this should be reopened, I'm having the same issue with 2.001

**Comment by philippnurullin** [comment]
Hi @Lanayx , please provide screenshots of the old font & new.

**Comment by Lanayx** [comment]
@philippnurullin Sure, first is 1.6, second one is 2.001
![image](https://user-images.githubusercontent.com/3329606/87921804-bede7d00-ca83-11ea-9560-809c6ddabc58.png)
![image](https://user-images.githubusercontent.com/3329606/87921811-c1d96d80-ca83-11ea-8bff-f5d84a8a1b78.png)

**Comment by philippnurullin** [comment]
@Lanayx as you can see above in one of my comments, this change is intended. So no future fixes will be applied. Sorry to disappoint you. 

Yo can give your eyes time to adapt. If after 2—3 days you will find it hard on your eyes, i suggest trying other fonts with wide proportions like Source Code Pro.
