### ISSUE TITLE
REQ: Need a "Powerline" version

### ISSUE THREAD

**Issue by pulberg** [JetBrains/JetBrainsMono#2]
Powerline is a statusline plugin for vim, and provides statuslines and prompts for several other applications, including zsh, bash, tmux, IPython, Awesome and Qtile.

https://github.com/powerline/powerline

https://github.com/powerline/fonts

**Comment by willbarkoff** [comment]
This is the only thing stopping me from switching from Fira Code, and I think it's something that is important to a lot of people when picking a main programming font.

**Comment by AnimiVulpis** [comment]
Would this also include *Box Drawing* and *Block Elements*, or should I open another ticket?
It's very convenient that "Fira code" does include these because it avoids the need to care for font fallbacks in your fontconfig.

Example for *Box Drawing* characters:
```
┌─┐
┢━┥
┗┭┘
═╧╕
```
Example for *Block Elements*:
```
▁▂▃▄▅▆▇█
█
▉
▊
▋
▌
▍
▎
```

**Comment by ryoppippi** [comment]
I made powerline version of Jetbrains Mono
But it rejected maybe...
If you want, please use it!
https://github.com/JetBrains/JetBrainsMono/pull/28

**Comment by philippnurullin** [comment]
Hi @pulberg , in v1.0.2 we added the Powerline set of glyphs. Is it working for you?

**Comment by npupko** [comment]
@philippnurullin It doesn't work with Regular version for me. Only for Medium and ExtraBold

**Comment by philippnurullin** [comment]
@npupko What IDE you using?

**Comment by npupko** [comment]
@philippnurullin iTerm 2
Something cached. I've deleted the old fonts and everything began to work. 
Thanks. This solved the problem for me.
Think this issue may be closed

**Comment by RinsedSloth** [comment]
I am currently using the 1.0.2 version on Windows for WSL and Powershell and the powerline symbols are not displaying correctly, just as boxes for example using tmux. 

Just installed the fonts after a format so don't had an old version installed previously.

**Comment by hahuang65** [comment]
@npupko how did your fix your issue? I'm having the same problem. I uninstalled the font and reinstalled it but I'm still having the same problem.

**Comment by npupko** [comment]
@hahuang65 I just play a little with my iTerm2 settings.

**Comment by bs** [comment]
I'm also not able to get powerline characters to render in iTerm. Using the very latest, macOS. Not showing up in zsh, vim, or fish.
