### ISSUE TITLE
iterm/terminal symbols not showing

### ISSUE THREAD

**Issue by Limonkufu** [JetBrains/JetBrainsMono#200]
Hi, I can't see any of the symbols that are in the above image with this font. I am only seeing a question mark in a box. I checked #2 but I am not able to see them. I uninstalled the font and installed again. They are also not available in vscode terminal window.

<img width="594" alt="Screenshot 2020-04-08 at 21 58 45" src="https://user-images.githubusercontent.com/7647900/78833362-a66eb900-79e4-11ea-83fc-9a423551b8c9.png">

**Comment by philippnurullin** [comment]
Hi, believe this is related issue https://github.com/JetBrains/JetBrainsMono/issues/189
In v1.0.5 we had e problem with rendering Powerline symbols.
Workaround is to install v1.0.4 & wait for the v1.0.6 fixing this problem.
Let me know if this helps.

**Comment by philippnurullin** [comment]
@Limonkufu Did you have any luck with v1.0.4?

**Comment by Limonkufu** [comment]
@philippnurullin yeah 1.0.4 works fine but I went with Nerd Font Patched version since there were some symbols there I wanted.

**Comment by philippnurullin** [comment]
Nice! 
Can you send me the unicode numbers, meaning of this symbols/how you use them. It will be helpful for the future updates.

**Comment by philippnurullin** [comment]
Will close this because the problem not in the JB Mono.
