### ISSUE TITLE
Ligature request: /**

### ISSUE THREAD

**Issue by CodeCrazy-ywt** [JetBrains/JetBrainsMono#202]
In JavaScript and some other languages, `/**` marks the beginning of a doc comment, e.g.
```javascript

/**
 * Represents a book.
 *
 * @param {string} title Title of the book
 * @param {string} author Who wrote the book
 */
function Book(title, author) {
    this.title = title;
    this.author = author;
}
```
However, the `*` in `/*` is on the top, but `/**` is just `/` plus `**`. Isn't there a ligature for `/**`?
(English is not my mother language, so I may have some difficulty expressing my idea exactly.)
![批注 2020-04-09 190032](https://user-images.githubusercontent.com/62426149/78888908-33714b00-7a95-11ea-9653-6ad6fd76d3b6.png)

**Comment by philippnurullin** [comment]
Hi, it was removed because of this issue https://github.com/JetBrains/JetBrainsMono/issues/88

**Comment by BornForFever** [comment]
I came up with a better solution: if `/*` or `/**` follows or is followed by any character that matches this regex `\w|\.|/`, then disable it. Is it feasible?

**Comment by BornForFever** [comment]
I came up with a better solution: if `/*` or `/**` follows or is followed by any character that matches this regex `\w|\.|/`, then disable it. Is it feasible? _(I just realized that email reply don't support markdown😅)_

**Comment by philippnurullin** [comment]
Sadly this will be really hard to make in OpenType. There is no way to make complex rule as this. To work it needs "clear" instructions on every case.
I will try to think of a way, but don't see a better solution that removing the `/**`.

**Comment by BornForFever** [comment]
OK, I see.

**Comment by trygveaa** [comment]
> Hi, it was removed because of this issue #88

Hm, I don't see why that issue would cause a difference between `/*` and `/**`. Shouldn't the same rules apply for those two?

**Comment by BornForFever** [comment]
I also think so.

**Comment by philippnurullin** [comment]
Here is discussion about this ligature from Fira Code community https://github.com/tonsky/FiraCode/issues/367

The problem i see here is https://github.com/tonsky/FiraCode/issues/219 & it will affect the case @BornForFever set as example.

I agree with Nikita (Tonsky) here. Removing `/**` seems like a good compromise.

**Comment by tomByrer** [comment]
> Removing `/**` seems like a good compromise.

I think so also.
Unless there is a way to detect the beginning of lines in OpenType?
Or as a compromise to the compromise, is the have only the italic version have the ligature (since comments are almost always italics).?

**Comment by philippnurullin** [comment]
@tomByrer but it won't fix the problem with shifted asterisks. It's a main problem.

**Comment by trygveaa** [comment]
> Unless there is a way to detect the beginning of lines in OpenType?

I think doing something specific when it's the beginning of the line is a bad idea. Comments are often indented, and would be weird if that's different from the beginning of the line.

**Comment by BornForFever** [comment]
> It might be a good idea to turn those ligatures off for `/*/` and `/**/` (and perhaps `/*.`)

Is it possible?

**Comment by philippnurullin** [comment]
@BornForFever The /*/, /**/ sequence removed in 1.0.6 This will be the next update.

**Comment by philippnurullin** [comment]
Added back this ligature. Grab the files here https://github.com/JetBrains/JetBrainsMono/tree/master/fonts
Added some exclusions so the #88 woun't be a problem. If you find more conflicts feel free to create a new issue.
