### ISSUE TITLE
v1.0.5 and v1.0.4 unicode not rendering in OSX

### ISSUE THREAD

**Issue by hahuang65** [JetBrains/JetBrainsMono#203]
I'm not able to render unicode glyphs. They all show up as a square with a ? in it.
I'm using the exact same font files on my Linux box (literally the exact same file cuz they're checking into my dotfiles directory) and it works fine over there.

Here's what it looks like
![Screen Shot 2020-04-09 at 10 45 44 AM](https://user-images.githubusercontent.com/280972/78924821-495c1d00-7a4f-11ea-866c-643ff07f207f.png)

I've tried this not only in vim inside iTerm, but also in Atom. Both have issues rendering.
These are specifically the glyphs I've been trying to render:

"\uf110"
"\uf129"
"\uf071"
"\uf05e"
"\uf00c"

I saw https://github.com/JetBrains/JetBrainsMono/issues/200 so I tried v1.0.4 and it's the same issue.

Anyone had any similar experiences?

**Comment by philippnurullin** [comment]
Hi, @hahuang65 we will try to reproduce. Please add the exact software versions.

**Comment by hahuang65** [comment]
macOS 10.14.6 (18G3020)

iTerm2 Build 3.3.2

Vim:

```
$ vim --version
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr  4 2020 14:33:44)
macOS version
Included patches: 1-500
Compiled by Homebrew
```

atom: 1.45.0

Anything that I'm missing?

**Comment by philippnurullin** [comment]
Sorry for misleading you. We don't support this glyphs. The are placed in private area, so there is no common containment in them. What you were expecting to see? Can you send the example with maybe other font rendering them?

**Comment by hahuang65** [comment]
It's definitely working on my Arch laptop:
![2020-04-10-005317_1411x768_scrot](https://user-images.githubusercontent.com/280972/78973938-b611fe80-7ac5-11ea-8f10-d2d4ff138810.png)

The glyphs I'm trying to render are from these instructions:
https://github.com/maximbaz/lightline-ale#using-icons-as-indicators

I'm able to write them in Vim by pressing (in insert mode) ctrl-v then u, then the corresponding code, so for example, for the checkmark, my keystrokes would be exactly:

```
<C-v>uf00c
```

And here's my font config for Alacritty on that machine:

```
$ awk 'NR >=68 && NR <=106' ~/.config/alacritty/alacritty.yml
font:
  # The normal (roman) font face to use.
  normal:
    family: JetBrains Mono # should be "Menlo" or something on macOS.
    # Style can be specified to pick a specific face.
    style: Retina

  # The bold font face
  bold:
    family: JetBrains Mono # should be "Menlo" or something on macOS.
    # Style can be specified to pick a specific face.
    style: Bold

  # The italic font face
  italic:
    family: JetBrains Mono # should be "Menlo" or something on macOS.
    # Style can be specified to pick a specific face.
    style: Italic

  # Point size of the font
  size: 12.0

  # Offset is the extra space around each character. offset.y can be thought of
  # as modifying the linespacing, and offset.x as modifying the letter spacing.
  offset:
    x: 0
    y: 0

  # Glyph offset determines the locations of the glyphs within their cells with
  # the default being at the bottom. Increase the x offset to move the glyph to
  # the right, increase the y offset to move the glyph upward.
  glyph_offset:
    x: 0
    y: 0

  # OS X only: use thin stroke font rendering. Thin strokes are suitable
  # for retina displays, but for non-retina you probably want this set to
  # false.
  use_thin_strokes: true
```

As you can see, there's no fallback font configured.

**Comment by philippnurullin** [comment]
I'm sorry to disappoint you, but there is some kind of fallback mechanism is involved. There is no such glyph in JetBrains Mono for now. I'm 100% sure, because a drew all of them. On the bright side i can add them in one of the next updates.

**Comment by hahuang65** [comment]
I believe you, but then I wonder what I did.

I've been using JetBrains Mono for at least 3 months now, haven't changed fonts.

Yesterday I attempted to add these glyphs. It didn't work, so I went to download Power line patched version of JetBrains Mono. On that GitHub page it mentioned you guys officially supported Powerline glyphs since 1.0.2.

So I downloaded latest version, and as soon as I did, the glyphs appeared.

**Comment by philippnurullin** [comment]
Can you send me the exact link to the patched version? Maybe you downloaded the NerdFont patched version & it having this icons. 
That's the freshest version i can find wit it https://github.com/ndtho8205/JetBrainsMono

**Comment by hahuang65** [comment]
I downloaded it directly from your repos Releases page. 1.0.5 version

**Comment by hahuang65** [comment]
I'll be more clear, sorry.

I found this page 
https://github.com/seanghay/JetBrainsMono-Powerline

But when I read that first few lines, I went directly to your releases page to download it

**Comment by hahuang65** [comment]
I just did an experiment.  I reverted my dotfiles (I keep my font in there) to the version I was running in January when I first installed JetBrains.

The glyphs still show up. I wonder what is going on here? What could the fallback be?

**Comment by hahuang65** [comment]
Okay, feel free to close this, or use it as the ticket to add those aforementioned glyphs. The kind people over at alacritty showed me how the font fallback system works, and so it's definitely coming from one of the fallbacks.

Thank you for your patience with me and the great support! Keep up the awesome work! I haven't stuck to a font for so long since I found Input. I really love JetBrains Mono!

**Comment by philippnurullin** [comment]
Glad to hear you found a solution & thanks for the kind words! 
We are working on making JetBrains even better. Stay tuned.

**Comment by hasanelfalakiy** [comment]
does the jetbrainsmono font support the Unicode symbols degrees, minutes and seconds?

**Comment by alexeyten** [comment]
> does the jetbrainsmono font support the Unicode symbols degrees, minutes and seconds?

Yes, it does.

![image](https://github.com/JetBrains/JetBrainsMono/assets/44377/4b1dee28-ff27-470a-af2b-cd5aa85692a7)

https://www.jetbrains.com/lp/mono/

**Comment by hasanelfalakiy** [comment]
okay thanks sir
