### ISSUE TITLE
Request to change ligature for ~= and add ligature for =~=

### ISSUE THREAD

**Issue by thebertster** [JetBrains/JetBrainsMono#204]
Currently the ligature for ~= is rendered as an "approximately equal to" glyph.

In Lua and Matlab, ~= means "not equal to" - using the approximately equals sign both looks strange and is prone to mis-reading, especially when scanning through code quickly.

I couldn't find any language where "~=" actually means "approximately equal to", so it would seem sensible to change this ligature to the "not equals" glyph (same as !=).

Just to note that the latest version of Fira Code has (finally) made this change after it was requested quite some time ago.

Also to note that in Perl, "=~=" actually does mean "approximately equal" so it would also make sense for this ligature to be added as the "approximately equal to" glyph.

**Comment by philippnurullin** [comment]
Nice, thanks for bringing that up. Will fix soon.

**Comment by philippnurullin** [comment]
`~=` will be removed the in the next update.

On the `=~=` need to think more. Found the discussion in Fira Code community: 
https://github.com/tonsky/FiraCode/issues/407 
https://github.com/tonsky/FiraCode/issues/143

**Comment by philippnurullin** [comment]
The change from `=~=` to "approximately equal" is to dramatic. Don't see a good way to implement that.
