### ISSUE TITLE
U+220F N-ARY PRODUCT and U+2210 N-ARY COPRODUCT are too short

### ISSUE THREAD

**Issue by dscorbett** [JetBrains/JetBrainsMono#205]
As <var>n</var>-ary operators, U+220F N-ARY PRODUCT and U+2210 N-ARY COPRODUCT should be as tall as U+2211 N-ARY SUMMATION.
![∏∐∑](https://user-images.githubusercontent.com/1124347/78954232-75a48780-7aa9-11ea-9bd0-5403df1aeb86.png)
The current glyphs for U+220F and U+2210 would be appropriate for U+03A0 GREEK CAPITAL LETTER PI and U+2A3F AMALGAMATION OR COPRODUCT, their cap-height counterparts.

**Comment by philippnurullin** [comment]
Sounds legit. Will fix in the next update.
