### ISSUE TITLE
Misplaced crossbars on U+2020 DAGGER and U+2021 DOUBLE DAGGER

### ISSUE THREAD

**Issue by dscorbett** [JetBrains/JetBrainsMono#206]
The crossbar of U+2020 DAGGER is too low: it should be nearer the top, as in the guard of a dagger. The crossbars of U+2021 DOUBLE DAGGER are too near the middle: the top one should be at the height of U+2020’s and the bottom one should be the same distance from the bottom.
![†‡](https://user-images.githubusercontent.com/1124347/79050063-83672380-7bf5-11ea-85e8-f9d764d4e2ae.png)
The current glyph of U+2020 would be appropriate for U+27CA VERTICAL BAR WITH HORIZONTAL STROKE.

**Comment by philippnurullin** [comment]
Sounds legit. Will include in the next update.
