### ISSUE TITLE
Curly braces don’t align at certain font sizes in PyCharm

### ISSUE THREAD

**Issue by davidskeck** [JetBrains/JetBrainsMono#21]
When using {} in PyCharm, the curly braces don’t align at sizes 10-15. They always seem a little misaligned after that, but it is much better.

**Comment by latifrons** [comment]
![image](https://user-images.githubusercontent.com/1080266/72495721-7b9c1b00-3862-11ea-9a10-6c2d99836148.png)

![image](https://user-images.githubusercontent.com/1080266/72495751-85be1980-3862-11ea-87c8-f9d7837b288f.png)


Agreed.

**Comment by artem1458** [comment]
Same in WebStorm. Size 13 
![image](https://user-images.githubusercontent.com/33227963/72500435-213c9380-383d-11ea-9a74-8c445c658d2a.png)

**Comment by svenbit** [comment]
Also happens on Jetbrains Rider 2019.3.1
![2020-01-16_16h29_40](https://user-images.githubusercontent.com/1471939/72511315-8b752880-387d-11ea-97b1-83625bc6ccd0.png)

Font size: 14
Line spacing: 1.0

**Comment by DominikPalo** [comment]
WS-193.5662.54

Font sizes: 12, 13, 14
Line spacing: 1.2


![image (4)](https://user-images.githubusercontent.com/1623257/72527594-6971ab00-3869-11ea-8850-bff51ca39805.png)
![image (3)](https://user-images.githubusercontent.com/1623257/72527595-6971ab00-3869-11ea-8bea-be6548c5f022.png)
![image (5)](https://user-images.githubusercontent.com/1623257/72527593-6971ab00-3869-11ea-89ec-b1a04e9f8fcb.png)

**Comment by philippnurullin** [comment]
Hi, it's a bug of the v 0.23 of the JetBrains Mono. Unfortunately, the bundled fonts is always have priority when IDE decided which to use. We are working on correcting this behaviour. This problem will be solved when v 1.0 will be bundled. 
You can try to fix it for now by switching to grayscale _antialiasing_ in Settings → Appearance

**Comment by pakLebah** [comment]
I don't see the misalignment on VS Code, XCode, IntelliJ, and TextEdit on my Mac.

![jetmono_bracket_alignment](https://user-images.githubusercontent.com/11470932/72573254-a4222480-38f7-11ea-895d-f1c807896d67.png)

**Comment by aaronbell** [comment]
Likely a slight misalignment between brace outlines. A custom CVT would also help lock these together.

**Comment by Renerick** [comment]
> This problem will be solved when v 1.0 will be bundled.

Any ETA on v1 bundle?

**Comment by gimmi** [comment]
Seems that this problem is still present in `v1.0.0` bundle, see the following screenshot from JetBrains Rider IDE:

![image](https://user-images.githubusercontent.com/6589/72725197-70f4c500-3b85-11ea-8a54-5d42aec1c98e.png)

**Comment by Renerick** [comment]
Workaround found in #49 - remove bundled font and install latest version from the site systemwide

**Comment by gimmi** [comment]
I am using the font downloaded from https://www.jetbrains.com/lp/mono/ but the issue is still there.

Here is the reported version:

![image](https://user-images.githubusercontent.com/6589/72726636-152c3b00-3b89-11ea-9eb5-d36b94dc9488.png)

**Comment by hntd187** [comment]
I did the same thing as @gimmi and the bracers are still mis-aligned.

**Comment by jtouati-keyyo** [comment]
Can confirm this is... a bit disturbing :)

Using latest IntelliJ Idea (2019.3.2) on Windows (didn't try downloading the font separately, but it doesn't seem to be making any difference anyway).

**Comment by dennis-f** [comment]
a workaround is to use the medium variant of the font. (using phpstorm + windows 10 @1080p)

**Comment by philippnurullin** [comment]
@gimmi Did you properly removed the bundled fonts? 

The files can be found in:

**Win**
1. `IDEA\jbr\lib\fonts`
2. If you using Toolbox `C:\Users\ username\AppData\Local\JetBrains\Toolbox\apps\CLion\ch-0\193.6015.37\jbr\lib\fonts\`

**Mac**
`IntelliJ\ IDEA.app/Contents/jbr/Contents/Home/lib/fonts/`

And it's important to restart.

**Comment by gimmi** [comment]
@philippnurullin It worked!

I'm using Rider, so I removed the JetBrains fonts from

`C:\Program Files\JetBrains\JetBrains Rider 2019.3.1\jbr\lib\fonts`

**Comment by davidskeck** [comment]
This issue is fixed in the latest version of PyCharm. Thank you!
