### ISSUE TITLE
Official page links to old version download

### ISSUE THREAD

**Issue by kolyshkin** [JetBrains/JetBrainsMono#213]
This is not a bug in the font itself, but I don't know where else to file it, thus filing here.

The official font page (https://jetbrains.com/mono/) has a download link, which currently (as of today) results in downloading version 1.0.3 of the font (JetBrainsMono-1.0.3.zip, released back in Feburary), while here on github the latest version is 1.0.5, released 22 days ago.

Serving the old font might result in people filing bugs that were already fixed, etc.

**Comment by kolyshkin** [comment]
@bulenkov PTAL

**Comment by shabahengam** [comment]
duplicate of #192

**Comment by kolyshkin** [comment]
Closed as a duplicate of #192
