### ISSUE TITLE
Why isn't there a ligature for `<--`?

### ISSUE THREAD

**Issue by gsbhasin123** [JetBrains/JetBrainsMono#214]
There are ligatures for `->`, `-->`, and `<-`. I fail to understand why a ligature for `<--` was not provided.

**Comment by trygveaa** [comment]
I get a ligature for `<--`. 
![image](https://user-images.githubusercontent.com/601966/79699872-6a640f80-8292-11ea-9c99-b7100419e872.png)

**Comment by gsbhasin123** [comment]
Ah, I guess this is an issue with the nerd font not having the latest version. Thank you!
