### ISSUE TITLE
Ligatures misaligned in multiline comments

### ISSUE THREAD

**Issue by mceyran** [JetBrains/JetBrainsMono#215]
The single remaining ligature that involves comments, namely the closing "*/", is misaligned with the other comment lines. See the following picture, where the asterisk is moved more to the bottom right, while the opening "/**" looks pretty normal.
![image](https://user-images.githubusercontent.com/6681908/79763330-39341f80-8324-11ea-802f-b311d92e95cd.png)

**Comment by BornForFever** [comment]
I hope the asterisk in `*/` can be aligned well with the asterisks above.

**Comment by Omnieboer** [comment]
I love that look when it's at the end of a line, but I guess /* */ comments instead of // comments in a single line are rarely used, if ever.

Still though, I still like the instant visibility of the end character of a comment block.
