### ISSUE TITLE
Tab character has the wrong width

### ISSUE THREAD

**Issue by PlusMinus0** [JetBrains/JetBrainsMono#217]
We use tabs in python. The attached image was made with these settings:
Tab width: 4
Indent width: 4
Actual indentation: 1,5?

![2020-04-22-080438](https://user-images.githubusercontent.com/11473351/79946437-478f5200-8470-11ea-93c2-f69f74012b2a.png)

**Comment by alexeyten** [comment]
There is no JetBrains Mono on your screenshot. Looks like Helvetica (Arial)

**Comment by PlusMinus0** [comment]
That might explain, why I can't find it in the dropdown, after it has been deselected. Will investigate further.

**Comment by PlusMinus0** [comment]
Okay, the actual bug was, that Pycharm selected the font although it was not installed.
