### ISSUE TITLE
Misaligned Height

### ISSUE THREAD

**Issue by rysktky** [JetBrains/JetBrainsMono#218]
Sometimes, the height of some **Large letters** and **numbers** are misaligned with some size.

-  This does NOT seem to happen with NL version.
-  This is NOT always reproducible. Even with the same settings, the problem only appears sometimes 
- Noticed this when I was changing font seizes, including zoom in and out, changing from the application menu.
-  Seems that NOT all editors/terminals are affected. (Seen on MS notepad and mintty for cygwin. Notepad++ or VSC seem to work OK)

![image](https://user-images.githubusercontent.com/39027949/79997790-e362a180-84f4-11ea-9f52-fb7d35ae0b3c.png)
Above shows some alphabets and 3 are lower.

![image](https://user-images.githubusercontent.com/39027949/79999767-481efb80-84f7-11ea-9494-d1ec04f7fb32.png)
with different size, now some large letters are taller.

![image](https://user-images.githubusercontent.com/39027949/80002192-4c004d00-84fa-11ea-9bac-94a35b82fdf9.png)
This has gone very bad.
 

*Work around
Set it to another font and set it back to JetBrainsMono may(or may not) fix the alignment.

Could this be a hinting bug of JetBrainsMono or 
a compatibility issue for some editors/terminals? (but not seen this with other fonts than JetBrainsMono)

**Comment by philippnurullin** [comment]
Hi @rysktky . We had similar report https://github.com/JetBrains/JetBrainsMono/issues/40
What version of the font you using?

**Comment by rysktky** [comment]
@philippnurullin 
Thank you for quick response!
I am using 1.0.5

**Comment by rysktky** [comment]
I saw the same symptom with with NL version today when I was using it with MobaXtrem.

**Comment by philippnurullin** [comment]
@rysktky Ok, then. We will need the info so we can reproduce the problems.
1. Name end version of editors. It will be nice to have a screenshot for each case. Or you can just add the editor info to the screens you already took.
2. OS with basic version.

**Comment by rysktky** [comment]
@philippnurullin , Here are some new pictures.

All taken with the same PC, Windows10 Enterprise 1803.
Previous screenshots were taken with the same PC with *mintty 3.1.4 with Cygwin (latest version)*

I cannot really reproduce this constantly, especially the one with lower 'R' which is the first screenshot of this thread.

Still don' t know what makes these differences.

![image](https://user-images.githubusercontent.com/39027949/80271243-79ffb000-86f9-11ea-8d1c-fe88b1c3a9bc.png)

**Comment by rysktky** [comment]
I just found that small letters are slightly misaligned sometimes as well.
(noticed this when typed 'vacuum')

![image](https://user-images.githubusercontent.com/39027949/80274219-d8d22300-8713-11ea-9e4d-bc5a3a7461c9.png)

Screenshots were taken with the same windows PC.

**Comment by mfocko** [comment]
Not sure if it's related, but I've noticed misaligned `[]` for Fira Code in Windows Terminal and only in Windows Terminal...

**Comment by rysktky** [comment]
I agree with @mfocko . I haven't seen this with my Gnome desktop on my Fedora.

By the way, I just found Wireshark goes really messy almost always with the same Windows PC.
Hope this helps you, @philippnurullin .



Version 3.2.3   (v3.2.3-0-gf39b50865a13)  ( Latest wire shark. Main window draws the same,,,)
![image](https://user-images.githubusercontent.com/39027949/80785754-52f32380-8bbc-11ea-8a6d-bdcadc291a78.png)

**Comment by archilkarchava** [comment]
I downgraded to v1.0.4 and the problem is gone now.

**Comment by rysktky** [comment]
Thanks for the awesome font and work!!

**Comment by philippnurullin** [comment]
@rysktky You are welcome. ))
