### ISSUE TITLE
JetBrainsMono not working on Linux

### ISSUE THREAD

**Issue by TrentonAdams** [JetBrains/JetBrainsMono#219]
It appears that the JetBrainsMono font either doesn't work properly on Linux, or won't activate, because this font does not look like JetBrainsMono...

You can see that it works on MacOS just fine, but not Linux.
![mono-macos](https://user-images.githubusercontent.com/534192/80150306-6a575e80-8575-11ea-8c47-42ace92a0957.png)
![mono-linux](https://user-images.githubusercontent.com/534192/80150335-72170300-8575-11ea-99a7-14d1803356f5.png)

**Comment by trygveaa** [comment]
The font definitely works on Linux. You probably have to provide some more info on what distro you are using, how you installed it, how your fonts are configured etc. for anyone to be able to help you.

**Comment by TrentonAdams** [comment]
It's LinuxMint. I didn't install the font it came with IDEA.  I don't really know anything other than.  I simply updated to the latest IDEA, and wanted to use the new font, but it's clearly not the JetBrainsMono font is it?    Maybe it is.  When I examine it letter by letter it seems to have the same shape of letters, but it just doesn't look quite as good.  Maybe it's MacOS font smoothing or something that makes it look better, but there's a clear difference.

**Comment by vladimir-poleh** [comment]
You have same font on both screenshots but MacOS version is bolder because of different font rendering engine. You can try install JetBrainsMono to the system and use Medium version (it is a bit bolder).

**Comment by philippnurullin** [comment]
@TrentonAdams Hi, can you specify what screenshot is which OS? 
Bothe are the JetBrains Mono. The difference may be in versions.

**Comment by TrentonAdams** [comment]
The first one is MacOS.

**Comment by TrentonAdams** [comment]
JetBrainsMono medium now looks like on my Mac.  Thanks.
