### ISSUE TITLE
ligature display error

### ISSUE THREAD

**Issue by Zheaoli** [JetBrains/JetBrainsMono#22]
When I input `<=|` in Idea 2019.3 

the display with ligature should be like this

![image](https://user-images.githubusercontent.com/7054676/72490915-797e9000-3853-11ea-8e36-858d9c3c7939.png)

But it's just like this

![image](https://user-images.githubusercontent.com/7054676/72490951-8f8c5080-3853-11ea-8c76-db0badbf5b90.png)

I'm sure I have already enable the font ligature

**Comment by cjmaxik** [comment]
It is not the case in other IDEs btw

**Comment by philippnurullin** [comment]
Hi, it's a bug of the v 0.23 of the JetBrains Mono. Unfortunately, the bundled fonts is always have priority when IDE decided which to use. We are working on correcting this behaviour. This problem will be solved when v 1.0 will be bundled.
To fix it you need to delete the bundled font from it installation folder. That makes the IDEs use the system-wide installed v 1.0

**Comment by philippnurullin** [comment]
@Zheaoli Did you try to remove the bundled font & install the latest? 

They can be found in:

**Win**
a) `IDEA\jbr\lib\fonts`
b) If you using Toolbox `C:\Users\ username\AppData\Local\JetBrains\Toolbox\apps\CLion\ch-0\193.6015.37\jbr\lib\fonts\`

**Mac**
`IntelliJ\ IDEA.app/Contents/jbr/Contents/Home/lib/fonts/`

And it's important to restart.

https://github.com/JetBrains/JetBrainsMono/issues/49
https://github.com/JetBrains/JetBrainsMono/issues/21
