### ISSUE TITLE
Italic capital height is inconsistent (F and russian О)

### ISSUE THREAD

**Issue by habamax** [JetBrains/JetBrainsMono#220]
Latest version.

![image](https://user-images.githubusercontent.com/234774/80200093-ce882a00-862a-11ea-99a0-17ba515e854b.png)

**Comment by philippnurullin** [comment]
@habamax Hi, is it reproducing with the 1.0.4?
Can you please add the editor (with its version) you using, OS steps to reproduce this issue.

**Comment by habamax** [comment]
not sure about 1.0.4 (will try to install and check)

win10, gvim

just checked other applications:
* wsltty -- ok
* notepad -- ok

![image](https://user-images.githubusercontent.com/234774/80205744-d0a2b680-8633-11ea-857d-ed631222a4b0.png)

**Comment by habamax** [comment]
Well, I can not reproduce it consistently :(

When I start gVim sometimes those letters have different height, more often it is ok. (default size 13).

When there is this issue with height -- increase font by 1pt and decrease it back "fixes" it.

**Comment by philippnurullin** [comment]
Thanks! Looks like this is related https://github.com/JetBrains/JetBrainsMono/issues/218

**Comment by habamax** [comment]
Yes, looks like the same (btw, I use NL version)
