### ISSUE TITLE
Ligatures request: /\ and \/

### ISSUE THREAD

**Issue by srghma** [JetBrains/JetBrainsMono#222]
the interesting question is how they will look inside the regex

```
/\s/
```

I think it should ligate, but height should be consistent

**Comment by alexeyten** [comment]
They was removed exactly because they looked wrong in regexps. https://github.com/JetBrains/JetBrainsMono/issues/78#issuecomment-578710304

**Comment by srghma** [comment]
also it should work even when surrounded by spaces

e.g. there is an issue in `https://github.com/tonsky/FiraCode/issues/1013`

**Comment by srghma** [comment]
> They was removed exactly because they looked wrong in regexps. [#78 (comment)](https://github.com/JetBrains/JetBrainsMono/issues/78#issuecomment-578710304)

hi, well, I understand, but maybe it should ligate only when surrounded by whitespace OR start/end of line

e.g. in haskell `\/` is either function. Example - `doOnLeft \/ doOnRight $ xxx`

**Comment by philippnurullin** [comment]
@srghma Hi, i will add this in one of the next updates.

**Comment by philippnurullin** [comment]
https://github.com/tonsky/FiraCode/issues/1013
