### ISSUE TITLE
Ligature Request: 'lambda' keyword in Python

### ISSUE THREAD

**Issue by ionutgoldan** [JetBrains/JetBrainsMono#223]
In Python there is a special keyword for defining lambda functions, namely `lambda`.
However, it's using a lot of characters & it's a bit cumbersome to read. *(Javascript has a simpler syntax, like `item => <some_expression>`.)*

Would it be possible to use an intuitive, single ligature character such as **λ**?
I *think* it could help catch up the better syntax alternatives from other languages.

Example:
```python
for obj in sorted(some_items, key=lambda item: item["some_key"])
    pass
```
vs
```python
for obj in sorted(some_items, key=λ item: item["some_key"])
    pass
```

**Comment by philippnurullin** [comment]
This looks like a potential show stopper. All the ligatures made to maintain the expected width of the line, by occupying the same amount of space as the original sequence of symbols. This ligature will modify the line width too much.

The only way to have this, is to make language sensitive ligatures, which may work in this case, or modify the syntax of the Python.

**Comment by trygveaa** [comment]
Even with language sensitive ligatures, I'm pretty sure you couldn't change the width. It would break the whole concept of monospace.

Additionally, the word "lambda" may be used for different things, even in a Python script. It would be very confusing to have that word appear as `λ` in strings and comments.

**Comment by ionutgoldan** [comment]
I see. I wasn't really aware of the ligature limitations.
Thanks for clarifying this!
