### ISSUE TITLE
=== rendered improperly

### ISSUE THREAD

**Issue by Summerer** [JetBrains/JetBrainsMono#224]
On JetBrains Mono v1.0.5 the `===` and `!==` ligatures are rendered improperly.

**Expected appearance:**
![Screenshot_28_04_2020-17_27_30](https://user-images.githubusercontent.com/16060333/80506253-9dcf2a00-8975-11ea-87c0-c888c62e2b8b.png)
![Screenshot_28_04_2020-17_28_32](https://user-images.githubusercontent.com/16060333/80506325-b50e1780-8975-11ea-9fc4-6716d847d012.png)

**Actual appearance:**
Firefox Inspector (OK probably because tiny maybe 8pt): 
![Screenshot_28_04_2020-17_29_01](https://user-images.githubusercontent.com/16060333/80506402-cfe08c00-8975-11ea-9283-ee95ff1b1ad4.png)

Firefox .txt file (font size 14):
![Screenshot_28_04_2020-17_29_49](https://user-images.githubusercontent.com/16060333/80506440-dff86b80-8975-11ea-98d8-b6032e42ad12.png)

kitty terminal (font size 11):
![Screenshot_28_04_2020-17_30_10](https://user-images.githubusercontent.com/16060333/80506481-f1417800-8975-11ea-9d04-7206b8b35144.png)

IntellijIDEA 2020.1 (font size 14):
![Screenshot_28_04_2020-17_31_26](https://user-images.githubusercontent.com/16060333/80506600-1afa9f00-8976-11ea-84fd-e11d7234a0bc.png)

I set up no special fontconfig settings.

**Comment by philippnurullin** [comment]
This is a hinting problem. Actually its duplicated https://github.com/JetBrains/JetBrainsMono/issues/25 We aware of this problem. The effective fix of this and similar problems will need to changes in the process of font mastering, so that's why it taking so long. But we aware of that problem.
