### ISSUE TITLE
Just a question: what is that owl?

### ISSUE THREAD

**Issue by AlsoScratch** [JetBrains/JetBrainsMono#229]
Character U+E000 appears to be an owl with the version number. I am curious to know what that owl means; possibly some logo?

**Comment by philippnurullin** [comment]
This is a font version guardian. Her name is Tulip.

**Comment by AlsoScratch** [comment]
Is it the logo for some company?

**Comment by philippnurullin** [comment]
No, this is a font mascot. If you want to use Tulip as a logo please don't.

**Comment by AlsoScratch** [comment]
Cool.
