### ISSUE TITLE
1.0.6 Does not show as monospaced font

### ISSUE THREAD

**Issue by capturethefire** [JetBrains/JetBrainsMono#230]
Not sure whether this is a font bug or an issue with my DE, but with v1.0.6 all the normal "JetBrains Mono" fonts stopped displaying in font selection dialogs that filter for monospaced fonts (e.g. in the gnome-terminal), only the "JetBrains Mono NL" versions are showing.

This is the font selection window for the gnome-terminal with font version 1.0.5:  
![image](https://user-images.githubusercontent.com/24480574/80720023-d98c0000-8aeb-11ea-810f-9dc288e99a89.png)

And this is the same window with font version 1.0.6 installed (and 1.0.5 uninstalled ofc):
![image](https://user-images.githubusercontent.com/24480574/80720493-7fd80580-8aec-11ea-921b-82ec603a3032.png)

I have no idea whether a font could cause this issue, but i thought since it works with v1.0.5 and the 1.0.6 "NL" fonts, it might be a bug in the font release.

Thanks for all your work, really love the font :)

_edit: just to make that clear, the font does display in "normal" font selection dialogs, just not in ones that filter for monospaced fonts only_

**Comment by trygveaa** [comment]
Possibly related to #227, see https://github.com/JetBrains/JetBrainsMono/issues/227#issuecomment-621785510

Though, for me both normal and NL, regular and medium, show as monospace with 1.0.6, while all the bold and extrabold variants do not. So its strange that you're getting different results. Which OS are you on?

**Comment by capturethefire** [comment]
Yeah unfortunately i have 0 experience with fonts so i don't know how it is determined by gnome-terminal :/

Looking into its source it seems like [this is the line](https://gitlab.gnome.org/GNOME/gnome-terminal/-/blob/master/src/profile-editor.c#L990) where it is checked, but so far i was not able to find where that function is implemented. Im guessing its somewhere in a c++ gtk lib, the only hint i found so far is [this pygtk documentation entry](https://developer.gnome.org/pygtk/stable/class-pangofontfamily.html#method-pangofontfamily--is-monospace) of a similar method. Will update if i find more.

**Comment by capturethefire** [comment]
Alright, it seems like this is actually because of the spacing issue described in #227 .  
If i remove the Bold and ExtraBold weights and reload the font cache, then the font shows up normally (but obviously missing the bold and extra bold weights). So it seems like one weight not having monospaced characters is enough to filter out the whole font family.
