### ISSUE TITLE
Double Dashes/Hyphens Join Up To Make What Looks Like One Long Dash/Hyphen

### ISSUE THREAD

**Issue by pauljohnknight** [JetBrains/JetBrainsMono#231]
Hi,

Firstly can I congratulate you on a beautiful font !

I would love to use this in my code tutorials, but I've hit an issue: when you do double dashes i.e. the " - " character twice, they join up. This would be really confusing to my new students when looking at code in the following instances:

HTML comments
SASS commands
BEM notation in CSS

Is there any way of making these separated like in other monospace fonts?

Example of the issue:

![image](https://user-images.githubusercontent.com/7756758/80724265-8e78e980-8af9-11ea-9be7-d33ec649a66c.png)

Many thanks,

Paul.

**Comment by alexeyten** [comment]
May be you just use JetBrains Mono NL?

**Comment by pauljohnknight** [comment]
@alexeyten I can't see that version on the download page? Unless I'm missing something?

**Comment by pauljohnknight** [comment]
@alexeyten ?? What does that even mean. There is no JetBrains Mono NL either in the download files or this repository.

**Comment by trygveaa** [comment]
The NL version was introduced in 1.0.4 and the web page still only has 1.0.3 (ref #192). You can download newer versions with the NL version from the releases page: https://github.com/JetBrains/JetBrainsMono/releases

However, the NL version is only provided for the ttf format. If you are going to use it on a web page, you might want to set `font-variant-ligatures: none` in CSS instead.

**Comment by pauljohnknight** [comment]
@trygveaa thanks for that. I really try and avoid .ttf or .otf on web pages because of file size. I put it through a file converter to make it a woff.2 file, but sadly it doesn't render quite as well (it's only a marginal difference, but it's noticeable). Sadly I think I'll have to take a pass until they do woff.2 version of the NL variant.

**Comment by trygveaa** [comment]
Did you try using the normal woff2 file with `font-variant-ligatures: none`?

**Comment by pauljohnknight** [comment]
Oh actually that works grand. Sorry, I thought that was only relevant if using the .oft/.ttf file. Yes thanks for that. Oddly if you add a letter-spacing of any value in Chrome (even + or - 0.1px) it solves the joined up hypens in the non-NL version, but sadly this fix doesn't work in other browsers. It's a shame the `font-variant-ligatures` ligatures property doesn't work in Edge, but I can live with that with the Edge Chromium rollout imminent.

**Comment by trygveaa** [comment]
Maybe `font-feature-settings: "liga" 0;` works in Edge?

**Comment by alexeyten** [comment]
It should https://caniuse.com/#search=font-feature-settings

**Comment by trygveaa** [comment]
Yeah, it's supported, I just wasn't sure if it has the desired effect. If I try setting it in Chromium, it doesn't work, but maybe that's because Chromium uses `font-variant-ligatures` instead.

**Comment by pauljohnknight** [comment]
I'll have to check that when I'm back at home tonight on my Windows machine...I only looked at https://caniuse.com/#search=font-variant-ligatures but will have a play around. It's not a biggy anyway, most windows users who'll be looking at the code examples use chrome/firefox anyway and I'll check in on the Jetbrains site for when the full NL version is uploaded.

**Comment by alexeyten** [comment]
It is
```css
font-feature-settings: "calt" 0;
```

**Comment by philippnurullin** [comment]
Looks like the solution was found. Closing the issue.
