### ISSUE TITLE
Some lowercase letters are cut off at the x-height on Android

### ISSUE THREAD

**Issue by kdrag0n** [JetBrains/JetBrainsMono#233]
On Android 10 (other versions are most likely affected too) with JetBrains Mono 1.0.5, some lowercase letters such as `e`, `p`, `s`, `g`, and `a` are cut-off at the x-height at some smaller sizes. No capital letters are affected.

This can be seen in the Termux terminal emulator:
![image](https://user-images.githubusercontent.com/7930239/80845509-496abb00-8bbe-11ea-85da-aabb0c988188.png)

It's not just Termux — other apps are affected too, e.g. Telegram:
![image](https://user-images.githubusercontent.com/7930239/80845551-669f8980-8bbe-11ea-960f-b8f7d800bc50.png)

Not all sizes are affected:
![image](https://user-images.githubusercontent.com/7930239/80845626-a4041700-8bbe-11ea-9dbb-72dd68f4e32c.png)

**Comment by Morpheus2077** [comment]
Same problem, sometimes it gets misaligned, it is also not very readable with the smaller font size.

![Screenshot_20200511-221151~2](https://user-images.githubusercontent.com/57775700/82502975-c35fd700-9ace-11ea-883d-6406212f738f.png)

**Comment by philippnurullin** [comment]
The current workaround is to downgrade to the 1.0.4 version.
https://github.com/JetBrains/JetBrainsMono/releases/tag/v1.0.4

**Comment by philippnurullin** [comment]
@kdrag0n Do you still have this problem after updating to v2.000?

**Comment by kdrag0n** [comment]
It looks fine now, I can't reproduce the issue at any size on v2.000.

**Comment by philippnurullin** [comment]
Glad to hear it! Have a nice day.
