### ISSUE TITLE
wrong interpretation in "<||> |>"

### ISSUE THREAD

**Issue by WuglyakBolgoink** [JetBrains/JetBrainsMono#234]
```
blabla <||> |> blabla
```
![image](https://user-images.githubusercontent.com/2271337/80941262-4c45f580-8de2-11ea-98eb-81d5c450b9c8.png)

tested on v1.0.6

now: it should be always one space between this ligatures
expected no space needed

**Comment by philippnurullin** [comment]
Hi @WuglyakBolgoink  Don't get why you mentioning the interpolation process. Do you mean that `<||>` sequence should't legaturise? Please add more information. In which context this expression is used.

**Comment by WuglyakBolgoink** [comment]
Hallo @philippnurullin 

yes. I think, it should be ligatured.

currently: 
![image](https://user-images.githubusercontent.com/2271337/81150792-a2e93600-8f80-11ea-905f-24e4ef0c90b2.png)

expected:
![image](https://user-images.githubusercontent.com/2271337/81150840-ada3cb00-8f80-11ea-8ef3-5c2ebd79f4b1.png)

**Comment by BornForFever** [comment]
> Hi @WuglyakBolgoink Don't get why you mentioning the interpolation process. Do you mean that `<||>` sequence should't legaturise? Please add more information. In which context this expression is used.

Perhaps he means cancel `<||` when followed by a `>`.
