### ISSUE TITLE
Some letter/number are taller than others

### ISSUE THREAD

**Issue by AndiDisch** [JetBrains/JetBrainsMono#235]
I'm using font size 11 in Visual Studio 2019. Some letters and numbers are smaller than others.

I'm using font size 11 because 10 is too small and 12 is too big for my Monitor setup.

The numbers are: 1, 4, 7, 8, 9 and 0
The lower case letter that are not as tall as the others are: m, q, v
The middle of the upper case G, O and R look weird.
These upper case letters are not tall enough: G, L, R, S

I am using Version 1.0.6
I can provide screenshots if necessary.

**Comment by philippnurullin** [comment]
Hi @AndiDisch  please add the screenshots. Do you use any zoom or scaling option, OS vise?

**Comment by philippnurullin** [comment]
https://github.com/JetBrains/JetBrainsMono/issues/218
