### ISSUE TITLE
Character % doesn't seem to be part of this family

### ISSUE THREAD

**Issue by cata0309** [JetBrains/JetBrainsMono#236]
Hello!
Something I noticed using JetBrains Mono font is that the `%` symbol doesn't feel right.
![image](https://user-images.githubusercontent.com/35623921/80954373-ebc8af80-8e05-11ea-83c2-70fb427d63ba.png)
It seems to be lighter than the other glyphs which gives it a weird look.
Consider making a little bit bolder !

**Comment by philippnurullin** [comment]
This was made to make `%` more pronounced in small sizes. I will look at it, maybe it can be a bit more bold.

**Comment by cata0309** [comment]
I understand, thank you ! Looking forward to seeing the updated one
