### ISSUE TITLE
Difficult to tell difference between opening and closing curly quote

### ISSUE THREAD

**Issue by Fjan** [JetBrains/JetBrainsMono#237]
First off, I love this font and have it now set as my default programming font.

One small issue I ran into is that curly quotes are rarely used in programming, but if they are it's important to tell the difference between ’ and ’. Currently those two look almost exactly the same at size 13. For the curly double quote, I can also only barely make out the difference between “ and ”.

I would argue that for a programming font it's more important to be able to tell which character it is than to make it look pretty. Can we please consider making the curly quotes look more like inverted commas so they clearly stand out?

**Comment by trygveaa** [comment]
> ’ and ’

These two characters are the same. I assume you meant ‘ and ’.

> One small issue I ran into is that curly quotes are rarely used in programming

Which language(s) uses these?

> Can we please consider making the curly quotes look more like inverted commas so they clearly stand out?

What do you mean? As far as I can see ’ looks exactly the same as comma, but is placed in the top, and ‘ is the same but upside down.

I agree that it's hard to see a difference at normal font sizes though.

**Comment by Fjan** [comment]
Ah yes, ‘ and ’, sorry 😀
My specific use case is that I often work on scripts that contain user provided input, and in that case I need to process / filter text that contains these characters. They are typically copy/pasted from somewhere else.

But we also often need to edit documentation pages in markdown / yaml / erb format that are run through a static site generator to turn into HTML, and those tend to contain curly quotes sometimes as well.

I was thinking of quotation marks as in a serif font as seen here: https://en.wikipedia.org/wiki/Quotation_mark

**Comment by martin-sucha** [comment]
Hey, I've hit this same issue.

I'm editing a website source code and need to fix occurrences of quotes so that the text on the website is properly formatted. It's hard to tell the difference between “ and ” unless I zoom or look very closely.

Please make the difference more visible.

**Comment by philippnurullin** [comment]
Remade quotation marks in the latest push. You can grab the files here https://github.com/JetBrains/JetBrainsMono/tree/master/fonts
