### ISSUE TITLE
Add alternate l (small L) in Regular

### ISSUE THREAD

**Issue by den32ds** [JetBrains/JetBrainsMono#238]
Thank you for the wonderful font (он словно Helvetica, я не могу больше его ни с чем сравнить). But it would be better (IMHO) if it were like in Consolas and Inconsolata
![изображение](https://user-images.githubusercontent.com/24569064/81215791-88e03f80-8fe2-11ea-95a2-8d08c5adbd69.png)

**Comment by philippnurullin** [comment]
Hi @den32ds .Thanks for the kind words. This construction of the `l` is similar to the `1`. To make them different & easy to distinguish with construction you suggesting, the `1`must be stripped from the horizontal bar at the bottom. This will make it to "bright" in the line.

The current construction of the `l` is easy to distinguish. The suggestion you making can be brought by stylistic sets. Which is not a priority right now. When the time will come i will consider this construction.

**Comment by philippnurullin** [comment]
Added in 2.304.
https://github.com/JetBrains/JetBrainsMono/releases/tag/v2.304
