### ISSUE TITLE
Fonts "wave"

### ISSUE THREAD

**Issue by jaclas** [JetBrains/JetBrainsMono#239]
I skipped a few last versions, but I installed the last one and it's terrible, there is a "wave" of letters.

![obraz](https://user-images.githubusercontent.com/17312717/81261362-3b90bc00-903c-11ea-9209-7c99c4cc596f.png)

This was the case at the beginning, then the next versions corrected it.
I use IDE RAD Studio.

**Comment by philippnurullin** [comment]
Hi @jaclas what was previous version that worked for you? What OS you working on?
Seems related to https://github.com/JetBrains/JetBrainsMono/issues/218

**Comment by jaclas** [comment]
Previous I used 1.0.4 version. I use Windows 7.

**Comment by michael-damatov** [comment]
Same with 1.0.6:
![image](https://user-images.githubusercontent.com/11958365/81334127-d8d40a80-90a5-11ea-9ea8-f447e151d99b.png)

in Visual Studio 2019 (16.5.4)
Font: JetBrains Mono
Font Size: 11

**Comment by Ilis** [comment]
I have the same issue on Win10 with FAR manager and CMD as well

![изображение](https://user-images.githubusercontent.com/1223140/84378785-2b9d6680-abfe-11ea-8abd-b0fbf2827731.png)
