### ISSUE TITLE
Add C0 and C1 Control code support

### ISSUE THREAD

**Issue by OmegaRogue** [JetBrains/JetBrainsMono#241]
it would be nice to have the control codes shown as their according control pictures instead of diamonds with question marks and boxes

**Comment by philippnurullin** [comment]
Hi @OmegaRogue . Please add the screenshots. It's difficult to understand your request.

**Comment by trygveaa** [comment]
Control codes are generally not printable characters. When would they be shown?

Are you sure it's not your application rendering a control code as something else?

**Comment by alexeyten** [comment]
May be this? https://en.wikipedia.org/wiki/Control_Pictures

**Comment by OmegaRogue** [comment]
> May be this? https://en.wikipedia.org/wiki/Control_Pictures

yes, there are more of them listed here https://en.wikipedia.org/wiki/C0_and_C1_control_codes#Basic_ASCII_control_codes

**Comment by OmegaRogue** [comment]
this is what all non whitespace characters from ascii 0x00 to 0x1F look currently in JetBrains Mono:
![image](https://user-images.githubusercontent.com/24958536/82069169-3cc48780-96d3-11ea-8c07-3ff779225b40.png)
this is the same file but opened in the [IntelliJ BinEd Plugin](https://bined.exbin.org/intellij-plugin/), which has support for control pictures:
![image](https://user-images.githubusercontent.com/24958536/82069409-8ca34e80-96d3-11ea-97a1-b1e216bb7dbe.png)
These still have the problem of being a bit too small to be easily read, so having these control pictures in JetBrains mono could make reading binary serialized data easier by having distinguishable symbols instead of boxes

**Comment by somethingSTRANGE** [comment]
Characters associated with control code are probably best represented with symbols like those in the screenshot @OmegaRogue provided above, since it's easy to identify what they are.

```
N      S      S      E      E      E      A      B      B      H      L      V      F      C      S      S
 U      O      T      T      O      N      C      E      S      T      F      T      F      R      O      I
  L      H      X      X      T      Q      K      L
```

```
D      D      D      D      D      N      S      E      C      E      S      E      F      G      R      U      
 L      C      C      C      C      A      Y      T      A      M      U      S      S      S      S      S
  E      1      2      3      4      K      N      B      N             B      C
```

Personally, however, I have nostalgia for [Code page 437](https://www.ascii-codes.com/) (used by the the original IBM PC) and how the control characters were represented there:

![Codepage-437](https://user-images.githubusercontent.com/6905832/90298676-fd2f4800-de47-11ea-9f03-73e65b26b02e.png)

The best roguelikes use code page 437.

That said, the @OmegaRogue suggestion makes more sense.

**Comment by philippnurullin** [comment]
Hi, added the Control codes. Experimented with placement of letters. The diagonal placement was not adding anything particular good. There were no additional space to make letters bigger, and there is a downside of shifting reading pattern from horizontal. Please see and test.
Grab the files from here https://github.com/JetBrains/JetBrainsMono/tree/master/fonts

**Comment by OmegaRogue** [comment]
I don't see any characters for the control codes in those files, and whats weird is that I thought this issue was already resolved, as the control codes already got support in the IDEs (at least goland, where i tested it), and it works very well there, and i thought it was part of JetBrains Mono already, and that it just didnt work correctly in terminals

goland:
![image](https://user-images.githubusercontent.com/24958536/125777217-f585cab1-9d69-463c-ad90-c22b6121fece.png)
gedit:
![image](https://user-images.githubusercontent.com/24958536/125777293-0fdcb99d-fdf8-48dc-a609-098919882adc.png)
fontforge:
![image](https://user-images.githubusercontent.com/24958536/125777405-34c62854-a116-48b9-bf7e-d6a3006e4421.png)

**Comment by philippnurullin** [comment]
Ok, let's see.
Here is a screenshot of what they should look.
<img width="952" alt="Screenshot 2021-07-15 at 13 51 48" src="https://user-images.githubusercontent.com/48058957/125783587-a5bcbccf-8736-4faa-8727-42e260a186f6.png">
Can you please paste the actual unicode numbers for the symbols or a sampel of text so i can test it?

**Comment by OmegaRogue** [comment]
[C0.txt](https://github.com/JetBrains/JetBrainsMono/files/6823123/C0.txt)
in the format
0x[Unicode byte]: [character]

**Comment by OmegaRogue** [comment]
HT (0x09) and LF (0x0A) aren't in there, because they are Linefeed and tab

**Comment by OmegaRogue** [comment]
the codes for the last half was missing a 1
[C0.txt](https://github.com/JetBrains/JetBrainsMono/files/6823157/C0.txt)

**Comment by philippnurullin** [comment]
Please test the latest push. Remapped the glyphs to the new unicode numbers.
