### ISSUE TITLE
Add Chinese language Support

### ISSUE THREAD

**Issue by Lizhilin** [JetBrains/JetBrainsMono#242]
The Chinese characters currently displayed are not supported, which is ugly🌗

**Comment by philippnurullin** [comment]
We don't have an expertise in Chinese & currently don't have plans to add its support in JetBrains Mono.

**Comment by BornForFever** [comment]
@Lizhilin In fact, there are tens of thousands of Chinese characters, so it may be too difficult to support Chinese. BTW, is it somehow helpful to make a narrow style to match the half width of Chinese? @philippnurullin

**Comment by Lizhilin** [comment]
> @Lizhilin实际上，有成千上万个中文字符，因此支持中文可能太困难了。顺便说一句，缩小样式以匹配中文的一半宽度是否有帮助？@philippnurullin

I think it is possible to use a part of the Chinese part of Microsoft Yahei or other fonts (Microsoft YaHei Mono) to become a mixed font

**Comment by Lizhilin** [comment]
> @Lizhilin In fact, there are tens of thousands of Chinese characters, so it may be too difficult to support Chinese. BTW, is it somehow helpful to make a narrow style to match the half width of Chinese? @philippnurullin

I think it is possible to use a part of the Chinese part of Microsoft Yahei or other fonts (Microsoft YaHei Mono) to become a mixed font

**Comment by philippnurullin** [comment]
@Lizhilin You can set Microsoft Yahei as fallback in your IDE. This will solve this problem. 
I believe we don't have legal rights do merge other fonts in our family.

@BornForFever Unfortunately we don't have plans to add more narrow group to the font family. At least for now.

**Comment by luweijun1992** [comment]
> 

How do I set the backup font ?

**Comment by jcyrss** [comment]
> > 
> 
> How do I set the backup font ?

In vscode, Just like what you set in CSS font-family.

For example, 
```
'JetBrains Mono',  '微软雅黑',  Menlo
```
