### ISSUE TITLE
font is too higher than unicode chars

### ISSUE THREAD

**Issue by znydev** [JetBrains/JetBrainsMono#243]
In gvim,  they are not equal high, like this.
![image](https://user-images.githubusercontent.com/30818783/81917336-a4150580-9607-11ea-8868-3b0ed7d47730.png)

config:

    set guifont=JetBrains_Mono:h10.5:cANSI
    set guifontwide=黑体:h11
    set linespace=0

**Comment by trygveaa** [comment]
gvim is probably falling back to another font for those characters. I don't think they exist in JetBrains Mono.

**Comment by znydev** [comment]
@trygveaa , yes, you are right. I mean jetbrains mono is not equal high with other font.
This may cause this problem. The chinese font is simhei, but other chinese font is the same result.

**Comment by philippnurullin** [comment]
JetBrains Mono don't support Chinese characters. 
In this issue there are some suggestions for the fallback fonts. https://github.com/JetBrains/JetBrainsMono/issues/20
1. https://github.com/be5invis/Sarasa-Gothic
2. Or you can use SF Mono if you working on Mac.

**Comment by znydev** [comment]
@trygveaa @philippnurullin , may be this is the reason?
![image](https://user-images.githubusercontent.com/30818783/81919671-b80e3680-960a-11ea-8717-ff9dceb8af0d.png)

**Comment by znydev** [comment]
@trygveaa @philippnurullin 

Yes, I know. I mean, JetBrains mono is hard to match with other Unicode Fonts. Their height is inconsistent

**Comment by znydev** [comment]
Their height is inconsistent.
![image](https://user-images.githubusercontent.com/30818783/81920075-42569a80-960b-11ea-861f-1711c9cadb4a.png)

**Comment by philippnurullin** [comment]
@znydev You mean that the Chinese glyphs are placed higher?

**Comment by znydev** [comment]
@philippnurullin , the right one should be like this:

![image](https://user-images.githubusercontent.com/30818783/81922896-6025fe80-960f-11ea-9b6b-dc9ddd235331.png)

**Comment by znydev** [comment]
@philippnurullin  or this:
![image](https://user-images.githubusercontent.com/30818783/81922976-86e43500-960f-11ea-84bd-d3cf3b02689a.png)

the font is https://github.com/be5invis/Sarasa-Gothic

**Comment by philippnurullin** [comment]
@znydev Based on info i see the this could be helped by enlarging the descender in JetBrains Mono, but will increase the line height of the font & that we can't do. We keeping the line height at minimum so the code is compact.
