### ISSUE TITLE
`∪` and `u` look too similar

### ISSUE THREAD

**Issue by singularitti** [JetBrains/JetBrainsMono#244]
Love this font! However, found a little bit unsatisfied with `∪` (the symbol for set union in mathematics) and `u`. They just look too similar:

![code](https://user-images.githubusercontent.com/25192197/82123745-f3267c00-9768-11ea-8424-a7a601fda163.png)

The intersection symbol (`∩`) and `n` are distinguishable:

![code2](https://user-images.githubusercontent.com/25192197/82123786-3b459e80-9769-11ea-8c77-c540816e768e.png)

Is it possible to increase the size of `∪` and `∩` to make them more noticeable? Thanks!

**Comment by philippnurullin** [comment]
JetBrains Mono currently not supporting this characters. I believe they are from your fallback font.

**Comment by philippnurullin** [comment]
@singularitti Can you send examples when `∪` `u` can be mistaken in context. I believe the context of usage will leave no place for mistake.

Here is a link to similar request. There is some info on  `u`  construction. https://github.com/JetBrains/JetBrainsMono/issues/212

**Comment by singularitti** [comment]
In the [Julia language](https://julialang.org/), they allow using unicode operators to express mathematical calculations. `` means `union` in set theory.

```julia
julia> c = [1,2,3]
3-element Array{Int64,1}:
 1
 2
 3

julia> p = [2,3,4]
3-element Array{Int64,1}:
 2
 3
 4

julia> c∪p
4-element Array{Int64,1}:
 1
 2
 3
 4
```
So `c∪p` means "the union of `c` and `p`". In real-world, this example may never happens, though.

**Comment by Ilis** [comment]
I like “u” with small tail, it is more distinguished of “union” sign and letter “v”.

One more reason is letter u looks similar to Greek mu (μ) and used to sign prefix “micro”. E. g. 10 ms for ten milliseconds, but 10 us for ten microseconds.

**Comment by 1900011604** [comment]
I like “u” with a small tail too but it seems that the designers put without it as a selling point.

**Comment by philippnurullin** [comment]
Aded the support of `∪`. Its differentiated from `u` by size and width.
If you still want it more different please wait for release of alternate set with `u`.
