### ISSUE TITLE
'<*>' is not shown correctly in some cases

### ISSUE THREAD

**Issue by snappdevelopment** [JetBrains/JetBrainsMono#245]
If you type `<*>` it gets replaced with a weird dot, where the asterisk would be.
It looks like this:

<img width="50" alt="Screenshot 2020-05-18 at 09 08 20" src="https://user-images.githubusercontent.com/33195281/82184069-51796900-98e7-11ea-96dc-f22b4e4ff785.png">

**Comment by philippnurullin** [comment]
This bug was present in v1.0.4 https://github.com/JetBrains/JetBrainsMono/issues/180 & foxed in the latest versions.
Please update to the latest version.

**Comment by snappdevelopment** [comment]
Oh okay thanks. The official website still hands out v1.0.3

**Comment by snappdevelopment** [comment]
This happens again with version 1.0.6 and android studio 4.0

**Comment by philippnurullin** [comment]
Sorry, can't reproduce. The 1.0.6 files are good.

Maybe the older version of the font is bundled in Android studio. 
This will give you a general idea where to find the bundled font. https://github.com/JetBrains/JetBrainsMono/issues/142
Hope this helps. If not i recommend contacting the Android Studio support.

**Comment by snappdevelopment** [comment]
Thanks for linking the other issue.
Uninstalling and reinstalling the font helped
