### ISSUE TITLE
Ligature request: %>%, %<>%

### ISSUE THREAD

**Issue by omega1x** [JetBrains/JetBrainsMono#249]
First of all, great thanks for your product, its is really awesome.
Please, consider ligature for pipe operators `%>%` and `%<>%` for [R](https://cran.r-project.org/doc/manuals/r-release/R-lang.html).

**Comment by Omnieboer** [comment]
For the uninitiated, like me, the pipe operators are not native in R, but part of extremely popular packages.

[Here is an explanation of Pipes.](https://www.datacamp.com/community/tutorials/pipe-r-tutorial) There are apparently also `%T>%` and `%$%` on top of `%>%` and `%<>%`. The `%<%` in the above article seems to be a typo and not really an actual operator.

Just mentioning this because `%>%` isn't mentioned in the linked page as far as I can see.

[Also, what people think about this when it comes to Fira Code.](https://github.com/tonsky/FiraCode/issues/473)

**Comment by philippnurullin** [comment]
@Omnieboer Thanks for the input! Looks interesting.

On the first glance the it will be hard to simplify the construction of `%>%` in ligature & don't mess this up. I will think what can be done.

**Comment by bwu62** [comment]
Hey, commenting here to register my interest, subscribe to updates, and crosspost my idea for a `%>%` ligature from [this parallel issue](https://github.com/tonsky/FiraCode/issues/473) raised in the FiraCode repo:

> ![image](https://private-user-images.githubusercontent.com/32756964/359000160-755f558c-dde8-45ee-b532-bb7f5d2ccacf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwNDk1NzMsIm5iZiI6MTcyNDA0OTI3MywicGF0aCI6Ii8zMjc1Njk2NC8zNTkwMDAxNjAtNzU1ZjU1OGMtZGRlOC00NWVlLWI1MzItYmI3ZjVkMmNjYWNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDA2MzQzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhZjRhMzM3OGVlYzg3Mjc1YTlmM2ViY2FiYjc0MGQxYjE0NmMwYzBhMmI2YWYwYzk0M2Y5ZWQwYTNmNmJkMWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kJ-EdaL8SynUHp5ajy-j3LUEVnhY59yEZ8835_3JCYE)
> 
> The exact proportions should obviously be fine tuned more but I think this might be a good starting point. The ligature is both identifiable as %>% but also cohesive as a single unit.
> 
> Other iterations that could be considered if people think the ligature isn't clear enough:
> 
> 1. The circles in the percent symbols can be slightly horizontally offset from each other if desired.
> 2. The bars in the percent symbols (i.e. just the first and last third of the long line) can be slightly sloped.
> 3. Both of the above?
> 
> This is my draft idea, so feedback is welcome, thanks.

Let me know if you have any thoughts. Really hoping to see more development on this in the future. Thanks! :)
