### ISSUE TITLE
ExtraBold/ExtraBold Italic show glyph on Font Book on MacOs

### ISSUE THREAD

**Issue by wilsonrivera** [JetBrains/JetBrainsMono#250]
I just downloaded and installed the latest version (1.0.3 as of writing this) and after installing it on Mac the ExtraBold and ExtraBold Italic fonts are shown as glyphs the Font Book, it happens only with those two, the others work fine and it only happens on the Font Book, if I open the font file directly it is shown correctly

![image](https://user-images.githubusercontent.com/225781/82839898-e3144800-9e9e-11ea-9638-0dfcf18fe8ac.png)

**Comment by philippnurullin** [comment]
This is an issue of Font Book. Restart & font will look normal.
