### ISSUE TITLE
Disable `>-` ligature when followed by `<` (`>-<`)

### ISSUE THREAD

**Issue by MTCoster** [JetBrains/JetBrainsMono#251]
*Please comment below if you have a legitimate use case for this combination of glyphs. I can't think of one, but that doesn't mean there isn't one!*

I find myself writing `>-<` somewhat frequently in doc comments to signify string templates. For example:

```
<name>-<version>-<release>
```

JBM currently renders a ligature for `>-`, while leaving `<` as its own character. While the intention is still perfectly clear, it just looks a bit weird to my eye.

---

Using JetBrains Mono v1.0.6 from [`homebrew-cask-fonts`](https://github.com/Homebrew/homebrew-cask-fonts/blob/master/Casks/font-jetbrains-mono.rb).

**Comment by philippnurullin** [comment]
Sounds legit. I will add this exclusion in the next update.
