### ISSUE TITLE
Provide glyphs for ⟵⟷ ⟶ 

### ISSUE THREAD

**Issue by derekschinke** [JetBrains/JetBrainsMono#255]
[Similarly to this issue](https://github.com/JetBrains/JetBrainsMono/issues/159), glyphs should be provided for these longer variants of arrows as well, `⟵ ⟷ ⟶`. I believe Fira Code accomplishes this by using the same glyph that it uses for the `-->` ligature.

**Comment by philippnurullin** [comment]
Hi @derekschinke , i have fear that adding glyphs with double weight will brake things like in this issue https://github.com/JetBrains/JetBrainsMono/issues/230. We will test it, if there will be no problems, i will add the glyphs.
