### ISSUE TITLE
subscript and superscript chars aren't showing well

### ISSUE THREAD

**Issue by rdsu-pt** [JetBrains/JetBrainsMono#257]
Hi,

The subscript and superscript chars aren't showing very well, as you can see:

JetBrainsMono
![2020-06-16_19h48_04](https://user-images.githubusercontent.com/10651797/84815414-e9639300-b00a-11ea-99a2-93e6a148cb71.png)

Input Mono
![2020-06-16_19h48_59](https://user-images.githubusercontent.com/10651797/84815479-0009ea00-b00b-11ea-8d1c-1fb1055f7820.png)

Victor Mono Medium
![2020-06-16_19h50_04](https://user-images.githubusercontent.com/10651797/84815529-131cba00-b00b-11ea-80a8-7eddf8ae9b29.png)

Regards

**Comment by philippnurullin** [comment]
Hi, @rdsu-pt . Yes, this can be improved. Thanks for the feedback.

**Comment by rdsu-pt** [comment]
With v2.000 this seems to be fixed... :)

Thanks!

**Comment by philippnurullin** [comment]
Yes, forgot to include it in release notes. Have fun!

пт, 10 июля 2020 г., 16:01 rdsu-pt <notifications@github.com>:
