### ISSUE TITLE
wrong font weight for `--`

### ISSUE THREAD

**Issue by bluelovers** [JetBrains/JetBrainsMono#258]
![image](https://user-images.githubusercontent.com/167966/85166452-e4684300-b299-11ea-82d2-cea379a0bf21.png)

**Comment by philippnurullin** [comment]
Hi @bluelovers. Can't reproduce it in IntelliJ IDEA 20.1.

I suggest removing the bundled font version (a little help → https://github.com/JetBrains/JetBrainsMono/issues/142) & installing the latest font version on OS.

**Comment by bluelovers** [comment]
im sure installed lastest version and delete bundled font

but i don't don't know why this

![image](https://user-images.githubusercontent.com/167966/85268340-f7049700-b4a8-11ea-954f-48229e6e5819.png)

![image](https://user-images.githubusercontent.com/167966/85268543-3b903280-b4a9-11ea-8f70-e1fe51a7a4bb.png)

**Comment by bluelovers** [comment]
hmm looks like is some old version is not overwrite when update to 1.0.6
they are still 1.02
![image](https://user-images.githubusercontent.com/167966/85270642-31bbfe80-b4ac-11ea-8584-634b0f7c98fb.png)

**Comment by philippnurullin** [comment]
@bluelovers Yes this seems like the cause. 
It's important to remove all the installed in OS fonts first & after that install the new ones.
