### ISSUE TITLE
Feature request: Please add to WinGet

### ISSUE THREAD

**Issue by weitzhandler** [JetBrains/JetBrainsMono#260]
Hi,

WinGet is a common CLI to install apps on Windows. It's shipped with the newer versions of Windows.
Please add JetBrainsMono to it.

**Comment by philippnurullin** [comment]
Hi @weitzhandler , i have no idea how to add files to WinGet. Will need help with this.

**Comment by weitzhandler** [comment]
Related: https://github.com/microsoft/winget-cli/issues/166

**Comment by philippnurullin** [comment]
Ok, then. )
