### ISSUE TITLE
render error on firefox

### ISSUE THREAD

**Issue by hingbong** [JetBrains/JetBrainsMono#261]
![BB$@YE(@CXE )D@1QU7D_~G](https://user-images.githubusercontent.com/26398240/85828669-8668bd80-b7bb-11ea-93ac-8c1013513e01.png)
render error on firefox 
the kotlin file is [file](https://github.com/blokadaorg/blokada/blob/master/app/src/core/kotlin/core/Emit.kt)

**Comment by philippnurullin** [comment]
Hi @hingbong , this looks strange. Please provide more info so we can reproduce this.
1. Your OS.
2. Your Editor, or you rendering plainly on web page?
3. What font version you using?

**Comment by hingbong** [comment]
> Hi @hingbong , this looks strange. Please provide more info so we can reproduce this.
> 1. Your OS.
> 2. Your Editor, or you rendering plainly on web page?
> 3. What font version you using?

1. Windows 10 2004 Firefox 77
2. on GitHub web page
3. 1.0.6

**Comment by BornForFever** [comment]
Please try updating to v2.0 and see if the bug occurs again.

**Comment by hingbong** [comment]
> 
> 
> Please try updating to v2.0 and see if the bug occurs again.

it is fixed, thanks
