### ISSUE TITLE
Add the Latin Capital Letter Sharp S (U+1E9E)

### ISSUE THREAD

**Issue by jessestricker** [JetBrains/JetBrainsMono#262]
Can you add a glyph for the letter ẞ (U+1E9E) to this font?
I really like JetBrains Mono and use it everywhere for coding.

Here is some [article](https://typography.guru/journal/how-to-draw-a-capital-sharp-s-r18) on the design of ẞ.

**Comment by philippnurullin** [comment]
Hi @jessestricker It will be added in the next update.
