### ISSUE TITLE
Please, provide a changelog

### ISSUE THREAD

**Issue by rbrito** [JetBrains/JetBrainsMono#263]
For distributions like Debian (and others, including people that want to know what is new with the font), it would be quite nice to have a changelog provided in the root directory of the project.

Thanks,

Rogério Brito.

P.S.: Depending on how you develop the font, continuously updating the changelog can also help with how you announce the changes in pages like https://github.com/JetBrains/JetBrainsMono/releases and other places.

**Comment by philippnurullin** [comment]
Hi @rbrito. Thanks for the input, i will think about it.

**Comment by Calinou** [comment]
It might be worth following the [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) format for this purpose.

**Comment by philippnurullin** [comment]
Added it without fancy dates for now. Will improve it the next updates.
https://github.com/JetBrains/JetBrainsMono/blob/master/Changelog.txt
