### ISSUE TITLE
Faint i dot

### ISSUE THREAD

**Issue by frithrah** [JetBrains/JetBrainsMono#265]
Thank you for a great font.

On Windows at low point sizes the dot above i and j is mostly lost by anti-aliasing. Please see the screenshots from CLion. Size 11 gives a clear dot but sizes 12 and 13 do not.

Config: Windows 10, 1920x1080, ClearType on

I tested with the Hack font too. That gives a single pixel dot at those sizes.

![JetBrains Mono size11](https://user-images.githubusercontent.com/46793160/87166653-c81d5c00-c2c3-11ea-9a5f-d1ce14579ca6.png)
![JetBrains Mono size12](https://user-images.githubusercontent.com/46793160/87166657-c8b5f280-c2c3-11ea-8934-6b0acd6781ab.png)
![JetBrains Mono size13](https://user-images.githubusercontent.com/46793160/87166662-c8b5f280-c2c3-11ea-88b2-87d69e9e94d1.png)

**Comment by philippnurullin** [comment]
Hi @frithrah . Yes, this will be improved in next update.

**Comment by frithrah** [comment]
Brilliant news. This is a work of art.

**Comment by philippnurullin** [comment]
Hey @frithrah did you have the time to look at the latest update?

**Comment by frithrah** [comment]
@philippnurullin I just did and it looks good. The tittles are now clear and present. Good work. And thank you.

**Comment by philippnurullin** [comment]
Glad to hear!
