### ISSUE TITLE
Italic variant broken

### ISSUE THREAD

**Issue by atauzki** [JetBrains/JetBrainsMono#266]
OS：Windows 10 build 19041.0
JetBrains Mono：2.0
Editor：Visual Studio Code 1.47.0

expected display（v1.0.6）：
![image](https://user-images.githubusercontent.com/19769843/87214504-bb4e4600-c35f-11ea-85ec-3f7c1ddd53fe.png)

what it looks like on 2.0：
![image](https://user-images.githubusercontent.com/19769843/87214540-141dde80-c360-11ea-977c-4f6339013629.png)

**Comment by philippnurullin** [comment]
Hi @atauzki , did you install the new version on top of the old?

**Comment by atauzki** [comment]
yeah, I uninstalled the old version and installed newest version. and this issue happend.

**Comment by philippnurullin** [comment]
Ok, i will continue to investigate this problem on monday.

**Comment by saidattax** [comment]
Same problem with me on VSCode

Windows 10 Version - 10.0.18363 Build 18363
VSCode 1.47.0

Although it works fine with Sublime Text 3

@atauzki Does italic work fine for you on Sublime Text 3?

**Comment by atauzki** [comment]
The problem caused by the inconsistent width attribute.
![image](https://user-images.githubusercontent.com/19769843/87221912-359fba00-c3a2-11ea-8bbb-263c3771fc87.png)
![image](https://user-images.githubusercontent.com/19769843/87221858-e5c0f300-c3a1-11ea-927a-c24bbdadcf45.png)
When I changed the width to normal with FontCreator, the italic displayed fine.

**Comment by philippnurullin** [comment]
Yes, confirm that. My bad, will fix this asap.

**Comment by cata0309** [comment]
Will a quick fix release come this week ?

**Comment by philippnurullin** [comment]
@saidattax Yes.

**Comment by amsokol** [comment]
Hi @atauzki. Sorry for off-topic. Have you succeeded to turn on semi light font width for VSCode? Set "editor.fontWeight" to "350" works fine for "Cascadia Code" font but does not work for "JetBrains Mono" font.

**Comment by cata0309** [comment]
Any updates @philippnurullin ?

**Comment by philippnurullin** [comment]
@cata0309 Sorry i misguided you. Right now it's holiday. I will fix this on Monday, when my working hours will start.

**Comment by cata0309** [comment]
No problem, I understand !

În dum., 12 iul. 2020 la 19:56, philippnurullin <notifications@github.com>
a scris:

**Comment by atauzki** [comment]
> Hi @atauzki. Sorry for off-topic. Have you succeeded to turn on semi light font weight for VSCode? Set "editor.fontWeight" to "350" works fine for "Cascadia Code" font but does not work for "JetBrains Mono" font.

No. you may file another issue.

**Comment by atauzki** [comment]
static works but variable font still broken in 2.001.

**Comment by philippnurullin** [comment]
@atauzki This is done on purpose. More in the issue. https://github.com/JetBrains/JetBrainsMono/issues/270
