### ISSUE TITLE
Official website still showing 4 weights

### ISSUE THREAD

**Issue by BornForFever** [JetBrains/JetBrainsMono#268]
With the release of v2.0, there are 4 more weights added into the JetbrainsMono family, so there are 8 weights in total. The official website, however, is still showing 4 weights, which may lead to confusion or misleading.
![Screenshot_20200711_192801_com huawei browser](https://user-images.githubusercontent.com/62426149/87236071-d334d100-c416-11ea-998d-1a5692154b90.jpg)

**Comment by philippnurullin** [comment]
Hi @BornForFever , yes we are aware of this. Will update in near future. Thanks for the feedback!

**Comment by BornForFever** [comment]
Great thanks for being aware of this and updating the archives on the official website!🎉

**Comment by philippnurullin** [comment]
The page was updated.

**Comment by BornForFever** [comment]
Thank u for updating. However, the animation is gone. Is it on purpose?

**Comment by philippnurullin** [comment]
Hi @BornForFever . Can you please provide screenshots of animation that is missing.

**Comment by BornForFever** [comment]
Umm...I mean in the past, there was a smooth transition between different number 4's. However, the transition was missing, and there was only a 'leap' between number 7's.

**Comment by philippnurullin** [comment]
Yes, this this is working like intended. 
I see only a minor bug with slightly misplaced one of the `7`. I will let the designer know. Maybe we can bring back the smooth transition.
