### ISSUE TITLE
Filenaming/tagging different from previous versions

### ISSUE THREAD

**Issue by MindTooth** [JetBrains/JetBrainsMono#269]
Hi,

I'm in the process of updating the font for Homebrew, but for some reason you've chosen to use a different file layout and version schema.

Are there any particular reasons for this?  It makes it harder for package managers (not that I am one that for the Homebrew cask) to do a fast bump when we need to change the whole formulae just for an update.  I would rather recommend that the same convention is used, and not change between space/dots, folder/non-folder, etc.

Thanks for the continues development of the font. 👍🏻

**Comment by philippnurullin** [comment]
Hi @MindTooth . In the process of making 2.0 we migrated to the another editor. In comparison to FontLab, Glyphs have `0.000` format as default & to change it manually in each file after export will be problematic. & `0.000` format is actually preffered https://silnrsi.github.io/FDBP/en-US/Versioning.html.

The new folder structure was made to be more transparent on content. The short "NL" in file names is hard to recognize as No Ligature.

We understand that this kind of changes a pain in the ass, & will try to keep it to the minimum.

**Comment by MindTooth** [comment]
Sound good to me. 👌🏻  Thanks.
