### ISSUE TITLE
Missaligned #{ ligature

### ISSUE THREAD

**Issue by cata0309** [JetBrains/JetBrainsMono#272]
I am using VS Code.
JetBrains Mono font V2.001
![image](https://user-images.githubusercontent.com/35623921/87350670-e784e500-c560-11ea-91ec-406d6790dfd9.png)

**Comment by philippnurullin** [comment]
Dependent on https://github.com/JetBrains/JetBrainsMono/issues/275

**Comment by philippnurullin** [comment]
Hi @cata0309 We changed a x-height treatment with hinting os this may affect this issue. We can't reproduce this issue with 2.200.
