### ISSUE TITLE
JetBrains similar to Go Mono shape

### ISSUE THREAD

**Issue by cprog** [JetBrains/JetBrainsMono#276]
Hello,
Is it possible to make JetBrains in shape similar to Go Mono ?
May be I am wrong but this is called slab font variant.

**Comment by philippnurullin** [comment]
Hi @cprog , unfortunately this modification will lead to total remake of the JetBrains Mono. Serifs (slab or any other) are not working with the initial concept of the font. We believe that they will lead to the eye fatigue when you reading code.
So, we will not provide this version, sorry.
