### ISSUE TITLE
Glyphs, look, or why not JBM

### ISSUE THREAD

**Issue by Antiever** [JetBrains/JetBrainsMono#277]
Overall, I like this font and have been wanting to switch to it for a long time, but a few things are stopping me...

First of all - missing glyphs.
here is a comparison from notepad++ (vs DejaVu Sans Mono):

![j1](https://user-images.githubusercontent.com/9666515/87713934-aafcf780-c7b3-11ea-8c05-c4253cb776bc.png)

◯ glyph exist but seems malformed
Also note that subscript and superscript characters (if present) looks poorly readable.
Maybe it makes sense to borrow them?

![j2](https://user-images.githubusercontent.com/9666515/87713972-bbad6d80-c7b3-11ea-94b3-bb8245087582.png)

And one more non-obvious thing - bold font.

![j3](https://user-images.githubusercontent.com/9666515/87713999-c6680280-c7b3-11ea-8349-47aeb6b17108.png)

It looks like 'Semi-bold' or even more like 'Medium' for some reason.
It is "visually not intuitive" what is important in programming.

I hope someday I'll make JBM my main font.

**Comment by philippnurullin** [comment]
Hi @Antiever .
1. If you want particular glyphs added please copy paste them or send unicodes. 
2. Please upgrade to the v2.001 (fris delete old files from OS. Installing on top can cause errors). The superscript & subscript was updated.
3. It's hard to say but it looks like there is no Bold on your screen. This looks like Medium indeed. To correct that please update to the latest version of the font. If the problem is persistent please create a separate issue.

**Comment by Antiever** [comment]
>  The superscript & subscript was updated
Confirm - it's fixed in 2.001

> If you want particular glyphs added please copy paste them

□
◆ - fix
◇ - fix size
△ - fix size
▽ - fix size
◁
▷
▻
◅
►
◄
▪
▫
▴
▾
◂
▸
▵
◃
▹
▿
∘
❮
❯
❰
❱
◌
◯ - fix size
◎ - fix size
✕ - fix size
⚠
⚡
⌂
◔
◧
◨
◩
◪
◫
⌃
⌄
⌅

Pixel "bug" in:
┌┐╭╮
└┘╰╯

![notepad++_2020-07-17_19-46-07](https://user-images.githubusercontent.com/9666515/87811853-f7097400-c867-11ea-9362-1442ab9b15da.png)

![PixelZoomer_2020-07-17_19-45-44](https://user-images.githubusercontent.com/9666515/87811886-0a1c4400-c868-11ea-9c21-f9b9d5c39b71.png)


Also, I hope that you keep in mind that most of the PC monitors have a dpi of 96 and do not test everything on MacPro etc :)

**Comment by p00f** [comment]
Where can I find the set of all glyphs included?

**Comment by philippnurullin** [comment]
@p00f Please create a new issue, because this one is unrelated. 
I can send you all the glyphs available right now. When we update the JetBrains Mono site, all list of glyphs will be there.

**Comment by p00f** [comment]
> @p00f Please create a new issue, because this one is unrelated. 
> I can send you all the glyphs available right now. When we update the JetBrains Mono site, all list of glyphs will be there.

Can you mail them to me? My email is in my profile. Sorry for the noise in this issue

**Comment by philippnurullin** [comment]
@p00f 
https://github.com/JetBrains/JetBrainsMono/wiki/List-of-supported-symbols
