### ISSUE TITLE
Request for subscript digits

### ISSUE THREAD

**Issue by AI-4** [JetBrains/JetBrainsMono#279]
JetBrainsMono is great font. It has U+2080 U+2081 U+2082 U+2083 U+2084, but has not U+2085 U+2086 U+2087 U+2088 U+2089. I use them for writing some simple chemical formulas in code for output formatting. It looks very bad when some of the numbers are loaded from a different font.

**Comment by philippnurullin** [comment]
Hi @AI-4 . Support for Superscript & subscript was added from v2.0.0. 

1. delete all old files from OS.
2. Download the latest build from here → https://github.com/JetBrains/JetBrainsMono/releases/tag/v2.001
3. Install.

**Comment by philippnurullin** [comment]
Any luck with update?
Closing this issue, feel free to reopen if problem is persistent.
