### ISSUE TITLE
Some ligatures are missing in various editors (Emacs, Atom, Idea)

### ISSUE THREAD

**Issue by andreyorst** [JetBrains/JetBrainsMono#280]
Hello, thanks for this great font!

I've noticed that not all ligatures, listed on [official page](https://www.jetbrains.com/lp/mono/#font-family) are working though. I was able to reproduce this issue with two text editors. First was Emacs, with HarfBuzz, and `auto-composition-mode`, with these settings:

```emacs-lisp
(when (aorst/font-installed-p "JetBrainsMono")
  (let ((ligatures `((?-  ,(regexp-opt '("-|" "-~" "---" "-<<" "-<" "--" "->" "->>" "-->")))
                     (?/  ,(regexp-opt '("/**" "/*" "///" "/=" "/==" "/>" "//")))
                     (?*  ,(regexp-opt '("*>" "***" "*/")))
                     (?<  ,(regexp-opt '("<-" "<<-" "<=>" "<=" "<|" "<||" "<|||" "<|>" "<:" "<>" "<-<"
                                           "<<<" "<==" "<<=" "<=<" "<==>" "<-|" "<<" "<~>" "<=|" "<~~" "<~"
                                           "<$>" "<$" "<+>" "<+" "</>" "</" "<*" "<*>" "<->" "<!--")))
                     (?:  ,(regexp-opt '(":>" ":<" ":::" "::" ":?" ":?>" ":=" "::=")))
                     (?=  ,(regexp-opt '("=>>" "==>" "=/=" "=!=" "=>" "===" "=:=" "==")))
                     (?!  ,(regexp-opt '("!==" "!!" "!=")))
                     (?>  ,(regexp-opt '(">]" ">:" ">>-" ">>=" ">=>" ">>>" ">-" ">=")))
                     (?&  ,(regexp-opt '("&&&" "&&")))
                     (?|  ,(regexp-opt '("|||>" "||>" "|>" "|]" "|}" "|=>" "|->" "|=" "||-" "|-" "||=" "||")))
                     (?.  ,(regexp-opt '(".." ".?" ".=" ".-" "..<" "...")))
                     (?+  ,(regexp-opt '("+++" "+>" "++")))
                     (?\[ ,(regexp-opt '("[||]" "[<" "[|")))
                     (?\{ ,(regexp-opt '("{|")))
                     (?\? ,(regexp-opt '("??" "?." "?=" "?:")))
                     (?#  ,(regexp-opt '("####" "###" "#[" "#{" "#=" "#!" "#:" "#_(" "#_" "#?" "#(" "##")))
                     (?\; ,(regexp-opt '(";;")))
                     (?_  ,(regexp-opt '("_|_" "__")))
                     (?\\ ,(regexp-opt '("\\" "\\/")))
                     (?~  ,(regexp-opt '("~~" "~~>" "~>" "~=" "~-" "~@")))
                     (?$  ,(regexp-opt '("$>")))
                     (?^  ,(regexp-opt '("^=")))
                     (?\] ,(regexp-opt '("]#"))))))
    (dolist (char-regexp ligatures)
      (apply (lambda (char regexp) (set-char-table-range
                                    composition-function-table
                                    char `([,regexp 0 font-shape-gstring])))
             char-regexp))))
```

You can see, that most ligatures work, but not all: [[off]](https://user-images.githubusercontent.com/19470159/88204501-ff8cf080-cc53-11ea-8c8b-660b079079fa.png) / [[on]](https://user-images.githubusercontent.com/19470159/88204584-277c5400-cc54-11ea-8431-feb504b9f5a2.png) (you can toggle between tabs with images to see what changes and what not). Mainly, there are four missing ligatures: `~=`, `\`, `\/`, and `/**`

Atom editor also has this issue:

![image](https://user-images.githubusercontent.com/19470159/88206398-d9b51b00-cc56-11ea-9b3b-8e453dbeb480.png)

I was unable to set up VSCode ligatures, as their interface is unfumiliar.

In Intellij Idea Community Edition ligatures partly work:

![image](https://user-images.githubusercontent.com/19470159/88207036-db331300-cc57-11ea-872d-f1bed9697bb3.png)

Again, no `\`, and `\/`

**Comment by philippnurullin** [comment]
Hi @andreyorst . 
The `/\` `\/` was removed because of this issue https://github.com/JetBrains/JetBrainsMono/issues/78#issuecomment-578710304
The `/**` was removied beacuse of this https://github.com/JetBrains/JetBrainsMono/issues/88
`~=` was removed after this request https://github.com/JetBrains/JetBrainsMono/issues/204
In IDEA JetBrains Mono is bundled with an older version, so some ligature alterations is not applied.

We are currently working on page update. We will remove all the irrelevant ligatures. Thanks for the feedback!

**Comment by andreyorst** [comment]
Ah, okay!

Should I close this now, or you'll close it after page update?

**Comment by philippnurullin** [comment]
Worry not, i will close this when we update the page.

**Comment by philippnurullin** [comment]
The page was updated.
