### ISSUE TITLE
Powerline glyphs not working

### ISSUE THREAD

**Issue by atg22896** [JetBrains/JetBrainsMono#281]
Hello, when using MesloLGM Nerd Font Mono, all of my glyphs show.

![Screen Shot 2020-07-30 at 5 17 17 PM](https://user-images.githubusercontent.com/33287665/88975636-88c1aa00-d288-11ea-9217-8834875d8987.png)
![Screen Shot 2020-07-30 at 5 20 04 PM](https://user-images.githubusercontent.com/33287665/88975840-f7066c80-d288-11ea-8e09-5cfb76871086.png)

When using Jetbrains latest font, they don't show.
![Screen Shot 2020-07-30 at 5 17 43 PM](https://user-images.githubusercontent.com/33287665/88975658-95de9900-d288-11ea-9406-d92ad2de8705.png)
![Screen Shot 2020-07-30 at 5 20 51 PM](https://user-images.githubusercontent.com/33287665/88975867-05548880-d289-11ea-82d5-31100ef717ab.png)

**Comment by atauzki** [comment]
Powerline don't contain these symbols. You should patch the symbols by yourself.

**Comment by philippnurullin** [comment]
Hi @atg22896 . This icon are not the part of Powerline symbols. I believe they can be found in Nerd Font patched version here https://github.com/ndtho8205/JetBrainsMono. Sadly It's a bit outdated.

Also you can create a separate issue with request with unicode numbers of missed symbols. We will add them in one of the future updates.

**Comment by mfocko** [comment]
You can also check here... but Fira is updated more often than the fonts patched, so...
on the other hand, if you want to patch it yourself it ain't that hard... dependencies are described (https://github.com/ryanoasis/nerd-fonts#font-patcher) and from sources (since the git repo is big af) you need `src/glyphs`
