### ISSUE TITLE
Medium weight font not in the monospaced list

### ISSUE THREAD

**Issue by ahmed-alamer** [JetBrains/JetBrainsMono#283]
I am on RubyMine 2020.2 and JetBrains Mono Medium is now showing up in the list with the monospaced fonts is checked, I also noticed that the rendering overall is a bit off even with JetBrains Mono Regular. I did reinstall the fonts and restared the IDE with the same outcome.

**Comment by philippnurullin** [comment]
Hi @ahmed-alamer , please provide screenshots so i can understand the issue better.

**Comment by ahmed-alamer** [comment]
Screenshots below

<img width="666" alt="JetBrains Mono Screenshot with Non Monospaced" src="https://user-images.githubusercontent.com/7933802/89252234-2ac5f700-d5e7-11ea-97c8-e858ffd7c230.png">
<img width="560" alt="JetBrains Mono Screenshot with Monospaced" src="https://user-images.githubusercontent.com/7933802/89252235-2b5e8d80-d5e7-11ea-9d1e-5ff3b684243b.png">

**Comment by philippnurullin** [comment]
I believe this is a duplicate problem https://github.com/JetBrains/JetBrainsMono/issues/267
Feel free to reopen if you disagree.

**Comment by ahmed-alamer** [comment]
Agreed, Thank you kindly
