### ISSUE TITLE
Font height changed in v2.x (at least on Windows)

### ISSUE THREAD

**Issue by rh63** [JetBrains/JetBrainsMono#286]
As the title says...

In v1.0.6, the world was fine:

![Anmerkung 2020-08-03 233405](https://user-images.githubusercontent.com/65854998/89229636-17fcf380-d5e2-11ea-86f8-25c61293be15.png)

In v2.001, the glyphs are higher than before:

![Anmerkung 2020-08-03 233330](https://user-images.githubusercontent.com/65854998/89229698-3a8f0c80-d5e2-11ea-8a72-37cf4e213bf6.png)

To really see the effect, save the two images and switch back and forth between them in your preferred viewer. It really makes a difference in text editors or mail clients - a change not for the better, at  least for me. YMMV... ;)

All this on Windows 10 (obviously!) 1909 Build 18363.997.

**Comment by rh63** [comment]
Just tested the font update on Windows 10 2004 Build 19041.388. Same effect.

**Comment by moritzdietz** [comment]
![image](https://user-images.githubusercontent.com/7935536/91296358-c5f05d80-e79c-11ea-86ed-1400bde45cc7.png)
Definitely can see height changes for glyphs.

**Comment by philippnurullin** [comment]
@moritzdietz This is not relevant. The powerline symbols on your screenshot are not from the JetBrains Mono. Looks like they brought from NERD patch.

**Comment by radzio** [comment]
Same here on Windows 10 2004, I was forced to downgrade Jetbrains Mono to 1.0.6

**Comment by moritzdietz** [comment]
@philippnurullin I checked and made sure to test without the patched nerdfont font.
This is the stock font:
![image](https://user-images.githubusercontent.com/7935536/91298561-8a579280-e7a0-11ea-9bda-08cb82e9327b.png)
Causing:
![image](https://user-images.githubusercontent.com/7935536/91298870-0e117f00-e7a1-11ea-9df8-0715213f293f.png)

**Comment by MicroJoe** [comment]
Same issue on Linux, drawing lines can help compare the two sizes:

![jetbrains_mono_1 0 6_vs_2 002](https://user-images.githubusercontent.com/989521/91996615-7c25eb00-ed39-11ea-8b3a-6bc63fdf5d21.png)

Other regressions found:

- Underscore character too low
- Underscore character dimmer
- Period character dimmer

**Comment by philippnurullin** [comment]
@MicroJoe Top left is only JetBrains Mono on this image. Look at the construction of `r` & `w` in other examples. Please double check the fonts.

**Comment by MicroJoe** [comment]
> @MicroJoe Top left is only JetBrains Mono on this image. Look at the construction of `r` & `w` in other examples. Please double check the fonts.

My bad, I have deleted my comment. It was totally irrelevant. My system switched to the default Monospace font instead of the new version of Jetbrains Mono. This is why it looked totally different.

**Comment by csabii** [comment]
+1-ing this issue as this is the case for me as well. Unfortunately the height is definitely different (fonts are taller) in the new version, it does not look like fie as in the code snippets on https://www.jetbrains.com/lp/mono/
I'm using Android Studio with Win10 (10.0.19041)

**Comment by philippnurullin** [comment]
Hi @csabii Can you please send the screenshots.

@rh63 Also please try to reproduce the problem with the latest version from here https://github.com/JetBrains/JetBrainsMono/tree/master/fonts

**Comment by csabii** [comment]
Hi Philipp,

Attached screenshots from 1.0.6. and 2.210. I got used to the increased height in the meantime so if it is intentional than I can live with it :)

![mono2210](https://user-images.githubusercontent.com/29076417/99241638-697e6680-27fe-11eb-936e-94dc2c88b644.png)
![mono106](https://user-images.githubusercontent.com/29076417/99241640-6a16fd00-27fe-11eb-81ba-b958a3d1d3b6.png)

**Comment by rh63** [comment]
Hi,

can confirm that the fonts look "normal" again (like before 2.x). But I didn't need 2.211 for this. I had installed 2.210 before and this did the trick already.

Anyway, thanks for fixing this and for creating my favorite editor font! :)

Cheers!

**Comment by rh63** [comment]
Hi,

loke @csabii commented before: I got used the "new" look. I did like the more compact appearance of the versions up to 1.06 better, but I learned how to live with it.

Anyway, thanks for your work and the excellent font you created!

Cheers!

**Comment by csabii** [comment]
yes, a big thank you from me as well :) 👍

**Comment by philippnurullin** [comment]
At the earlier version we used ttfautohinting (the hinting is a process of deforming the contour to best fit in pixel grid) without optimal settings. In the latest version the x-height increased to look more like the original, hi res contour. Basically the JB Mono looks more like v2.1xx.

Ok, looks like this issue can be closed. Thanks for the feedback.
