### ISSUE TITLE
The letter i looks like 1 at certain font sizes

### ISSUE THREAD

**Issue by komodovaran** [JetBrains/JetBrainsMono#289]
Windows 10. Font version 2.001.

![Screenshot 2020-08-18 183627](https://user-images.githubusercontent.com/20357875/90540674-d5aae900-e181-11ea-9e79-f7c69f91cef1.png)

**Comment by Omnieboer** [comment]
Ah yes, the Sem1 L1ght Ital1c font..

In all seriousness, that does look exactly like a 1 when reading fast, especially a bit more out of context.

**Comment by philippnurullin** [comment]
Hi, this issue is dublicating this one https://github.com/JetBrains/JetBrainsMono/issues/265
The  `i` will be updated in the next release.
Closing it.
