### ISSUE TITLE
Not all ligatures shown in VS Code on Mac

### ISSUE THREAD

**Issue by derfrankie** [JetBrains/JetBrainsMono#29]
I installed the font and setup VS Code as of instructions and some ligatures are not working.

![ligatures-not-working](https://user-images.githubusercontent.com/1045325/72526052-d5521480-3865-11ea-949a-b39794f0366b.png)

**Comment by pakLebah** [comment]
It works on mine. VS Code 1.41 on Mac Mojave.

**Comment by derfrankie** [comment]
For me it doesn't even after a re-install..
Mac Mojave, VS CodeVersion: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:57:51.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0

- It works fine in normal terminal and other apps.

**Comment by pakLebah** [comment]
There must be something wrong with your VS Code installation or something. On mine, the font works perfectly. It matches every single [ligatures](https://www.jetbrains.com/lp/mono/#font-family) shown on the official site.

![Jepretan Layar 2020-01-22 pukul 06 25 11](https://user-images.githubusercontent.com/11470932/72852276-9f3ae780-3ce0-11ea-9a3a-b7c8666d3527.png)

**Comment by philippnurullin** [comment]
@derfrankie https://github.com/tonsky/FiraCode/issues/259 Maybe thats your case?
