### ISSUE TITLE
Request for supporting multiline bracket characters

### ISSUE THREAD

**Issue by mahozad** [JetBrains/JetBrainsMono#290]
The glyphs for multi-line bracket characters are not in full height:
![Screenshot (890)](https://user-images.githubusercontent.com/29678011/90612962-fb85cb80-e21d-11ea-9d2e-ef52ccd74532.png)

The [official list of supported symbols](https://github.com/JetBrains/JetBrainsMono/wiki/List-of-supported-symbols) dose not contain these characters in the first place.
Is it possible to add support for them?

I found some multiline brackets in [this Wikipedia page](https://en.wikipedia.org/wiki/Bracket#Encoding_in_digital_media).

The above image shows the default JetBrainsMono font in IntelliJ IDEA 2020.2.

---
As a side note I should say that the box-drawing characters have a tiny gap between them as well.

**Comment by philippnurullin** [comment]
Hi @mahozad Please paste the code with brackets that on you screen. It will be easy for me to find the exact symbols you want to be added.

As for the space between the boxdrawing. Make sure that your line height in setting is set to 1.0. You can find this option in *Preferences* → *Editor* → *Line spacing*

**Comment by mahozad** [comment]
Sure. This is the example code:
```
 ⎛                ⎞
 ⎜ very important ⎟
 ⎝                ⎠
```

---
I typed these chars in the editor with line spacing set to 1.0:

```
    ┌──┬──┐
    ├     ┤
    └──┴──┘
```
JetBrains Mono:
![jetbrains-mono](https://user-images.githubusercontent.com/29678011/91831235-0ea28d80-ec59-11ea-888f-522a24cebc25.gif)

Fira Code:
![fira-code](https://user-images.githubusercontent.com/29678011/91831395-414c8600-ec59-11ea-8bd4-3516c93c224b.gif)

It seems to me that with small font sizes there is even horizontal gap between the symbols.

I should say it again that this is the default font in IntelliJ IDEA 2020.2 (so I think it is not version 2.000 of font)

**Comment by philippnurullin** [comment]
Please grab the files from here https://github.com/JetBrains/JetBrainsMono/tree/master/fonts to confirm.

**Comment by mahozad** [comment]
@philippnurullin With font size 13 and line spacing 1.0, there seems a little bit vertical overlap between them. But anyway, thank you.

**Comment by philippnurullin** [comment]
@mahozad Yes, the overlap can be present. It can occur when some rounding is applied to calculation of line height in IDE. The height of multiline brackets can be reduced but is will create gaps in some cases, so that's a compromise.
