### ISSUE TITLE
Add bitcoin symbol

### ISSUE THREAD

**Issue by bulenkov** [JetBrains/JetBrainsMono#292]
https://en.bitcoin.it/wiki/Bitcoin_symbol

**Comment by haardikdharma10** [comment]
Hi @bulenkov, @philippnurullin, what exactly needs to be done in this issue?

**Comment by philippnurullin** [comment]
Hi @haardikdharma10 to add Bitcoins symbol support in JetBrains Mono.
It's already included in the next update.
