### ISSUE TITLE
Inconsistent family name between variable upright and variable italic

### ISSUE THREAD

**Issue by Jeremiidesu** [JetBrains/JetBrainsMono#293]
![Windows Font Viewer](https://user-images.githubusercontent.com/20820425/90643376-d56b2600-e233-11ea-9269-223ffaafd0d9.png)
*(No, the `t` from ExtraLight is not cropped in the bottom window, but it is present in the Notepad font picker)*

The italic variant's family name is `JetBrains Mono` while the upright variant is named `JetBrains Mono Variable`, and as such are separated when selecting the font in for example Notepad.

![Notepad font picker](https://cdn.platea.moe/Jeremii/2020/08/notepad_KgrfEqtvRw.png)

OS: Windows 10 v2004, build 19041.388

**Comment by philippnurullin** [comment]
Hi, please do not use variable font with non variable. This will lead to bugs. 
If you want to use JetBrains Mono you have to choose fors what version is suitable for you. I suggest using non variable. But variable function is essential to your project & you not expecting auto pairing with italics you can go wit it. https://github.com/JetBrains/JetBrainsMono/issues/270

**Comment by Jeremiidesu** [comment]
I raised this issue precisely because I was using the two variable variants:
![image](https://user-images.githubusercontent.com/20820425/90652507-6ba44980-e23e-11ea-9ae0-77d85fd80db4.png)

**Comment by Jeremiidesu** [comment]
If anything, I can suggest using the family name `JetBrains Mono Variable Italic` for the variable italic family in order to avoid such issues, just like the variable upright family is called `JetBrains Mono Variable`, or the non-ligatured version is called `JetBrains Mono NL`.

**Comment by philippnurullin** [comment]
Thanks for names suggestion. This may solve the problem. 
Actually i don't remember why i didn't use that strategy. Maybe the were some problems with it or maybe i was tired & stupid.
