### ISSUE TITLE
Small "f" letter looks squished on small fonts with v. 2.001

### ISSUE THREAD

**Issue by raduacosma** [JetBrains/JetBrainsMono#294]
This is v. 1.06:
![Screenshot from 2020-08-22 10-18-55](https://user-images.githubusercontent.com/49650267/90952692-f31fd180-e465-11ea-88a8-17227129a8d5.png)
And this is v. 2.001:
![Screenshot from 2020-08-22 10-19-39](https://user-images.githubusercontent.com/49650267/90952694-f5822b80-e465-11ea-9a23-4162ad808ae8.png)
On the fourth smallest row of the quick brown fox for v. 2.001, the small "f" letter is pretty squished and is not noticeable or aesthetically pleasing. This is not the case for v. 1.06. As an additional note, I think that the previous "f", from version 1.06, also looked better overall. I notice with the new version that the change may have been made in order to line up the lower line of the "f" with the other letter heights, but I think that some tweaks are needed. For example, the horizontal size of the lines is much bigger than the vertical space between them, which is why the letter looks squished. Maybe if the lines were made a bit shorter, the effect would not be as pronounced. Perhaps there is also the fact that the space between the two lines is not as obvious on the fourth smallest row as it is on the others, and if this space is adjusted then the problem would dissapear. This problem also appears for the italic version of the font.

Thank you for the great font and hope this gets addressed soon!

**Comment by philippnurullin** [comment]
Closing it because of the dublication. Please follow the #273
