### ISSUE TITLE
Request for Permission to Use Reserved Font Name

### ISSUE THREAD

**Issue by sharpjs** [JetBrains/JetBrainsMono#295]
In accordance with the OFL-1.1 licence in version 2.002 (#99), I must request permission to continue using the Reserved Font Name "JetBrains Mono" in my modified version, [JetBrains Mono Slashed](https://github.com/sharpjs/JetBrainsMonoSlashed).  The modified version exists _only_ to set the slashed-zero stylistic alternate as the default zero, using [pyftfeatfreeze](https://github.com/twardoch/fonttools-opentype-feature-freezer).

If you choose to not grant permission, I will rename my variant to be in compliance with the new licence.  I would most likely choose a playful name like "SharpBrains Mono Slashed", "JetTrains Mono Slashed", or "SlashBrains Mono".   I would prefer to continue using the name "JetBrains Mono Slashed" though.

**Comment by philippnurullin** [comment]
Permission granted.
Just don't remove us from the credits. )

**Comment by sharpjs** [comment]
Thanks.  Definitely will keep the credits in sync with upstream, because upstream did 100% of the work compared to my 0%. 👍
