### ISSUE TITLE
JetBrainsMono Display Error  in Android ，But Fine in  Newest IDEA

### ISSUE THREAD

**Issue by huminted** [JetBrains/JetBrainsMono#296]
![image](https://user-images.githubusercontent.com/6681890/91513690-88640f80-e917-11ea-9bfb-230675d5cedf.png)

Android Studio 4.0.1
Build #AI-193.6911.18.40.6626763, built on June 25, 2020
Runtime version: 1.8.0_242-release-1644-b01 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by philippnurullin** [comment]
Hi @huminted What font version you installed. Did you install the new version on top of the old one? What are the exact files you installed?

**Comment by huminted** [comment]
I have installed the font which downloaded from the official website and install all of the new version of the zip file  on top of the old one,

发件人: philippnurullin <notifications@github.com>
发送时间: 2020年8月28日 15:06
收件人: JetBrains/JetBrainsMono <JetBrainsMono@noreply.github.com>
抄送: 胡敏 <humin147@live.com>; Mention <mention@noreply.github.com>
主题: Re: [JetBrains/JetBrainsMono] JetBrainsMono Display Error in Android ，But Fine in Newest IDEA (#296)


Hi @huminted<https://github.com/huminted> What font version you installed. Did you install the new version on top of the old one? What are the exact files you installed?

**Comment by philippnurullin** [comment]
Delete all the font from OS first. Install them again. Don't install font on top the old ones, it may lead to some bugs.

Note that *JetBrains Mono Variable* & *JetBrains Mono Variable Italic* will lead to conflict if you install them with normal font version. I recommend to not install variable font if you don't have need for variable function.

**Comment by philippnurullin** [comment]
Look like this helped. If not feel free to reopen the issue.
