### ISSUE TITLE
Is the `hyphen_bar.liga less_asterisk.liga` kern of `-1` intentional or accidental?

### ISSUE THREAD

**Issue by arrowtype** [JetBrains/JetBrainsMono#297]
I’ve noticed that the `hyphen_bar.liga` & `less_asterisk.liga` have a kern of `-1` in the Regular weight. Is this intentional or accidental?

https://github.com/JetBrains/JetBrainsMono/blob/09d45c95de9a6cdd8949892129cb76161b958d3e/source/UFO/Normal/JetBrains%20Mono-Regular.ufo/kerning.plist

I’m guessing it’s accidental (probably caused by hitting the wrong hotkey combo at some point), but the other possibility is that it could be a brilliant weird hack that makes the code ligatures work in Netbeans, which [I am currently having issues with in my own project](https://github.com/arrowtype/recursive/issues/369).

If you have any insight into this, I would really appreciate it! Or, if it’s an accident, no worries.

**Comment by philippnurullin** [comment]
Hi @arrowtype . Sorry to disappoint, this is just a mistake. Thanks for pointing it out. Will correct it in next update. 

Maybe that will help you. It seems like you exporting fonts from Robofont. Both JetBrains Mono & Fira Code mastered/exported from Glyphs app. So it may be a good idea to export Recursive from Glyphs too (free trial?) & compare the end results.
Sorry again & good luck with finding a solution.

**Comment by arrowtype** [comment]
:) Thanks for the quick response!

Interesting suggestion; maybe I'll give that a try and see what f anything changes.

**Comment by arrowtype** [comment]
(Just posting for future reference in case someone else comes across this: the issue in Recursive was that these glyphs overflowed to the right, rather than the left. I had to basically move all points to the left in these glyphs, and shuffle around the placeholder in my OpenType feature. https://github.com/arrowtype/recursive/issues/369#issuecomment-683893101)
