### ISSUE TITLE
Add ‾ {U+203E} character 

### ISSUE THREAD

**Issue by Boreychuk-Ivan** [JetBrains/JetBrainsMono#298]
Can you please add  ‾  {U+203E} character to your font?

**Comment by philippnurullin** [comment]
@Boreychuk-Ivan Hi, can you send an example of text with this symbol. I want to better understand the context of use.

**Comment by Boreychuk-Ivan** [comment]
Here is example. I use it to display logic signals. Editor: Sublime Text 3 (Win 10).
1. Font - "Hack". 
![image](https://user-images.githubusercontent.com/47390744/91726095-5a492e80-eba8-11ea-9d28-63a8a6c737dc.png)
2. Font - "JetBrains Mono"
![image](https://user-images.githubusercontent.com/47390744/91726739-641f6180-eba9-11ea-8cfb-62b3f4ce9df8.png)


As you can see, in second case alignment is broken.

**Comment by philippnurullin** [comment]
Ok, got it. Will add it on the next update.
Please paste a sequence of chars with vertical line, want to know the exact symbol used.

**Comment by Boreychuk-Ivan** [comment]
_______|‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾|________

Thank you!

**Comment by philippnurullin** [comment]
Sorry, mistakenly added this to v2.200 release but it will be added in the next one.
