### ISSUE TITLE
Google Fonts Onboarding

### ISSUE THREAD

**Issue by RosaWagner** [JetBrains/JetBrainsMono#299]
Hello, as you probably know, a lot of people are interested in using this font through Google Fonts platform: https://github.com/google/fonts/issues/2308. I am in charge of preparing it in order to add it to the catalogue. Who can I contact to talk about the process ?

**Comment by philippnurullin** [comment]
Hi @RosaWagner That would be me.

**Comment by RosaWagner** [comment]
Cool. So the idea would be to re-export the fonts with Fontmake, while make sure they match [google fonts spec](https://github.com/googlefonts/gf-docs/tree/master/Spec) in terms of metadata and glyphset (mostly). 

- Is the last release ready enough to allow me to prepare the font ?
- Do you want to fix some open issues first ? In that case, when do you think the font would be ready?
- Do you feel comfortable with receiving a PR from me that fix some stuff and make Fontbakery happy ? (I spotted a naming issue and other metadata stuff for now)

**Comment by RosaWagner** [comment]
We also need tot talk about the reserved font name… maybe a video call could be easier ?

**Comment by philippnurullin** [comment]
Ok. I planned to run test with *Fontbakery* on wednesday. I will fix as much as i can & probably will have questions, so i will be grateful if i can send them to you.

I am comfortable with PR but i don't want to take advantage on your generosity.

I would like to fix #286 before the release on Google Fonts. i believe this will be closed somewhere on this week.

Video Call will be nice. We can schedule on wednesday. I'm available from 11am to 19am (UTC +3).

**Comment by RosaWagner** [comment]
Eheh I am UTC+2, so let's do video call around 4pm for you, 3pm for me. To what email address can I send you a hangout link ? (or you can send me any link to my email address on my website)

To run fontbakery you will have to resolve the naming issue first: italic has "variable" in the family name, so FB doesn't recognise the font as the same family. Make sure the upright and the italic share the same family name.

**Comment by philippnurullin** [comment]
Ok, it's settled then philipp.nurullin@jetbrains.com 

Ok, will correct that.

**Comment by davelab6** [comment]
Thank you both! Really nice to see your active maintenance @philippnurullin :D
