### ISSUE TITLE
Android Studio editor font

### ISSUE THREAD

**Issue by nuhkoca** [JetBrains/JetBrainsMono#3]
Do you support Android Studio? I cannot see JetBrains Mono in the dropdown menu.

**Comment by Diablo-D3** [comment]
Android Studio doesn't seem to have shipped a version based on 2019.3, so you'd follow the directions you would for "older IDEA or other IDE", which is download the font, install it on your computer like you would any font, and then select it in your IDE.

**Comment by nuhkoca** [comment]
@Diablo-D3 thanks for informing. I will do that once 2019.3 is shipped.

**Comment by AkashKumarKhatri** [comment]
> Android Studio doesn't seem to have shipped a version based on 2019.3, so you'd follow the directions you would for "older IDEA or other IDE", which is download the font, install it on your computer like you would any font, and then select it in your IDE.

Thanks for sharing.

**Comment by gaofeng390379848** [comment]
The fonts installed in Android Studio look different from those in IDEA, with large font sizes and small font spacing that cannot be adjusted

**Comment by knifebrink** [comment]
copy **-Bold, **-Bold-Itailc,  **-Itailc, **-Regular to *\Android Studio\jre\jre\lib\fonts will be well.

**Comment by Sormox** [comment]
its 2021 . still Android studio don't support Jetbrain Mono font , so to install it , 
1- first download it : https://www.jetbrains.com/lp/mono/  as zip file
2- extract it and go JetBrainsMono-2.225\fonts\variable\
3- Select JetBrainsMono[wght].tff and install it to windows system 
4- Now go to android Studio open settings -> Editor -> fonts 
5- Uncheck Show only monopaced fonts box and Select the Jetbrain Mono 
6- Apply and ok

**Comment by dev-sareno** [comment]
> copy **-Bold, **-Bold-Itailc, **-Itailc, **-Regular to *\Android Studio\jre\jre\lib\fonts will be well.

This works, but the path is slightly different, it's `C:\Program Files\Android\Android Studio\jre\lib\fonts`.
