### ISSUE TITLE
Are you planning to add a retina version like Fira Code Retina?

### ISSUE THREAD

**Issue by eranthis** [JetBrains/JetBrainsMono#30]
Thank you for your work! It would be nice if there was a version optimized for HiDPI displays, bolder than regular but lighter than medium. Do you have similar plans?

**Comment by only** [comment]
@eranthis JetBrains Mono Retina is halfway through the development... Coming soon!!!

**Comment by Jeff11** [comment]
Strangely, my problem is the other way around. JetBrains Mono is too bold for me. I wonder if that's just my machine. Screenshots here: https://intellij-support.jetbrains.com/hc/en-us/requests/2453835

**Comment by philippnurullin** [comment]
Hi. Actually the Regular wight of JetBrains Mono is already a lot bolder that usual (to grab extra pixels on monitors), so instead we thought to add the Semilight version, to perform best on the dark background, as one of the next steps. Right now the bug fixing is our top priority. After that we will analyse all the feedback & decide on the order of additions. So, to be direct, we don't have plans to make an HiDPI weight now, but if it will be highly demanded we will add it.

**Comment by philippnurullin** [comment]
@Jeff11 Looks like it's a bug. The image with JetBrains Mono is set in Bold weight. We had a few of such reports & continue to research the problem. 
Thank you for feedback!

**Comment by philippnurullin** [comment]
Closing this issue because it was answered & no fix is required.
@Jeff11 I believe the problem you encountered is https://youtrack.jetbrains.com/issue/IDEA-224652. Unfortunately it can be slowed only on IDE level. The current workaround is to switch to Grayscale antialiasing. Please follow the ticket on youtrack.

**Comment by sihayas** [comment]
curious if you ever got around to this?
