### ISSUE TITLE
Apache v2 license still mentionned in README after move to OFL

### ISSUE THREAD

**Issue by MicroJoe** [JetBrains/JetBrainsMono#301]
In commit 09d45c9, the SOURCE_CODE_LICENSE file is deleted.

We assume that the goal is to move the whole project under OFL instead of Apache v2.0. However the `README.md` file still mentions Apache v2 license after OFL license.

See PR #300 for a resolution proposal.

**Comment by MicroJoe** [comment]
s/SIL/OFL

**Comment by philippnurullin** [comment]
Closing it, because discussion is in the PR.
