### ISSUE TITLE
Recommended line height?

### ISSUE THREAD

**Issue by derekschinke** [JetBrains/JetBrainsMono#302]
On the info page for JetBrains Mono [here](https://www.jetbrains.com/lp/mono/), the recommended _line spacing_ is 1.2. But some editors, like VSCode and Visual Studio, don't let you set _line spacing_; they only support setting the _line height_ as an integer number of pixels. Would this mean that the recommended _line height_ (for the recommended font size of 13) is 16 (rounded from 15.6)?

**Comment by philippnurullin** [comment]
Yes. 

But bear in mind that it's only a recommendation. The optimal line height is dependent on line length. So if you deal with a lot of long lines in your language it may be wise to increase line height. Trust your eyes & don't hesitate to tweak it.

Do you have any more questions or i can close the issue?

**Comment by derekschinke** [comment]
You can definitely close it! Couldn't find any other documentation so this confirmation great, thanks!
