### ISSUE TITLE
Add =: ligature to be the same as :=

### ISSUE THREAD

**Issue by ilyakooo0** [JetBrains/JetBrainsMono#305]
I thought the two operators should look the same but reversed.

This can be very useful in languages where you can define custom operators.

This is how they currently look:

<img width="372" alt="Screenshot 2020-09-08 at 22 42 09" src="https://user-images.githubusercontent.com/6209627/92520599-89087a00-f224-11ea-8f88-23155b63b49a.png">

**Comment by BornForFever** [comment]
Could u tell me where is `=:` used?

**Comment by ilyakooo0** [comment]
Here is one of the example I had the need to use: https://hackage.haskell.org/package/req-3.6.0/docs/Network-HTTP-Req.html#v:-61-:

There are actually numerous libraries the define it in Haskell: https://hoogle.haskell.org/?hoogle=%3D%3A&scope=set%3Astackage

**Comment by BornForFever** [comment]
OK, I see.
