### ISSUE TITLE
Font ligature request: -=, +=

### ISSUE THREAD

**Issue by mateushnsoares** [JetBrains/JetBrainsMono#306]
Add font ligature to -= and +=

-= and += is a javascript, python, and others languages operator.

In most languages is used to make something like this:
```js
variable += 2
```
is the same as
```js
variable = variable + 2
```
the same thing too -=:
```js
variable -= 2
```
is the same as
```js
variable = variable - 2
```

**Comment by philippnurullin** [comment]
Hi @mateushnsoares . Please add more context to your suggestion. 
1. Is this sequence of symbols is logical bit? For example is it an operator?
2. In what context this is used?
3. In what language & situation it can be helpful?

**Comment by Omnieboer** [comment]
I think -= and += are pretty universal in being compound operation and assignment, but wouldn't necessarily benefit from a ligature. I think they are already incredibly readable. However, the same is true for == as far as I'm concerned, and I love the ligature for that.

In my use case (where -= and += do only mean operation and then assignment) I think a ligature would be super cool, but not necessary.

Also don't have any idea how it would make the meaning clearer. The /= ligature does increase readability in my opinion, but I don't know how -= or += would look, never mind *=.

It feels like the only option is almost completely replacing the glyphs, like in >= and <=, but I'm not sure that's a good idea in this case.

Just my two cents.

**Comment by mateushnsoares** [comment]
> Hi @mateushnsoares . Please add more context to your suggestion.
> 
> 1. Is this sequence of symbols is logical bit? For example is it an operator?
> 2. In what context this is used?
> 3. In what language & situation it can be helpful?

I will edit

**Comment by BornForFever** [comment]
> I think -= and += are pretty universal in being compound operation and assignment, but wouldn't necessarily benefit from a ligature. I think they are already incredibly readable. However, the same is true for == as far as I'm concerned, and I love the ligature for that.
> 
> In my use case (where -= and += do only mean operation and then assignment) I think a ligature would be super cool, but not necessary.
> 
> Also don't have any idea how it would make the meaning clearer. The /= ligature does increase readability in my opinion, but I don't know how -= or += would look, never mind *=.
> 
> It feels like the only option is almost completely replacing the glyphs, like in >= and <=, but I'm not sure that's a good idea in this case.
> 
> Just my two cents.

@philippnurullin  I think they currently already look good. If you are going to add ligatures, I think moving these two characters a little closer is enough.

**Comment by philippnurullin** [comment]
I don't see the problem we will solve by making ligature out of `+=`, `-=`.
Good cause for ligature to appear is ability to improve spacing. However in this case the spacing of `+`, `=`, `-` is well balanced & tight to the system. The changing of it may cause negative effect on reading.
<img width="1278" alt="Screenshot 2020-09-21 at 10 58 58" src="https://user-images.githubusercontent.com/48058957/93744457-8a5d7d80-fbfa-11ea-8383-2f30226a37d4.png">

**Comment by CodeCrazy-ywt** [comment]
Well, in my opinion, `+=` looks good enough, but as for `-=`, there is too much whitespace between `-` and `=`.
