### ISSUE TITLE
JavaScript's strict equality operator (===) ligature looks ugly in many font sizes

### ISSUE THREAD

**Issue by jwbth** [JetBrains/JetBrainsMono#307]
JavaScript's [strict equality operator (===)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Strict_equality) and [strict inequality operator (!==)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Strict_inequality) have unevenly distanced strokes in many font sizes.

15px (good)
![image](https://user-images.githubusercontent.com/33615628/92973063-0255d600-f48c-11ea-8a0b-9ab6b03ba5dd.png)
![image](https://user-images.githubusercontent.com/33615628/92974129-35996480-f48e-11ea-8b98-fd3809f25902.png)
14px (bad)
![image](https://user-images.githubusercontent.com/33615628/92972857-a8eda700-f48b-11ea-94b0-fdeb33455f40.png)
![image](https://user-images.githubusercontent.com/33615628/92974175-519d0600-f48e-11ea-9734-22f571214b25.png)
13px (bad)
![image](https://user-images.githubusercontent.com/33615628/92974361-afc9e900-f48e-11ea-9be7-414ac334403d.png)
![image](https://user-images.githubusercontent.com/33615628/92974208-64173f80-f48e-11ea-9222-959ff71243b3.png)
12px (bad/good)
![image](https://user-images.githubusercontent.com/33615628/92973006-efdb9c80-f48b-11ea-8569-58a7c178693c.png)
![image](https://user-images.githubusercontent.com/33615628/92974252-74c7b580-f48e-11ea-93b9-28f4515cc2d7.png)

The look of the operators is also inconsistent in 12px: the bottom stroke is at a larger distance in the first case.

Compare [Cascadia Code](https://github.com/microsoft/cascadia-code) SemiLight
15px
![image](https://user-images.githubusercontent.com/33615628/92973349-ae97bc80-f48c-11ea-9631-822549f0501d.png)
14px
![image](https://user-images.githubusercontent.com/33615628/92973398-cbcc8b00-f48c-11ea-9be8-698331723785.png)
13px
![image](https://user-images.githubusercontent.com/33615628/92973424-dab33d80-f48c-11ea-95f6-b6eef69beb54.png)
12px
![image](https://user-images.githubusercontent.com/33615628/92973459-eacb1d00-f48c-11ea-8967-0d317c1ceb7a.png)

This harms the experience when coding in JavaScript.

**Comment by BornForFever** [comment]
That's the TTF rendering problem.

**Comment by jwbth** [comment]
What can users like me do about it? I'm on Windows 10.

Also, is the different look of glyphs ![image](https://user-images.githubusercontent.com/33615628/92973006-efdb9c80-f48b-11ea-8569-58a7c178693c.png) ![image](https://user-images.githubusercontent.com/33615628/92974252-74c7b580-f48e-11ea-93b9-28f4515cc2d7.png) also a rendering problem? Would seem to me it's related to their internal characteristics, they won't look different if it isn't.

**Comment by BornForFever** [comment]
You can try installing the variable fonts, but that kind of fonts may blur.

**Comment by jwbth** [comment]
Haven't succeed with that in Sublime Text 3 unfortunately.

**Comment by BornForFever** [comment]
Maybe that's because sublime text 3 doesn't support variable fonts. However, vscode does.

**Comment by philippnurullin** [comment]
Dublicated https://github.com/JetBrains/JetBrainsMono/issues/25

**Comment by BornForFever** [comment]
> Haven't succeed with that in Sublime Text 3 unfortunately.

Oh, i forgot to tell you to uninstall the old fonts first.
