### ISSUE TITLE
Do you have plan to add Chinese word support

### ISSUE THREAD

**Issue by DreamParadise** [JetBrains/JetBrainsMono#310]
Do you have plan to add Chinese word support?🙂

**Comment by philippnurullin** [comment]
Hi @DreamParadise Here is similar issue https://github.com/JetBrains/JetBrainsMono/issues/242
To make it short, we don't have expertise to add Chinese support.

**Comment by BornForFever** [comment]
> Do you have plan to add Chinese word support?🙂

Why not set a Chinese font as a fallback font? That's the easiest way to solve this problem.
