### ISSUE TITLE
messy code in Android studio

### ISSUE THREAD

**Issue by suifengczc** [JetBrains/JetBrainsMono#311]
there are all messed up codes in Android studio4.0.1
Jetbrains Mono version = V2.002
looks like this 
![jbMono](https://user-images.githubusercontent.com/20556245/93108628-a1293f00-f6e5-11ea-8e2b-8f3b7d193866.png)
![jbMono1](https://user-images.githubusercontent.com/20556245/93108659-a71f2000-f6e5-11ea-9f4b-a33ee44ccc6b.png)

**Comment by philippnurullin** [comment]
This might help. https://github.com/JetBrains/JetBrainsMono/issues/296

**Comment by suifengczc** [comment]
> This might help. #296

Thank you! It's working now.
One thing to note is that the font files still exist in the C:\Windows\Fonts folder after deleting them via windows settings. They are not visible though, which can be disruptive. Need to delete them manually.
