### ISSUE TITLE
Add promotional documents

### ISSUE THREAD

**Issue by RosaWagner** [JetBrains/JetBrainsMono#313]
Can you add a folder called "documentation" with a specimen and 2-3 images (or even a video) for promotional purpose? We will need to tweet about the font when it will be released on GF ;)

**Comment by philippnurullin** [comment]
Shure, will work on that after we settle with font corrections. 
Video will be nice. Any suggestion on aspect ratio or example?

**Comment by RosaWagner** [comment]
Your are completely free for that matter ;)

**Comment by bulenkov** [comment]
@tatianatulu could you please help us with materials?
