### ISSUE TITLE
Activate GH actions

### ISSUE THREAD

**Issue by RosaWagner** [JetBrains/JetBrainsMono#315]
Hello, with a colleague we would like to test the installation of a GH action for continuous integration testing with Fontbakery. It would allow to test the binaries every time they are built in the repo, without having to install Fontbakery locally. I would like to experiment this on my fork, but I may need you to activate the GH actions here. 

It would also help a lot if you merge my PR so I can experiment on my fork without influencing things here. Is there a problem with the PR ?

**Comment by philippnurullin** [comment]
Hi @RosaWagner Looks like Actions are enabled in setting of this repo. Do you have issues?

**Comment by RosaWagner** [comment]
Great thank you :) I wasn't sure. We are trying to automate the building and the checking to avoid users to have to install all the packages. For example they just would have to modify the sources, and then the github actions take care of the rest! 

Tell me when your fonts is pushed in the repo, which branch, and I'll check it.

**Comment by philippnurullin** [comment]
Ok, i expecting the update in the start of the next week. Need to redo italics. 
Also can you help with this issue https://github.com/JetBrains/JetBrainsMono/issues/25 I experimineted with manual hinting but it broke the variable fonts on export so i'm kinda stuck with it. Any thought will be appreciated.
