### ISSUE TITLE
Glyphs for up and down arrows.

### ISSUE THREAD

**Issue by pjrvs** [JetBrains/JetBrainsMono#317]
Please and thank you! Love this font, I just need those to work as HTML characters.

**Comment by philippnurullin** [comment]
Hi @pjrvs 
I suggest updating to the latest version from here https://github.com/JetBrains/JetBrainsMono/releases Thees arrows `↑` `↗` `→` `↘` `↓` `↙` `←` `↖` `↔` `↕` was added some time ago.

If you did not find the arrows you were looking for please add the exact unicodes for symbols or paste them in text.
