### ISSUE TITLE
Differentiating between hyphen, en-dash, and em-dash

### ISSUE THREAD

**Issue by dervist** [JetBrains/JetBrainsMono#318]
Currently, the difference between the three: the hyphen, the en-dash, and the em-dash, is so small, that it is hardly perceivable, which makes JetBrains unusable in any area in which that difference is important – basically, in every setting except programming. It would be awesome if this could be remedied since authors and especially editors benefit greatly from monospaced typefaces.

My suggestion regarding this would be as follows:

1. make the em-dash, as wide as possible,
2. make the hyphen about 1/2 the width of the em-dash,
3. finally, make the en-dash somewhere in between, about 3/4 the width of the em-dash.

In proportional typefaces, the ratio is usually this: em-dash = 1, en-dash = 0.5, hyphen = 0.25. This would be ideal, but it’s hardly achievable in monospaced typefaces.

![dashes](https://user-images.githubusercontent.com/26790323/94128294-7fe4f300-fe49-11ea-8483-be76f3b46e9f.png)

**Comment by philippnurullin** [comment]
Hi @dervist Thanks for the feedback. 
I will update the symbol in the next release.
