### ISSUE TITLE
Package for iOS/iPad OS

### ISSUE THREAD

**Issue by pdfinn** [JetBrains/JetBrainsMono#319]
It would be great to see JetBrains Mono packaged as an app for installation on iOS — particularly iPadOS.  An increasing number of developers, including myself, are using this tool for lightweight coding and we miss this excellent font.

**Comment by bulenkov** [comment]
Please use the Foncase app to install JetBrains Mono on iOS/iPadOS 
https://9to5mac.com/2020/06/12/fontcase-open-source-fonts-app-iphone-ipad/

![image](https://user-images.githubusercontent.com/4202603/95001879-b3a0e500-05ce-11eb-869b-e1f0114ad420.png)
