### ISSUE TITLE
Font smoothing problem

### ISSUE THREAD

**Issue by DjArt** [JetBrains/JetBrainsMono#32]
There are some problems with font smoothing in Windows 10.0.19541.0
![image](https://user-images.githubusercontent.com/1651555/72550185-be8eda80-38c4-11ea-8992-9314add5ab3a.png)

**Comment by DjArt** [comment]
Also on image from post on habr.com too
![image](https://user-images.githubusercontent.com/1651555/72550491-6e644800-38c5-11ea-9640-ebd0de4eb8e2.png)

**Comment by philippnurullin** [comment]
I'm not sure i follow the problems you mentioned. Can you describe it more precise?

**Comment by aaronbell** [comment]
@philippnurullin 

I think what @DjArt is noting is the stair-step rendering, particularly in the italic form. Might you be serving the OTF versions on the website? If so, I’d suggest using the TTF versions.

**Comment by philippnurullin** [comment]
@philippnurullin Yes, i see the stairs, but it is to be expected on low dpi screen. The same artefacts can be seen in slanted strokes of M, at the top of screenshot. So to me it looks like the harsh truth of low dpi. But i will be glad to help, if it is not.
We are not using OTF.

**Comment by aaronbell** [comment]
True, low dpi will show stepping, but at this point size I’d expect it to be much less prominent, no? This sample almost looks like antialiasing is turned off.

It would be useful to get the specs on @DjArt’s computer screen.

**Comment by DjArt** [comment]
@aaronbell Right, that is low dpi 1600x900 screen. Segoe UI and DejaVu Sans Mono looks better, but Consolas has same problems.
![image](https://user-images.githubusercontent.com/1651555/72648613-0b9aab80-39ae-11ea-85cd-54637ff28707.png)
![image](https://user-images.githubusercontent.com/1651555/72648621-0fc6c900-39ae-11ea-88ac-73f41ace3f3b.png)
![image](https://user-images.githubusercontent.com/1651555/72648622-11908c80-39ae-11ea-8808-7665c34da101.png)

**Comment by aaronbell** [comment]
@DjArt what application is this?

It is looking increasingly like an app rendering issue than a font rendering one :)

**Comment by DjArt** [comment]
@aaronbell That's Windows Settings -> Personalization -> Fonts, so usual UWP font rasterizer.

**Comment by aaronbell** [comment]
Ahh. So Grayscale Cleartype most like. Probably not much that can be done to improve rendering unfortunately.

**Comment by philippnurullin** [comment]
@DjArt Sorry we can't do anything to help.
