### ISSUE TITLE
uni00A

### ISSUE THREAD

**Issue by RosaWagner** [JetBrains/JetBrainsMono#324]
I got a fail from Fontbakery
```
    * FAIL: The following unacceptable control characters were identified:
 fonts/variable/JetBrainsMono[wght].ttf: uni000A
 fonts/variable/JetBrainsMono-Italic[wght].ttf: uni000A
 [code: unacceptable]
    Result: FAIL
```

Apparently Google doesn't accept this glyphs. Do you need it for a reason ? It looks like a legacy glyphs that is not used anymore.

**Comment by philippnurullin** [comment]
Hi @RosaWagner .
Shure i will remove it.

**Comment by RosaWagner** [comment]
It's okay I do it ;)

**Comment by philippnurullin** [comment]
Fixed in latest push. )
