### ISSUE TITLE
Visual Studio Ligature -> not working

### ISSUE THREAD

**Issue by Frank-Mayer** [JetBrains/JetBrainsMono#326]
I am using Visual Studio 2017 and all Ligatures are working, except of ->
![screenshot](https://user-images.githubusercontent.com/53651857/95837153-91326880-0d40-11eb-854f-9e1ecc997e22.JPG)

**Comment by philippnurullin** [comment]
Hi @Frank-Mayer This is bug in Visual Studio. 
Dublicated in  https://github.com/JetBrains/JetBrainsMono/issues/133
