### ISSUE TITLE
Add font to Microsoft Store

### ISSUE THREAD

**Issue by DjArt** [JetBrains/JetBrainsMono#33]

**Comment by mgruca** [comment]
I would raise my hand for Chocolatey but all sources of distribution of updates that are widely acceptable would help to be controlled by JB :)

**Comment by philippnurullin** [comment]
https://github.com/JetBrains/JetBrainsMono/issues/93

**Comment by Cirzen** [comment]
It's now live in Chocolatey: https://chocolatey.org/packages/jetbrainsmono/1.0.2
`choco install jetbrainsmono` will pull it down to your machine.

**Comment by philippnurullin** [comment]
@Cirzen Nice! Although you might want tot update it to 1.0.3  https://github.com/JetBrains/JetBrainsMono/releases/tag/v1.0.3

**Comment by Cirzen** [comment]
I have done; needed to get the first version approved first. Hopefully the update will come through a little quicker!
Would you consider adding it to the install instructions in the readme, below the homebrew instructions?

**Comment by philippnurullin** [comment]
@Cirzen Yes! It will help greatly if you can do the pull request with legitimate instructions.

**Comment by Cirzen** [comment]
#154 Opened with instructions

**Comment by philippnurullin** [comment]
Considering the amount of sources you can get JetBrains Mono from,  i'm not seeng the need to add it to the Microsoft Store. Closing this issue.

**Comment by brokenthorn** [comment]
> Considering the amount of sources you can get JetBrains Mono from, i'm not seeng the need to add it to the Microsoft Store. Closing this issue.

Because Microsoft has opened the MS Store to all binaries, not only UWP applications. Even Android apps are coming. It will probably become the Deb/Apt sources.list for the Windows world. 😊
