### ISSUE TITLE
Does JB Mono/JB Code support Powerline?

### ISSUE THREAD

**Issue by 1900011604** [JetBrains/JetBrainsMono#331]
I am using oh-my-zsh and some of its themes requires powerline fonts like Cascadia Code PL. I don;t know if JB code supports this.

**Comment by 1900011604** [comment]
By the way I met this when installing an my Linux
```
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/JetBrains/JetBrainsMono/master/install_manual.sh)"
Installing latest JetBrains Mono fonts...
Checking requirements...
awk... Found
curl... Found
fc-cache... Found
mkdir... Found
mktemp... Found
unlink... Found
unzip... Not found

```

**Comment by philippnurullin** [comment]
Hi @1900011604 

- JetBrains Mono supports Powerline. You can find the symbol preview at the bottom of all symbols showcase. https://www.jetbrains.com/lp/mono/#font-family
- Regarding `install_manual.sh` you can ask the original creator of this script https://github.com/JetBrains/JetBrainsMono/pull/288

**Comment by nisrulz** [comment]
I wasn't tagged earlier here. @1900011604  I can take a look again at the script :)

**Comment by nisrulz** [comment]
The script got changed in PR #308 . @1900011604 you are missing the `unzip` cli tool, not sure how.. but try installing using `sudo apt install unzip`. The script is just making sure you have all CLI tools it uses upfront. If missing it tells you which ones are missing. Simply install them and you should be good. 

Note: There is an ongoing issue #405 with the script. So keep an eye on it, maybe you might also encounter it. Once that is fixed you should be good :)
