### ISSUE TITLE
Different look of JBM on Chrome & Safari Browser

### ISSUE THREAD

**Issue by itsderill** [JetBrains/JetBrainsMono#332]
Hi there,

first: thanks for creating this amazing font! I am using JBM for my Shopify Store but one thing is weird: the font weight on Chrome is totally different as on Safari Browser. On Safari the font looks much thinner and uglier. On Safari it should look like the same as on Chrome. Are you able to help here?

**See Screenshot:**

<img width="405" alt="JBM on Safari and Chrome" src="https://user-images.githubusercontent.com/73215165/96680758-69618700-1376-11eb-9382-6304159ca652.png">

Thank you and best regards from Germany
Patrick

**Comment by philippnurullin** [comment]
Hi @itsderill I'm not a front end developer but lets see. What format you using in `@font-face`?

**Comment by itsderill** [comment]
Hi @philippnurullin thanks for your reply. Enclosed in the screenshot you can find the code. Mainly I am using JetBrainsMono-Regular for text and all headlines (like the gradient headline you can see above). But the font-weight on Apple devices looks way lower as on Chrome. Do I have to change the code here a bit?

<img width="412" alt="FontFace_code" src="https://user-images.githubusercontent.com/73215165/96865591-752e7580-146a-11eb-8c1d-b8d8dc1b6ad4.PNG">

**Comment by philippnurullin** [comment]
Looks like there is an error in your code. The font weight is not specified for the bold weight.

Here is example:
```
@font-face {
  font-family: JetBrains Mono;
  src: url("...") format("woff");
  font-weight: 700; /* Bold */
  font-style: normal;
}
```
And it will be vise to update to the latest version of the font and use .woff2 instead of .woff.

**Comment by itsderill** [comment]
Thank you, I will give it a try an let you know!

**Comment by itsderill** [comment]
I have downloaded the last version of JBM and now I am using woff2. Also I have adapted the code accordingly but unfortunately without success. The font still looks different in Safari than in Chrome (see screenshot for comparison). Any other thoughts?

![Uploading JBM_on safari and chrome.png…]()

**Comment by philippnurullin** [comment]
The error is in the CSS. You using the `JetBrainsMono-Regular` with weight 700. This will not work. 
Please look again at the example of thee code above. The problem is here `font-family: JetBrains Mono;`. Just use name of the font family, not the exact weight.
<img width="336" alt="Screenshot 2020-10-22 at 16 27 52" src="https://user-images.githubusercontent.com/48058957/96878488-9780bd00-1483-11eb-83d1-64ba6147a1c9.png">
