### ISSUE TITLE
Bold russian "в" looks not that great

### ISSUE THREAD

**Issue by habamax** [JetBrains/JetBrainsMono#335]
Gvim, fontsize 14

![image](https://user-images.githubusercontent.com/234774/96745621-0223f100-13cf-11eb-8051-afbecfa35ee4.png)

fontsize 12
![image](https://user-images.githubusercontent.com/234774/96745728-1bc53880-13cf-11eb-9451-081357eeee76.png)

**Comment by philippnurullin** [comment]
Yes this can be improved. Thanks for the feedback.

**Comment by philippnurullin** [comment]
@habamax Hi please confirm or deny the change. Grab the font from here https://github.com/JetBrains/JetBrainsMono/tree/master/fonts

**Comment by habamax** [comment]
Отлично!

![image](https://user-images.githubusercontent.com/234774/102996646-86603500-4534-11eb-8c53-ffe877f69a91.png)

**Comment by philippnurullin** [comment]
Thanks! 
I see the «ж» needs some tuning too. Will fix this in the next update.
