### ISSUE TITLE
Hexadecimal rendering issue: "0xFF" turns to "0 times FF"

### ISSUE THREAD

**Issue by mvasilkov** [JetBrains/JetBrainsMono#337]
Hi,

Just wanted to point out that the new ligature for the 0x prefix in hexadecimal is misleading:

- the multiplication sign between numbers is commonly used for, well, multiplying numbers
- 0 × N == 0 in most cases
- therefore misrepresenting "0xFF" as "0 × FF" actually changes the meaning of the text as written: 255 != 0.

This is also inconsistent with the other prefix notations, such as 0b, 0o, and with the uppercase notation 0X (which stays correct and doesn't turn into multiplication sign).

Please fix / revert.

**Comment by philippnurullin** [comment]
This issue is creates an opportunity for duplicate discussion. I'm closing it.

Please use the original issue for the feedback and discussion.
https://github.com/JetBrains/JetBrainsMono/issues/98

**Comment by mvasilkov** [comment]
That issue is also closed though.

**Comment by philippnurullin** [comment]
Yes it's closed because the request was satisfied.
Please explain your point. What's wrong with it being closed?

**Comment by mvasilkov** [comment]
I observed a rendering issue with the font, where a character 'x' occasionally gets substituted by an unrelated math symbol. IMO it's a bug, so I opened an issue to report a bug.

I mean, it's your thing as a maintainer to do whatever, I don't argue. I legit just want a good programming font, is all.
