### ISSUE TITLE
VOTE ---- Which type do you want for 'u' and 'a'?

### ISSUE THREAD

**Issue by 1900011604** [JetBrains/JetBrainsMono#338]
1.There are 2 u's:
A. with a vertical line on the right
![Screenshot_20201022_193952](https://user-images.githubusercontent.com/65082432/96866763-5c3fb780-149e-11eb-8420-4677a902cb51.png)
B. without a vertical line on the right
![Screenshot_20201022_194030](https://user-images.githubusercontent.com/65082432/96866825-75e0ff00-149e-11eb-872c-373fc33fb049.png)

2.And there are 2 a's:
A. Consolas' type
![Screenshot_20201022_193836](https://user-images.githubusercontent.com/65082432/96866652-30bccd00-149e-11eb-910b-9e783af7567c.png)
B. Monaco's type
![Screenshot_20201022_193918](https://user-images.githubusercontent.com/65082432/96866726-492ce780-149e-11eb-82bd-6b1404482def.png)

Which type do you programmers think that is easier (to use less time) for you to recognize?

**Please do not close this!**

**Comment by 1900011604** [comment]
First for me it is 
1.A
2.B

**Comment by philippnurullin** [comment]
Hi @1900011604 This is not a platform for creating polls and i don't see at as constructive.
If you have an issue please describe what difficulties you experience or leave a request. If you have a suggestion please present arguments of your point.
