### ISSUE TITLE
Brace alignment

### ISSUE THREAD

**Issue by EugeneDraitsev** [JetBrains/JetBrainsMono#34]
Hi, I have pretty simple question/feature request

Is there any reasons why braces in font are misaligned? It looks a bit confusing and maybe make sense to fix alignment?

![image](https://user-images.githubusercontent.com/16540432/72563803-ba57c280-38ae-11ea-8032-ff1f3ca88f8a.png)

**Comment by fuzzywalls** [comment]
Came here to put the same ticket in, however my brackets are uneven in the opposite direction. 

![Screen Shot 2020-01-16 at 4 13 37 PM](https://user-images.githubusercontent.com/39141855/72564123-130e6780-387d-11ea-9814-b06998e162a2.png)

**Comment by EugeneDraitsev** [comment]
Whoops, Duplicate of #21
