### ISSUE TITLE
'b' 'p' 'd' 'q' are barely distinguishable on small size.

### ISSUE THREAD

**Issue by pakLebah** [JetBrains/JetBrainsMono#35]
Because JBM (Jetbrains Mono) font has bigger body, it makes the head and tail smaller. It becomes problem on small size font, which is less than 14 pt for my eyes. For example, the 'b' and 'p' are barely distinguishable, the 'd' and 'q' as well. So with JBM, you have to choose a bit bigger font size than normally you use to make those letters more obvious.

Here's a video that shows how JBM looks from 10 pt to 11, 12, 13, 14, 18, 24, 36, 48 respectively.
![jbm_10 11 12 13 14 18 24 36 48](https://user-images.githubusercontent.com/11470932/72573130-4097f700-38f7-11ea-9174-c316bc24e1c2.gif)

**Comment by philippnurullin** [comment]
@pakLebah Hi, i changed the _asc_ & _desc_ a bit in v1.0.3 The further modification will start to breaking the eye flow i was talking earlier.
