### ISSUE TITLE
Exaggerated line height in 2.200

### ISSUE THREAD

**Issue by DannyBen** [JetBrains/JetBrainsMono#350]
The line height changes in 2.200 make it much less usable than 2.001.

It looks unnatural in my opinion, and reduces the number of visible lines noticeably.

I observed this undesired height in two non-editor applications: PuTTY and Free Commander file browser. However, the line height still seem to be ok (== same as before?) when used in Sublime Text.

## Screenshots from PuTTY

Same number of rows require different screen height.

![image](https://user-images.githubusercontent.com/2405099/97153893-deb8c780-177b-11eb-801d-952701222fc6.png)

## Screenshots from Free Commander

Same screen height, showing 2 files less in 2.200.

![image](https://user-images.githubusercontent.com/2405099/97154054-1f184580-177c-11eb-91ae-619064647023.png)

**Comment by shabahengam** [comment]
duplicate of #334

**Comment by DannyBen** [comment]
Oh sorry, didn't notice.
