### ISSUE TITLE
Brace after sharp symbol ("#{") seems odd

### ISSUE THREAD

**Issue by trishchuk** [JetBrains/JetBrainsMono#352]
Don't know if this is a bug or a feature, but with brace (curly bracket) the 'sharp' symbol seems a little bit overfilled comparing to other types of brackets.

Example (C# string interpolation):
![image](https://user-images.githubusercontent.com/177282/97289058-5ad00f80-184f-11eb-8b2b-1b4e16c5bd57.png)

**Comment by philippnurullin** [comment]
Dblicated in https://github.com/JetBrains/JetBrainsMono/issues/130
This is ligature for Ruby operator.
