### ISSUE TITLE
Different ligatures for brackets in `[| |]` and `[||]`

### ISSUE THREAD

**Issue by auduchinok** [JetBrains/JetBrainsMono#353]
When using F#/OCaml arrays, a different ligature is used for an empty array without a space between the brackets:

<img width="320" alt="Screenshot 2020-10-29 at 15 35 50" src="https://user-images.githubusercontent.com/3923587/97576864-be00a400-19ff-11eb-9d7a-e3c05f717ded.png">

More examples of arrays:
```fsharp
let a1 = [| foo; bar |]
let a2 = [| |]
let a3 = [||]
```

**Comment by philippnurullin** [comment]
Please test the latest update https://github.com/JetBrains/JetBrainsMono/tree/master/fonts

**Comment by auduchinok** [comment]
Works perfectly, thanks!
<img width="215" alt="Screenshot 2021-01-25 at 17 55 37" src="https://user-images.githubusercontent.com/3923587/105722301-9190f100-5f36-11eb-8c88-5cb997d945d4.png">
