### ISSUE TITLE
Request for ૪ and Ɛ

### ISSUE THREAD

**Issue by meta-meta** [JetBrains/JetBrainsMono#356]
I have a niche application which requires the characters ૪ and Ɛ. So far I have been falling back to Segoe UI for these characters but AFAIK Microsoft does not license Segoe UI for the web. The use case is a duodecimal numeral system so if possible, they should look natural alongside the other digits: 0123456789૪Ɛ

GUJARATI DIGIT FOUR (U+0AEA)
LATIN CAPITAL LETTER OPEN E (U+0190)

**Comment by trygveaa** [comment]
I have never heard about gujarati digit four being used for duodecimal. Why don't you use the [more standard](https://en.wikipedia.org/wiki/Duodecimal#Transdecimal_symbols) ↊ and ↋ (U+218A TURNED DIGIT TWO and U+218B TURNED DIGIT THREE)?

Not that JetBrains Mono supports those either, but seems like they would make more sense to ask for.

**Comment by meta-meta** [comment]
Good question. I was convinced by the thinking in Dominique Waller's paper: http://musicnotation.org/wp-content/uploads/2013/03/Waller_single_digit_symbols.pdf

This is specifically for alternate music notation so I'm putting more weight on distinct looking, quick to read symbols -- the turned digit two reminds me of a 7 -- and not worrying so much about friction with the dozenal society. I wonder now which would fit in better once Jetbrains style is applied to ↋ or Ɛ.

**Comment by meta-meta** [comment]
Another reason, at least on Android these have better built-in support.

**Comment by meta-meta** [comment]
Is there any way to put a bounty on this issue or something?

**Comment by philippnurullin** [comment]
If you mean "how to speed up the process". Ask politely. ))
I will add this to the next update queue.

**Comment by meta-meta** [comment]
Thank you! I'm sorry that came off as impolite. I had started typing a bit about how I'd love to contribute but lack the skills and software plus I didn't want to assume anything about your process or even whether this would make it into the queue.

**Comment by philippnurullin** [comment]
No worries. This project is maintained by a very few people (me mostly), so adding things takes time. 
Sorry if this is not very fast.

**Comment by meta-meta** [comment]
Thank you! This helped me simplify a bunch of code and looks great!
