### ISSUE TITLE
Add to Google Docs, Sheets and Slides

### ISSUE THREAD

**Issue by inferno986return** [JetBrains/JetBrainsMono#357]
Can you JetBrains Mono to Google Docs? I'd like to use it in my documents. 😃

**Comment by Omnieboer** [comment]
https://github.com/google/fonts/issues/2308 <- Follow this. (@)philippnurullin and (@)RosaWagner are on it.

Didn't want to bother them with a notification.

**Comment by inferno986return** [comment]
Ah cool, thanks.

**Comment by hibissscus** [comment]
Please, would be so cool to have it.

**Comment by philippnurullin** [comment]
JetBrains Mono is available on Google Fonts. You can use it in GDocs now.

**Comment by inferno986return** [comment]
@philippnurullin I can't see JetBrains Mono on Google Docs when I edit. Nevertheless, well done getting it onto Google Fonts. Will the non-ligature version be available too?

**Comment by philippnurullin** [comment]
Hi @inferno986return Unfortunately i can't help with integration with Google Docs. It's on Google side now. 
The separate NL version is not planned for Google Fonts.
