### ISSUE TITLE
Make character \u2502 (`│`/ Long |) use full height

### ISSUE THREAD

**Issue by levirs565** [JetBrains/JetBrainsMono#358]
Excepted behavior (like `Fira Mono`):
![brave_LG5Ho1HcLl](https://user-images.githubusercontent.com/42236775/98432948-87a8e000-20f5-11eb-85fe-bf0b33477806.png)
Actual behavior (JetBrains Mono):
![brave_ZetOmSi8tr](https://user-images.githubusercontent.com/42236775/98432955-a313eb00-20f5-11eb-9b64-f04250a1e733.png)

The \u2502 character is widely used in Vim/NeoVim. This make NeoVim looks bad when use JetBrains Mono.

**Comment by philippnurullin** [comment]
Hi @levirs565 Please tell me what version of JetBrains Mono you using?

**Comment by levirs565** [comment]
It turns out that this only happens in JetBrains Mono Nerd Font. It seems I was wrong.
