### ISSUE TITLE
Ligature request: Laravel Blade Template Comment / {{-- --}}

### ISSUE THREAD

**Issue by RajcsanyiZ** [JetBrains/JetBrainsMono#359]
Helo,

When I work with Laravel Blade Template (https://laravel.com/docs/8.x/blade), I use HTML and blade comments too.

HTML comment is displayed with ligature format, but the blade comment is displayed in standard characters. Maybe something similar would be nicer, (than the ```{{-- --}}``` characters ) :

![image](https://user-images.githubusercontent.com/1152691/98452579-dd5ea600-2150-11eb-8605-99ee03ee6e78.png)

Thanks,
  Zoltan

**Comment by RajcsanyiZ** [comment]
The #360 issue is really don't close, but I don't know how to merge in here. Sorry, but that issue I think maybe not is an important feature.

**Comment by philippnurullin** [comment]
Maybe you can just copy paste the content here?

**Comment by RajcsanyiZ** [comment]
Okay, of course. 

Some Laravel Blade template ligatures suggestions:

![image](https://user-images.githubusercontent.com/1152691/98812129-3a44af80-2422-11eb-94a6-2442c52bc591.png)

more details: https://laravel.com/docs/8.x/blade
