### ISSUE TITLE
◄ ► ▲ ▼ symbols are of different sizes

### ISSUE THREAD

**Issue by rabbitinspace** [JetBrains/JetBrainsMono#36]
Firstly, thanks for the fonts! Love them.

I've noticed an issue with ◄ ► ▲ ▼ symbols (in [lazygit](https://github.com/jesseduffield/lazygit) app) on macOS in both Terminal.app and iTerm2:
![Screen Shot 2020-01-17 at 2 49 14 pm](https://user-images.githubusercontent.com/31989081/72583122-3565bb00-3939-11ea-8ba7-6167ddfaae3b.png)

The same symbols with Fira Code font:
![Screen Shot 2020-01-17 at 2 52 31 pm](https://user-images.githubusercontent.com/31989081/72583136-4282aa00-3939-11ea-8b58-642440e3cbd6.png)

**Comment by delphinus** [comment]
That's why JetBrains Mono has no glyphs for them. You're seeing ones from other fonts.

**Comment by philippnurullin** [comment]
We don't have support  ◄ ► ▲ ▼ in JetBrains Mono (at least for now). They are from your fallback font.

**Comment by rabbitinspace** [comment]
Thanks!
Going to close the issue then
