### ISSUE TITLE
Ligature: Laravel Balde template: "{{ ... }}", "{!! ... !!}", "@{{ ... }}"

### ISSUE THREAD

**Issue by RajcsanyiZ** [JetBrains/JetBrainsMono#360]
Helo,

I don't know it is a ligature question or not, but I think the Laravel Blade template is more readable with this ligatures:

![image](https://user-images.githubusercontent.com/1152691/98717924-01f39180-238e-11eb-977d-8bcd1d9cc9c4.png)

see: See: https://laravel.com/docs/8.x/blade#displaying-unescaped-data

Zoltan

**Comment by philippnurullin** [comment]
Hi @RajcsanyiZ . This issue seems to almost duplicate #359 . Can you please merge these in one. 
Regarding the ligatures. I'll think about it and see how it may affect general usage of }}. In `{!!` `!!}`, the `!!` is already ligaturized.

**Comment by RajcsanyiZ** [comment]
Oke, thanks.
