### ISSUE TITLE
Variable font in v2.210 is not installable on MAC OS

### ISSUE THREAD

**Issue by philippnurullin** [JetBrains/JetBrainsMono#361]
Hi @RosaWagner can you please look at the build scripts. 

To reproduce. Remove previous version from FontBook app. Try to install `JetBrainsMono-Italic[wght].ttf` and `JetBrainsMono[wght].ttf`. The font will not appear in the FontBook app.

If i exporting variable fonts directly from Glyphs app. The files are installable.

**Comment by RosaWagner** [comment]
Did you try to quit and restart the app, and the computer?
Did you try to clean your font cashes ?

**Comment by RosaWagner** [comment]
https://glyphsapp.com/tutorials/eliminating-font-cache-problems

**Comment by philippnurullin** [comment]
Seems like it's definitely problem with the FontBook app. So i'm closing this issue.
Simple renaming files makes them installable.

But no luck with fixing it. Even the fancy script not helping.
