### ISSUE TITLE
Font at 13px size is stretched by height in 2.210 release

### ISSUE THREAD

**Issue by Virss1** [JetBrains/JetBrainsMono#362]
I compared it with 2.210 DEV version and height differs **only at 13px**.
![jbm 2 210 vs 2 210 dev 13px](https://user-images.githubusercontent.com/44531490/98810046-60794800-2440-11eb-87c0-e9366daf9bb1.png)
It is noticeable when I change fonts and sizes (Visual Studio Code on Windows 10). At 12px and 14px and others there is no difference in height.
![Settings - Toxin - Visual Studio Code 2020-11-11 16-33-36](https://user-images.githubusercontent.com/44531490/98808635-4474a700-243e-11eb-9dd9-3112351ff966.gif)

**Comment by philippnurullin** [comment]
Hi @Virss1 If we compare the rendering to the original unhinted font, the x-height will be more similar to it.
Here is a comparison.
<img width="1460" alt="Screenshot 2020-12-23 at 12 15 04" src="https://user-images.githubusercontent.com/48058957/102980392-8fdba400-4518-11eb-86f0-64614e3cfe95.png">
So this is rendering is more precise.

**Comment by Virss1** [comment]
After all I think this taller symbols height is better than that smaller one. If I compare them now, font height in new releases is more enjoyable for me than it was in first versions. Althought, when I earlier used that font in version 1.0.6 I thought it is ideal for me, but now when I got used to latest version(s), I realized that newer is even better :)
