### ISSUE TITLE
SemiBold Weight - Please Add

### ISSUE THREAD

**Issue by kenmcd** [JetBrains/JetBrainsMono#363]
Please add a SemiBold (600) weight.
I have been working on some JBM documentation and sometimes the Bold is just too much.
And the Medium is not enough.
I use various fonts' SemiBold a lot in documentation as it works well in running text.
Whereas Bold can create a visual boat anchor.
So for using JBM in print a SemiBold would be very useful.

And a SemiBold may be just right onscreen for some users.
This was the case with a user who was using another mono code font.
The SemiBold was just right on his screen. Less blurry. It just fit better.

Thanks!

**Comment by philippnurullin** [comment]
Thanks for feedback. We will think about it.
For now you can use Variable font to tune the exact weight you want. Sadly, it depends on support of this function in your editor.

**Comment by kenmcd** [comment]
OK. I just created an instance and exported it for my use.
Thanks.
