### ISSUE TITLE
Add Persian (also called Farsi) to the supported languages

### ISSUE THREAD

**Issue by mahozad** [JetBrains/JetBrainsMono#365]
As far as I know Persian characters are available in JetBransMono. So is it possible to add [Persian (Farsi)](https://en.wikipedia.org/wiki/Persian_language) language to the list of supported languages?

**Comment by philippnurullin** [comment]
https://github.com/JetBrains/JetBrainsMono/issues/211

**Comment by philippnurullin** [comment]
O, sorry didn't read you issue right. 
As far as i know we didn't add the support of Fars in JetBrains Mono. ) Looks like it's your fallback font.

**Comment by morezafard** [comment]
https://github.com/rastikerdar/vazir-code-font
