### ISSUE TITLE
When there are certain characters after "/ \", they should not be combined

### ISSUE THREAD

**Issue by houinchengdu** [JetBrains/JetBrainsMono#368]
![2020-11-18_14-38-32](https://user-images.githubusercontent.com/62967959/99494310-bfdcd800-29ab-11eb-9581-a0f1c823ad1f.png)

```
        let reg = /\[(b|url|quote)\].*?\[\/\1\]/gs;
     //   \/
     //   /\
     //   /\/
     //   \/\
     //   \/<
        let str = `
[b]hello![/b]
[quote]
    [url]http://google.com[/url]
[/quote]
`;
        console.log( str.match(reg) );

**Comment by philippnurullin** [comment]
Hi this ligature was removed https://github.com/JetBrains/JetBrainsMono/issues/78#issuecomment-578710304
Please update to the latest version of JetBrains Mono.
