### ISSUE TITLE
Box drawing light vertical bar is too short

### ISSUE THREAD

**Issue by abusch** [JetBrains/JetBrainsMono#37]
The character U+2502 BOX DRAWINGS LIGHT VERTICAL is too short and doesn't make a continuous line. Contrast with # U+2503 BOX DRAWINGS HEAVY VERTICAL which does.

![2020-01-17-152033_422x203_scrot](https://user-images.githubusercontent.com/506344/72584192-33056000-393d-11ea-8112-bd00779a45cf.png)

**Comment by delphinus** [comment]
JetBrains Mono v1.0 now has no Box Drawing (U+2500 .. U+257F) glyphs. So you see ones from other fonts.

**Comment by philippnurullin** [comment]
JetBrains Mono is not supporting Box Drawing right now.

**Comment by abusch** [comment]
Indeed! Sorry, I should have checked before opening the issue...

Back to sorting out my font config then :)
