### ISSUE TITLE
Feature request: add font to MS store for easy upgrade

### ISSUE THREAD

**Issue by Wongboo** [JetBrains/JetBrainsMono#372]
Why not path these font to Microsoft store, this can greatly benefit Windows's users upgrade experience (they can upgrade along with MS store check update for all applications, nowadays the best solution for windows user to do so is by git version, which is too large)

**Comment by philippnurullin** [comment]
Hi @Wongboo . Not getting what do you mean by _git version is too large_? 
We don't have plans to release the JetBrains Mono in Microsoft store.

**Comment by Wongboo** [comment]
> Hi @Wongboo . Not getting what do you mean by _git version is too large_?
> We don't have plans to release the JetBrains Mono in Microsoft store.

If you want to easily upgrade font after installation(upgrade automatically or by a single command), the possible solution is by git clone the whole repository but git repo is too big, which the problem I mention about. Or using Homebrew or Chocolatey as an alternative, anyway the former one doesn't work for Windows, I think in Windows MS store works much better than chocolatey personally, because you can use MS store without other installation. 

BTW, I do not like the installation position in chocolatey, but that's another stuff with other applications
