### ISSUE TITLE
"m" character hinting problem

### ISSUE THREAD

**Issue by vadersb** [JetBrains/JetBrainsMono#375]
Font: **JetBrainsMonoMedium**
"**m**" character has too thin top segments in specific case:
Windows 10
DPI Scaling 125%

VSCode:
font size: **13.5**

JetBrains Rider 2020.2:
font size: **14
![m_problem_01](https://user-images.githubusercontent.com/53225685/99932183-62100d80-2d68-11eb-9346-8729e896dd53.png)
![m_problem_02](https://user-images.githubusercontent.com/53225685/99932186-63d9d100-2d68-11eb-9551-9fed29477224.png)

**

**Comment by philippnurullin** [comment]
Ok, i will see what can be done. Thanks for the feedback.

**Comment by vadersb** [comment]
This issue is resolved in v2.221

**Comment by vadersb** [comment]
Well, the problem remains in _italic_ style:
![italic_still_problem](https://user-images.githubusercontent.com/53225685/103367328-d8293200-4ad5-11eb-8b59-0016449975df.png)

**Comment by philippnurullin** [comment]
Please confirm the positive change in the latest push https://github.com/JetBrains/JetBrainsMono/tree/master/fonts

**Comment by vadersb** [comment]
Yes, the latest push fixes the problem with "m" symbol, here's an example:

![m_fix](https://user-images.githubusercontent.com/53225685/104925708-35ffba00-59b0-11eb-8fbb-e1a35b9ed6f0.png)

Thank you!

**Comment by philippnurullin** [comment]
Glad to hear!
