### ISSUE TITLE
Website shows and downloads version v2.001

### ISSUE THREAD

**Issue by JanPokorny** [JetBrains/JetBrainsMono#378]
Website https://www.jetbrains.com/lp/mono/ shows and downloads version v2.001 instead of the up-to-date v2.210

![obrazek](https://user-images.githubusercontent.com/4580066/100148410-072c0280-2e9d-11eb-95c6-58434204506d.png)

**Comment by philippnurullin** [comment]
Updated with the latest release 2.221.
