### ISSUE TITLE
Renaming master branch to main branch

### ISSUE THREAD

**Issue by TourneyMan** [JetBrains/JetBrainsMono#379]
This is a simple change that many projects have been making in order to use more inclusive terminology.

**Comment by kenmcd** [comment]
What exactly does that "inclusive" include?

**Comment by VaslD** [comment]
Really? We're opening issues like this on GitHub now?

Almost every word can be "exclusive" or "offensive" if you use it in a certain way, just look up Urban Dictionary and Know Your Meme. There's not a single word that doesn't have some double-meaning according to the Internet. Similarly, every word can be just "inclusive" and "correct" if you use its intended meaning in the intended context and do not over-interpret it.

"Master" here is the perfect example of using its intended meaning in the intended context without being offensive. It's not exclusive if you're a person, not another branch.
