### ISSUE TITLE
Certain ligatures not working in PyCharm 2019.3

### ISSUE THREAD

**Issue by lanrete** [JetBrains/JetBrainsMono#38]
For example, __ (double underscore) does not work in PyCharm 2019.3.1
![image](https://user-images.githubusercontent.com/14850324/72591366-e882e400-393a-11ea-87fe-2049d4b1ed74.png)

After manually install v1.0 version, same ligature works in VS Code.
![image](https://user-images.githubusercontent.com/14850324/72591387-f3d60f80-393a-11ea-844c-68ae01cd04d5.png)

**Comment by philippnurullin** [comment]
Hi, the version of JetBrains Mono you are looking at PyCharm is 0.23 (the last before 1.0). Unfortunately, the bundled fonts is always have priority when IDE decided which to use. We are working on correcting this behaviour. This problem will be solved when v 1.0 will be bundled.

**Comment by lanrete** [comment]
@philippnurullin This font looks truly amazing & really looking forward to the stable version in 2020.1.
