### ISSUE TITLE
Build script placing comb mark at the right side when making glyph with zero width

### ISSUE THREAD

**Issue by philippnurullin** [JetBrains/JetBrainsMono#383]
Hi @RosaWagner 
When exporting with build script comb marks like `gravecomb` and others having positive LSB and RSB negative but to work properly it should be the other way around.

This is build script result
<img width="181" alt="Screenshot 2020-12-09 at 17 16 32" src="https://user-images.githubusercontent.com/48058957/101641078-5d26ab80-3a42-11eb-8bbd-3c7ef95abc5b.png">

This is expected results
<img width="162" alt="Screenshot 2020-12-09 at 17 16 11" src="https://user-images.githubusercontent.com/48058957/101641085-5f890580-3a42-11eb-8d8c-62de902b100d.png">

Look like this is an origin for this issue. https://github.com/JetBrains/JetBrainsMono/issues/228

Can we tune it?

**Comment by RosaWagner** [comment]
Fontmake is doing thing this way, I can't do anything. You can raise an issue there maybe…

**Comment by philippnurullin** [comment]
Ok, thanks.
