### ISSUE TITLE
Provide glyph for ➜

### ISSUE THREAD

**Issue by frei-0xff** [JetBrains/JetBrainsMono#386]
Could you please provide glyph for ➜ (Heavy Round-Tipped Rightwards Arrow U+279C)
It is useful as a character for the shell prompt. For example, it is used as default prompt of [zsh spaceship](https://github.com/denysdovhan/spaceship-prompt)
Thank you for the great font, you've done an amazing job!

**Comment by mfocko** [comment]
is added in v2.220, it's not in releases, but if you download whole repo as zip, you can install the fonts from the `fonts` directory

**Comment by frei-0xff** [comment]
Thank you very much!
