### ISSUE TITLE
Update to v2.221 breaks font width in xterm

### ISSUE THREAD

**Issue by cglogic** [JetBrains/JetBrainsMono#387]
After update to v2.221 glyphs are wider and not centered. Also before fc-list shows JetBrainsMono as monospace, but not after update.

`fc-list :scalable=true:spacing=mono: | grep jet` shows 28 lines with v2.210 and no one with v2.221.

**Comment by philippnurullin** [comment]
Hi @cglogic Please attach screenshots with both samples.

**Comment by cglogic** [comment]
v2.210:
![screenshot-2020 12 29-13 32 04](https://user-images.githubusercontent.com/14204812/103281377-505efd00-49db-11eb-9c5e-3bec3ef4da2d.png)

v2.221:
![screenshot-2020 12 29-13 33 06](https://user-images.githubusercontent.com/14204812/103281378-51902a00-49db-11eb-9d4f-3d240bd85451.png)

And as I mentioned before, after update font isn't recognized as monospace.

**Comment by philippnurullin** [comment]
Yes, looks like adding this symbols broke the "monospaceness" https://github.com/JetBrains/JetBrainsMono/issues/255
it's not very smart on the xterm side, because they are modular to mono width. But we will think of some solution.
For  now the workarounds are:
- Rollback to 2.210
- Remove manually `⟵`(uni27F5) `⟷`(uni27F7) `⟶`(uni27F6) from `.ttf` files by some opensource editor like https://fontforge.org/en-US/

**Comment by designxcode** [comment]
oh,there is something wrong with my computer,I just&nbsp; want to get the ttf file

**Comment by cglogic** [comment]
Ok, I switched to previous version. Thanks!

**Comment by FlyingBBQ** [comment]
I experience a similar problem. I have some colored status output of which I calculate the width of the text (string) in pixels using Xft. With v2.221 this length is wrong. It appears that the [advance width](https://stackoverflow.com/questions/20103312/paint-gettextwidths-what-is-advance-width) has doubled for characters?

I'll rollback to v2.210 for now.

**Comment by philippnurullin** [comment]
Made a push with fix. Please use these files https://github.com/JetBrains/JetBrainsMono/tree/master/fonts

**Comment by 1900011604** [comment]
![IMG_20210116_095459](https://user-images.githubusercontent.com/65082432/104795168-4fa1d580-57e7-11eb-8683-01646d767767.jpg)


It has fixed with Konsole and Kate but not with spyder on linux

**Comment by cglogic** [comment]
> Made a push with fix. Please use these files https://github.com/JetBrains/JetBrainsMono/tree/master/fonts

Works for me. Thanks!

**Comment by philippnurullin** [comment]
@1900011604 Please create separate issue for Spyder. 
Closing this one because general problem is solved.
