### ISSUE TITLE
ligatures do not work after square brace

### ISSUE THREAD

**Issue by mikucionisaau** [JetBrains/JetBrainsMono#388]
I am trying to typeset expression `[<=5]`, but the pair `<=` is not ligated after `[`, this pair is ligated fine after space or a number:
![image](https://user-images.githubusercontent.com/4868894/103893685-fdc5c500-50ed-11eb-8675-b55a30227574.png)

I do not experience this issue with other fonts (FiraCode, VictorMono). 
The ligation also works fine after the parenthesis, curly braces, quotation marks -- everything seems consistent except after `[`.
So what is special about the square brace? Why the ligation does not work after `[`?

**Comment by auduchinok** [comment]
I guess it's F# attribute list brackets kicking in: `[<` and `>]`.
@philippnurullin Is there some way to make operators like `<=` to have higher priority than these brackets?

**Comment by mikucionisaau** [comment]
Interesting, it is so subtle, that I can barely see ligation in `[<` :-)  
Alternatively, maybe all three symbols could be ligated so everyone is happy?

**Comment by philippnurullin** [comment]
Yes, i will add an exception for this case in on of the next updates.

**Comment by philippnurullin** [comment]
Please test with the latest update https://github.com/JetBrains/JetBrainsMono/tree/master/fonts

**Comment by mikucionisaau** [comment]
It fixes this issue. Thank you very much!
