### ISSUE TITLE
feat request: add compatibility with hyper terminal

### ISSUE THREAD

**Issue by r3nanp** [JetBrains/JetBrainsMono#390]
###  Feat request
I was trying to use font ligature in Hyper terminal, and didn't work. I would love to have support ligature in Hyper terminal.

My hyper settings: 
```
module.exports = {
  config: {
    // default font size in pixels for all tabs
    fontSize: 14,

    // font family with optional fallbacks
    fontFamily: 'Jetbrains Mono',
}
```

![font](https://user-images.githubusercontent.com/47953339/104110522-4381b980-52b7-11eb-855e-54ddc5b647a8.png)
[Hyper support font ligatures](https://github.com/vercel/hyper/pull/3853)

**Comment by philippnurullin** [comment]
Hi @r3nanp May it be related to the wrong font name in settings? Try `JetBrains Mono`.

**Comment by alexeyten** [comment]
Are you sure it's JetBrains Mono? Could you provide screenshot with text? E.g. with `Quick brown fox …`.

**Comment by r3nanp** [comment]
> Hi @r3nanp May it be related to the wrong font name in settings? Try `JetBrains Mono`.

I tried and nothing changes. Look this picture:
![font](https://user-images.githubusercontent.com/47953339/104359212-22ef7480-54ee-11eb-9852-fe359d8b104d.png)

**Comment by alexeyten** [comment]
There are some suggestions like disabling WebGL rendering should help
See https://gist.github.com/dariuszparys/64fdba8cb802d3f8ef87cdadbf2afb73#file-hyper-js-L6-L8

Also try this https://gist.github.com/dariuszparys/64fdba8cb802d3f8ef87cdadbf2afb73#file-hyper-js-L35-L40

**Comment by r3nanp** [comment]
> There are some suggestions like disabling WebGL rendering should help
> See https://gist.github.com/dariuszparys/64fdba8cb802d3f8ef87cdadbf2afb73#file-hyper-js-L6-L8
> 
> Also try this https://gist.github.com/dariuszparys/64fdba8cb802d3f8ef87cdadbf2afb73#file-hyper-js-L35-L40

 I tried this, but nothing changes:
```
    termCSS:` 
      x-screen x-row {
        font-variant-ligatures: initial;
    }
    `,
    webGLRenderer: false,
```

**Comment by CodeCrazy-ywt** [comment]
Maybe it's your terminal's issue not the font's.

**Comment by r3nanp** [comment]
Well, it was a long time ago, now I'm using a different terminal. Thank you all for your help!
