### ISSUE TITLE
Add Cyrillic Kazakh letters

### ISSUE THREAD

**Issue by le91** [JetBrains/JetBrainsMono#391]
Добрый день.
Возможно google.translate не верно переведет смысл данной просьбы, но думаю суть будет понятна, прощу не судите меня =).
Хотел бы попросить разработчиков чтобы добавили поддержку казахского языка на кириллице, а именно буквы:
Ә ә Ғ ғ Қ қ Ң ң Ұ ұ Ү ү Һ һ І і Ө ө
Примерные кривые ниже, так же вылодил в нескольких форматах:
|	 Letter, Буква 	|	~Чертеж, ~Drawing	|	 https://unicode-table.com 	|	Example, Для примера взят 	|
|	 -- 	|	 ------------------------------------------------------------ 	|	 ------------------------------------ 	|	 ------------- 	|
|	Все, All	|	https://github.com/le91/JetBrainsMono_KAZ_cyrillic	|	[JetBrainsMono_KAZ.zip](https://github.com/JetBrains/JetBrainsMono/files/5814003/JetBrainsMono_KAZ.zip)	|	[JetBrainsMono_KAZ.zip](https://github.com/JetBrains/JetBrainsMono/files/5814003/JetBrainsMono_KAZ.zip)	|
|	 Ә 	|	![http://0x0.st/-zv8.png](http://0x0.st/-zv8.png)	|	 https://unicode-table.com/ru/04D8/	|	180° е (edit / изминен)	|
|	 ә 	|	![http://0x0.st/-zt7.png](http://0x0.st/-zt7.png)	|	https://unicode-table.com/ru/04D9/	|	180° е (edit / изминен)	|
|	 Ғ 	|	![http://0x0.st/-zvX.png](http://0x0.st/-zvX.png)	|	https://unicode-table.com/ru/0492/	|	F (edit / изминен)	|
|	 ғ 	|	![http://0x0.st/-zvi.png](http://0x0.st/-zvi.png)	|	https://unicode-table.com/ru/0493/	|	F (edit / изминен)	|
|	 Қ 	|	![http://0x0.st/-zvi.png](http://0x0.st/-zvi.png)	|	https://unicode-table.com/ru/049A/	|	K (edit / изминен)	|
|	 қ 	|	![http://0x0.st/-zvo.png](http://0x0.st/-zvo.png)	|	https://unicode-table.com/ru/049B/	|	K (edit / изминен)	|
|	 Ң 	|	![http://0x0.st/-zvZ.png](http://0x0.st/-zvZ.png)	|	https://unicode-table.com/ru/04A2/	|	H (edit / изминен)	|
|	 ң 	|	![http://0x0.st/-zvq.png](http://0x0.st/-zvq.png)	|	https://unicode-table.com/ru/04A3/	|	H (edit / изминен)	|
|	 Ұ 	|	![http://0x0.st/-zvc.png](http://0x0.st/-zvc.png)	|	https://unicode-table.com/ru/04B0/	|	Y (edit / изминен)	|
|	 ұ 	|	![http://0x0.st/-zvT.png](http://0x0.st/-zvT.png)	|	https://unicode-table.com/ru/04B1/	|	Y (edit / изминен)	|
|	Ү	|	![http://0x0.st/-zvA.png](http://0x0.st/-zvA.png)	|	https://unicode-table.com/ru/04AE/	|	Y	|
|	ү	|	![http://0x0.st/-zvm.png](http://0x0.st/-zvm.png)	|	https://unicode-table.com/ru/04AF/	|	Y (edit / изминен)	|
|	 Һ 	|	![http://0x0.st/-zva.png](http://0x0.st/-zva.png)	|	https://unicode-table.com/ru/04BA/	|	h (edit / изминен)	|
|	 һ 	|	![http://0x0.st/-zvB.png](http://0x0.st/-zvB.png)	|	https://unicode-table.com/ru/04BB/	|	h (edit / изминен)	|
|	І	|	![http://0x0.st/-zvS.png](http://0x0.st/-zvS.png)	|	https://unicode-table.com/ru/0406/	|	I	|
|	і	|	![http://0x0.st/-zvQ.png](http://0x0.st/-zvQ.png)	|	https://unicode-table.com/ru/0456/	|	i	|
|	Ө	|	![http://0x0.st/-zvM.png](http://0x0.st/-zvM.png)	|	https://unicode-table.com/ru/04E8/	|	О (edit / изминен)	|
|	ө	|	![http://0x0.st/-zvu.png](http://0x0.st/-zvu.png)	|	https://unicode-table.com/ru/04E9/	|	О (edit / изминен)	|

**Comment by philippnurullin** [comment]
Привет @le91 , не судим тебя. )
Shure, we will add the support of Kazakh language.

**Comment by le91** [comment]
@philippnurullin Я так понимаю поддержку языка еще не добавили, ну или по срокам ориентировочно это когда произойдёт? Может чем помочь?

**Comment by philippnurullin** [comment]
Добавил. Файлы для теста можно взять в мастере.

**Comment by AlsoScratch** [comment]
The letter һ appears to be missing.

**Comment by philippnurullin** [comment]
@AlsoScratch Yes, seems right. 
I will add the letter in the quick fix.

**Comment by AlsoScratch** [comment]
Much thanks!
