### ISSUE TITLE
JetBrainsMono is not recognized as monospaced font on Manjaro and Spyder

### ISSUE THREAD

**Issue by 1900011604** [JetBrains/JetBrainsMono#392]
I cannot find it on the monospaced list

![image](https://user-images.githubusercontent.com/65082432/104610675-4cabc580-56bf-11eb-81c3-e845edb25cab.png)

**Comment by kenmcd** [comment]
What version of JetBrains Mono are you using?

**Comment by 1900011604** [comment]
from 2.200 to 2.221, the latest

**Comment by philippnurullin** [comment]
Please update to latest push https://github.com/JetBrains/JetBrainsMono/tree/master/fonts
The source of the problem is the same as here #387 so closing this one.
