### ISSUE TITLE
ligature request: triple semicolon

### ISSUE THREAD

**Issue by andreyorst** [JetBrains/JetBrainsMono#393]
It is often used in Lisp code for documentation comments.  Currently, in Emacs, it looks like this:

![image](https://user-images.githubusercontent.com/19470159/104690607-cd95ac00-5715-11eb-9262-27a2217b7d75.png)

The third semicolon in the first line is disjoined from the first two, which doesn't look right.

**Comment by philippnurullin** [comment]
Sure, we will add this ligature.
