### ISSUE TITLE
v 2.222 didn't releases

### ISSUE THREAD

**Issue by bluelovers** [JetBrains/JetBrainsMono#396]
https://github.com/JetBrains/JetBrainsMono/releases

![image](https://user-images.githubusercontent.com/167966/104857757-a6c5b880-5955-11eb-8e88-adbbc6b395b6.png)

https://www.jetbrains.com/lp/mono/

![image](https://user-images.githubusercontent.com/167966/104857771-b513d480-5955-11eb-8bcd-1fc7e6154943.png)

**Comment by philippnurullin** [comment]
Hi, @bluelovers Yes, this is intended. I will add more changes and make a release later.
