### ISSUE TITLE
Ligature for <=>

### ISSUE THREAD

**Issue by dangelog** [JetBrains/JetBrainsMono#397]
Hi,

The sequence '<=>' currently gets a ligature for the <= part (≤) but does not take into account the following >, becoming '≤>'. I'm not sure if there's a good symbol to replace the whole sequene; U+22DA ⋚ is very close and formally correct but doesn't "look" that good to me...

The sequence is commonly found in C++20 as well as other programming languages; it goes under the name of "three way comparison", "spaceship operator", "3-way compare" (trying to list them all so to maximize SEO...).

**Comment by trygveaa** [comment]
Works fine here:
![image](https://user-images.githubusercontent.com/601966/104937357-f3d57900-59ad-11eb-9b58-8a2269a3fc9a.png)

**Comment by dangelog** [comment]
Hi,

Uhm, interesting, it doesn't work here. Must be a problem of the IDE (or the OS). 

![screenshot](https://user-images.githubusercontent.com/4455745/104938483-73b01300-59af-11eb-9a9f-c4e2820d4301.png)

Feel free to close this one, sorry for the noise. Just in case, do you happen to know how to possibly investigate it?

**Comment by philippnurullin** [comment]
Hi @dangelog . Can you tell me the exact version of the font & name the IDE?

**Comment by dangelog** [comment]
I'm using 2.221 , on Ubuntu 20.04. The IDE is Qt Creator 4.14 (you can download it for free here https://www.qt.io/offline-installers , select Creator on the list unfortunately it seems the download mirrors are offline at the moment...).

I suspect a kerning bug into the Qt font stack (Harfbuzz / Freetype / ...), but I'm not sure how to investigate it further.

**Comment by kdrag0n** [comment]
If you look very closely at your screenshot, you can see a slight difference in text colors:
![image](https://user-images.githubusercontent.com/7930239/105449480-56887800-5c2d-11eb-9212-565079974da7.png)

Your editor is tokenizing the `<=` and `>` parts separately, so it's not considered a single continuous span of text that the ligature can render across.

**Comment by philippnurullin** [comment]
Thanks @kdrag0n . Looks like this is a solution for ligature behavior indeed.
Closing this issue.
