### ISSUE TITLE
?. ligature makes spacing not uniform in Rust

### ISSUE THREAD

**Issue by GrayJack** [JetBrains/JetBrainsMono#398]
In Rust the dot and the question mark are always separate "operators", and it's common to do a field access or method call after the use of `?` as error early return.

Since they are not used together as an operator I expected that the dot had the same spacing on both sides like in the second image between `vec` and the method call.

![image](https://user-images.githubusercontent.com/17973728/105558099-9498a100-5cec-11eb-954f-10f1005b22f4.png)

![image](https://user-images.githubusercontent.com/17973728/105558115-a0846300-5cec-11eb-95f9-fff7a7189cd5.png)

**Comment by CodeCrazy-ywt** [comment]
Emmm...that's really a problem, because in Kotlin `?.` is a null-safety operator, and `a?.b` equals `if (a != null) a.b else null`.

**Comment by GrayJack** [comment]
Maybe it's possible to to enable/disable it through stylistic sets?

**Comment by Omnieboer** [comment]
Stylistic sets would be the answer for many problems people have. All ligatures are language dependent in the end.
It would require [IDE Support (please vote)](https://youtrack.jetbrains.com/issue/IDEA-221886) as well though.
I think stylistic sets are definitely the way forward, even though it might be a huge undertaking.

**Comment by philippnurullin** [comment]
@Omnieboer yes, but we have only 20 of them. So this is not a universal bandaid. )

**Comment by GrayJack** [comment]
There is a way for me to manually remove the `?.` ligature for the time being?

**Comment by philippnurullin** [comment]
- Remove the ligature from the source and build files with script. You will need the Glyphs app. It have have trial version.
- The second option is to modify the compiled .ttf files.
You can convert the them to .ttx (which will be readable by hyman) format with this tool https://fonttools.readthedocs.io/en/latest/ttx.html. 
Find this exact code: 
```
lookup question_period.liga {
ignore sub question question' period;
ignore sub question' period period;
sub SPC period' by question_period.liga;
sub question' period by SPC;
} question_period.liga;
```
Add the `#` before every line (convert code to comments). And convert files to back to .ttf.

**Comment by GrayJack** [comment]
I managed to convert to ttx, but the ttx file was basically a XML file and I couldn't find the exact code you gave

**Comment by philippnurullin** [comment]
Ok then. Looks like it is getting lost in the process of compilation.

I found this short tutorial how to remove ligatures using FontForge. It's free and Open Source font editor.
https://stackoverflow.com/questions/43315957/how-to-remove-ligatures-from-a-font-using-fontforge

The easiest way is to use Glyphs app https://glyphsapp.com/buy.
- Open the `JetBrainsMono.glyphs` file in the **Source** folder.
- **File** → **Font Info** or (cmd+i).
- → **Features**. In the menu to the left find the `calt` feature. And search for the `question_period.liga` (cmd+f).
- Add the `#` before every line of this lookup. 
- Save the files. Repeat same process with `JetBrainsMono-Italic.glyphs`
- After that you can export files using Glyphs export dialog (cmd+e) or use scripts (recommended). To build files from source you will need to install **gftools** `pip install gftools` (requires python 3.9.5 or higher on BigSur). After the installation drop the `sources/config.yaml` in terminal and run it.
