### ISSUE TITLE
JetBrains font with no ligatures

### ISSUE THREAD

**Issue by Stefanosapk** [JetBrains/JetBrainsMono#399]
I have downloaded from here the jetbrains font https://www.jetbrains.com/lp/mono/#font-family and I want to use this font in my css code snippets  but without ligatures. The only file format with no ligatures (NL) is `.tff`.

I'm using this font but now i want to change it in no ligatures. In my project in order to apply the font im doing this:

.scss
```
@font-face {
    font-family: JetBrainsMono-Regular;
    src: url('fonts/JetBrainsMonoNL-Regular.ttf');

}

.className li{
    font-family: JetBrainsMono-Regular, sans-serif!important;
    font-size: 15px;
    line-height: 32px;
}
```

So how can I import the font with no ligatures or is there available a font version with no ligatures to use for code snippets?

**Comment by alexeyten** [comment]
In browsers you could disable ligatures with one line of CSS:
```css
.className li {
    font-feature-settings: "calt" off;
}
```

**Comment by Stefanosapk** [comment]
Thanks for the answer, I finally solved it without adding any extra line of css.

Just adding the font will work fine! (I just had messed up with the fonts files)
