### ISSUE TITLE
Windows 10 doesn't register it as monospace type?

### ISSUE THREAD

**Issue by otterpro** [JetBrains/JetBrainsMono#4]
On my Windows 10 setup, it seems to be registering as a proportional and not monospaced type.  For that reason, it won't show up as available font in Command Prompt or Powershell.  Other fonts like Fira Code or Inconsolata are fine.

**Comment by philippnurullin** [comment]
We aware if this problem, one of the weights is missing "monospace" tag in metadata. This will be fixed in next update.
Thanks for feedback.

**Comment by damieng** [comment]
I think this might actually be a lack of Panose flags set - that's what Windows Command Prompt uses to identify monospaced fonts. While it was included in FontLab Studio 5 it did not make FontLab 6 or 7.

A separate process/patcher might be required to fix up the ttf after processing.  Here's what it looks like in FontLab Studio 5.  Toggling this flag is the difference between it showing up in Command Prompt options or not although toggling it does not affect Visual Studio for example.

![image](https://user-images.githubusercontent.com/118951/72579568-54f3d980-388e-11ea-924d-973efc01aaaa.png)

**Comment by atsusta** [comment]
I use gVim and it loads monospaced fonts only. same here like cmd or powershell.

**Comment by AndreyKozhevnikov** [comment]
Hello. Is there any time frame for this update?

**Comment by philippnurullin** [comment]
if stars will be merciful, the v 1.0.1 will be up in next 8 hours.

**Comment by philippnurullin** [comment]
The stars was not so merciful, but we fond the solution. Expect 1.0.1  in Monday. Sorry for the wait.

**Comment by neshanjo** [comment]
Thanks for fixing! Now we can have JetBrains Mono in Windows Command Line, too! 😄 

![image](https://user-images.githubusercontent.com/22233722/72798967-76651480-3c44-11ea-82d8-40ef285c36ca.png)

See e.g. [this post](https://www.techrepublic.com/blog/windows-and-office/quick-tip-add-fonts-to-the-command-prompt/) on how to add fonts to the windows command line font chooser.

**Comment by orivej** [comment]
Thank you! 1.0.1 became monospace on Linux.

**Comment by philippnurullin** [comment]
The v 1.0.1 is out & it fixing the bug on Win 10.

**Comment by MinchinWeb** [comment]
Thanks for getting this fixed!!

**Comment by dnelson-1901** [comment]
Looks like the https://jetbrains.com/mono webpage is still serving the 1.0.0 version when you click the "Download font" button; could someone update that too?

**Comment by philippnurullin** [comment]
@dnelson-1901 Thanks for bringing this up. We will update the link after the release of 1.0.2.

**Comment by MinchinWeb** [comment]
ETA on when version 1.0.2 is supposed to drop?
