### ISSUE TITLE
Choco release flow?

### ISSUE THREAD

**Issue by WeihanLi** [JetBrains/JetBrainsMono#400]
As I can see, the latest release on choco is not the latest release on github.

Could we have better release flow for choco? So that we could always install the latest fonts with choco

**Comment by philippnurullin** [comment]
Hi @WeihanLi . The delivering to Chocolate is not managed by JetBrains. 
Yo can finde more info here https://github.com/JetBrains/JetBrainsMono/issues/93. I believe @Cirzen generously was taking care of this.

**Comment by WeihanLi** [comment]
@philippnurullin thanks for the info
