### ISSUE TITLE
En dash and hyphen are indistinguishable

### ISSUE THREAD

**Issue by a-ignatev** [JetBrains/JetBrainsMono#404]
**Description**
en dash: –
hyphen: -

**Observed result:**
![image](https://user-images.githubusercontent.com/64772919/106619081-7e9ea200-6570-11eb-98ed-8375a4a2bdb1.png)

**Expected result:**
(DejaVu Sans Mono as an example)
![image](https://user-images.githubusercontent.com/64772919/106619229-a4c44200-6570-11eb-8bac-244fd11f7e3e.png)

**Comment by philippnurullin** [comment]
Hi, @a-ignatev . Can you please specify what JetBrains Mono you have? 
We had similar issue https://github.com/JetBrains/JetBrainsMono/issues/318
Here is a small preview of hyphen and en dash in latest version.
<img width="35" alt="Screenshot 2021-02-02 at 17 09 55" src="https://user-images.githubusercontent.com/48058957/106627834-7b5be400-6579-11eb-938c-b440d6129ca3.png">

**Comment by trygveaa** [comment]
@philippnurullin: It's because of the ligature. Hyphens change width when there are two or three consecutive.

**Comment by a-ignatev** [comment]
> Hi, @a-ignatev . Can you please specify what version of JetBrains Mono you have?
> We had similar issue #318
> Here is a small preview of hyphen and en dash in latest version.
> <img alt="Screenshot 2021-02-02 at 17 09 55" width="35" src="https://user-images.githubusercontent.com/48058957/106627834-7b5be400-6579-11eb-938c-b440d6129ca3.png">

I'm using RubyMine 2020.3.2 built-in JetBrains Mono.
Here is an example with and without ligatures.
![image](https://user-images.githubusercontent.com/64772919/106632997-a3017b00-657e-11eb-8b21-b0b859ed2560.png)
![image](https://user-images.githubusercontent.com/64772919/106633078-ba406880-657e-11eb-92b4-b9165daa96ee.png)

I'm not sure if it's the same font or what version it is.

**Comment by philippnurullin** [comment]
Looks like bundled version of the font in RubyMine is old.
- Delete the old version of JetBrains Mono. Here you can have the idea where the bundled fonts are located https://github.com/JetBrains/JetBrainsMono/issues/142
- Download and install the latest release from here https://github.com/JetBrains/JetBrainsMono/releases/tag/v2.225

**Comment by a-ignatev** [comment]
@philippnurullin Thank you very much for your support. It works now. I was really hoping that the latest IDE build (2020.3.2, released on Jan 26, 2021) would use the latest JetBrains Mono released at that moment.

**Comment by philippnurullin** [comment]
Glad to hear it! 
Sorry, the bundle process is a bit slow. So the fastest way is to update manually. We will think on how to make this more convenient.
