### ISSUE TITLE
The goland terminal icon shows an error

### ISSUE THREAD

**Issue by hznuksco** [JetBrains/JetBrainsMono#408]
OS: Ubuntu 18.04.5 LTS x86_64
Terminal: deepin-terminal
Shell: zsh 5.4.2
Terminal Font: JetBrains Mono 13

terminal 

![image](https://user-images.githubusercontent.com/27288263/106978650-9dcb4880-6797-11eb-957e-e10626afbc4a.png)

goland terminal

![image](https://user-images.githubusercontent.com/27288263/106978674-a9b70a80-6797-11eb-97e7-87673d8915ea.png)

**Comment by philippnurullin** [comment]
Hi @hznuksco . This looks like the issue on the Goland IDE. The symbol you referring to is an Emoji. This is separate software ad not related to JetBrains Mono. I suggest you contact Goland support. Here is an issue i found regardint the support of Emoji in JetBrains IDE https://youtrack.jetbrains.com/issue/IDEA-118832#focus=Comments-27-4625808.0-0

**Comment by mfocko** [comment]
@hznuksco i suggest you to look into configuration of goland, some bars (used in windows managers) or terminals support multiple fonts and if the character (e.g. emote) is not found in the first one it tries the next one (basically fallback font)... some terminals do it by default (for example in Alacritty it doesn't matter if I have JetBrainsMono or FiraCode as default font, emotes are still same (they do not even conform to monospace))

**Comment by hznuksco** [comment]
Thanks!! Eh I know it's a goland terminal issue, I don't know where this goland issue is raised, so I'll mention it here
