### ISSUE TITLE
U+2502's length is bigger than it should

### ISSUE THREAD

**Issue by ndavidq0** [JetBrains/JetBrainsMono#409]
All the information I have on the issue is on this link https://github.com/alacritty/alacritty/issues/4770

I think the issue is related to the font and not the terminal

**Comment by philippnurullin** [comment]
Hi @ndavidq0 
The set of BoxDrawing characters is higher that the Block. This is true. 
This made intentionally. There are 2 cases where it can be useful:
1. The line height in terminal is rounded up to full pixel in the process of rasterisation. It leads to small shift in its size and as a result, if the size of Block and BoxDrawing is the same, gaps can appear. The size of BoxDrawing `│` elements made bigger to exclude vertical gaps.
2. Also this gives the ability to tune the line-height slightly bigger from 1.0.

We believe that this is an optimal solution.
