### ISSUE TITLE
Problems with ligatures => and !=

### ISSUE THREAD

**Issue by avgoncharov** [JetBrains/JetBrainsMono#41]
In Rider in C# code, with font size = 14, for both ligatures bottom lines are thicker than the top.
![image](https://user-images.githubusercontent.com/2749062/72597418-cda27680-391e-11ea-8077-624a3d85f17d.png)

**Comment by turansky** [comment]
IDEA 2020.1 
Windows
    size = 12..14
![image](https://user-images.githubusercontent.com/9942723/73944391-88f97200-4903-11ea-8a7f-5292c9f0f780.png)

macOS
   Works fine
