### ISSUE TITLE
'#' and '{' too close too each other

### ISSUE THREAD

**Issue by enkeyz** [JetBrains/JetBrainsMono#413]
I was writing Sass code, when I noticed: '#' and '{' characters are overlapping:
![image](https://user-images.githubusercontent.com/17646853/107893608-73faea00-6f2c-11eb-8b86-2129319479fe.png)

**Comment by philippnurullin** [comment]
Hi @enkeyz . This is a ligature used in Clojure.
If you not comfortable with ligatures you can use NL (No Ligature) version that can be found in `ttf` folder.
Closing this issue because it's work like expected.
