### ISSUE TITLE
Italic variants of a and o at default/smaller font sizes are difficult to distinguish

### ISSUE THREAD

**Issue by krish-r** [JetBrains/JetBrainsMono#416]
Hello, 

I'm currently using the latest version of Jetbrains Mono v2.225 (Windows 10, with 1920x1080 resolution).

And, it is slightly difficult to distinguish italic variants of `a` and `o` at default/smaller font sizes at first glance. 

I could see that v2.200 changelog includes - "Removed the "tail" in the italic a.". It was easier to distinguish with a tail in the older version IMHO.

Can you please take a look into this? 

---

**Sample screenshots with comparison between v2.225 and v2.001:**

VS Code with 'Material Theme Palenight Theme' and default font size (14):
v2.225
![image](https://user-images.githubusercontent.com/54745129/109425568-dfee4f80-7a0e-11eb-8b5d-90deb6652ad0.png)
v2.001
![image](https://user-images.githubusercontent.com/54745129/109425747-e0d3b100-7a0f-11eb-9bd2-362a3ae67fbd.png)

Windows font settings screen:
v2.225
![image](https://user-images.githubusercontent.com/54745129/109425873-82f39900-7a10-11eb-9c10-4cc08e38a4f5.png)

v2.001
![image](https://user-images.githubusercontent.com/54745129/109425885-91da4b80-7a10-11eb-980d-6176d49e542d.png)

from Google fonts - at 20px:
![image](https://user-images.githubusercontent.com/54745129/109424944-0bbc0600-7a0c-11eb-95c7-4b1e00b48e8c.png)

**Comment by TheMadHau5** [comment]
IMHO adding the tail back would be the best solution

**Comment by CodeCrazy-ywt** [comment]
Yes, the former one is not only good-looking but also easy to distinguish.

**Comment by philippnurullin** [comment]
Thanks for the feedback. I'll see what can be done. It can be brought back by the default character or by the stylistic alternate.

**Comment by TheMadHau5** [comment]
Default character, please

**Comment by philippnurullin** [comment]
Reverted to old construction.
https://github.com/JetBrains/JetBrainsMono/releases/tag/v2.304
