### ISSUE TITLE
Ligature request: add <-- to be the same as -->

### ISSUE THREAD

**Issue by exorcist365** [JetBrains/JetBrainsMono#417]
This can be very useful in languages where you can define custom operators.

For example haskell where this already [exists](https://hackage.haskell.org/package/ghc-source-gen-0.4.0.0/docs/GHC-SourceGen-Binds.html#v:-60--45--45-)

Current look:
![image](https://user-images.githubusercontent.com/51526053/109855290-c2182900-7c60-11eb-9a41-e58c008080b6.png)

**Comment by trygveaa** [comment]
@philippnurullin: This is a regression. The ligature was working in v2.210, but stopped working in v2.220 and newer.

**Comment by philippnurullin** [comment]
@trygveaa Yes it is. Will be fixed with the net update.
