### ISSUE TITLE
JavaScript symbol

### ISSUE THREAD

**Issue by janos-r** [JetBrains/JetBrainsMono#424]
Please add the JS symbol that starship started to use recently as default
https://starship.rs/config/#nodejs

Right now it displays like this:
![image](https://user-images.githubusercontent.com/30606201/112854465-2b4b5a80-90ae-11eb-814e-ba7d323db53f.png)

**Comment by Nexion** [comment]
JetBrains Mono doesn't include those symbols. If your font file does, it was previously patched. What you are searching for is most likely this project: [ryanoasis/nerd-fonts](https://github.com/ryanoasis/nerd-fonts)

**Comment by janos-r** [comment]
I see, thank you for the info.
No, I never had the "correct" symbol. It came with the new version of starship.rs. So it is probably their fault for adding non-standard characters.

**Comment by Nexion** [comment]
Yea, the Starship manual says you should have one of the Nerd Fonts installed as a prerequisite. If you have the original unpatched JetBrains Mono font installed, then most likely the symbol is substituted by your terminal emulator from another font. The original font doesn't have that glyph at all:
![JetBrains Mono Regular in FontForge](https://i.postimg.cc/j5Cpf8tf/image.png)

Pre-patched JetBrains Mono distributed by nerd-fonts project is outdated, I'd recommend to patch the recent version yourself if you want to see all the fancy characters in your terminal. The one you've mentioned is a part of Material Design Icons set. Yesterday I successfully did it with this settings `./font-patcher -s --fontlogos --mdi --octicons --powerlineextra`. However, when I tried to add the FontAwesome set, my Kitty terminal stopped seeing it. So you may need to try different options to find the settings that suit you best.

**Comment by janos-r** [comment]
I just added a config setting to behave like before. But Im a little disappointed by starship. I love the tool, but they should not expect some 3rd party font with their default setting.

starship.toml:
[nodejs]
symbol = "⬢ "

**Comment by philippnurullin** [comment]
Here is a link to the PR with JetBrains Mono https://github.com/ryanoasis/nerd-fonts/pull/572

I could add this symbol in the font, but this may look inconsistent after Nerd Fonts patch, so the optimal solution is to wait for the merge, or patch the font like @Nexion is suggesting.

Closing this issue because the symbol is not supported by JetBrains Mono.
