### ISSUE TITLE
IDEA shows two bold weights: `Extra Bold` and `ExtraBold`

### ISSUE THREAD

**Issue by real-mikhail** [JetBrains/JetBrainsMono#426]
Screenshot which shows issue:

![image](https://user-images.githubusercontent.com/3635408/113173500-1ad3e500-9252-11eb-8514-0e603ebc7560.png)

Possibly related to #122

**Comment by philippnurullin** [comment]
Hi @real-mikhail .
This seems like outdated files are stuck somewhere.
1. Maybe you have 2 version of JetBrains Mono installed or a problem with name versions occurred. To confirm that is nit please delete all the JetBrains Mono font from OS. Please delete the files one time and check it again. The older version may appear after deleting the current.
2. The bundled version of JetBrains Mono is outdated and needs to be removed. Please look here to locate where bundled fonts https://github.com/JetBrains/JetBrainsMono/issues/142 After you remove the bundled version the version from OS will be used. So install the latest one.

**Comment by real-mikhail** [comment]
Hm.. I've just tried that. No luck.

I removed all JetBrains Mono fonts installed on my OS (Windows). After that I've opened IDE and checked this dropdown - it contained fewer items but both "ExtraBold" and "Extra Bold" were still there.

After that I've closed IDE and deleted all bundled JetBrains Mono fonts from all JetBrains' IDEs (both manually installed and from Toolbox). Then I've installed latest version of font to OS. Then I've opened Rider and these two weights are still there:

![image](https://user-images.githubusercontent.com/3635408/114079385-d03a1480-98b2-11eb-937b-b6df69193ff4.png)

**Comment by real-mikhail** [comment]
If that is important: I have installed font manually:
> Select all font files in the folder [ttf], right-click any of them, then pick "Install" from the menu

**Comment by philippnurullin** [comment]
I'm not seeing the `Extra Bold` and `Semi Light` that are legacy weights your latest screen. So this means it's working as expected. Seems like there were the old versions somewhere.

JetBrains Mono have 7 weight indeed. They are all presented in the dropdown menu.

**Comment by real-mikhail** [comment]
Oh, indeed, sorry. Mislooked it on the last screenshot.
