### ISSUE TITLE
fix comments ligatures for javadoc-style comments

### ISSUE THREAD

**Issue by stephc-int13** [JetBrains/JetBrainsMono#427]
/** and /// comments should not use ligature or have specific ligatures to avoid weird spacing for javadoc-style comments.

**Comment by philippnurullin** [comment]
Hi @stephc-int13 Please explain you point more broadly. Adding the screenshots will give more context and i will be able to understand your point better.

**Comment by stephc-int13** [comment]
Sorry, I forgot to close this.
It was not related to the font itself but to sublime text handling of ligature when they crossed tokens recognized by the syntax highlighter.

**Comment by philippnurullin** [comment]
Ok, no problem. Closing it then.
