### ISSUE TITLE
Wrong interpolation of ==> and => ligatures in Italic fonts

### ISSUE THREAD

**Issue by philippnurullin** [JetBrains/JetBrainsMono#431]
![image](https://user-images.githubusercontent.com/48058957/115377435-e6f43b80-a1cf-11eb-901e-e5b7480ddbe8.png)
![image](https://user-images.githubusercontent.com/48058957/115377465-ee1b4980-a1cf-11eb-9bdd-285108705315.png)

**Comment by cwdsubs** [comment]
It does it for me when [ main weight ] in editor font settings is set to medium (Sept. 2022)
