### ISSUE TITLE
Allow infinite ligature expansion

### ISSUE THREAD

**Issue by Nytelife26** [JetBrains/JetBrainsMono#433]
Another popular programming font, Fira Code, has an interesting feature that caught my eye - infinite ligature expansion.

Something that bugs me when I'm using JetBrains Mono is that if I continue to use characters, the ligatures do not expand - past a certain point, they just disappear. I do not know how they did it, however, I know that it is possible to do.

[From their arrows](https://github.com/tonsky/FiraCode):

![arrows.png](https://github.com/tonsky/FiraCode/raw/master/extras/arrows.png)

That suggests to me that it should be possible to make ligatures of arbitrary length. Would that be something you could consider?

**Comment by philippnurullin** [comment]
Closing because it's duplicated in https://github.com/JetBrains/JetBrainsMono/issues/256

**Comment by trygveaa** [comment]
Note that infinite length ligatures have some issues. See https://github.com/tonsky/FiraCode/issues/1081
