### ISSUE TITLE
Request: Group 3 digits together to improve readability of large integer numbers

### ISSUE THREAD

**Issue by DerDan** [JetBrains/JetBrainsMono#435]
instead of showing numbers like:
![2021-05-03_15h04_37](https://user-images.githubusercontent.com/41516401/116879849-7c0c2100-ac21-11eb-8a20-4482ffb7ab5c.png)

it would be better to read numbers in this form:
![2021-05-03_15h04_37_grouped](https://user-images.githubusercontent.com/41516401/116879859-7dd5e480-ac21-11eb-9de8-cd9e7af30b66.png)
(modified with a painting tool, same width)

With every thousand separators, the right digit is moved to the left and the left digit to the right.
to build a small visual gap between each group.

**Comment by auduchinok** [comment]
It might hurt readability in places where numbers represent some codes/identifiers instead of ordinary numbers, or when, say, they are grouped by 4/8. Some programming languages allow adding `_` inside numeric literals for the grouping, it's probably a better way to have such grouping where needed.

**Comment by philippnurullin** [comment]
Kinda duplicated here https://github.com/JetBrains/JetBrainsMono/issues/182

**Comment by DerDan** [comment]
yes, my suggestion is a duplicate of #182, sorry
