### ISSUE TITLE
Couldn't you explain 'NL' in readme.md?

### ISSUE THREAD

**Issue by schittli** [JetBrains/JetBrainsMono#438]
Good evening

Thanks a lot for offering this great work!, as usual, JetBrains makes working a lot of more fun :-)

Unfortunately, you use the NL abbreviation, but you don't explain it.

Couldn't you please briefly describe both offered Font-Types (NL / Non-NL)?

Thanks a lot, kind regards,
Thomas

**Comment by TaigaYamada** [comment]
NL means No Ligature. So that version does not have any ligatures. The other version has ligatures. In the version with the ligatures, things like multi-character operators are substituted by a single, connected glyph.

**Comment by Alex-MXY** [comment]
I've been wondering about “NL” for a long time. After many trials, I found that the NL fonts looks much better in Linux (console terminal & gvim text &coding).
Also recommended to add "NL" explanation. : )

**Comment by philippnurullin** [comment]
Added an explanation about NL version in the README.
Feel free to ask questions if you have any.
