### ISSUE TITLE
Would be useful: `U+2001` / `EM QUAD` (Unicode Whitespace) should be a copy of the normal space char

### ISSUE THREAD

**Issue by schittli** [JetBrains/JetBrainsMono#439]
Good evening

Unfortunately there are sourcode files on the internet which use the Unicode Character `EM Quad` / `U+2001` to format block graphics.

When we open them in the editor with Jetbrains mono, the graphics are torn because the font doet not have defined the unicode white space `U+2001` / `EM Quad`.

Therefore, 
#### it would be great if you could just copy the normal Space `U+0020` to `U+2001` / `EM Quad` 
with exactly the same specification/size. This way such graphics would be displayed correctly again.

#### To test the result

you can just copy the generated Ascii Text art into the source code and comment out the pasted Text:
https://textkool.com/en/ascii-art-generator?hl=default&vl=default&font=ANSI%20Regular&text=%20JetBrain%20%0A%20is%20great!

You should get:

![image](https://user-images.githubusercontent.com/8282673/118317801-cb433300-b4f8-11eb-8051-470a27b66b96.png)

Thanks a lot, kind regards,
Thomas

**Comment by philippnurullin** [comment]
Hi @schittli . Sure. Will add it in the next update.
