### ISSUE TITLE
Add some missing latin symbols

### ISSUE THREAD

**Issue by ashkan-leo** [JetBrains/JetBrainsMono#440]
Hi, Thanks for making these beautiful fonts!

The following Latin symbols are missing from the font: 𝕋, 𝔽, 𝕊, 𝔹, 𝕃. I imagine there are many other missing Latin symbols that I haven't found. It would be useful to add them to the font.

**Comment by philippnurullin** [comment]
Added in https://github.com/JetBrains/JetBrainsMono/releases/tag/v2.304
