### ISSUE TITLE
The lowercase f in italic slightly overlaps with other italic charaters

### ISSUE THREAD

**Issue by minhduc0711** [JetBrains/JetBrainsMono#441]
This causes a problem in kitty terminal emulator (https://github.com/kovidgoyal/kitty/issues/3630) because it only renders what is inside a character cell.
I wonder if it is possible to shorten the top/bottom hook of the italic `f`, to make its width consistent with other italic characters?

![image](https://user-images.githubusercontent.com/34294427/118429717-81c33580-b6fc-11eb-9d34-51fba044bcef.png)

**Comment by philippnurullin** [comment]
Hi @minhduc0711 There is about 300 glyph in italic that have negative value of left side bearing. For example all the BoxDrawing elements happen to have the LSB equal to -20 so they maintain the correct position. 

The problem as is see it that the kitty terminal is modifying the original spacing in the font. I'm sure they have reasons for it, but it is still not showing the font how it was designed. 

I will see what can be tweaked in `f` and dependent symbols. It must solve most common problems but not sure it will solve all the potential problems.

**Comment by kovidgoyal** [comment]
You dont need to fix box drawing symbols, kitty will draw them itself, not from the font. Just letter shapes in all variants of a monospace font need to fit within the same bounding box and not bleed into neighboring characters, as kitty draws all characters independently, in parallel, for performance reasons.

**Comment by philippnurullin** [comment]
Changed the italic `f`.
Please test with the files from here https://github.com/JetBrains/JetBrainsMono/tree/master/fonts

**Comment by minhduc0711** [comment]
Thank you, looks great now :raised_hands: 
![image](https://user-images.githubusercontent.com/34294427/125787680-3c98bedb-62d7-4470-a8a4-4d87c862f54a.png)
