### ISSUE TITLE
Variable font looks blurry

### ISSUE THREAD

**Issue by BlueStaggo** [JetBrains/JetBrainsMono#444]
I loved the look of JetBrains Mono, so I decided to install it myself. I thought I wouldn't like the default weight, so I went to install the variable version. However, I was disappointed to see that the font was blurry. I do not have a screenshot of this, as I don't want to install that version of the font again.

First, here's the normal version:
![image](https://user-images.githubusercontent.com/71090710/118673257-c4663a00-b7f0-11eb-90ab-de7efa39b317.png)
Nice and crisp.
What about the variable font?
![image](https://user-images.githubusercontent.com/71090710/118673361-d811a080-b7f0-11eb-9dbe-62f190501e8e.png)
Look at these characters: `T j l t b 3 5 7`. They look a bit blurry on the top, don't they? The non-variable version looks more cleaner. In fact, this is a general problem with <ins>every variable font</ins>! I just want to know why this happens.

*Lesson of the day: If you want a nice and crisp font, don't get a variable font!*

**Comment by philippnurullin** [comment]
Hi @BlueStaggo Please confirm the OS and IDE you using to reproduce this problem.

**Comment by BlueStaggo** [comment]
It appears everywhere on Windows 10 x64 1909. I've seen it on these programs:
- The font viewer pre-installed into Windows
- Visual Studio Code
- Notepad
- Google Chrome

Cascadia Code is a variable font, but it doesn't appear blurry on Visual Studio or Visual Studio Code.

**Comment by CodeCrazy-ywt** [comment]
Well, imo that's because of the difference of methods to render an ordinary TTF(to ensure clarity) and a variable font(to make the text look what they look originally) on Windows.

**Comment by BlueStaggo** [comment]
Closed due to inactivity.
