### ISSUE TITLE
中文宽度不等于两个字母宽度

### ISSUE THREAD

**Issue by fuguocheng** [JetBrains/JetBrainsMono#447]
什么时候能支持中文，最新版本中，一个中文宽度与两个字母宽度不相等。
如图：
![image.png](https://i.loli.net/2021/05/24/INx53BUmPdypfX8.png)

**Comment by alexeyten** [comment]
Потому что в шрифте нет иероглифов
#20

**Comment by philippnurullin** [comment]
Hi @fuguocheng Currently we don't have plans to support Chinese.
Closing because this is a duplicating https://github.com/JetBrains/JetBrainsMono/issues/242 and #20
