### ISSUE TITLE
请求 能支持一下中文吗,

### ISSUE THREAD

**Issue by huzhujiang2014** [JetBrains/JetBrainsMono#451]
请求 能对中文优化一点吗,觉得这个字体在开发过程中确实很完美,但是对于简体中文的支持不是很好,能优化一下,只需要简体中文即可.

**Comment by philippnurullin** [comment]
Hi @huzhujiang2014 This issue is dublicating https://github.com/JetBrains/JetBrainsMono/issues/242
Closing it.
