### ISSUE TITLE
Please add a SemiBold instance

### ISSUE THREAD

**Issue by thlinard** [JetBrains/JetBrainsMono#453]
According to Google Fonts specs:

> When a variable font is onboarded to Google Fonts, we will provide instantiated static fonts for legacy applications. Thus, bear in mind Google’s API will automatically create all the 100x weights along the used range of the axis when producing static fonts, whether or not they are included in the designer's original design space.
https://github.com/googlefonts/gf-docs/tree/main/Spec#stat-table

So, a SemiBold static font is downloadable on https://fonts.google.com/specimen/JetBrains+Mono

Please add a SemiBold instance to the VF.

See also https://github.com/google/fonts/issues/3411

**Comment by philippnurullin** [comment]
Restructured the placement of Medium on the weight axis. 
The Medium is now is more thin and SemiBold is the same weight as old Medium.
