### ISSUE TITLE
"source" bashism in shell scripts with /bin/sh shebang

### ISSUE THREAD

**Issue by moosotc** [JetBrains/JetBrainsMono#454]
cf https://github.com/aspnet/dnx/issues/1064
https://github.com/JetBrains/JetBrainsMono/blob/d5b56fc2876bc6ae036fd665274a74c41697e4a6/sources/build-vf.sh#L2

**Comment by philippnurullin** [comment]
Hi @moosotc . Please explain your point.

**Comment by moosotc** [comment]
philippnurullin ***@***.***> writes:

> Hi @moosotc . Please explain your point.

If /bin/sh is not bash (for instance it is ash) there is no guarantee
that bashism that the script uses will work. Worse still they might
"work" and do something entirely unexpected. There is standard way to do
this - '.' which should work universally bash or not.
