### ISSUE TITLE
2.230 Release

### ISSUE THREAD

**Issue by Jeddix** [JetBrains/JetBrainsMono#457]
The commit for the 2.230 release is now almost 2 months old. Will there be an official release?

The website and the releases here on Github are still on 2.225.

**Comment by philippnurullin** [comment]
Yes, of course there will be an official release.
The archive on the website will be updated after the release on GitHub.

Do you wait for a particular feature or a fix that was made in 2.230?

**Comment by CodeCrazy-ywt** [comment]
So far I've seen many notable changes in the changelog. So I wonder when will  2.230 be released.

**Comment by philippnurullin** [comment]
Just made a release with 2.241.
