### ISSUE TITLE
JetBrainsMono website korean translation error (https://www.jetbrains.com/ko-kr/lp/mono/)

### ISSUE THREAD

**Issue by OctopusET** [JetBrains/JetBrainsMono#458]
[Korean translation site url](https://www.jetbrains.com/ko-kr/lp/mono/)
> JetBrains Mono is free & open source

In the website, they are translated like "JetBrains Mono는 무료 오픈 소스입니다."

"free" does not meaning price. It's "free" as in "free speech" 
And "무료" means only "free" as in "free beer"
Luckly korean language has accurate word "자유". It means "free" as in "free speech".

So those terms can be translated like

> "JetBrains Mono는 자유 오픈소스 입니다." 

or using term of "프리" for just transliteration. 

>  "JetBrains Mono는 프리 오픈소스 입니다." 

If you need more infomation please checkout this. 
[Free & Open Source English ver.](https://en.wikipedia.org/wiki/Free_and_open-source_software)
[Korean ver.](https://ko.wikipedia.org/wiki/%EC%9E%90%EC%9C%A0-%EC%98%A4%ED%94%88_%EC%86%8C%EC%8A%A4_%EC%86%8C%ED%94%84%ED%8A%B8%EC%9B%A8%EC%96%B4)

Please make translations right.

Thanks.

**Comment by philippnurullin** [comment]
Thanks for the feedback! 
I will send it to the translators team.

**Comment by philippnurullin** [comment]
Looks like the corrections are done. 
It's hard for me to confirm it. )) Please take a look.

**Comment by OctopusET** [comment]
Corrections are right. They changed into "JetBrains Mono는 프리-오픈 소스입니다."

Thanks for changes.
