### ISSUE TITLE
是不是把我们中国的英文打错了

### ISSUE THREAD

**Issue by BaotaoWang** [JetBrains/JetBrainsMono#459]
您好，官网的介绍页，语言支持列表中，是不是把China错写成Chiga了，是的话，可不可以改一下。确实就是Chiga的话，对不起，打扰了

**Comment by CodeCrazy-ywt** [comment]
本来就不支持中文的，Chiga确实是另一个语言的名字。
Jetbrains Mono doesn't support Chinese language, and Chiga does is another language.
