### ISSUE TITLE
Feature request: Dim escape backslashes

### ISSUE THREAD

**Issue by p00f** [JetBrains/JetBrainsMono#460]
Fira Code dims backslahes:
![image](https://user-images.githubusercontent.com/36493671/122664308-4d8cda00-d1be-11eb-802e-5b670018ca18.png)

Can this be a stylistic set? In my use case backslashes are always used for escaping.

In fact the only exception I can think of is windows paths, so windows users can disable this ligature in their terminal

**Comment by philippnurullin** [comment]
Hi @p00f . This issue is dubliacated here https://github.com/JetBrains/JetBrainsMono/issues/264
Closing this one.
