### ISSUE TITLE
U+FFFD symbol missing

### ISSUE THREAD

**Issue by errhammr** [JetBrains/JetBrainsMono#461]
I've noticed that the unicode codepoint `U+FFFD REPLACEMENT CHARACTER` does not have a representation in JetBrains Mono. This leads to characters breaking out of monospace alignment when the symbol is borrowed from a fallback font.

Including this symbol in JetBrains Mono is important because it is the fallback symbol for invalid codepoints. These will be shown if the code editor comes across a character that isn't encoded in the expected charset.

See the attached screenshot for an example. The red and blue stripes should go continuously and straight from top to bottom which they do not.

![jetbrains-missing-fffd](https://user-images.githubusercontent.com/50107940/122930673-78b52c00-d36c-11eb-8bc3-f2c9a56a75e9.png)

**Comment by errhammr** [comment]
Just for completeness an example how it should be.

The Iosevka font has the `U+FFFD` character so the example text in the screenshot above aligns perfectly:

![iosevka-having-fffd](https://user-images.githubusercontent.com/50107940/122933383-e5c9c100-d36e-11eb-9024-446b6cefd5ac.png)

**Comment by philippnurullin** [comment]
Sure. Will add it in the next update.

**Comment by philippnurullin** [comment]
Please grab the files from here if untill the release https://github.com/JetBrains/JetBrainsMono/tree/master/fonts
