### ISSUE TITLE
Licensing and attribution question

### ISSUE THREAD

**Issue by DervishD** [JetBrains/JetBrainsMono#462]
First of all, my excuses for asking here but I didn't know where to ask.

I would like to use JetBrains Mono in a web app I'm developing for free, to help some librarians I know. I can provide the link to the web app, it's openly hosted here at GitHub, under my user page.

Right now I can use the font as provided, but in the future I may need it to subset it. So, technically I will be redistributing a modified version. The web app itself is released under the terms of MIT license.

I have three issues with this:

1. Is 'JetBrains Mono" a Reserved Font Name under OFL? I can't find the confirmation anywhere. If so, I'll ask here for permission to do the subsetting before doing it.
2.  The user interface for the web app has to be kept simple (you can check HOW simple it is now), so I would like to avoid adding links to legalese texts if I can avoid it. This may be a problem in order to comply with OFL, as I can serve the contents of the OFL.txt file, no big deal, but it won't be accessible from the main web page, only when the corresponding URL is typed by hand. Would this be enough or do you request a different mechanism from me?
3. Related with the previous one, and since for me is not easy to modify the user interface to add links, how do you want to be credited in my web app, given these limitations? Would a `THANKS.txt` file or similar suffice for you, available if you type the corresponding URL, but not directly accessible from the web page or will you request some explicit text on the web page or a button, link, etc?

Thanks a lot in advance, not only for your useful font, but for making it available under OFL and taking the time to read this.

**Comment by philippnurullin** [comment]
Hi @DervishD .
Regarding your questions about license.

1. No, in the license agreement for JB Mono we do not reserve the name JetBrains Mono. 
2. and 3. The answer for them will be a cite from the official page of JetBrains Mono 

> "JetBrains Mono typeface is available under the SIL Open Font License 1.1 license and can be used free of charge, for both commercial and non-commercial purposes. You do not need to give credit to JetBrains, although we will appreciate it very much if you do."

This reply is not a legal advice. The responsibility of interpretation of  and that he/she is responsible for interpretation of the OFL.

**Comment by DervishD** [comment]
Hi @philippnurullin 
First of all, THANKS a lot for the advice..

Second, I've decided to credit you in the CSS file, where the font is loaded, so the attribution can be seen with the typical browser inspector, but I can credit you in a comment in the HTML file if you want, too.

The actual content of the CSS file is:
```
/*
 * Thanks to JetBrains for making this font available under SIL Open Font
 * License, and to Philipp Nurullin <philipp.nurullin@jetbrains.com> and
 * Konstantin Bulenkov <kb@jetbrains.com>, the font creators.
 */
@font-face {
    font-family: 'JetBrains Mono';
    font-display: swap;
    font-style: normal;
    font-weight: 400;
    src: url('index_mono_r_400.woff2') format('woff2');
} 
```

If you want me to change anything, please tell me. The repo is publicly available at my user in GitHub (it's called "trujaman") and even though is not a commercial product (I'm not making any money out of it) because it's some volunteering job I'm doing for a local library, they have some requirements anyway and that's the reason why the user interface is so terse.

If they change their minds, I'll add a footer with an attribution, too.

And thanks for the font, it's just FANTASTIC. I owe you one ;)

**Comment by philippnurullin** [comment]
Happy to hear you like JB Mono. Have fun with it and good luck with the app!
