### ISSUE TITLE
Characters with more vertical content (e.g "f") overlap with overhead bar

### ISSUE THREAD

**Issue by darsnack** [JetBrains/JetBrainsMono#463]
See the screenshot below. Certain characters when combined with an overhead bar look like they are overlapping with the bar. This is especially hard to read for cases like "f" or "t" where it becomes difficult to see what overhead character is used at a glance.
<img width="69" alt="Screen Shot 2021-06-23 at 9 38 41 AM" src="https://user-images.githubusercontent.com/4811350/123116765-ce3e1700-d406-11eb-88e0-e12440c6dd4f.png">

For example, the following are "f" + "bar" and "f" + "hat/carrot".
<img width="31" alt="Screen Shot 2021-06-23 at 9 39 32 AM" src="https://user-images.githubusercontent.com/4811350/123116902-ec0b7c00-d406-11eb-8f3e-4a64e8a2d2ac.png">

Sorry that I am not familiar with the Unicode numbers off the top of my head.

**Comment by philippnurullin** [comment]
Hi @darsnack . Please copy and paste the letters. This will be a great help.
In what language they are used?

**Comment by darsnack** [comment]
I use these characters in Julia, and I created them using the Julia REPL. I pasted the characters and the sequence I typed into the REPL to generate them below

The first screenshot:
```
x̄ȳāj̄f̄h̄t̄

julia> x\bar[TAB] y\bar[TAB] a\bar[TAB] j\bar[TAB] f\bar[TAB] h\bar[TAB] t\bar[TAB]
```

The second screenshot:
```
f̄f̂

julia> f\bar[TAB] f\hat[TAB]
```

**Comment by philippnurullin** [comment]
I see what the problem is. Will fix this in the one of the next updates.

**Comment by philippnurullin** [comment]
Hi, please grab files from here https://github.com/JetBrains/JetBrainsMono/tree/master/fonts and confirm/deny postive change. Thanks in advance!

**Comment by darsnack** [comment]
I don't think it has changed:
<img width="69" alt="Screen Shot 2021-07-15 at 4 01 38 PM" src="https://user-images.githubusercontent.com/4811350/125857092-0cac5fbe-ac7b-4989-b60a-5eb658c3394b.png">

<img width="279" alt="Screen Shot 2021-07-15 at 4 03 11 PM" src="https://user-images.githubusercontent.com/4811350/125857293-6c8e0549-89d9-4404-8d93-d2b1ea64e7aa.png">

**Comment by darsnack** [comment]
It looks okay in iTerm, but not VS Code.

<img width="147" alt="Screen Shot 2021-07-15 at 4 43 10 PM" src="https://user-images.githubusercontent.com/4811350/125861748-159e65bf-db68-4e04-acfc-78cee2b9aab2.png">

**Comment by philippnurullin** [comment]
Ok, thanks for the feedback I will continue to work on that

**Comment by philippnurullin** [comment]
Please test again.

**Comment by darsnack** [comment]
Sorry for the delay. Just tested again, and it looks good. Thanks for your work!

**Comment by philippnurullin** [comment]
No worries. I was pretty confident this time .))
