### ISSUE TITLE
Italic variable ligature bug: => and ==> breaks

### ISSUE THREAD

**Issue by CodeCrazy-ywt** [JetBrains/JetBrainsMono#466]
Adjust the 'wght' to a value between 400 and 800, and you will see these two ligatures look wrong.
![20210701-feedback-ligatures_break](https://user-images.githubusercontent.com/62426149/124080335-d50b0080-da7c-11eb-8379-3b1f2be5750b.png)

**Comment by philippnurullin** [comment]
Dublicated https://github.com/JetBrains/JetBrainsMono/issues/431

Please take the files from master to get rid of this bug. https://github.com/JetBrains/JetBrainsMono/tree/master/fonts

**Comment by mahdiamer** [comment]
Good
