### ISSUE TITLE
Character missing when importing into Unity

### ISSUE THREAD

**Issue by greuelpirat** [JetBrains/JetBrainsMono#467]
I just tried to import `JetBrainsMono-Regular.ttf` into Unity `2020.3.12f1`.

And it warned about a missing character `200B` (what ever this is):

![image](https://user-images.githubusercontent.com/16866222/124157935-9fc0db80-da99-11eb-8c23-75970bbf1d60.png)

This is no problem for me, but I tough I report it.

**Comment by philippnurullin** [comment]
Thanks for the report!
This is `zero width space`symbol. I will add it in the next update.
