### ISSUE TITLE
Font is not showing. 2017.1.5

### ISSUE THREAD

**Issue by jsypsy** [JetBrains/JetBrainsMono#468]
Hi, I'm using phpstorm 20171.5.
I installed this font and try to change font in settings menu.
But there is no JetBrainsMono font.
Does not support old version?

![image](https://user-images.githubusercontent.com/58464634/124204913-04704a80-db1b-11eb-8da8-8ac75f85e214.png)

**Comment by CodeCrazy-ywt** [comment]
Maybe you need to update your phpstorm to the latest version

**Comment by philippnurullin** [comment]
Nobody reported this kind of problem, so i'm thinking everything is fine with the font.

Did you install the font in to the OS?
The version of IDE is old and the font is not bundled with it.

If this not help please contact the PhpStorm support. https://intellij-support.jetbrains.com/hc/en-us/?phpstorm

**Comment by jsypsy** [comment]
> Nobody reported this kind of problem, so i'm thinking everything is fine with the font.
> 
> Did you install the font in to the OS?
> The version of IDE is old and the font is not bundled with it.
> 
> If this not help please contact the PhpStorm support. https://intellij-support.jetbrains.com/hc/en-us/?phpstorm

Yes, I installed the font in to the OS (Windows10).
Please check this out.
![Screenshot_2](https://user-images.githubusercontent.com/58464634/124403441-6e822d00-dd71-11eb-9cc1-2354984187c2.png)


And I can use the font on other programs like PUTTY.
![Screenshot_3](https://user-images.githubusercontent.com/58464634/124403461-8a85ce80-dd71-11eb-8016-e74fb55b444d.png)

**Comment by CodeCrazy-ywt** [comment]
Seems that it's your PhpStorm's issue. The latest version of PhpStorm is 2021.1. Please try updating your PhpStorm and see whether this bug occurs again.

**Comment by jsypsy** [comment]
> Seems that it's your PhpStorm's issue. The latest version of PhpStorm is 2021.1. Please try updating your PhpStorm and see whether this bug occurs again.

Because of license I cannot update PhpStorm 😢

**Comment by drakex90** [comment]
While installing the font did you chose **Install for all users** if not try to reinstall it and choose for all users.

**Comment by jsypsy** [comment]
> While installing the font did you chose **Install for all users** if not try to reinstall it and choose for all users.Wow

Wow! It worked!
You save my life !! 🙏

But that's really weird.
I installed every font file with same way. (Drag and Drop into "C:\Windows\Fonts")
And then, some fonts worked fine and some others did not work.
