### ISSUE TITLE
Wrong glyph for U+2288 NEITHER A SUBSET OF NOR EQUAL TO

### ISSUE THREAD

**Issue by dscorbett** [JetBrains/JetBrainsMono#475]
The glyph for U+2288 NEITHER A SUBSET OF NOR EQUAL TO is wrong. This glyph should be mapped to U+2289 NEITHER A SUPERSET OF NOR EQUAL TO.
![x](https://user-images.githubusercontent.com/1124347/127172019-08da1564-4792-49f6-b5c3-5de2c6efb4fc.png)

**Comment by philippnurullin** [comment]
Yes, seems right. 
Thanks for the feedback!

i will wait a few more days and make quickfix for 2.241.
