### ISSUE TITLE
Is there new symbol to display tabs? 

### ISSUE THREAD

**Issue by florianbuerger** [JetBrains/JetBrainsMono#476]
I updated to the newest version today (`2.241`) and now I see these characters in Xcode (file uses tabs, not spaces) Doesn't happen in version `2.225`

`2.241`

<img width="554" alt="ScreenShot 2021-07-27 at 22 09 39" src="https://user-images.githubusercontent.com/119219/127220815-24e1eb01-f4be-4a3b-ab94-d96dc1a95e32.png">

`2.225`

<img width="566" alt="ScreenShot 2021-07-27 at 22 08 54" src="https://user-images.githubusercontent.com/119219/127220790-be44d1a2-ef03-42a4-88ba-9f7281d2dd72.png">

Not sure if this is intentional? If it is a new feature, this should be off by default. Xcode doesn't give any control over font features (like many other apps) and I find it rather distracting. Thanks!

I doubt the versions for Xcode / macOS are relevant, but just in case: 

Xcode 12.5.1 / 13.0 Beta 3
macOS 11.5.1

**Comment by alexeyten** [comment]
Looks like related to #241

**Comment by florianbuerger** [comment]
> Looks like related to #241

Ah yes, that is it. Somehow I overlooked that in the release notes. I read through the linked issue, I don't see a way to disable them.

**Comment by philippnurullin** [comment]
Hi @florianbuerger . There is no way to disable them manually. 
I'll make a quick fix and remove `HT` (u+2409 u+0009) `CR` (u+240D u+000D) `LF` (u+240A u+000A) from the second unicode value. This should fix the problem.
