### ISSUE TITLE
letters cropped from top

### ISSUE THREAD

**Issue by novotnyfra** [JetBrains/JetBrainsMono#48]
Some letters are cropped from the top in **Android Studio**.
Issue is related with `Jetbrains Mono` only, `Jetbrains Mono Medium` / `ExtraBold `is ok.

![image](https://user-images.githubusercontent.com/26295670/72632529-79c67a80-397c-11ea-824d-6c81e15bd98b.png)

**Comment by philippnurullin** [comment]
Hi, @novotnyfra . Looks odd. We will look in to it.
Thanks for feedback!

**Comment by novotnyfra** [comment]
It disappeared without apparent cause. Maybe it's an Android Studio problem

**Comment by philippnurullin** [comment]
@novotnyfra Thanks for an update! I will close the issue for now. Feel free to reopen it if this problem reappears.
