### ISSUE TITLE
U+FE62  1 ﹢1 

### ISSUE THREAD

**Issue by bluelovers** [JetBrains/JetBrainsMono#482]
https://unicode-table.com/cn/FE62/

![image](https://user-images.githubusercontent.com/167966/130313718-ffa82c11-14d7-4c67-a506-61ea45cbb184.png)

maybe should make this to be in `center middle`

**Comment by kenmcd** [comment]
JetBrains Mono does not include this character (FE62).
So what you are probably seeing is a fallback font for that character.

**Comment by bluelovers** [comment]
hope can include it
