### ISSUE TITLE
about `{}`

### ISSUE THREAD

**Issue by bluelovers** [JetBrains/JetBrainsMono#49]
is this is expected display?

![image](https://user-images.githubusercontent.com/167966/72633616-cf5a5180-3993-11ea-8071-e3da2ca19694.png)

**Comment by only** [comment]
@bluelovers remove the bundled font and install this instead system-wide. 
https://www.jetbrains.com/lp/mono/

(And windows sucks at Java)

**Comment by bluelovers** [comment]
how to remove bundled font?

**Comment by lppedd** [comment]
There is an issue for this https://youtrack.jetbrains.com/issue/JBR-1909
It should be solved. Be sure to have the right version of the font.

**Comment by Renerick** [comment]
@bluelovers , I found it in `JetBrains/Tollbox/<product (Rider in my case)>/ch-0/<build number>/jbr/lib/fonts`. Can confirm that after removal braces look OK.
![image](https://user-images.githubusercontent.com/20725046/72662013-e1bba600-39fa-11ea-876b-f032189392b8.png)
