### ISSUE TITLE
SOH display, not happening with other fonts

### ISSUE THREAD

**Issue by joao** [JetBrains/JetBrainsMono#491]
Have a bug using the font in a macOS terminal, inside an application (Panic's Nova), with a unicode character in my bash prompt.

<img width="63" alt="screenshot 2021-09-02 at 15 03 16" src="https://user-images.githubusercontent.com/1041/131857961-90c21126-8526-4715-8b68-6bf942cb50d8.png">
<img width="320" alt="screenshot 2021-09-02 at 15 13 22" src="https://user-images.githubusercontent.com/1041/131859547-9b1ba1ac-d258-45f6-8691-4401e5d20d43.png">

It shows a 'SOH' (start of heading) written after the character, which doesn't happen in any other font I've tried, thus being something with the font and its characters - also happens with others besides this one.
Any idea why this might be happening?

Have the bash prompt defined like this:
`PS1='\n\[\033[0;32m▲\[\033[00m \]\[\033[00;36m\W\]\[\033[00m:\] ';
`

**Comment by trygveaa** [comment]
Probably caused by #241. I always found it strange that control characters were added to the font.

#476 is a similar issue for some of the other control characters.

**Comment by joao** [comment]
@trygveaa Thank you for explaining it.
Hope it gets removed in a future version, as in the issues you linked it indicates there isn't any way to disable it.

**Comment by philippnurullin** [comment]
Removed in the latest push. Grab the files here https://github.com/JetBrains/JetBrainsMono/tree/master/fonts
