### ISSUE TITLE
OpenType vs TrueType

### ISSUE THREAD

**Issue by natros** [JetBrains/JetBrainsMono#493]
I want to use your fonts with ligatures. What type of font should I use in Intellij, iTerm2 and SublimeText? Both programs support both types. Should I use OpenType or TrueType?

I'm macOS Catalina user with iMac 27 5k display.

Thanks.

**Comment by philippnurullin** [comment]
On 5K display it doesn't matter. ))
I prefer to use TrueType because of variable function.
