### ISSUE TITLE
!= is broken with Light and ExtraLight with 2.250 and above

### ISSUE THREAD

**Issue by rysktky** [JetBrains/JetBrainsMono#494]
Hi, team. Thank you for the awesome font!

Problem:
Version 2.250 and above, "!=" looks broken.
Symptom on Light and ExtraLight only (which I use for the most, by the way..).
Verified with different types of terminal or editor on Linux and Windows.
Font size does not seem to matter.

![image](https://user-images.githubusercontent.com/39027949/134767176-a8b981d2-c204-4275-8acd-185927947606.png)

![image](https://user-images.githubusercontent.com/39027949/134767166-b7be4483-0f19-4445-80c1-7863d684bcda.png)

**Comment by philippnurullin** [comment]
Yes, it is! 
Thanks for the report. Will fix in the next push.

**Comment by natros** [comment]
any news on this issue?

**Comment by philippnurullin** [comment]
The beta of 2.300 will be pushed soon. It has this issue fixed. Sorry for the wait.
