### ISSUE TITLE
A bunch of website zh-cn translating improvement suggestions

### ISSUE THREAD

**Issue by YVVT** [JetBrains/JetBrainsMono#498]
I found that in zh-cn website, some translations may be hard to understand or different from original English text.
Here's my suggestion, open to discussion.
A ~strikethrough~ represents a deletion, and a **bold text** represents an addition.
___
~给~**为**开发人员**设计**的字体
~特定于~**专为**读代码**而设计**的连字
字体粗细和**对应的**斜体~设置~
但小写字母的高度~已~最大化。 
考虑一下此字体~语~**与**其他字体的比较。*（Oops... a typo!!! TAT）*
代码行的~运行时间~**长度**往往比预期的要长。*（What does text size have to do with code running time???）*
JetBrains Mono 的标准宽度字母有助于使~线条~**代码行**保持预期的长度。
这使整个文本~模式~更加清晰。
~“零”~**数字 0** 在中间有一个点。
~削减~笔划**的水平末端**
笔划~结束~的~削减~**水平末端**更适合像素网格
好斜~率~**体**的关键是微调直立字体和斜体字体之间的对比度。
通常，~该~**倾斜**角度约为 11°–12°。
连字是由两个或多个连接**的**符号组成的字符
等宽~合~**连**字
~框图~**制表符**
选择文件夹中的所有字体文件，然后双击 “~Install Font~**安装字体**” 按钮。
选择文件夹中的所有字体文件，右键单击其中任何一个，然后从菜单中选择 “~Install~**安装**”。

**Comment by philippnurullin** [comment]
Thanks a lot, I will send it to the localization team.
