### ISSUE TITLE
What file type should I use on Windows (static TTF vs. variable TTF)?

### ISSUE THREAD

**Issue by trallnag** [JetBrains/JetBrainsMono#499]
Hello, is one option recommended over the other? For example Cascadia Code (another quite young font) outright recommends the variable TTF

**Comment by CodeCrazy-ywt** [comment]
Just follow your heart! You can try both of them and choose what makes you more comfortable.

**Comment by philippnurullin** [comment]
Use a Variable .ttf. Its only 2 files to install. This is the only benefit if you want to use the font in IDE.
On other hand if you writing code in browser you can use specific to Variable fine tuning of weight.
Here you can read about Variable fonts and see ghot to use them in CSS. https://web.dev/variable-fonts/

**Comment by trallnag** [comment]
Thanks for the clarification
