### ISSUE TITLE
Repository should use diff-capable format

### ISSUE THREAD

**Issue by damieng** [JetBrains/JetBrainsMono#5]
I'd recommend switching over from the binary-only "FontLab Compact" vfc files to the "FontLab json" vfj files so that PR's can be evaluated/checked to make sure nothing else is impacted etc.

**Comment by aaronbell** [comment]
Or better yet, UFO! 👍

**Comment by damieng** [comment]
I think UFO will be lossy though with regards to things like hinting?  Still, would open up the gate to Glyphs users etc.

**Comment by damieng** [comment]
The author of Glyphs actually recommends against using .ufo files to go between FontLab and Glyphs as they lose other stuff too - instead he has some macros.  See toward the end of https://glyphsapp.com/tutorials/working-with-ufo

**Comment by aaronbell** [comment]
Yes. Sorry, I should have cautioned that if you’re using the glyphs or fontlab specific functionality, UFO may not preserve the data seamlessly. I don’t know how they’ve built the font, so that is something to consider.

**Comment by signalwerk** [comment]
I think it would be cool to have at least an export as UFO along side with the vfc. Because there is not only Glyphs and FL. There are so many processors and editors and they often just can handle UFO.

**Comment by philippnurullin** [comment]
Added .vfj version to the source folder.
