### ISSUE TITLE
remove left baseline from lowercase i

### ISSUE THREAD

**Issue by michaeldurland** [JetBrains/JetBrainsMono#50]
Very nice font!
Please consider removing the left baseline on the lowercase i so that it matches the style of the lowercase l ("ell").
Currently having the sequence "li" (lowercase ell lowercase eye) makes the right baseline from the l run into the left baseline of the i.

**Comment by philippnurullin** [comment]
Hi, Michael. This modification will make an `i` to similar to the `l`. The dot, at the top of an `i` will be not enough to distinguish these two letters fast. The addition you suggesting may be included as a stylistic alternative, which is not our priority right now.
