### ISSUE TITLE
Ligature request: ...

### ISSUE THREAD

**Issue by NicolaIsotta** [JetBrains/JetBrainsMono#501]
In java, the [vararg feature](https://docs.oracle.com/javase/8/docs/technotes/guides/language/varargs.html) is declared using three periods: ...
Using JetBrains Mono, the periods are rendered asymmetrically:
![varargs](https://user-images.githubusercontent.com/18428155/136364320-2d32052b-5040-44cf-93df-0abb25b65bf7.jpg)

**Comment by NicolaIsotta** [comment]
Hi @philippnurullin , thanks for the reply.
I'm using NetBean 8.1 and 11.2. Deleting IDE cache did not solve the issue.

**Comment by philippnurullin** [comment]
Did you reinstall the font files in OS?

**Comment by CodeCrazy-ywt** [comment]
@NicolaIsotta Is your Jetbrains Mono font the latest version? If not, you can turn to #142 for ways to remove older bundled fonts.
