### ISSUE TITLE
[Feature Request] '&' and '@' alternative forms via OpenType Features

### ISSUE THREAD

**Issue by errr-maxx** [JetBrains/JetBrainsMono#507]
I really like JetBrains Mono font, but FireCode's '@' and '&' feels for me better

So I decided to request adding that alternative symbols as OpenType's font features (that I can later freeze with '[fonttools-opentype-feature-freezer](https://github.com/twardoch/fonttools-opentype-feature-freezer)')

**Comment by philippnurullin** [comment]
Hi @UnknownErrror . Glad you liking JB Mono. I'll think on that. Thanks for the feedback.

**Comment by philippnurullin** [comment]
The alternate for `&` i added in 784f65aca6b8c2b5cf4061b45b079f0e3f391248
The construction `@` in of Fira Code has different logic of the strokes. It will look alien in JetBrains Mono, so the alternate will not be added.
