### ISSUE TITLE
Powerline symbols are not aligned properly 

### ISSUE THREAD

**Issue by GreenTeaSeb** [JetBrains/JetBrainsMono#509]
Tested with multiple fonts, and 3 different terminal emulators (st, alacritty and konosole), nothing seem to have fixed this issue. 
![powerline_st](https://user-images.githubusercontent.com/81326680/141663773-eadbc77e-1a0c-442a-a5f6-8f04a831fc42.png)
The diagonal split is 1 pixel too short, and the rounded corners are 1 pixel away from the bottom.

I'm running a fresh install of Arch with x11, not sure if I'm missing any packages, and this shouldn't require the patched fonts, if I'm not mistaken.

**Comment by philippnurullin** [comment]
Thanks for the report @GreenTeaSeb . The original version of JB Mono dont have this form of powerline symbols. I'm think you have the patched version of the font.

The original symbols we have for powerline.
<img width="776" alt="Screenshot 2021-11-17 at 11 11 56" src="https://user-images.githubusercontent.com/48058957/142181136-4f007d42-6916-43c6-9810-91d29c49f5b5.png">
.

**Comment by GreenTeaSeb** [comment]
ah I see, yea, my mistake.
