### ISSUE TITLE
numbers are not fixed width

### ISSUE THREAD

**Issue by michaeldurland** [JetBrains/JetBrainsMono#51]
Numbers appear to have different widths.
Observe this screenshot at 9pt where the first digit does not line up vertically. e.g. the "4" appears to be wider, and the 0 is narrower.
Also the dot in the 0 is not centered.
Screenshot taken in Geany 1.36 on Linux.
![image](https://user-images.githubusercontent.com/4379812/72642845-27f10680-3922-11ea-860c-484c579fc431.png)

**Comment by sirinath** [comment]
Miss alignment of numbers makes reading line numbering irritating.

**Comment by philippnurullin** [comment]
@michaeldurland Hi, sorry for the long response. Did you try the latest version of the font 1.0.2? I believe the root of this issue is lack of monospace property in the early versions of JetBrains Mono. Let me know if this wont help.

**Comment by philippnurullin** [comment]
@michaeldurland I'm closing this issue because i believe this problem is fixed in latest release. Feel free to reopen it you still experiencing it.
