### ISSUE TITLE
○ (U+25CB) is wider than other characters

### ISSUE THREAD

**Issue by MonstraG** [JetBrains/JetBrainsMono#516]
![image](https://user-images.githubusercontent.com/17963791/145165218-99575722-d133-4cc6-96cc-d401d4f11e0d.png)
![2](https://user-images.githubusercontent.com/17963791/145165421-6c6dcc80-a1da-4508-a7fc-82a166209c97.gif)

This character happens to be used in Next.js build output

My Webstorm version is 2021.3, I'm not sure on how to get font version.

**Comment by alexeyten** [comment]
That's because JetBrains Mono does not have this glyph and you see it from a fallback font.
![image](https://user-images.githubusercontent.com/44377/145189539-2b9e2992-bf93-4dad-b738-00ba5e8e8609.png)

**Comment by MonstraG** [comment]
Okay, then I guess this issue turns into "plz add U+25CB" instead.

**Comment by philippnurullin** [comment]
Nope. The symbol is already added in the process of making #47 
It will be in the next release.
