### ISSUE TITLE
HTML tag overlap

### ISSUE THREAD

**Issue by royfrancis** [JetBrains/JetBrainsMono#517]
Is this how it is supposed to be?

![screenshot](https://user-images.githubusercontent.com/5083500/145981792-e11f28ce-6283-4661-9f0d-58beb5024745.png)

**Comment by CodeCrazy-ywt** [comment]
It's a ligature, and if you don't want it, you can download the NL version.

**Comment by royfrancis** [comment]
Ah ok. I like most of the ligatures. I didn't know about this. I thought this one was weird. For anyone else who stumbles across this, here is a full list of ligatures: https://www.jetbrains.com/lp/mono/
