### ISSUE TITLE
[question] [help] dollar sign alternative 

### ISSUE THREAD

**Issue by samadadi** [JetBrains/JetBrainsMono#527]
currently dollar sign contains cross line that makes it, in my opinion super ugly. does this font has an alternative to enable, specially for these <$> <$ $> ligatures? is it possible to build font from source without cross line?

**Comment by philippnurullin** [comment]
In the first version the construction of `$` was without the bar. Bur after receiving the feedback we changed it to be more classical. 
Here is an issue about it. https://github.com/JetBrains/JetBrainsMono/issues/110

**Comment by shahmilav** [comment]
@samadadi, in the meantime, what you could use is the ![nerd font patched](https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/JetBrainsMono.zip) version from https://www.nerdfonts.com/font-downloads. It is not yet updated with the newer ```$``` (although I suspect it is a matter of time), and it has the un-crossed glyph.

**Comment by philippnurullin** [comment]
The alternate construction was added in the `cv14`. This can be accessed through OpenType setting in your application.
You can grab files from here https://github.com/JetBrains/JetBrainsMono/tree/master/fonts

Here are instructions on how to build from source https://github.com/JetBrains/JetBrainsMono#building-from-source-files
