### ISSUE TITLE
Several glyphs are outline-incompatible

### ISSUE THREAD

**Issue by madig** [JetBrains/JetBrainsMono#53]
Specifically, 'B', 'dcroat', 'exclam_equal.liga', 'g', 'greater', 'hbar', 'i', 'j', 'onehalf', 'onequarter', 'question', 'question_equal.liga', 'semicolon', 'threequarters', 'uni02C9' and 'uni045B'. A spot check hints at different contour starting points and e.g. 'hbar' mixing contours and components in one master.

FontLab 7 can guess to make the outlines compatible, but will not export them like that to UFO and Designspace.

@twardoch: an "apply compatibility fix to outlines so it actually gets source-exported" button would be _highly_ appreciated not just by me personally, *wink wink nudge nudge*.

Edit: Found it, it's in the top bar in matchmaker mode :D

**Comment by philippnurullin** [comment]
@madig sorry don't understand, do you still need help?

**Comment by madig** [comment]
It's less that I need help, more that one can't load the source files and export to UFO plus Designspace to generate a variable font, because several glyphs are not actually compatible. FontLab does some magic to make them compatible, but only if you generate the fonts from FontLab.

**Comment by philippnurullin** [comment]
@madig Ok, got it. I will double check thees glyphs & flatten the outline so it will work. Sorry for the messy outline management, i know its not optimal. Will clean in future.

**Comment by philippnurullin** [comment]
The cleaning of mentioned glyphs was done. If you stumble upon more problems feel free to open new issue.

**Comment by madig** [comment]
Some issues remain.

```
$ fontmake -m JetBrainsMono.designspace -o variable
INFO:fontmake.font_project:Building variable font variable_ttf/JetBrainsMono-VF.ttf
INFO:ufo2ft:Pre-processing glyphs
ERROR:cu2qu.ufo:Glyphs named 'caron.salt' have different number of segments
ERROR:cu2qu.ufo:Glyphs named 'uni02C9' have different number of segments
ERROR:cu2qu.ufo:Glyphs named 'dotaccent.case' have different number of segments
ERROR:cu2qu.ufo:Glyphs named 'napostrophe' have different number of segments
fontmake: Error: In 'JetBrainsMono.designspace': Generating fonts from Designspace failed: fonts contains incompatible glyphs: 'caron.salt', 'dotaccent.case', 'napostrophe', 'uni02C9'
```

```
$ fontmake -m JetBrainsMono_Italic.designspace -o variable
INFO:fontmake.font_project:Building variable font variable_ttf/JetBrainsMono_Italic-VF.ttf
INFO:ufo2ft:Pre-processing glyphs
ERROR:cu2qu.ufo:Glyphs named 'numbersign_braceleft.liga' have different number of segments
ERROR:cu2qu.ufo:Glyphs named 'onequarter' have different number of segments
ERROR:cu2qu.ufo:Glyphs named 'uni02C9' have different number of segments
ERROR:cu2qu.ufo:Glyphs named 'bar_bar_bar_greater.liga' have different number of segments
ERROR:cu2qu.ufo:Glyphs named 'uni2084' have different number of segments
ERROR:cu2qu.ufo:Glyphs named 'less_bar_bar_bar.liga' have different number of segments
fontmake: Error: In 'JetBrainsMono_Italic.designspace': Generating fonts from Designspace failed: fonts contains incompatible glyphs: 'bar_bar_bar_greater.liga', 'less_bar_bar_bar.liga', 'numbersign_braceleft.liga', 'onequarter', 'uni02C9', 'uni2084'
```
