### ISSUE TITLE
在Sublime Text 4中简体汉字显示错误

### ISSUE THREAD

**Issue by WangHub666** [JetBrains/JetBrainsMono#530]
在Sublime Text 4中使用该字体时，输入简体汉字“类”，上半部分为“米”，下半部分为“犬”，下半部分正确的显示应该为“大”。
在Sublime Text 4中使用`Microsoft YaHei UI`显示的简体汉字“类”如下图
![imagec288f4efd03a40fb.png](https://imgpp.com/s1/2022/02/24/imagec288f4efd03a40fb.png)

在Sublime Text 4中使用`JetBrains Mono`显示的简体汉字“类”如下图
![imageb4b1aac3e93ed43c.png](https://imgpp.com/s1/2022/02/24/imageb4b1aac3e93ed43c.png)

已经找到解决方法，在Sublime Text的设置里面添加代码`"font_options": ["gdi"],`即可解决
![image.png](https://imgpp.com/s1/2022/02/28/image.png)

**Comment by philippnurullin** [comment]
Hi @WangHub666 . JetBrains Mono not supporting the Chinese language. So the font you see is default fallback font. 
To have the desired look of the Chinese symbols, you can set the fallback font to `Microsoft YaHei UI` and `JetBrains Mono` as a primary.

**Comment by luweijun1992** [comment]
> Hi @WangHub666 . JetBrains Mono not supporting the Chinese language. So the font you see is default fallback font. To have the desired look of the Chinese symbols, you can set the fallback font to `Microsoft YaHei UI` and `JetBrains Mono` as a primary.

How to set the backup font ?

**Comment by alexeyten** [comment]
I guess it's impossible for now.

https://github.com/sublimehq/sublime_text/issues/2795
https://github.com/sublimehq/sublime_text/issues/2973

**Comment by ChenZhu-Xie** [comment]
I partially achieved this by merging CN+EN fonts :

<img width="2442" height="1538" alt="image" src="https://github.com/user-attachments/assets/fcc89898-a2df-4936-b238-2726e244f963" />

[![Font_Merger](https://opengraph.githubassets.com/1/ChenZhu-Xie/Font_Merger)](https://github.com/ChenZhu-Xie/Font_Merger)

see also: https://forum.sublimetext.com/t/plug-error/76271/4 
and https://community.silverbullet.md/t/custom-font-doesnt-work/1237/5?u=chenzhu-xie

**Comment by Charles94jp** [comment]
直接用混合字体https://github.com/CandyTek/EditorMonospacedFont/blob/main/JetBrains%20Mono%20Source%20Han%20Sans.otf
sublime设置
```
"font_face": "JetBrains Mono Source Han Sans",
"font_options": ["gdi","no_bold", "no_italic"], 
"line_padding_bottom": 1,
"line_padding_top": 1,
```
