### ISSUE TITLE
distinct (`!=`) ligature is not rendering properly in 2.251

### ISSUE THREAD

**Issue by carlosala** [JetBrains/JetBrainsMono#532]
I add two screenshots, first one with v2.242 (latest released version):
![v2.242](https://user-images.githubusercontent.com/66907184/158066997-6961b032-d538-4f4b-a58c-6b47a515ad5a.png)

Second one using v2.251 (latest repo version):
![v2.251](https://user-images.githubusercontent.com/66907184/158067034-6a1e6a20-c829-49ee-95fe-cd685cac7844.png)

Maybe there was some update there non intentional? It happens with every font size.

**Comment by philippnurullin** [comment]
Duplicated in https://github.com/JetBrains/JetBrainsMono/issues/494

**Comment by carlosala** [comment]
Ups sorry, thanks for the answer!
