### ISSUE TITLE
The text blurs in StackOverflow site

### ISSUE THREAD

**Issue by Jeff-Tian** [JetBrains/JetBrainsMono#536]
Hi I installed the JetBrainsMono and applied to all the system in Windows 11. In other words, not only applied to code editors but also to browsers.

It looks great almost everwhere, except for StackOverflow site:

![image](https://user-images.githubusercontent.com/3367820/161178082-e73f97ea-0451-49dd-ac84-39e0f72c5660.png)

What can be the cause? Is there way to use different font for StackOverflow site, and deep using JetBrainsMono in other places?

**Comment by alexeyten** [comment]
This is 1th April joke by StackOverflow.

It has nothing to do with this font
