### ISSUE TITLE
The number '0' does not exist ?

### ISSUE THREAD

**Issue by KivinStudio** [JetBrains/JetBrainsMono#541]
I don't want 'dot' ... ...
![图片](https://user-images.githubusercontent.com/48846439/169257315-62a97143-1b0b-406e-9b34-0962981e4561.png)

**Comment by CodeCrazy-ywt** [comment]
It depends on whether your editor supports opentype features. For example, in VS Code, you should add this setting `"editor.fontLigatures": "'zero' 1"` to settings.json file.

**Comment by philippnurullin** [comment]
Hi @KivinStudio What editor are you using?

**Comment by th-bu** [comment]
You could use https://github.com/sharpjs/JetBrainsMonoSlashed
