### ISSUE TITLE
Rendering of the "➔" glyph is very different between normal and italic

### ISSUE THREAD

**Issue by Leonya** [JetBrains/JetBrainsMono#545]
The normal version looks correct, while the italic one is much bigger. The font size and all other properties are the same.

<img width="540" alt="Screenshot 2022-05-31 at 17 36 19" src="https://user-images.githubusercontent.com/46537/171213079-ef8c7bf0-a990-4cd1-99a3-6c8ae82d0e44.png">

**Comment by CodeCrazy-ywt** [comment]
I have tested, but didn't encounter your situation.

**Comment by philippnurullin** [comment]
JetBrains Mono does not support the "➔" symbol used in the heading of this issue.
So, this means that symbol is taken from fallback font.
How to fix it:
- Use similar symbol from JB Mono `→` or `⟶`.
- I can add this symbol in the next update.

**Comment by philippnurullin** [comment]
The accurate depiction of ➔ is closer to the version you don't like, so add a couple of alternates you can use `➝` `➞`.
