### ISSUE TITLE
when will the 2.251 font release?

### ISSUE THREAD

**Issue by Firestar-Reimu** [JetBrains/JetBrainsMono#547]
I found fonts and sources are in [2.251](https://github.com/JetBrains/JetBrainsMono/commit/9a01623903be1c12fc1a14ea3801e42e004f4223)

will this be released? or we have to wait for 2.300?

**Comment by liangjingkanji** [comment]
I have a [2.251 version](https://github.com/liangjingkanji/JetBrainsMono-patch), but modified the character `g`, temporary use if you are in a hurry

**Comment by CodeCrazy-ywt** [comment]
You manually modified the lowercase g?

**Comment by liangjingkanji** [comment]
> You manually modified the lowercase g?

Yes, because I don't like the original `g`

**Comment by philippnurullin** [comment]
The release version is 2.300. It will be available for test in one month and released soon after.

**Comment by cmarincia** [comment]
@liangjingkanji can you please add a PR with the alternative `g` glyph? Looks nice

**Comment by mon-jai** [comment]
> @liangjingkanji can you please add a PR with the alternative `g` glyph? Looks nice

I would like to have that option too.

**Comment by liangjingkanji** [comment]
> @liangjingkanji can you please add a PR with the alternative `g` glyph? Looks nice

Such PR is pointless, does not conform to the author's design, and the font files cannot be merged

**Comment by oshytiko** [comment]
Is it possible to have double story open `g` exposed as a feature? As it's done with slashed zero? I very much prefer Fira Code style `g`.

**Comment by CodeCrazy-ywt** [comment]
Hmm... I don't think so, because it doesn't conform to the design concept of JBM -- reduce noices.

**Comment by cmarincia** [comment]
@philippnurullin any updates on the release of 2.300?

**Comment by philippnurullin** [comment]
Just pushed 2.300. 
There will be no additional features. After polishing and removing errors this version will be released.
The alternate symbol for `g`is under OpenType feature `cv03`.

**Comment by Firestar-Reimu** [comment]
Last line of Changelog.md `Updated marks placement in Ľ, ď, ľ, ť #522`

it should be #552 as #522 has not been fixed

There is still no NL otf fonts

**Comment by philippnurullin** [comment]
@Firestar-Reimu Yes you are correct. Thanks!

**Comment by cmarincia** [comment]
How is this even completed? @philippnurullin
