### ISSUE TITLE
Missing Ligatures in Microsoft Visual Studios

### ISSUE THREAD

**Issue by JoeyJaySWE** [JetBrains/JetBrainsMono#549]
Been using these fonts for VSC and loved it,
however, work want us to switch over to MS VS and even though I can set the font family and it loads in, 
I can't seem to trigger the ligatures. 
Micrsoft Visual Studios 2022(x64-bit), V.17.2.3

**Comment by JoeyJaySWE** [comment]
Sorry for the late reply @philippnurullin 
But I wouldn't call this Issue being fixed and thereby I wouldn't consider the matter closed either.
And the link didn't provide a solution to the problem, rather a "You are not alone".

If you read through the link trees not only would you notice that Microsoft has ignored the issue, or brushed the bug off as an idea, but they're also focusing on hyphen-based ligatures, while my issue is that no ligatures work at all.
No ===, ==. !=. !==, =>, ==>. The reason I wanna clarify that it's not just a hyphen-based issue is that the threads specify a WPF bug with hyphens that trigger line breaks, however nothing about equal signs.

**Comment by philippnurullin** [comment]
@JoeyJaySWE is it working in your case? https://github.com/tonsky/FiraCode/wiki/Visual-Studio-Instructions
Thanks @alexeyten
