### ISSUE TITLE
about `\u2500` ─ ──

### ISSUE THREAD

**Issue by bluelovers** [JetBrains/JetBrainsMono#55]
http://unicode.org/cldr/utility/character.jsp?a=%E2%94%80

1. size not change

> bug

![image](https://user-images.githubusercontent.com/167966/72660150-63640180-3a04-11ea-839c-ecb6a5677d23.png)

2. `─` + `─` = `──`

> hope can have no margin/space between `─`

![image](https://user-images.githubusercontent.com/167966/72660161-973f2700-3a04-11ea-8794-1df0e09c2491.png)

![image](https://user-images.githubusercontent.com/167966/72660174-dcfbef80-3a04-11ea-9a49-1578ca51f68b.png)

3. width

> hope can same as full-width

![image](https://user-images.githubusercontent.com/167966/72660376-e044aa80-3a07-11ea-9394-5bf658b01574.png)

**Comment by philippnurullin** [comment]
The link above redirecting to the `uni2500 BOX DRAWINGS LIGHT HORIZONTAL`. JetBrains Mono currently don't support Box Drawing set of glyphs.
Not sure i got you request right. If i misunderstood it, please add more information.

**Comment by bluelovers** [comment]
hope can support it
