### ISSUE TITLE
Increase height of vertical bars

### ISSUE THREAD

**Issue by UtkarshVerma** [JetBrains/JetBrainsMono#554]
Could you please consider increasing the height of vertical bar glyphs like "▏" so that they are connected when vertically aligned.

In the image below, it can be seen that they are slightly shorter than required.
 
![image](https://user-images.githubusercontent.com/31820255/187277714-2b3bc20a-caaf-44b5-867a-04d35ddf0fe4.png)

Having them longer would be really helpful for terminal applications.

**Comment by philippnurullin** [comment]
Hi @UtkarshVerma Please let me know:
- what version of JetBrains Mono are you using?
- what Editor/ IDE are you using?
- and OS.

The gaps usually don't appear when the `line-height` in editor is set at 1/100% or basically left untouched.

**Comment by UtkarshVerma** [comment]
Hi, thank you for the quick response. Here is my setup:
- Version 2.242
- Editor: VS Code
- OS: Arch Linux

I didn't modify the line height in VS Code and this also happens with terminal apps.

**Comment by UtkarshVerma** [comment]
Don't use the font anymore.
