### ISSUE TITLE
Possible slab variant for lower case L

### ISSUE THREAD

**Issue by nashpatty** [JetBrains/JetBrainsMono#557]
Could a slab variant for lower case L be added to jetbrains mono and NL?
I was playing around with the idea:
<img width="205" alt="image" src="https://user-images.githubusercontent.com/28615881/188724099-f06f0e4a-9697-4a39-b587-b2417f008155.png">

I feel like this would be a nice variant to add, although I'm pretty sure the team could make it look much nicer in terms of spacing, rounding, and sizing.

**Comment by shahmilav** [comment]
I think this is a really good idea. Perhaps it could be achieved via a stylistic set, like the slashed zero?

Also @nashpatty, could you [email](mailto:shahmilav@gmail.com) me the font files you edited? I would like to try it out as well.

**Comment by CodeCrazy-ywt** [comment]
Maybe it's difficult to distinguish from figure 1.

**Comment by philippnurullin** [comment]
This alternate is present in the next version as `cv01`.
Closing because it's dublicatind this issue #238

**Comment by nashpatty** [comment]
> I think this is a really good idea. Perhaps it could be achieved via a stylistic set, like the slashed zero?
> 
> Also @nashpatty, could you [email](mailto:shahmilav@gmail.com) me the font files you edited? I would like to try it out as well.

I edited in glyphs app, didn't export the font though. I suppose we can wait until the next release of jetbrains mono, since it's already in the works.

**Comment by shahmilav** [comment]
Y

**Comment by shahmilav** [comment]
> > I think this is a really good idea. Perhaps it could be achieved via a stylistic set, like the slashed zero?
> 
> > 
> 
> > Also @nashpatty, could you [email](mailto:shahmilav@gmail.com) me the font files you edited? I would like to try it out as well.
> 
> 
> 
> I edited in glyphs app, didn't export the font though. I suppose we can wait until the next release of jetbrains mono, since it's already in the works.

Yeah, sounds good
