### ISSUE TITLE
Malformed showcases for control characters

### ISSUE THREAD

**Issue by YVVT** [JetBrains/JetBrainsMono#558]
![屏幕截图 2022-09-08 211152](https://user-images.githubusercontent.com/62426149/189131015-3d1308a6-84d9-4b4b-a849-c0f54f38b9d0.jpg)

**Comment by shahmilav** [comment]
Damn, that looks weird. What browser/OS are you using?

Seems fine in Safari Technology Preview (macOS)
<img width="1082" alt="Screen Shot 2022-09-08 at 11 05 31 PM" src="https://user-images.githubusercontent.com/53659750/189263780-9e45b603-5901-4d8a-b15e-982253cdb2a6.png">

**Comment by kenmcd** [comment]
> ![屏幕截图 2022-09-08 211152](https://user-images.githubusercontent.com/62426149/189131015-3d1308a6-84d9-4b4b-a849-c0f54f38b9d0.jpg)

That looks like a different font.
Like another font is being substituted as a fallback font.
Can you export that to a PDF and check which font is there.

**Comment by CodeCrazy-ywt** [comment]
> Damn, that looks weird. What browser/OS are you using?
> 
> Seems fine in Safari Technology Preview (macOS)
> <img width="1082" alt="Screen Shot 2022-09-08 at 11 05 31 PM" src="https://user-images.githubusercontent.com/53659750/189263780-9e45b603-5901-4d8a-b15e-982253cdb2a6.png">
> 

Microsoft Edge, Windows 11.

**Comment by philippnurullin** [comment]
This looks like is hinting problem. I think this is happening because of the symbols of Control Code are made with composite symbols that are referenced in the font and scaled down.

The good thing is that this is the old version of the font and this will be fixed when we do the next Site update.
