### ISSUE TITLE
[request] doc update about bounded font and web font

### ISSUE THREAD

**Issue by bluelovers** [JetBrains/JetBrainsMono#56]
1. add how to update/remove bounded font in readme

> i think ppl didn't know where is font path

`xxxxx\jbr\lib\fonts`

2. add web font link so we can use it like https://www.jetbrains.com/lp/mono/

**Comment by bluelovers** [comment]
https://github.com/JetBrains/JetBrainsMono/issues/49#issuecomment-575884476

**Comment by philippnurullin** [comment]
Created pinned issue to treat this problem.
