### ISSUE TITLE
Weird behavior with hash when type RTL Language

### ISSUE THREAD

**Issue by AhmedElTabarani** [JetBrains/JetBrainsMono#560]
When I try to make an Arabic header in Markdown like this: `## السلام عليكم` the second hash will disappear

## Showcase the Issue:

https://user-images.githubusercontent.com/69223584/191472933-fbbf8f3a-48cd-4fee-a9a7-0b5ced70bb6f.mp4

## I tried with all hashes 1-6 and got strange behavior
This image show the behavior if the issue with all hash headers

![image](https://user-images.githubusercontent.com/69223584/191475349-be1f5743-39a3-4722-9eb4-4340ddda70b2.png)

## Content to test

```
# test
## test
### test
#### test
##### test
###### test


# اختبار
## اختبار
### اختبار
#### اختبار
##### اختبار
###### اختبار
```

**Comment by philippnurullin** [comment]
Hi @AhmedElTabarani 
This issue is probably rooted in how ligatures are treated and it looks like it's not working well with Arabic scripts.
JetBrains Mono don't have Arabic language support so we do not expect the ligatures to work.
But you can disable ligatures in `settings.json`.
```
{
  "editor.fontFamily": "*** Your ligature enabled font ***",
  "editor.fontLigatures": fals,
  "...": "your other settings",
}
```

**Comment by AhmedElTabarani** [comment]
Thanks!
