### ISSUE TITLE
Opening and closing quotes in v2.300

### ISSUE THREAD

**Issue by YVVT** [JetBrains/JetBrainsMono#563]
Glad to see that opening and closing quotes become easily distinguishable in v2.300, but... they look quite “standing out”.

![image](https://user-images.githubusercontent.com/62426149/193808296-5985ff86-ee2f-4461-b6ae-a16fd33b074e.png)

As is shown in the screenshot above, quotes are inconsistent with the font construction.

My suggestion is that closing quotes revert to what they look like before, while opening quotes be horizontally symmetric with closing quotes, just like Tahoma and Verdana do.

![image](https://user-images.githubusercontent.com/62426149/193809115-a522f9a3-1270-4607-8806-700d7f44cbdb.png)

**Comment by Firestar-Reimu** [comment]
This may be not distinguishable between curved and vertical quotes

“” ""

**Comment by philippnurullin** [comment]
Thanks for the feedback. I'll think about it. 
The recognition of symbols is preferred in this case. Don't see a better solution right now.

**Comment by inferno986return** [comment]
I do e-book development and having distinguishable curly quotes is important for keeping beautiful formatting.
