### ISSUE TITLE
Is it possible to add ligature for Apache Freemarker comment opening tag <#-- ?

### ISSUE THREAD

**Issue by StanislavGrinkov** [JetBrains/JetBrainsMono#57]
Hi!

Is it possible to add ligature for html comment opening tag **<#--** ?

![image](https://user-images.githubusercontent.com/7836782/72663508-b39b8d80-3a1d-11ea-997a-77c847ecfe22.png)

Right now it looks a bit strange with 'normal' opening tag and 'ligatured' closing tag.

**Comment by alexeyten** [comment]
Er? Html comment is <!--

**Comment by StanislavGrinkov** [comment]
> Er? Html comment is <!--

@alexeyten  Thanks for pointing out!
I use Apache Freemarker as a template engine and Idea used its comment tag instead of html comment and I hadn't noticed.

I updated the title. Question is the same.

**Comment by philippnurullin** [comment]
Hi, @StanislavGrinkov . Sure, added this request for 1.0.2 list.

**Comment by philippnurullin** [comment]
@StanislavGrinkov Check the latest version of the font. If it's not working feel free to reopen the issue.
