### ISSUE TITLE
Can you use Glyphs3 edit font source?

### ISSUE THREAD

**Issue by liangjingkanji** [JetBrains/JetBrainsMono#571]
Hope to use Glyphs3 for editing font

**Comment by liangjingkanji** [comment]
Because Glyphs3 can't open the source file correctly

**Comment by philippnurullin** [comment]
Hi @liangjingkanji 
This problem can be easily fixed by removing secondary stem values. Just delete all `vStem1` & `hStem1` and this will eliminate the problem. Thees values are not essential.

**Comment by liangjingkanji** [comment]
It means that as long as Stems is zero I can delete it, Ok

**Comment by liangjingkanji** [comment]
If you upgrade to Glyphs3 I think it will be better, If JetBrains supports you, hhh
