### ISSUE TITLE
How to enable OpenType by default

### ISSUE THREAD

**Issue by liangjingkanji** [JetBrains/JetBrainsMono#572]
Excuse me. I think a lot of people have this need liangjingkanji/JetBrainsMono-patch/issues/2

Can use Glyphs3 achieve this requirement? 

Because I want to keep the complete opentype, So don't want to modify the characters

**Comment by philippnurullin** [comment]
Hi @liangjingkanji 
Not sure I understood your idea.
- You want to make a slashed zero a default figure? Here is a thread about slashed zero. https://github.com/JetBrains/JetBrainsMono/issues/8
- And here is a patched version with slashed zero used as default form. https://github.com/sharpjs/JetBrainsMonoSlashed
it looks like the font is not up to date in this repository.

**Comment by liangjingkanji** [comment]
I modified the default features, But I wonder if there is an option to quickly toggle the default features

on by default features: 'zero', 'cv02', 'cv03', 'cv04', 'cv05', 'cv17'

https://github.com/liangjingkanji/JetBrainsMono-patch

**Comment by philippnurullin** [comment]
You mean how to turn off/on OpenType features in text editors & IDE?
It depends on the editor. Usually it's well hidden, so you might want to google where to find it your exact case/editor.

**Comment by liangjingkanji** [comment]
> 

I want to directly set the font default features, Because the Jetbrains IDE does not support set font-features

**Comment by alexeyten** [comment]
So you just want to change the default, but still have access to other variants. Am I correct?

**Comment by liangjingkanji** [comment]
> So you just want to change the default, but still have access to other variants. Am I correct?

Yes

**Comment by philippnurullin** [comment]
In that case, switch glyphs from the desired `cv` with default glyph. 
You can make it by renaming the glyphs in source files.
For example, rename all `g.cv03` to `g`. And current `g` to `g.cv03`.

**Comment by liangjingkanji** [comment]
> 

That's what I'm doing right now, It feels troublesome, If that's the easiest way then I get it

Thank you very much for your work!
