### ISSUE TITLE
Plans to support Korean language in the future?

### ISSUE THREAD

**Issue by neoseed** [JetBrains/JetBrainsMono#573]
I am very satisfied, but Korean characters do not support the same fixed width as English characters.
Do you have any future support plans?

**Comment by philippnurullin** [comment]
Hi @neoseed 
It looks like this issue is duplicating already existing one. https://github.com/JetBrains/JetBrainsMono/issues/20
We do not have the expertise in Korean language, so we don't have any plans to add Korean language support.
