### ISSUE TITLE
Website font download link points at an old version while loading

### ISSUE THREAD

**Issue by hichemfantar** [JetBrains/JetBrainsMono#576]
The `download font` button in the [website](https://www.jetbrains.com/lp/mono/) points at an old version of the font 1.0.3.
However when the page finishes loading, it points at the latest release which is 2.242.

Using the dev tools I discovered that the default download link is set to 1.0.3, then an API call fetches the latest version and the download link is updated.

I suggest removing the default version entirely and only rendering the download button when the api fetch is complete to prevent visitors from downloading an outdated version of the font before the API call is complete.

**Comment by philippnurullin** [comment]
Hi @hichemfantar 
Thanks for the feedback. I will pass it to the web team.

**Comment by ice1000** [comment]
👍🏼 to the proposal. I think it may help to create a release in this repo.

**Comment by hichemfantar** [comment]
I wanted to say that this problem still exists.
