### ISSUE TITLE
Add Greek language.

### ISSUE THREAD

**Issue by N3tFX** [JetBrains/JetBrainsMono#58]
If it's possible, please add support for Greek language.

**Comment by singularitti** [comment]
I am a user of the [Julia language](https://julialang.org/), which encourages users to use Greek letters in programming mathematical formulae. Currently, this font lacks Greek letters support. Please add it if possible!

**Comment by whannes** [comment]
I would also like to use JetBrains Mono in Notepad++ for text files that contain greek letters. This is not possible and I have to use Fira Code or similar instead.

**Comment by 1900011604** [comment]
Me Too! I use Cascadia Code/Consolas/Fira Code for fallback fonts and their widths are small than JB Code.

**Comment by APerricone** [comment]
it is still unlisted in https://www.jetbrains.com/lp/mono/#support-languages :)
