### ISSUE TITLE
2.302 alternative variants looks real good

### ISSUE THREAD

**Issue by vikky49** [JetBrains/JetBrainsMono#580]
This is not an issue per se just wanted to send an appreciation note. I have checked out the fonts and used some of my favorite alternatives, and the font looks dope.

<img width="1894" alt="pratyush@MacBook-Pro-3:~ 2022-11-17 07-23-26" src="https://user-images.githubusercontent.com/180512/202486727-2a09b170-686c-4cc1-bcb4-72a515b78eb1.png">

**Comment by philippnurullin** [comment]
@vikky49 Glad to hear it! Thanks for the kind words.
