### ISSUE TITLE
Mathematical blackbold letter R and C

### ISSUE THREAD

**Issue by mulliganaceous** [JetBrains/JetBrainsMono#583]
So far, there are blackboard Q and N. However, I noticed blackboard R is missing despite being one of the important blackboard letters, as blackboard R represents the reals. The set of all primes and quaternions, both BMP blackboard fonts, are also absent.

Interestingly, blackboard F (field) and S (sphere) are present.

Note the difference in fonts for the blackboard (doublestuck) glyphs not included in JBM.

![∈ℍ](https://user-images.githubusercontent.com/29824582/206859851-04c8c5eb-b7d0-4e2f-8ff3-1e73568e39ab.png)

**Comment by philippnurullin** [comment]
Hi @mulliganaceous 
- What font version have you installed?
- Please send the exact uni-codes for missing letters or just paste them as plain text in a comment.

**Comment by mulliganaceous** [comment]
I have the latest version that is showcased on the site. 

The missing important blackblard letters are all found in the Letterlikes Symbols block; the rest are in Mathematical Letters.

**Comment by philippnurullin** [comment]
Ok. The support for the whole MATHEMATICAL DOUBLE-STRUCK block was added in 2.300 
So you can just upgrade to the latest fonts from master https://github.com/JetBrains/JetBrainsMono/tree/master/fonts

**Comment by mulliganaceous** [comment]
Thanks. Can you also update it on the main page?

**Comment by philippnurullin** [comment]
Yes, at some point the landing page will be updated.

Closing this issue because there is a solution for the original request.
