### ISSUE TITLE
Starting an expo app in WebStorm and qr code just doesnt work

### ISSUE THREAD

**Issue by Jindra123** [JetBrains/JetBrainsMono#585]
![image](https://user-images.githubusercontent.com/55125757/208089297-426258af-8054-48ac-8510-139e93167b03.png)

**Comment by philippnurullin** [comment]
Hi @Jindra123 
This behaviour is controlled by the `line-height`. This parameter is set in the IDE (WebStrom in your case). I suggest contacting WebStorm support here https://youtrack.jetbrains.com/issues/WEB
