### ISSUE TITLE
New application request

### ISSUE THREAD

**Issue by Arashvscode** [JetBrains/JetBrainsMono#586]
Hi, can you create a new symbol for html tags, i.e. the start tag
 <\
a symbol like less than equal to Java >=

**Comment by philippnurullin** [comment]
Hi @Arashvscode . I'm not understanding your request.
Can you please elaborate more, add screenshots with context.

**Comment by Arashvscode** [comment]
> Hi @Arashvscode . I'm not understanding your request. Can you please elaborate more, add screenshots with context.

![IMG_20221221_143658](https://user-images.githubusercontent.com/101287880/208891175-79a1f6c1-310c-4740-872a-1f01e3261d83.png)


You can fix something like this by yourself, thanks for your reply

**Comment by alexeyten** [comment]
`<\` is meaningless in HTML. DO you mean `</` or `/>`?

**Comment by Arashvscode** [comment]
> 

I mean the closing tag in html for example understand because code
</h4>

I would like to change the closing tag that I mentioned in the H4 code above. Thanks for your reply

**Comment by Arashvscode** [comment]
> 

Can you see the photo I posted above?  I need a new symbol like ## -> ## this time for the closed html tag please watch the picture

**Comment by YVVT** [comment]
But... that's not called closing html tag... And such a symbol (if I got it right) is meaningless.

PS: This is a closing tag: `</div>`. I haven't ever seen `<\` used anywhere.

**Comment by Arashvscode** [comment]
> 

One, I apologize because my English is not good. Two, it looks interesting because I work with React, and the terminating link symbol is interesting while coding.

**Comment by philippnurullin** [comment]
@Arashvscode 
I'm sorry, but we will be unable to add this ligature.
- It modifies the original sequence of symbols too much. And not making it more balanced visually.
- I can't find any information that `<\`  is a logical expression (an Operator fer example). The good ligature in programming font usually has some meaning behind it.

**Comment by Arashvscode** [comment]
> 

ok bro tnks
