### ISSUE TITLE
Dots on i and j and on umlauts

### ISSUE THREAD

**Issue by th-bu** [JetBrains/JetBrainsMono#589]
After upgrading from 2.242 to the current version 2.303 I saw that the dots on the i and j are now smaller.
At font size 9 (12px) they are now 1 pixel in height instead of the 2 before.

In the current state there are several problems with this:

## Due to the font rendering in Windows the dot looks more like a small line that is almost 2 pixels wide:
![grafik](https://user-images.githubusercontent.com/2885473/209708640-29c751a5-412e-4d9d-80db-0638247e8664.png)

## The dots on the umlauts are still *2* pixels tall:
![grafik](https://user-images.githubusercontent.com/2885473/209708527-6c3e717a-0bc4-47f3-a76d-0b436c52cbfd.png)

## When using the bold version, all dots are *1* pixel tall:
![grafik](https://user-images.githubusercontent.com/2885473/209708567-da10f6ce-9344-41da-ab90-c3a3353e7e6e.png)

## When using the italic version, all dots are now *2* pixels tall:
![grafik](https://user-images.githubusercontent.com/2885473/209708578-dfad2cec-40f8-4598-aba3-a0885165453a.png)

Personally I prefer the old version with the 2 pixel tall dots, even if it would go a bit above the rest of the font but I think I could get used to the new style.

But the dots should be the same on all characters.

**Comment by philippnurullin** [comment]
The recent update fixes the problem.
If you still have the issue, feel free to reopen.

**Comment by Sersery0606** [comment]
> After upgrading from 2.242 to the current version 2.303 I saw that the dots on the i and j are now smaller.
> At font size 9 (12px) they are now 1 pixel in height instead of the 2 before.
> 
> In the current state there are several problems with this:
> 
> ## Due to the font rendering in Windows the dot looks more like a small line that is almost 2 pixels wide:
> ![grafik](https://user-images.githubusercontent.com/2885473/209708640-29c751a5-412e-4d9d-80db-0638247e8664.png)
> 
> ## The dots on the umlauts are still *2* pixels tall:
> ![grafik](https://user-images.githubusercontent.com/2885473/209708527-6c3e717a-0bc4-47f3-a76d-0b436c52cbfd.png)
> 
> ## When using the bold version, all dots are *1* pixel tall:
> ![grafik](https://user-images.githubusercontent.com/2885473/209708567-da10f6ce-9344-41da-ab90-c3a3353e7e6e.png)
> 
> ## When using the italic version, all dots are now *2* pixels tall:
> ![grafik](https://user-images.githubusercontent.com/2885473/209708578-dfad2cec-40f8-4598-aba3-a0885165453a.png)
> 
> 
> Personally I prefer the old version with the 2 pixel tall dots, even if it would go a bit above the rest of the font but I think I could get used to the new style.
> 
> But the dots should be the same on all characters.
>
