### ISSUE TITLE
Downloading the font from the website is not the latest version 

### ISSUE THREAD

**Issue by rluvaton** [JetBrains/JetBrainsMono#593]
The font version in the website when pressing download is `2.242` instead of `2.304` in GitHub releases

**Comment by roelmagdaleno** [comment]
Same issue here. For some reason, replacing the file didn't work, so I had to uninstall the font and install it again and now the version (`2.304`) is correct.

**Comment by philippnurullin** [comment]
@rluvaton Thanks for the feedback. The process is automated but takes time. Now the site has the current version.
@roelmagdaleno When installing the new version always delete the old files first. It helps to exclude some funky errors.
