### ISSUE TITLE
Syntax Highlighting for constant in VSCode (go)

### ISSUE THREAD

**Issue by prakharporwal** [JetBrains/JetBrainsMono#596]
- Hi I have a source code of go.
- I am using VScode as my editor with the JetBrainsMono font.
- But I don't see my constant being picked up in italics. Like the do in Goland.
- Is this related to the JetBrainsMono font ?
- Are there ways to achieve the above

Current in VScode - 
<img width="311" alt="Screenshot 2023-01-19 at 11 09 48 PM" src="https://user-images.githubusercontent.com/49529937/213519524-7a7479b3-4ea0-4104-b8af-d597ede13f1a.png">

What I want ( as in Goland)

<img width="333" alt="Screenshot 2023-01-19 at 11 08 50 PM" src="https://user-images.githubusercontent.com/49529937/213519338-e49b5118-e049-473b-b322-6b35027975d8.png">

**Comment by alexeyten** [comment]
It has nothing to do with font.
You should find a color theme that make use of italic font. E.g. [Night Owl](https://marketplace.visualstudio.com/items?itemName=sdras.night-owl).

**Comment by YVVT** [comment]
> * Hi I have a source code of go.
> * I am using VScode as my editor with the JetBrainsMono font.
> * But I don't see my constant being picked up in italics. Like the do in Goland.
> * Is this related to the JetBrainsMono font ?
> * Are there ways to achieve the above
> 
> Current in VScode - <img alt="Screenshot 2023-01-19 at 11 09 48 PM" width="311" src="https://user-images.githubusercontent.com/49529937/213519524-7a7479b3-4ea0-4104-b8af-d597ede13f1a.png">
> 
> What I want ( as in Goland)
> 
> <img alt="Screenshot 2023-01-19 at 11 08 50 PM" width="333" src="https://user-images.githubusercontent.com/49529937/213519338-e49b5118-e049-473b-b322-6b35027975d8.png">

And the font in your VS code is not JetBrains Mono, but Monaco.

**Comment by philippnurullin** [comment]
Hi @prakharporwal 
It looks like all of your questions are already answered.
