### ISSUE TITLE
Font on website preview doesn't match downloaded file

### ISSUE THREAD

**Issue by MicaelJarniac** [JetBrains/JetBrainsMono#597]
Website preview (notice the `J`):
![image](https://user-images.githubusercontent.com/19514231/213538076-074b372c-1af0-4e8c-b64b-4b59c71d3355.png)

Downloaded file (notice the `J`):
![image](https://user-images.githubusercontent.com/19514231/213538181-560d7509-cbb3-4b61-9d3f-8ddc5b3b4e13.png)

I believe the `J` used to be as it is now on the website preview, because I have an older version of the font installed on my desktop computer, and the J looks just like that.

But I think it later changed to be as it is now on the downloaded file, and the website hasn't been changed to reflect that.

**Comment by Finii** [comment]
It happened with `2.300` 784f65aca6b8c2b5cf4061b45b079f0e3f391248

![image](https://user-images.githubusercontent.com/16012374/215331251-85bdeeec-cac7-478b-be39-94d4aaa8f934.png)

(from `git bisect`)

Checked the SS and CV and there is nothing that could have gone wrong, so this seems intended?

**Comment by MicaelJarniac** [comment]
> Checked the SS and CV and there is nothing that could have gone wrong, so this seems intended?

What seems intended? Them removing the top of `J` or the font on the website not matching the download?

I do think that the `J` was purposefully modified, but I believe the website should always have an up-to-date preview.
