### ISSUE TITLE
Issues with ligatures in xfce-terminal

### ISSUE THREAD

**Issue by AntiSol** [JetBrains/JetBrainsMono#6]
Hi. This looks like a very nice, clean font. Thanks for releasing it under such a permissive license! :)

I've just installed it on my system and tried to switch to using it as the font in xfce4-terminal (v0.6.3, xubuntu 16.04) and I'm having some issues with the ligatures.

Most notably, I can't see any equals signs at all. For example, this python code:
![no_equal](https://user-images.githubusercontent.com/351169/72450263-233b2e00-380e-11ea-86b6-253ed88a1a3f.jpg)

I can also see some other examples, e.g ligatures running over the top of text, and it seems to be displaying the wrong ligature (e,g ligrature for ==> rather than >=):
![wrong_ligs](https://user-images.githubusercontent.com/351169/72452027-f89ea480-3810-11ea-9f3a-139855695e56.jpg)

Note that this appears to be specific to xfce-terminal. I've also tried out Jetbrains Mono in a few other things (libreoffice, eclipse, geany) and everything seems to work fine there. I expect you'll say this is a bug in xfce4-terminal but I thought I'd raise it here first and see if you have any thoughts?

Thanks!

**Comment by philippnurullin** [comment]
Hi, looks like something horrible happened to ligatures. Seems xfce4-terminal treats them somehow specific. Did you try Fira Code in it?

**Comment by AntiSol** [comment]
I hadn't heard of Fira Code, but I've now tried it and yeah I see similar issues.
xfce4-terminal bug and not your problem? ;)

**Comment by philippnurullin** [comment]
Looks like the approach we are using to make ligatures is broken in xfce4-Terminal. And, unfortunately we can't change it, because it will remove the ability to place the cursor inside the ligature. [More about this method.](https://www.patreon.com/posts/fira-code-inside-28074541) Maybe you can contact the xfce4-Terminal team & they can add the support for this ligature treatment?

**Comment by AntiSol** [comment]
No problem, I'll raise it with the xfce team. Thanks for taking the time to look into this :)

**Comment by AntiSol** [comment]
For reference, this has already been reported to xfce, bugs: [12373](https://bugzilla.xfce.org/show_bug.cgi?id=12373) and [15803](https://bugzilla.xfce.org/show_bug.cgi?id=15803)

And the xfce team says that it's an issue in an underlying gnome widget, see https://bugzilla.gnome.org/show_bug.cgi?id=781597 and https://bugzilla.gnome.org/show_bug.cgi?id=584160
