### ISSUE TITLE
Provide version with lower lowercase letter level

### ISSUE THREAD

**Issue by CreamyCookie** [JetBrains/JetBrainsMono#60]
I really like the font, but I feel like the lower case letters are too "high", which makes it harder to differentiate them from uppercase letters at a glance. (This was also mentioned in the Reddit thread about the font.)

![adj](https://user-images.githubusercontent.com/3063858/72669077-ef3e5380-3a2d-11ea-849f-a30ad0f5511b.png)

**Comment by lanrete** [comment]
I feel like this is more of a design choice for this font.  They specifically mentioned that they increased the height for better reading experience (works for me by the way) on their website.

https://www.jetbrains.com/lp/mono/

**Comment by CreamyCookie** [comment]
> I feel like this is more of a design choice for this font.

Yes, but it's also a trade-off about how easy you can differentiate lowercase to uppercase letters, which is important to recognize spelling mistakes in camelCase function names and Class names.

And if you're using a big enough font size, I'm not sure there's that much benefit to increasing the height. It is subjective but FiraCode's level for lowercase letters seems better.

 Maybe JetBrains could provide a site where you can customize the font download similar to what the creators of the [Input Font](https://input.fontbureau.com/download/) are doing.

**Comment by philippnurullin** [comment]
Hi, @CreamyCookie . The x-height of JetBrains Mono is conches design decision which makes letters more recognisable at small sizes like 11, 12, 13. To increase the height of capital letters will generally increase the height of the line, which will lessen the amount of code on screen. 

To make the version with the lower x-height seems like a good extension for a font super-family which addresses all kinds of tasks & setting its goal to play well on all fields of typographic needs, which JetBrains Mono may become. In this case the site with preferred settings will be nice addition. It all needs a lot of time and resources. We see it as a "next" step in development of JetBrains Mono. For now the main priorities is fixing bugs, expanding weights & characters amount.
