### ISSUE TITLE
Ligature request: `---`

### ISSUE THREAD

**Issue by mayank99** [JetBrains/JetBrainsMono#601]
`---` is often used in markdown to separate out frontmatter (see examples: [1](
https://www.11ty.dev/docs/data-frontmatter/) and [2](https://docs.astro.build/en/guides/markdown-content/#using-frontmatter-variables-in-mdx))

[Fira Code](https://github.com/tonsky/FiraCode) has this too:
![](https://user-images.githubusercontent.com/9084735/216832528-d3d12e4f-5779-488f-b00a-ad800d41b0fb.png)

Would it be possible to add this to JetBrains Mono?

**Comment by philippnurullin** [comment]
JetBrains Mono have ligature `---` but there a re small gaps between the hyphens, so it's possible to count them.

Do you prefer the connected variant?

**Comment by mayank99** [comment]
ooh interesting. yeah i would have thought they should be connected, but if there is a strong reason for this then i don't mind 😄

**Comment by philippnurullin** [comment]
There is an open discussion on how much ligatures can change the original from of symbols.
So, if we are talking about consistency. The gaped version of `---` must be included in recently introduced Stylistic Set 19 with similar construction of `===`. 

But to proceed with that, I need to understand what construction is preferred by default & tune the Stylist Set accordingly.
Thanks for the feedback. I will continue to think about that.

Ok, closing the issue then.
