### ISSUE TITLE
Multiple Slants of Italics to Mirror the Variations of Bold

### ISSUE THREAD

**Issue by sirinath** [JetBrains/JetBrainsMono#61]
It is possible to have variations of italics also which mirrors the variations of bold:

- extra strong slant
- strong slant
- semi-strong slant
- regular slant
- semi-light slant
- light slant
- extra light slant
- upright italic
- extra light back slanted
- light back slanted
- semi-light back slanted
- regular back slanted
- semi-strong back slanted
- strong back slanted
- extra strong back slanted

**Comment by philippnurullin** [comment]
Hi @sirinath We don't planning to add backslanted italics & add variation to the angle of italics (if i understood you correctly). Backslainted italic  may be distracting when working with code.
