### ISSUE TITLE
Add a true-italic version of 'e'

### ISSUE THREAD

**Issue by gmosx** [JetBrains/JetBrainsMono#62]
The font is amazing, **thank you** for releasing it.

I am wondering if you would consider adding a 'true-italic' version of the 'e' glyph, to make the italics even better.

**Comment by philippnurullin** [comment]
We specially didn't made the True Italics. After test with True Italics letter forms we decided that its too distracting & making a lot of unneeded contrast/noise. This letter construction may be added in "True Italics" stylistic set later.

**Comment by gmosx** [comment]
Hm, hopefully you _will_ introduced the true-italics stylistic set. I thing a proper italic 'e' actually looks cleaner. Maybe I am too used to PlexMono.

**Comment by philippnurullin** [comment]
@gmosx Yes, but first we need to add support for this feature in IDE. So it won't be anytime soon. Sorry.
