### ISSUE TITLE
Capital J changed in the recent version

### ISSUE THREAD

**Issue by N-R-K** [JetBrains/JetBrainsMono#620]
It seems like the capital J changed in the recent version 2.304

![image](https://user-images.githubusercontent.com/79544946/236556790-0c75add5-0d88-4813-a36c-0a63f4eb0653.png)

This is from v2.242

![image](https://user-images.githubusercontent.com/79544946/236557010-424104ad-951d-420b-b767-e7f6dca5a73a.png)

Unless I've missed it, it wasn't mentioned in the release notes. I'm curious as to what's the rationale behind this change.

I personally like the older variant much more (since it's more "pronounced"). Any chance of getting it back? (perhaps as a character variant). Thanks.

(P.S: I also noticed the new `5` - which looks too "round-ish" and weird for my taste. But at least the older `5` is available as a character variant...)

**Comment by Finii** [comment]
See

* #574
* #597

**Comment by N-R-K** [comment]
> See
> 
> * [capital J old style as cv #574](https://github.com/JetBrains/JetBrainsMono/issues/574)
> * [Font on website preview doesn't match downloaded file #597](https://github.com/JetBrains/JetBrainsMono/issues/597)

Ah, thanks. I remember searching through the issues before opening this, no clue how I managed to miss that. But in any case, I'll close this off as a duplicate.
