### ISSUE TITLE
Please add a new glyph or character and ligature for =!=, which is UnSameQ in Mathematica

### ISSUE THREAD

**Issue by PeterCullenBurbery** [JetBrains/JetBrainsMono#627]
Please add a new glyph or character and ligature for =!=, which is UnSameQ in Mathematica. I understand there is a ligature for !==, but there is not a ligature for =!= which would be useful when programming in the Wolfram Language in Visual Studio Code with JetBrains Mono font ligatures turned on.

**Comment by YVVT** [comment]
There's already a ligature for `=!=`, where two equal signs get closer.

**Comment by PeterCullenBurbery** [comment]
That's good. I will close this issue.
