### ISSUE TITLE
One of three asterisks (***) has different hight

### ISSUE THREAD

**Issue by mehmandarov** [JetBrains/JetBrainsMono#63]
One of three asterisks (***) has different hight. It seems to happen only when there are three asterisks. See attached screenshot for an example.

![image](https://user-images.githubusercontent.com/5373549/72686808-97205380-3af8-11ea-8369-3a4e32d26ab7.png)

**Comment by CreamyCookie** [comment]
I think that's one purpose. FiraCode does the same: https://github.com/tonsky/FiraCode

**Comment by mehmandarov** [comment]
Ah, could be! Feel free to close this issue if this one was on purpose.

**Comment by Protectator** [comment]
It is a ligature, and it's intentional. It is shown in the ligatures section of the font presentation page : https://www.jetbrains.com/lp/mono/#ligatures
<img width="88" alt="Capture d’écran 2020-01-20 à 10 19 26" src="https://user-images.githubusercontent.com/1529017/72714116-7692e080-3b6e-11ea-890a-a8cb79a06529.png">

**Comment by philippnurullin** [comment]
This is a ligature. Works like intended. 
Thanks for feedback.

**Comment by languitar** [comment]
Can someone explain the reason for this ligature? I don't see any real use for this so far.

**Comment by hackel** [comment]
`***` is an operator in Haskell.  https://hectorhon.blogspot.com/2016/12/how-to-use-haskell-arrows-for-beginners.html

**Comment by con-f-use** [comment]
Did somebody make a version without this particular ligature?

**Comment by shamansir** [comment]
It is also can be useful in markups with lists’ items indentation using asterisks, such as [Org mode](https://orgmode.org/), as well as `###`… for headings

**Comment by navoyan** [comment]
> Did somebody make a version without this particular ligature?

If anyone needs it, I've patched the font to disable this particular ligature: https://github.com/navoyan/JetBrainsMono. Also for Nerd Font: https://github.com/navoyan/nerd-fonts
