### ISSUE TITLE
Some glyphs (like 5 and 8) are self-intersecting

### ISSUE THREAD

**Issue by MewPurPur** [JetBrains/JetBrainsMono#647]
I'm coming from the Godot Engine which uses JetBrainsMono as its default code font. I was trying to use it in a TextMesh but got barraged with warnings about self-intersections.

![image](https://github.com/JetBrains/JetBrainsMono/assets/85438892/c459d24e-eed2-42e2-a277-c8f02399265f)

This would make certain characters unable to be displayed. I was trying to use text meshes of numbers, so I've found that glyphs `5` and `8` are self-intersecting for example. This is an issue I don't face in most fonts

**Comment by kenmcd** [comment]
They must be using an older version of the fonts.
The most current variable version (v2.304) does not have overlaps in those figures (some older versions do).
So update to the current version.

**Comment by MewPurPur** [comment]
Thank you!
