### ISSUE TITLE
Bad interaction with Swift's string interpolation

### ISSUE THREAD

**Issue by tonyarnold** [JetBrains/JetBrainsMono#65]
I've come across a situation with a ligature that I'd prefer not to display. I understand that this might not be possible, but here's a report all the same:

Given the following Swift string:

```swift
let somePath = "/administration/organizations/\(anotherString)"
```

Using JetBrains Mono produces the following result:

<img width="512" alt="image" src="https://user-images.githubusercontent.com/4802/72696338-e2397580-3b8f-11ea-9436-79d01a0ae413.png">

Obviously the `/\` is unintentional, and probably quite situation/language specific.

**Comment by CreamyCookie** [comment]
Would #11 (Spacing only ligatures variant) help for that?

**Comment by pakLebah** [comment]
It's quite annoying actually which force me to back to Fira Code when I write Swift code. Please fix this ASAP. Thank you.

**Comment by philippnurullin** [comment]
Consulted with Nikita Prokopov on matter of `\/` `/\`. Looks like there is no way to make them work good. Too many exclusions, so in 1.0.3 we will remove thees ligatures.

**Comment by tonyarnold** [comment]
Ah, that's a shame. 

Look, I have to say that I understand that the use of JetBrains Mono with Swift probably isn't the primary use case so I'd be understanding if you left these ligatures in if they don't affect languages such as your own (Kotlin).

**Comment by pakLebah** [comment]
A coding font should have no bias toward any specific programming languages.
