### ISSUE TITLE
Unable to enable ligatures on VSCode

### ISSUE THREAD

**Issue by josecastillolema** [JetBrains/JetBrainsMono#655]
Hi,
for some reason I am unable to enable ligatures on VSCode using JetBrains Mono.

VSCode setup:
```
{
    "editor.fontFamily": "JetBrains Mono",
    "editor.fontLigatures": true,
}
```

The font gets properly loaded but the ligatures won't work.
If I replace the font with another one with ligature support, i.e.: `Fira Code`, ligatures work normally.

Have tried in two environments with the same results:
 - Environment 1:
    - Fedora Sericea 39
    - VSCode 1.84.1 installed via FlatPak
    - `jetbrains-mono-fonts-2.304-3.fc39.noarch` installed via rpm-ostree

- Environment 2:
    - Fedora 39 toolbox
    - VSCode 1.84.2 installed via rpm (https://packages.microsoft.com/keys/microsoft.asc)
    - jetbrains-mono-fonts v2.304 installed via manual installation

Notes:
 - The font works normally with ligatures on other programs, i.e.: Gnome TextEdit, Emacs, etc.

**Comment by josecastillolema** [comment]
Hi @mfocko , thanks for taking a look!
Your answer pointed me in the right direction, for some reason I had the fonts installed here: `$HOME/.local/share/fonts/` which somehow was producing the error.
After deleting this folder and only leave the rpm installed ones ligatures are working.
Thanks

**Comment by Navid-Rahman-Fahim** [comment]
Hi I also faced the same problem. My ligatures weren't working as well but I tweaked settings.json a bit and found the solution
![Image](https://github.com/user-attachments/assets/d88ad4f4-76fb-4087-af6a-c280f1897b8c)
