### ISSUE TITLE
Add gVim support for Windows

### ISSUE THREAD

**Issue by mrtank** [JetBrains/JetBrainsMono#67]
I have a gVim 8.2 install from the original site of vim (https://ftp.nluug.nl/pub/vim/pc/gvim82.exe), and I have been able to use Fira Code with ligatures with some extra vimrc tinkering:

```
set renderoptions=type:directx
set guifont=Fira\ Code\ Regular:h10
```

But the following doesn't work: `set guifont=JetBrains\ Mono\ Regular:h13`

**Comment by damnskippy** [comment]
Dupe of issue https://github.com/JetBrains/JetBrainsMono/issues/4 likely.

**Comment by mrtank** [comment]
Doesn't draw the ligatures as we type (like fira code did), but at least after reloading the file, the ligatures show.

**Comment by slobodanzivanovic** [comment]
Just use **set guifont=JetBrains\ Mono:h13**

**Comment by mrtank** [comment]
It doesn't matter if you add `\ Regular` or not. The problem is that it doesn't automatically draws the ligatures only for `CTRL` + `L` (refresh). FiraCode has that problem _Sometimes_ https://github.com/tonsky/FiraCode/issues/462 . But for JetBrains Mono it's constant.
