### ISSUE TITLE
Uppercase letters in JetBrains Mono with font size 15 are misaligned

### ISSUE THREAD

**Issue by asitnkova** [JetBrains/JetBrainsMono#72]
Problem seems to occur only on font size 15 and only with JetBrains Mono
Android Studio 4 Canary 8
![image](https://user-images.githubusercontent.com/44114796/72779100-7ddceb80-3c4d-11ea-8c3e-587d4c20c1f7.png)

**Comment by nizmow** [comment]
This is also occurring in Windows Terminal, latest stable build of Windows 10.

![image](https://user-images.githubusercontent.com/176703/72886892-ee960d80-3d0a-11ea-94d6-1b8f3aff8b00.png)

**Comment by philippnurullin** [comment]
Looks like hinting problem. Do you use scale in OS settings?

**Comment by asitnkova** [comment]
No, theres 100% scale (windows 10). And it is weird it only occurs in JetBrains Mono, not in Medium or ExtraBold

**Comment by neikist** [comment]
Not only 15, also 17. Win 10, no scale, android studio.

**Comment by nizmow** [comment]
No scale here, although I will note that the Windows Terminal font sizing is all messed up so I was kind of paraphrasing in my earlier comment: I actually have my Terminal profile set to use size 11 fonts, which turns out to be the same as 15 in other applications, which might mean it's doing something else screwy. Not sure how that relates to Android Studio, though.

**Comment by alaershov** [comment]
Same on:
Android Studio 3.6 RC 1
Build #AI-192.7142.36.36.6071332, built on December 13, 2019
Runtime version: 1.8.0_212-release-1586-b04 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 2014M
Cores: 4
Registry: ide.new.welcome.screen.force=true
Non-Bundled Plugins: Statistic, String Manipulation, net.vektah.codeglance, com.developerphil.adbidea

Font size 17.

**Comment by philippnurullin** [comment]
Is it still present in v 1.0.3?

**Comment by nizmow** [comment]
It's perfect now in Microsoft Terminal:

![image](https://user-images.githubusercontent.com/176703/75141807-0ab61180-56f2-11ea-8f9e-e6005fe3d39e.png)

Thank you!

**Comment by asitnkova** [comment]
Seems to be fixed in v1.0.3, thank you!

![image](https://user-images.githubusercontent.com/44114796/75219222-c77da080-57ce-11ea-94e3-27c1b53110dd.png)
