### ISSUE TITLE
Ligature for >>= (bind operator)

### ISSUE THREAD

**Issue by zsolt-donca** [JetBrains/JetBrainsMono#73]
There is no ligature for the monadic bind operator `>>=`, used in various programming languages (e.g. Scala, Haskell).

With Jebrains Mono, it appears as follows:
![image](https://user-images.githubusercontent.com/6824167/72783661-abb33780-3c2f-11ea-8f3e-95288ac97ba9.png)

However, Fira Code has ligature for this, which objectively looks much nicer:

![image](https://user-images.githubusercontent.com/6824167/72783722-c71e4280-3c2f-11ea-9468-6cf9720ea779.png)

**Comment by torifat** [comment]
I'm not sure if they updated it recently but I see the following:
<img width="71" alt="Screen Shot 2020-01-22 at 7 49 37 pm" src="https://user-images.githubusercontent.com/208544/72879108-5589e580-3d50-11ea-94db-5485c8001127.png">

**Comment by CreamyCookie** [comment]
Maybe it's okay, but Fire Code's ligature seems pretty confusing since it looks like it's representing `>==` and not `>>=`.

**Comment by philippnurullin** [comment]
@zsolt-donca Hi, looks like the bundled version of the font is old. It can be solved by removing the old version of the font & installing the new in your OS.
The bundled fonts are inside the JBR folder. For example, on mac it is IntelliJ\ IDEA.app/Contents/jbr/Contents/Home/lib/fonts/ After that you will need to install the latest version of JetBrains Mono in your OS.

**Comment by zsolt-donca** [comment]
I can confirm that the font indeed contains the ligature. It is weird that the latest version of IDEA ships with an outdated font though.

Thank you all for your contribution!

**Comment by philippnurullin** [comment]
@zsolt-donca Yes, thats an annoying problem. Gladly in 2020.1 update of all IDE this will be solved. The new version of the font always be picket after this update, so it will matter not, which version of the font is bundled.
