### ISSUE TITLE
Problems with ligatures `<+->`

### ISSUE THREAD

**Issue by chenboshuo** [JetBrains/JetBrainsMono#74]
![image](https://user-images.githubusercontent.com/43953268/72795767-22c0ee00-3c79-11ea-93ad-bb6a33aa9bb7.png)

 `<+->`  in latex beamer is showing up weird.

**Comment by philippnurullin** [comment]
@chenboshuo Looks like `->` ligature is breaking all the fun. Will fix it in v 1.0.2

**Comment by chenboshuo** [comment]
philippnurullin

Thanks you have fixed in `v1.0.2`, but it still have some bugs.

You change the ligature`+->`, but the usage is `<+->`
![image](https://user-images.githubusercontent.com/43953268/73155484-d6146180-4115-11ea-879d-f723760ea7e6.png)

May be we can exclude pattern like `<[+,\w]->` and `<-[+,\w]`
for instance
```tex
\onslide<2->
\item<-2,4-5,7>
\begin{itemize}[<+->]
```
in `1.0.2` they look like

![image](https://user-images.githubusercontent.com/43953268/73156502-fb569f00-4118-11ea-8d4b-7cf4e3af7e42.png)
![image](https://user-images.githubusercontent.com/43953268/73156527-10333280-4119-11ea-8051-75bb111edc9d.png)
![image](https://user-images.githubusercontent.com/43953268/73155484-d6146180-4115-11ea-879d-f723760ea7e6.png)



-   [reference manual (Beamer Presentations: A Tutorial for Beginners (Part 4)—Overlay Specifications)](https://www.overleaf.com/learn/latex/Beamer_Presentations:_A_Tutorial_for_Beginners_(Part_4)%E2%80%94Overlay_Specifications)
-   [Full document of beamer](http://tug.ctan.org/macros/latex/contrib/beamer/doc/beameruserguide.pdf)

**Comment by philippnurullin** [comment]
@chenboshuo Sorry it cant be implemented. The exclusion in ligature for case like `<-2, 4-5,7>`, specifically for `<-2` is too broad. It will create a lot of inconsistency in other programming languages. 

Or i don't understand your request. Can you describe more precise, what is bothering you? How ideally the ligature should behave?

**Comment by chenboshuo** [comment]
In beamer,  `<1->` means from first slide to last, `<``1-``>`, but the font regard `->` as ligature,  
so, I think we can exclude the construment `<` number `-` `>`, or `<` `+``-``>`

**Comment by chenboshuo** [comment]
:joy: I think it can be solved by add space`<1- >`, and I think it  become neater, thank your attention.

**Comment by chenboshuo** [comment]
:joy: I think it can be solved by add space`<1- >`, and I think it  become neater, thank your attention.
