### ISSUE TITLE
Nederlands/Dutch language support

### ISSUE THREAD

**Issue by jonbuffington** [JetBrains/JetBrainsMono#75]
Thanks for making this font available!

I installed JetBrainsMono and noticed that Nederlands/Dutch is not a supported language on macOS 10.15.2. Is that an oversight/bug or is support more complicated?

Here are the languages reported in Font Book.app:

Afaan Oromo, Afrikaans, Albanees, Asu, Baskisch, Bemba, Bena, Bosnisch, Bulgaars, Catalaans, Cebuano, Chiga, Cornish, Corsicaans, Deens, Duits, Embu, Engels, Erzja, Esperanto, Estisch, Faeröers, Filipijns, Fins, Frans, Friulisch, Galicisch, Gikuyu, Groenlands, Gusii, Hongaars, Ido, Iers, IJslands, Inari-Samisch, Indonesisch, Interlingua, Italiaans, Javaans, Jju, Jola-Fonyi, Kaapverdisch Creools, Kalenjin, Kamba, Kinyarwanda, Kirundi, Koerdisch, Kölsch, Kroatisch, Lets, Litouws, Lojban, Luganda, Luo, Luxemburgs, Luyia, Macedonisch, Machame, Makhuwa-Meetto, Makonde, Malagassisch, Maleis, Maltees, Manx, Maori, Meru, Morisyen, Nedersaksisch, Nedersorbisch, Noord-Ndebele, Noord-Samisch, Noord-Sotho, Noors - Bokmål, Noors - Nynorsk, Nyanja, Nyankole, Occitaans, Oppersorbisch, Pools, Portugees, Reto-Romaans, Roemeens, Rombo, Russisch, Rwa, Samburu, Sango, Sangu, Sardijns, Schots-Gaelisch, Sena, Servisch, Shambala, Shona, Sloveens, Slowaaks, Soga, Somalisch, Spaans, Swahili, Swazi, Taita, Taroko, Teso, Tsjechisch, Tsonga, Tswana, Turkmeens, Vunjo, Waals, Walser, Wit-Russisch, Wolof, Xhosa, Zoeloe, Zuid-Ndbele, Zuid-Sotho, Zweeds, Zwitserduits

**Comment by philippnurullin** [comment]
Hi @jonbuffington did you try to type text in Dutch language? I believe the JetBrains Mono have all required symbols to support it. If it isn't so, we will add them in one of the next updates.

**Comment by jonbuffington** [comment]
I do not think the issue is missing glyphs. I suspect it as simple as adding Nederlands to the **slng** attribute in the font metadata. It may be just an simple option to set in the FontLab/application that generates the the ttf files.

Here is a reference I found to the **slng** tag read by macOS to determine whether to display the Font in an app: https://docs.microsoft.com/en-us/typography/opentype/spec/meta

**Comment by philippnurullin** [comment]
Looks like we still need more glyphs. Closing this issue because it's duplicated. https://github.com/JetBrains/JetBrainsMono/issues/100
