### ISSUE TITLE
Ligatures for Perl and Julia  and matlab Languages are confusing

### ISSUE THREAD

**Issue by cems2** [JetBrains/JetBrainsMono#76]
Common Julia and matlab symbol combinations are 
.-   which JBMono renders •- turning the . into a bullet 
...  which JBMono renders . ..  adding adding space between two of the dots in the ellipsis

I note that the .-  in Julia and Matlab are part of family of symbol expressions that prefix a period before a symbol that include .+  .*   ./ and .-    of these only the .- one is modified to something that doesn't suggest it's intent, so the ligature seems inconsistent.

While not a ligature, the backslash and forward slash extend all the way to the edge of the character width allowing them to visually blend with the next character in what looks like a new ligature arrow-like symbol that obfuscates the intent /\  and \\/  instead of / \ or \ /  . Even worse  Other characters also blend with these slashes such as /> to produce something unreconizable

note: While this is not unique to JBMono it is specifically detrimental for Developers, the target audience of JBMono.  the backslash is the all important escape character in most languages.

**Comment by philippnurullin** [comment]
@cems2 Can you send me the version of IDE you using? The problem with `..`should be solved in recent versions. 

Understood the context of using `.-`, i will add the exclusion for this ligature.

The escape sequence ligature problem will be fixed in 1.0.2 https://github.com/JetBrains/JetBrainsMono/issues/78

**Comment by cems2** [comment]
I am using two different IDEs.  One is ATOM (using the JUNO plug in for Julia) , the other is simply the Julia REPL in the mac unix terminal, combined with emacs as an editor.    In atom after some effort I figured out how to turn off Ligtatures by altering the CSS.  It's all or nothing, so all ligatures are off now. 
This also means all ligatures are off for everything I edit in ATOM.
 In the mac terminal there is no configurable options to turn of ligatures. 

 I also use BBEDIT (barebones software) as an IDE.  on this one Ligatures are off by default.

The problem is not with the IDE I think.  It's just that two of the ligatures are inconvenient with Julia.  The other thing that there is to dislike in how forward and back slashes merge with adjacent characters.

**Comment by philippnurullin** [comment]
The `\/` & `/\` ligatures will be removed in v 1.0.3.

**Comment by philippnurullin** [comment]
https://github.com/tonsky/FiraCode/issues/670
