### ISSUE TITLE
*ML comment ligatures are vertically misaligned

### ISSUE THREAD

**Issue by zbee** [JetBrains/JetBrainsMono#77]
XML/HTML comment opening and closing ligatures are vertically misaligned, with the opening ligatures (\).

Please see the image below, red line added for clarity.
![image](https://user-images.githubusercontent.com/1582821/72827993-01401200-3c39-11ea-8df7-8f9af6c8107a.png)

**Comment by philippnurullin** [comment]
@zbee Hi, i made some adjustments in v1.0.4. Do you still experience this problem?

**Comment by zbee** [comment]
@philippnurullin Apologies, I did not see this before now. I will try to test this the day after tomorrow.

I do not, however, have access to that exact environment (my work machine, which is in a locked and closed office), so not seeing the issue may not be exemplary of the issue being resolved. Just a note.
