### ISSUE TITLE
Escape sequences shouldn't ligature

### ISSUE THREAD

**Issue by GeorgeLyon** [JetBrains/JetBrainsMono#78]
I think that common escape sequences shouldn't ligature. One common one I see is `\\/`, where the `\/` ligatures and looks weird.

**Comment by philippnurullin** [comment]
@GeorgeLyon Yes, will fix this in v 1.0.2

**Comment by philippnurullin** [comment]
@GeorgeLyon The `\/` & `/\` ligatures will be removed in v 1.0.3.
