### ISSUE TITLE
F# :?> ligature issue

### ISSUE THREAD

**Issue by thomasd3** [JetBrains/JetBrainsMono#80]
this cast operator   ":?>"   looks quite weird and ressembles    ":?:"

**Comment by auduchinok** [comment]
@thomasd3 Could you please attach a screenshot and editor/system info? It sounds as if you have the ligature trimmed for some reason but I cannot reproduce it.
<img width="507" alt="Screenshot 2020-01-22 at 17 04 21" src="https://user-images.githubusercontent.com/3923587/72900609-43e91380-3d39-11ea-9f85-ac4ed583ffba.png">

**Comment by philippnurullin** [comment]
@thomasd3 This sounds like old bug once we had in older versions. Can you also specify the IDE & its version.

**Comment by thomasd3** [comment]
[image: Screen Shot 2020-01-22 at 4.47.54 PM.png]

Here is a screenshot.

[image: Screen Shot 2020-01-22 at 4.49.12 PM.png]

And the settings. This is with Rider 2019.3 on MacOS

**Comment by philippnurullin** [comment]
@thomasd3 Sorry the images are not attached. Looks like you need to upload them from web interface.

**Comment by thomasd3** [comment]
yes, looks like it doesn't work when replying to the notification email.

<img width="124" alt="Screen Shot 2020-01-22 at 4 47 54 PM" src="https://user-images.githubusercontent.com/14313218/72910134-6595cb00-3d38-11ea-9973-e74241f63e8a.png">
<img width="678" alt="Screen Shot 2020-01-22 at 4 49 12 PM" src="https://user-images.githubusercontent.com/14313218/72910135-6595cb00-3d38-11ea-8cb3-268f4c0ac7d8.png">

**Comment by philippnurullin** [comment]
@thomasd3 Please send the version of IDE.

**Comment by thomasd3** [comment]
it's rider 2019.3

**Comment by philippnurullin** [comment]
@thomasd3 It can be solved by removing the old version of the font & installing the new in your OS. 
The bundled fonts are inside the JBR folder. For example, on mac it is IntelliJ\ IDEA.app/Contents/jbr/Contents/Home/lib/fonts/

**Comment by thomasd3** [comment]
that didn't work:

- I removed the jetbrainsmono fonts from the rider.app/Contents/jbr/Contents/Home/lib/fonts/ folder
- I reinstalled the font from github (first time I installed it was yesterday, so it was quite up to date anyways)

and now there is no ligature are all for :> and :?>

**Comment by philippnurullin** [comment]
@thomasd3 Ok. I'm sorry but look like its a problem on a particular Rider build. Can't help with that from font perspective. You can [contact support here. ](https://rider-support.jetbrains.com/hc/en-us)
