### ISSUE TITLE
Add Mongolian language 

### ISSUE THREAD

**Issue by khasbilegt** [JetBrains/JetBrainsMono#81]
First of all, thank you so much for this amazing looking font. 

As in the list of languages that are currently supported, Mongolian is not there. However, **Mongolian alphabet has only two additional letters (Өө, Үү) and a currency symbol (₮) to the Russian alphabet.** Even though it's just two letters and a symbol I know it's gonna be a decent amount of work to put. But in the future, would love to see those added and see my own language in the list.

**Comment by philippnurullin** [comment]
@khasbilegt Yes, we will include it in one of the next updates.
Thanks for the feedback!

**Comment by philippnurullin** [comment]
@khasbilegt Is all the letters correct?

**Comment by khasbilegt** [comment]
Yes. Looks good. Thanks.
