### ISSUE TITLE
Full Nerd Font Icon Set

### ISSUE THREAD

**Issue by AngerM-DD** [JetBrains/JetBrainsMono#82]
I like the Jetbrains mono font, but w/ the Powerlevel10k theme I use it seems to be missing a few symbols (and hence my terminal ends up with a bunch of squares). Any chance we get expand it to include the full Nerd Font icon set?

https://www.nerdfonts.com/

**Comment by philippnurullin** [comment]
You can use take patched version from here → https://github.com/JetBrains/JetBrainsMono/pull/10
