### ISSUE TITLE
not enough box drawings

### ISSUE THREAD

**Issue by vi-k** [JetBrains/JetBrainsMono#84]
Far Manager:

![image](https://user-images.githubusercontent.com/15190393/72946471-c79f1080-3dca-11ea-973c-83a22006c4ed.png)

**Comment by AnimiVulpis** [comment]
If I saw correctly JetBrains Mono also **only** includes one single Block Element character (the `U+2588 FULL BLOCK`) instead of the full range `U+2580` to `U+259F`

**Comment by vi-k** [comment]
![image](https://user-images.githubusercontent.com/15190393/74070338-835b7380-4a4c-11ea-8b70-dae17b04135c.png)

Thanks! But the lines don't converge.

**Comment by Ilis** [comment]
Close the gaps, please!

**Comment by philippnurullin** [comment]
The actual gap between the lines now is 0, but it renders wit a visual gap.Look like if a bit of overshoot will fix this problem. In horizontal lines there is a bit of it added so they work fine. Ok, fix this in v 1.0.4
