### ISSUE TITLE
Bug with ligature </ and />

### ISSUE THREAD

**Issue by asitnkova** [JetBrains/JetBrainsMono#86]
</ renders as <*
/> renders as </

**Comment by philippnurullin** [comment]
@asitnkova Hi, can you send me the bundled font files? It will be _JetBrains Mono-Regular.ttf_ You can find them in _jbr_ folder , for example, on mac it is IntelliJ\ IDEA.app/Contents/jbr/Contents/Home/lib/fonts/

**Comment by asitnkova** [comment]
I use AndroidStudio 4 Canary 9. AndroidStudio does not have bundled font in fonts/ directory, whereas IntellijIDEA 2019.3.2 has. Recently I installed JetBrains Mono 1.0.1 to OS, so I think AndroidStudio grabs font from OS while IntellijIDEA uses bundled font.

**Comment by philippnurullin** [comment]
Seems like something went horribly wrong. I have the fear it's not only on the font side. Will consult with the AndroidStudio to make it clear.

**Comment by philippnurullin** [comment]
@asitnkova Sorry don't have any news. I suggest you contact the Android studio support. There is nothing that can be done from font perspective.
