### ISSUE TITLE
Arrow symbol bug

### ISSUE THREAD

**Issue by horosgrisa** [JetBrains/JetBrainsMono#87]
The arrow symbol is rendered too near to the next symbol

![image](https://user-images.githubusercontent.com/4980269/72973642-51a0a680-3dd6-11ea-91b9-c4225819e9a5.png)

![image](https://user-images.githubusercontent.com/4980269/72973738-739a2900-3dd6-11ea-9958-e4317517f63d.png)

**Comment by horosgrisa** [comment]
![image](https://user-images.githubusercontent.com/4980269/72973848-a7754e80-3dd6-11ea-8987-c825b7c7584d.png)

**Comment by philippnurullin** [comment]
@horosgrisa The arrow symbols on your screenshot are taken from your fallback font. This symbols `←↑→↓↔↕↖↗↘↙` will be added to JetBrains Mono in v 1.0.2.

**Comment by horosgrisa** [comment]
@philippnurullin OK, nice. Thank you for fast response.

**Comment by horosgrisa** [comment]
@philippnurullin Thanks.

![image](https://user-images.githubusercontent.com/4980269/73103351-9292db00-3efc-11ea-890e-ee44d85e0b45.png)
