### ISSUE TITLE
Ligatures in a glob pattern look inconsistent

### ISSUE THREAD

**Issue by hudochenkov** [JetBrains/JetBrainsMono#88]
Thank for a very nice font!

I noticed in glob pattern ligatures for comments make it look funny:

<img width="363" alt="Screen Shot 2020-01-23 at 10 59 57" src="https://user-images.githubusercontent.com/654597/72974676-b73d6480-3dcf-11ea-89d2-117b0eac0982.png">

```
src/**.*    **/*.js    src/**/*.js
```

Hope it's possible to fix.

Font size 13px in VSCode 1.41.1 on macOS 10.14.6.

**Comment by philippnurullin** [comment]
@hudochenkov Yes it is. In v 1.0.3

**Comment by trygveaa** [comment]
Hm, there are still some issues here, for instance `src/*.*` looks weird. Maybe the `/*` ligature should only apply if it has whitespace on both sides?

![image](https://user-images.githubusercontent.com/601966/79041741-5c5b2280-7bf2-11ea-8ffd-aaea10d3521a.png)

**Comment by philippnurullin** [comment]
@trygveaa Thanks for bringing that up. Will fix this in next update.

**Comment by trygveaa** [comment]
While `/*.*` looks fine now, it's still an issue if you have characters between, like this:
![image](https://user-images.githubusercontent.com/601966/80730436-e15a9d00-8b09-11ea-8b15-0ac332da993b.png)

A similar issue exists with `*/` in regexes:
![image](https://user-images.githubusercontent.com/601966/80730637-1a930d00-8b0a-11ea-9ad0-1e11d1f64cf0.png)
vs. 
![image](https://user-images.githubusercontent.com/601966/80730675-267ecf00-8b0a-11ea-8884-f7264522ab9f.png)

Or this:
![image](https://user-images.githubusercontent.com/601966/80730712-3696ae80-8b0a-11ea-8651-8b6a59c7ee4b.png)

**Comment by philippnurullin** [comment]
Thanks for the examples. Update the ligatures in next version.
