### ISSUE TITLE
Missing Git Branch Symbol

### ISSUE THREAD

**Issue by mtslzr** [JetBrains/JetBrainsMono#9]
When using with iTerm and Starship prompt, the git branch icon appears broken.

JetBrains Mono:
![image](https://user-images.githubusercontent.com/6003715/72456201-301a3c00-3792-11ea-8019-568f06b865ce.png)

Fira Code:
![image](https://user-images.githubusercontent.com/6003715/72456223-3b6d6780-3792-11ea-9b01-6a0c59769bf0.png)

**Comment by emanguy** [comment]
This is a duplicate of #2, as this requires a font with powerline symbols/extra glyphs. Try the version on the related pull request.

**Comment by philippnurullin** [comment]
@mtslzr Will be included in v 1.0.2
