### ISSUE TITLE
Bold "w" too thin

### ISSUE THREAD

**Issue by patrickmcnamara** [JetBrains/JetBrainsMono#90]
![the word "down" in JetBrains Mono](https://user-images.githubusercontent.com/23199821/73069154-e540a880-3ea4-11ea-918d-72f40d93b90b.png)

The bold "w" is noticeably thinner than the other characters and looks slightly out of place in my opinion. Any chance it can be fattened up? 🙂

**Comment by auduchinok** [comment]
Thanks! I'd also mention `m` here.

**Comment by philippnurullin** [comment]
@patrickmcnamara @auduchinok  Fattening the strokes in `w` & `m` up will produce bad recognition at small sizes, which are popular when writing code. On HiDpi monitors it may be less of a problem, but it still is. The other way around, may be in lowering the connection point of the strokes in the middle, but that will make the line more ragged, so thats not an option too.

**Comment by aaronbell** [comment]
I ran into this same issue on Cascadia Code—by lightening the strokes to improve legibility / weighting, the /w and /m actually appear weak in comparison with the other letters, and that the overall color is not preserved.

If I may make a suggestion, the way I solved this in Cascadia was to darken the outer strokes, and keep the inner strokes thin:

<img width="136" alt="Screen Shot 2020-01-24 at 9 29 00 AM" src="https://user-images.githubusercontent.com/8460297/73089859-faf5a400-3e8b-11ea-8884-9e4fe5b3e6e5.png">

I found that this gives the /w and /m a lot more presence and strength, while not hindering legibility or character recognition. 

Though the design language of Cascadia is a bit different that Jetbrains Mono, so doing this might feel a little out of place. :)

**Comment by philippnurullin** [comment]
@aaronbell Thanks for sharing experience! Looks interesting. Will definitely experiment with this approach. I believe it works well in Cascadia because of its more dynamic nature. JetBrains Mono is more of a static font, so i fear it wont look so natural, but we will see.

**Comment by philippnurullin** [comment]
@auduchinok @patrickmcnamara Did you check the `w` & `m` in v1.0.3?

**Comment by auduchinok** [comment]
@philippnurullin It seem to look better, though, still subjectively not as good as in the suggestion above.

**Comment by patrickmcnamara** [comment]
I agree that it looks better. I've also gotten more used to it now so I don't really mind either way. Thanks again. :)

**Comment by philippnurullin** [comment]
@auduchinok You just don't like the pronounced ink traps. ) Tuned it a bit more in 1.0.4.
