### ISSUE TITLE
Add Chocolatey install package

### ISSUE THREAD

**Issue by Cirzen** [JetBrains/JetBrainsMono#93]
In the same way that FiraCode can be installed via a Chocolately package (https://chocolatey.org/packages/FiraCode) it would be great to get the same for Mono so that deployments of dev environments can be easily scripted to include it.
Happy to take ownership if needed.

**Comment by philippnurullin** [comment]
@Cirzen Sure. Feel free to grab the latest version of JetBrains Mono & upload it to Chocolatey.

**Comment by Cirzen** [comment]
Currently awaiting moderation but should be live here shortly: https://chocolatey.org/packages/jetbrainsmono/1.0.2
The nuspec and install script are being held in a repo here: https://github.com/Cirzen/choco-jetbrainsmono
