### ISSUE TITLE
Digit grouping symbol "blank"

### ISSUE THREAD

**Issue by greuelpirat** [JetBrains/JetBrainsMono#94]
The digit grouping symbol "blank" is corrupt

![image](https://user-images.githubusercontent.com/16866222/73087357-b0e3e100-3ed2-11ea-8225-42aedf34b7b6.png)

![image](https://user-images.githubusercontent.com/16866222/73087453-d113a000-3ed2-11ea-8cb5-c0f4e12e4256.png)

![image](https://user-images.githubusercontent.com/16866222/73087286-96aa0300-3ed2-11ea-82e1-107b535c30cc.png)

**Comment by philippnurullin** [comment]
@greuelpirat Seems like you referring to u+00A0, a no-break space. Sure, will add in 1.0.3.

**Comment by greuelpirat** [comment]
Updated to 1.0.3. Works great! Thank you
