### ISSUE TITLE
Bug with ligature <--

### ISSUE THREAD

**Issue by madhur4127** [JetBrains/JetBrainsMono#95]
Ligature --> works as expected.

![image](https://user-images.githubusercontent.com/29328609/73116929-a3773700-3f64-11ea-8834-d2f9fbfdb2e5.png)

Version: 1.0.0 (latest as per [JetBrains](https://download.jetbrains.com/fonts/JetBrainsMono-1.0.0.zip))

**Comment by philippnurullin** [comment]
@madhur4127 Will be added in 1.0.3.

**Comment by qgates** [comment]
Can't see this fixed in 1.0.3?

**Comment by philippnurullin** [comment]
@qgates Yes, my bad. Added the glyph, but not the code for it to work. Will fix it in 1.0.4. Sorry for this stupid mistake.
