### ISSUE TITLE
Incompatible with a lot of `spaceship-prompt` font symbols

### ISSUE THREAD

**Issue by JounQin** [JetBrains/JetBrainsMono#97]
https://github.com/denysdovhan/spaceship-prompt#features

FiraCode-Retina:

![image](https://user-images.githubusercontent.com/8336744/73134484-030f3880-4072-11ea-8875-aedf214e7600.png)

JetBrains Mono:

![image](https://user-images.githubusercontent.com/8336744/73134491-128e8180-4072-11ea-8efa-0bfa60cbfd38.png)

**Comment by elken** [comment]
[Powerline fonts](https://github.com/powerline/fonts), feel free to create & submit your own fork.

**Comment by NoICE** [comment]
Release 1.0.2 says "Added powerline glyphs", but now the character described in this issue is just blank, instead of "unknown unicode".

**Comment by JounQin** [comment]
![image](https://user-images.githubusercontent.com/8336744/73540656-7ac2d600-446b-11ea-9d08-6a9e40e5e89b.png)
