### ISSUE TITLE
Use the Open Font License(OFL) instead of the Apache license

### ISSUE THREAD

**Issue by eliheuer** [JetBrains/JetBrainsMono#99]
The [OFL(Open Font License)](https://en.wikipedia.org/wiki/SIL_Open_Font_License) is the standard license used for most open-source fonts. Using one standard license makes it much easier to work with collections of open-source fonts.

Is there a reason that the Apache License is used instead of the OFL?

Adding Jet Brains Mono to Google Fonts would be much simpler if it used the OFL for example: https://github.com/google/fonts/issues/2308

**Comment by bulenkov** [comment]
We made it Apache 2.0 because our target audience is software developers and Apache 2.0 is more popular and clear for them than SIL. For example, see https://github.com/google/fonts/blob/master/apache/robotomono/LICENSE.txt 

At the moment, we're thinking about dual-licensing for JetBrains Mono. Have you had experience with that?

**Comment by eliheuer** [comment]
Thanks! I know Google Fonts has some Apache fonts, but the number of fonts using Apache is far fewer than the OFL and designers are more familiar with the OFL than the Apache license for fonts. I was just wondering why the choice was made since it was [brought up](https://github.com/google/fonts/issues/2308#issuecomment-575856805) in a Google Fonts issue. 

licensing might be a good way to go, but feel free to close this issue since the question of license choice has been answered. 

Thanks again! :-)

**Comment by eliheuer** [comment]
One additional reason I like the OFL is I can search GitHub by license to see all the OFL open-source fonts available ranked by popularity: https://github.com/search?utf8=%E2%9C%93&q=license%3Aofl-1.1&type=Repositories&ref=advsearch&l=&l=

With Apache, the font wouldn't show up on in this search.

**Comment by thlinard** [comment]
Btw, Roboto is moving to OFL:
https://github.com/TypeNetwork/Roboto/issues/67
https://github.com/TypeNetwork/Roboto-Flex

**Comment by bulenkov** [comment]
That's interesting. They have different licenses for fonts and sources/docs. We will try it as well. Thanks for the link.
![image](https://user-images.githubusercontent.com/4202603/87166633-251d1000-c2cc-11ea-84c7-8f76ea60ec5a.png)

**Comment by thlinard** [comment]
Hi @bulenkov 

Thanks for the switch to OFL 1.1 in version 2.002! The metadata are fine, but the "LICENSE" file is still Apache.

**Comment by philippnurullin** [comment]
We will update it soon.

**Comment by Calinou** [comment]
This was changed in 2.002 according to the [changelog](https://github.com/JetBrains/JetBrainsMono/releases/tag/v2.002). This issue can now be closed :slightly_smiling_face:

**Comment by jwdomb** [comment]
I'm just seeing this a few weeks late. : / 

Would you all be open to reconsidering? Or dual-licensing everything?

- Roboto is still completely Apache-licensed (the linked repo above is a side-project, not the main one): https://github.com/googlefonts/roboto
- the Apache license is clear about patents
- the Apache license is easier to comply with in commercial contexts
- the Apache license is more familiar to developers, as you mentioned

While the OFL license is, indeed, more popular on Google Fonts, I'd bet that other designers (not just me) would prefer the terms of the Apache license if they understood the differences: it gives you more options.

**Comment by philippnurullin** [comment]
Hi @jwdomb . Sadly the license won't be changed to Apache 2.0. We want to publish JetBrain Mono in Google fonts and having SIL OFL is one of the key requirement.

Can you please point out the advantages of Apache more precise. I'm not very good with Licensing.
What do you mean by _"the Apache license is easier to comply with in commercial contexts"_?

**Comment by luke-jr** [comment]
OFL is a non-free license since it forbids sale by itself. Please keep a truly free license option.

You can dual license the font (so either Apache or OFL are allowed) to keep the Google Fonts compatibility.

**Comment by Calinou** [comment]
> OFL is a non-free license since it forbids sale by itself. Please keep a truly free license option.

[It's considered a free license by Linux distributions and the GNU project because it's considered easy to workaround.](https://www.gnu.org/licenses/license-list#SILOFL)

**Comment by luke-jr** [comment]
It's an irrational argument that likely would not hold up in court. The intent of the restriction is clear, and goes against the free software definition. Judges also don't like attempts to violate contracts via technicalities last I checked.
